### ISSUE TITLE
Respawn Feature NOT Reducing Money From Vault

### ISSUE THREAD

**Issue by lamblego** [xXKeyleXx/MyPet#1000]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Bukkit 1.11.2
**MyPet Build/Version:**
2.2.9
**Do you use the premium version? (this wont change anything for you)**
No
**What is the expected result?**
I expect money from my balance to be reduced when I used the respawn feature
**What happens instead of that?**
Money does not get reduced
**Error:** Respawn feature not working with Vault Economy

I changed .ylm to .docx because it wouldnt let me upload .yml

[config.docx](https://github.com/xXKeyleXx/MyPet/files/1032601/config.docx)

[pet-config.docx](https://github.com/xXKeyleXx/MyPet/files/1032602/pet-config.docx)

**Comment by xXKeyleXx** [comment]
Did you use the respawn command or did you expect that you always have to pay when the pet dies?

**Comment by lamblego** [comment]
Nevermind I was using both command and setting timer. I just disconnected and reconnected and it started working for some reason. Currently it only work when i used the command /petrespawn pay but won't work otherwise. Is there it cost money on respawn even if people don't use the command? I was also wondering you are able to make it so that people can have multiple pets out at the same time. Thank you!

**Comment by zerafox** [comment]
Multiple active pets at the same time will never be added to MyPet.
This has been requested and denied multiple times.

The pay method for pet re-spawning is only intended to work on the command
when re-spawning the pet sooner than the cool-down allows.
