### ISSUE TITLE
Mob riding speed static

### ISSUE THREAD

**Issue by FatalBlade** [xXKeyleXx/MyPet#1001]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.11.2 latest revision as of this posting. (spigot)
**MyPet Build/Version:**
2.2.9
**Do you use the premium version? (this wont change anything for you)**
No
**What is the expected result?**
Different mobs moving at different speeds
**What happens instead of that?**
Everything moves at the same speed regardless of the config changes
**Error:**
When trying to make it so that for instance a wolf moves faster than a cow when riding them via changing the speeds in the plugin config nothing happens.

**Comment by xXKeyleXx** [comment]
Is their speed different when you don't ride them?
