### ISSUE TITLE
Do you want to help translating MyPet into other languages? Click >>here<<

### ISSUE THREAD

**Issue by piech715** [xXKeyleXx/MyPet#1002]
hi

on your side:
https://dev.bukkit.org/projects/mypet

Is there a link there:

Do you want to help translating MyPet into other languages? Click >>here<<
This link does not work

I would like to have it in German.

**Comment by xXKeyleXx** [comment]
Link funktioniert wieder, danke für die Info. Und MyPet ist bereits vollständig auf deutsch Übersetzt ;)
