### ISSUE TITLE
Pet's health gets spammed in chat

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#1003]
**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.12-pre6
**MyPet Build/Version:**
Latest premium devbuild (2.3.5)
**Do you use the premium version? (this wont change anything for you)**
Yes.
**What is the expected result?**
No spam in the chat.
**What happens instead of that?**
Spam in the chat.
**Error:**
No error given.

Screenshot: http://prntscr.com/fenlv7

It spams the pet's health every second within the chat. The release before parrots/illusionors got added seems not to have this issue though?

**Comment by xXKeyleXx** [comment]
What is the saturation level of the pet and has the pet the healing skill?

**Comment by Sikatsu** [comment]
The hunger level? 93. 
Pet doesn't have a skilltree yet. But it happens for pets with a skilltree aswell.

**Comment by xXKeyleXx** [comment]
When does the spam happen?

**Comment by Sikatsu** [comment]
As soon as I do /petcall

Op vr 2 jun. 2017 om 14:38 schreef Sebastian Comans <
notifications@github.com>:

**Comment by xXKeyleXx** [comment]
It doesn't happen to me :/ Any idea why it could happen? Any plugins that cause damage over time? or are there any blocks on the floor that cause damage to the pet?

**Comment by Sikatsu** [comment]
They are just standing on grass. Perhaps it happens because most plugins
seem to have issues with the actionbar on 1.12?
Even with a full health pet it keeps spamming.

Op vr 2 jun. 2017 om 15:45 schreef Sebastian Comans <
notifications@github.com>:

**Comment by xXKeyleXx** [comment]
I don't know what I did but now it spams me too. At least I can fix it now.

**Comment by xXKeyleXx** [comment]
It was in fact the action bar xD
