### ISSUE TITLE
Skeleton horse pets

### ISSUE THREAD

**Issue by iamharrymc** [xXKeyleXx/MyPet#1004]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** 1.11.2

**MyPet Build/Version:** 2.3.4

**Do you use the premium version? (this wont change anything for you)** Yes

**What is the expected result?** I expect to be able to tame the skeleton horse, but you damage the skeleton horse til it dies; the pet taming isn't activating. This is with LowHp flag. It doesn't work with the taming flag either.

**What happens instead of that?** When using a lead on a tamed skeleton horse, with or without a saddle; damaged or freshly tamed; nothing happens

**Error:** The skeleton horse isn't tamed

**Comment by xXKeyleXx** [comment]
Could you attach the config.yml and pet-config.yml to this issue please.

**Comment by iamharrymc** [comment]
config.yml: https://hastebin.com/elosulekuw.bash
pet-config.yml: https://hastebin.com/fokibuvumo.bash

**Comment by xXKeyleXx** [comment]
When I set LeashFlags for SkeletonHorse to LowHp it works totally fine for me :/
