### ISSUE TITLE
MyPet crashes the server on 1.12

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#1007]
**Error:**
https://pastebin.com/9wwbuucS

Spawned my new illusioner pet and the server crashed right after.

Edit: Seems to apply on all pets. Once you spawn a pet the server crashes.

**Comment by Sikatsu** [comment]
This also applies to the parrot.

**Comment by Sikatsu** [comment]
Nevermind. Applies to all pets! Whenever I spawn a MyPet it crashes the server.

**Comment by xXKeyleXx** [comment]
The plugin wasn't updated to the 1.12 release...
