### ISSUE TITLE
Some of my friends cant catch pet

### ISSUE THREAD

**Issue by TigerSchnee** [xXKeyleXx/MyPet#1010]
Spigot 1.11.2 RO.1 SNAPSHOT

MyPet 2.2.9

Not Premium Version

**What is the expected result?**
Can use leash to catch pets.

**What happens instead of that?**
Only one person on my server can use leash to catch pets. Others including me, owner and op, just can using leash to kill mobs.

**Error:**
No error in log

**Comment by zerafox** [comment]
Are you sure you have given the correct permission node(s) to leash pets?

**Comment by TigerSchnee** [comment]
Yes, I gave leash.* and leash.every mobs, the only one of my friends who can catch pet has the same permission with us.

**Comment by TigerSchnee** [comment]
And I just bought premium version and running the MyPet Premium 2.3.5 on 1.12 R0.1 Snapshot, I didn't delete the plugin folder, and this issue is still there. Only the one of my friends can catch pet using leash.

**Comment by zerafox** [comment]
The permission node you want is:

 - MyPet.leash.<MyPet-Type>

or

MyPet.leash.*

Did you forget to put the "MyPet" part in your permission node?

"every" isn't an option in the nodes, if your permission nodes aren't
correct it wont work properly. :P

https://wiki.mypet-plugin.de/permissions

**Comment by TigerSchnee** [comment]
Yes, I have the correct nodes. For every mobs I mean I literally put each line of node for each mob in my permission. The pet we catches before it happened are working just fine. I turned permission off in mypet config at the first. I only added nods for MyPet after this happened. But it still not working for most of us. The one can catch pet is in the same group with rest of my friends who cant. And I'm in the group that inherit their group.
Those are the nodes I put into pex.
    - MyPet.leash.*
    - MyPet.leash.Bat
    - MyPet.leash.Blaze
    - MyPet.leash.CaveSpider
    - MyPet.leash.Chicken
    - MyPet.leash.Cow
    - MyPet.leash.Creeper
    - MyPet.leash.Donkey
    - MyPet.leash.ElderGuardian
    - MyPet.leash.EnderDragon
    - MyPet.leash.Enderman
    - MyPet.leash.Endermite
    - MyPet.leash.Ghast
    - MyPet.leash.Giant
    - MyPet.leash.Guardian
    - MyPet.leash.Husk
    - MyPet.leash.IronGolem
    - MyPet.leash.Llama
    - MyPet.leash.MagmaCube
    - MyPet.leash.Mooshroom
    - MyPet.leash.Mule
    - MyPet.leash.Ocelot
    - MyPet.leash.Pig
    - MyPet.leash.PigZombie
    - MyPet.leash.PolarBear
    - MyPet.leash.Rabbit
    - MyPet.leash.Sheep
    - MyPet.leash.Silverfish
    - MyPet.leash.Skeleton
    - MyPet.leash.SkeletonHorse
    - MyPet.leash.Slime
    - MyPet.leash.Snowman
    - MyPet.leash.Spider
    - MyPet.leash.Squid
    - MyPet.leash.Stray
    - MyPet.leash.Vex
    - MyPet.leash.Villager
    - MyPet.leash.Witch
    - MyPet.leash.Wither
    - MyPet.leash.WitherSkeleton
    - MyPet.leash.Wolf
    - MyPet.leash.Zombie
    - MyPet.leash.ZombieHorse
    - MyPet.leash.ZombieVillager

**Comment by zerafox** [comment]
Can you paste the entire group's permissions please?
And perhaps attach your mypet config file too.

It's difficult to tell what may be going wrong here at this point.

**Comment by TigerSchnee** [comment]
Sorry I cant attach zip for some reason, but I think change txt back to yml will work.


[permissions.txt](https://github.com/xXKeyleXx/MyPet/files/1080651/permissions.txt)
[config.txt](https://github.com/xXKeyleXx/MyPet/files/1080652/config.txt)

**Comment by xXKeyleXx** [comment]
What permission plugin do you use?

**Comment by TigerSchnee** [comment]
PermissionsEx

**Comment by zerafox** [comment]
There is no reason to break things down after a * style node.
This sort of thing is a redundancy, since PEX stops checking permissions at
the * style node.

    - MyPet.skilltree.*
    - MyPet.skilltree.Combat
    - MyPet.skilltree.Utility
    - MyPet.skilltree.PvP
    - MyPet.skilltree.Ride
    - MyPet.skilltree.Farm

You can easily and safely get rid of anything after the * style node and
clean up your file a great deal. ^.^;

**Comment by TigerSchnee** [comment]
Okay, I deleted those extra nodes, but I still can't catch any pet tho :(

**Comment by xXKeyleXx** [comment]
What is so special about the one player?

What does PEX say when you use the following command?: /pex user Keyle check MyPet.leash.Cow

Are there any plugins that could prevent your players to leash a pet?

**Comment by TigerSchnee** [comment]
I did /pex user *** check MyPet.leash.cow for all of us, and it says Player "UUID/name" has "MyPet.leash.*"

The one player is the last one join the server. Others including me played on server at the start with MyPet installed. 

But yesterday I tried use my another Minecraft account to log in my server, and he can catch pet with leash. Seems like only player joined before the one player cant use leash to catch pet.

I dont think there are any plugins can prevent leash a pet.

Will delete player file in /world/playerdata let MyPet forget me? If so I want to try to see what will happen.

**Comment by zerafox** [comment]
IF it's only the 1 player who is having trouble catching a MyPet, are you
100% certain they are using the right tactic to catch said pet?

What pets have they tried?
Have you watched them try to catch this pet?
What actions are they taking to catch the pet?

Originally I had players trying to "lead" or actually "leash" the mob and
not understanding why leading it with the rope didn't work. :P

**Comment by TigerSchnee** [comment]
No its not only one player can't catch pets.

Me and my friend know how to catch pets, and we successfully catch lots of pets. I have two Minecraft accounts. So after my main account and my friend cannot catch pet anymore, I tried my another account, and my another account can catch pets. I know how to and I use exactly same way trying to catch a chicken, spider, creeper, cow. Mean account still cant, some of my friend still cant.

I watched them and me punched mobs to death.

**Comment by zerafox** [comment]
Are there other things these accounts/players cannot do that they should be
able to?
This is sounding more and more like it's a permission issue somewhere in
your setup.

**Comment by TigerSchnee** [comment]
No, only catch pet. Not choose skilltree, not petrespawn, not other plugins.

**Comment by xXKeyleXx** [comment]
Could I visit your server to see what you do and what happens?

**Comment by TigerSchnee** [comment]
Yes, 198.143.187.94:25565 is my server address.
You can come to my Discord to check if I'm online. https://discord.gg/NWWF24K

**Comment by TigerSchnee** [comment]
Thanks for your help again! Keep up the good work! Love your plugin!
