### ISSUE TITLE
WorldGroups.yml not working correctly

### ISSUE THREAD

**Issue by darth123321** [xXKeyleXx/MyPet#1011]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot version 1.11.2
**MyPet Build/Version:**
MyPet version 2.2.9
**Do you use the premium version? (this wont change anything for you)**
No
**What is the expected result?**
I am trying to create per-world permissions with the WorldGroups.yml in order to disable pets in two specific worlds (Hub and Games). Regardless of what I do though, I cannot seem to disable pets in those worlds, even when negating their permissions (-MyPet.leash.*)
My group setup looks like this:
Groups:
  default:
  - flat_world
  - BowSpleef
  - PropHunt
  - world_the_end
  - world
  - world_nether
  - flat
  - FlatLandTimes
  - FlatWorld
  nopets:
  - Games
  - Hub
**What happens instead of that?**
Nothing, pets continue to appear in all worlds, and they transfer to each other world.
**Error:**
None

**Comment by xXKeyleXx** [comment]
What does it tell you when the plugin loads? Could you attache the serverlog please.

**Comment by darth123321** [comment]
It only says enabling MyPet, no error messages or anything. Even completely deleting the worldgroups.yml doesn't generate an error message. Nor does it create a new worldgroups.yml. 

Sorry for not responding sooner, didn't see I response was given.

**Comment by xXKeyleXx** [comment]
What happens when you have a pet in a default world and you enter a nopet world?

**Comment by darth123321** [comment]
Sorry, once again I didn't get a notification that you had responded.. Not sure why that is..
The pet transfers with me regardless of the world that they are in.

**Comment by xXKeyleXx** [comment]
Could you run the **/petadmin ticket** command and attach the generated zip in the MyPet folder file to this issue please.

**Comment by CLGREEN94** [comment]
I would like to point out this is happening to me as well, on my Dev server it works but on our Main server it's loading worlds that are not in the worlds folder or in the config.

https://puu.sh/wA2Nt/81d13eb6ba.png

The above screenshot shows you the worlds config on the server and the worlds mypet thinks is in the list. 

I can run the /petadmin ticket on both of my servers if you like. 

(Also I am using the premium version and the latest dev build).

**Comment by xXKeyleXx** [comment]
That would be great :+1:
