### ISSUE TITLE
pets not appearing

### ISSUE THREAD

**Issue by Sidious82** [xXKeyleXx/MyPet#1013]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
craftbukkit version git-spigot-0869666-03f1e37 (MC 1.12-R0.1-SNAPSHOT)

**MyPet Build/Version:**
2.3.0

**Do you use the premium version? (this wont change anything for you)**
no

**What is the expected result?**
issue /petcall and have your pet show up

**What happens instead of that?**
issue /petcall and notification says that pet has been summoned however they do not appear visually.

**Error:**

**Comment by xXKeyleXx** [comment]
Could you please tell me which build (b#### on server start) of MyPet you use?

**Comment by Sidious82** [comment]
MyPet-2.3.0-SNAPSHOT.jar (1145  1 day ago)

**Comment by xXKeyleXx** [comment]
Could any plugin you use prevent the pet from coming to you? Like region protection or spawn prevention plugins?

**Comment by Sidious82** [comment]
i have a few:  https://pastebin.com/FtXzJ1GW
thing is that ive been running your plugin with this combination of plugins more-or-less for a year now with no issues at all...

**Comment by xXKeyleXx** [comment]
So when did it happen? when you upgraded to 1.12? If so what was the last version of spigot/MyPet you were on? Could you tell me your Minecraft ingame name please.

**Comment by Sidious82** [comment]
ign = Sidious82
previously using...honestly i cannot tell.  i am religious about my updating so Spigot has always been the latest version, as for mypet i was prob on 2.2.8 and 2.2.9 when it was working without issue;  but what build it was i have no clue.  yes this happened with the 1.12 transition.
pets still summon, take damage and require feeding, just wont appear visually.

**Comment by xXKeyleXx** [comment]
Is it just one type or are all pets invisible?

**Comment by Sidious82** [comment]
i believe it is all pets, however i have not tested all mobs.  i know the entities for my personal client as well as any other player i asked in-server returned the same thing:  "invisible pets"

**Comment by Sidious82** [comment]
Checking dev build  MyPet-2.3.0-SNAPSHOT.jar (1148  1 hour ago) now...

**Comment by Sidious82** [comment]
am i missing some sort of dependency or something??

**Comment by xXKeyleXx** [comment]
OK I crosschecked your plugin list with another servert that has this problems and I still can not reproduce the problem yet.

Could I join your plugin and see if it does it for me too? How big is your server? Would it be possible to ZIP the whole server and upload it for me anywhere?

**Comment by xXKeyleXx** [comment]
OK got them from the other server and now I can reproduce the bug.

**Comment by xXKeyleXx** [comment]
@Sidious82 Please try the latest dev build!

**Comment by Sidious82** [comment]
ITS WORKING YASSSS!

**Comment by Sidious82** [comment]
thank you for your time and attention
