### ISSUE TITLE
REQUEST : Swiming Pet

### ISSUE THREAD

**Issue by Ripseync** [xXKeyleXx/MyPet#1014]
## **REQUEST :** 
Hi mate, have some suggestions for your new "Premium Features" ;)

- Should be nice and very usefull to have **pets able to swim** please (because it's really frustating).
- Also, can you please add the possibility to change the **speed attack for melee** ?
- An little **annimation while attacking** should be more realistic too.

Thank you so much for the great plugin, keep on good works !

Best Regards,

A big fan,
Ripsey_nc:1st_place_medal:

**Comment by zerafox** [comment]
Pets use the Minecraft Wolf's AI system, this is why they behave in a
similar manner to the default wolves and the swimming can be a little less
than desireable.

Also adding or changing animations isn't something that can be done within
a plugin, that requires altering models and changing the way they
function/react. The current animations the pets already provide are what
Minecraft already gives, any more than that I would believe it would be
required to be a mod instead.

**Comment by ScuroK** [comment]
i think many years ago pet spiders were actually running on water :D

**Comment by xXKeyleXx** [comment]
#605
