### ISSUE TITLE
Mypet Mobarena

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#1015]
I use
    MobArena:
      PvP: true
      DisablePetsInArena: false

In Config 
It should be possible to take my pet into Mobarena or?

**Bukkit/Spigot/Bungee Build/Version:**
Bungeecord Build 1244
Spigot git-Spigot-b78586d-f3356f1 (1.12)

**Mobarena Version:**
98.1

**MyPet Build/Version:**
Build 479 Premium

**What is the expected result?**
Take Mypet into the arena

**What happens instead of that?**

output: Mypet sind hier nicht erlaubt 

**Error:**
Nonne

**Comment by xXKeyleXx** [comment]
Disable the MobArena hook

**Comment by Sprungente** [comment]
I have 
I tried with all true all false and with remove out of the Config and it change nothing.

**Comment by Sprungente** [comment]
Ok it works but Pets can't hit monsters in the arena. Outside the arena they can damage monsters.

**Comment by xXKeyleXx** [comment]
I changed the config nodes in the latest dev build. They should be self explanatory.
