### ISSUE TITLE
Mypet and Safarinet Bug

### ISSUE THREAD

**Issue by Kirrasio** [xXKeyleXx/MyPet#1018]
Please provide the following info.

Spigot 1.12

 MyPet-2.3.0-SNAPSHOT.jar

**Do you use the premium version? No

We did not get an error, however we did experience a spam of you cannot capture mypet. Every time the pet is right clicked with any item and even when your hand is empty. Here is the link to the plugin that it is incompatible with. https://www.spigotmc.org/resources/safarinet-capture-mobs.9732/

Thank you so much for the time.

**Comment by xXKeyleXx** [comment]
There is not much I can do because I don't have access to this plugin and as far as I know there is no free version of it.

If you ask the SafariNet dev for help and he tells me what to do I will willingly fix the problem :)

**Comment by mastercake10** [comment]
The bug was in SafariNet, i forgot to check the item in player's hand.
This bug have been fixed.
