### ISSUE TITLE
Dev build creates conflicts with SilkSpawners.

### ISSUE THREAD

**Issue by FatherWh0** [xXKeyleXx/MyPet#1021]
The current dev build MyPet-Premium-2.3.5-SNAPSHOT is creating conflicts with another plugin, Silkspawners.
Silkspawner's perms involving mob names have taken on the prefix 'my' such as silkspawners.place.skeleton has become silkspawners.place.myskeleton.
Placed spawners lose show no mob and spawn nothing.
Silkspawners allows silktouch breaking and picking up spawners but instead they are simply breaking.
The developer of Silkspawners has been informed and said to inform you of he conflicts.

Silkspawners: https://www.spigotmc.org/resources/silkspawners-%E2%98%85-1-12-ready-%E2%98%85-1-million-downloads-%E2%98%85.7811/

**Comment by xXKeyleXx** [comment]
Are you sure you used the latest dev build (Build no. 485)?

**Comment by FatherWh0** [comment]
#485 fixes the perm issue. However they still break instead of drop. I am asking the SS dev if it's related to MyPet or his plugin. I will report here when he responds.

Thank you for your prompt help.
