### ISSUE TITLE
Skilltree creator doesn't seem to do anything

### ISSUE THREAD

**Issue by TheZenKitteh** [xXKeyleXx/MyPet#1024]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.1.2

**MyPet Build/Version:**
2.2.9

**Do you use the premium version? (this wont change anything for you)**
no

**What is the expected result?**
Should be able to use the skilltreecreator as per the instructions on the wiki

**What happens instead of that?**
Doesn't seem to do anything.
**Error:**
No errors.

Java version: java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Operating system (if it matters): Debian 8.

When I run the .jar file as per the instructions on the [wiki](https://wiki.mypet-plugin.de/skilltreecreator), a skilltree creator opens, however the only thing I can seem to do is choose a mob. Doubleclicking on things does nothing.
![untitled](https://user-images.githubusercontent.com/3247335/28255538-44b12ff6-6a86-11e7-87ff-5081f80ebc4b.png)

**Comment by xXKeyleXx** [comment]
I'm just curious, did you try the add button?
