### ISSUE TITLE
Fix the Ender Dragon

### ISSUE THREAD

**Issue by xXKeyleXx** [xXKeyleXx/MyPet#1028]
**Bukkit/Spigot/Bungee Build/Version:**
>All

**MyPet Build/Version:**
>All

**What is the expected result?**
> Possible Ender Dragons actions:
> * ridden
> * right click

**Error:**
> #977 
> #831

**Comment by andris155** [comment]
EnderDragon move bug
https://www.youtube.com/watch?v=Lounef_NANI
