### ISSUE TITLE
A Bug while players are sleeping.

### ISSUE THREAD

**Issue by luzhenbin** [xXKeyleXx/MyPet#1029]
**Spigot Version:1.12.1
**MyPet Version:2.3.0
**Do you use the premium version? (this wont change anything for you) No , sorry.
Sorry for my poor english.
The error is:
When a player is sleeping , he can type command to open his pet's bag and move some items to his bag ,
but when he get up , the items are still in his pet's bag (actually the items are moved to player's bag) so the player can use this bug to get double items and more , and when the player type some commands to get some effects , such as type "/pbeacon" the player can move the items in the GUI to his bag.

**Comment by xXKeyleXx** [comment]
This doesn't work for me. Sure I can move the items to my bag but they are not really there. And when I try to do something with these items they just disappear.

But I will still fix it so players can not open these inventories while in bed.
