### ISSUE TITLE
The plugin isnt working good (2.3.0)

### ISSUE THREAD

**Issue by BloodBugs** [xXKeyleXx/MyPet#1030]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
11
**MyPet Build/Version:**
2.3.0
**Do you use the premium version? (this wont change anything for you)**
no
**What is the expected result?**
I was trying to test some commands and some of them doesnt work
**What happens instead of that?**
well, when i do /petstore my pet got deleted, when i do /petadmin nothing happens just like
**Error:**
Anything happens
[mypet.log.txt](https://github.com/xXKeyleXx/MyPet/files/1203309/mypet.log.txt)

**Comment by xXKeyleXx** [comment]
- You know what /petstore does?
- /petadmin has no feedback atm but it has, like all MyPet commands, auto (TAB) command completion
