### ISSUE TITLE
Leash Error

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#1035]
Hello there @xXKeyleXx ,

I got spam error when I leash a mob 🙁 

Spigot Ver. : 1.11.2

MyPet Version : v2.3.4

Log : [latest.zip](https://github.com/xXKeyleXx/MyPet/files/1226761/latest.zip)

**Comment by xXKeyleXx** [comment]
I don't upload the latest version to Spigot anymore. Please download the latest version from https://mypet-plugin.de/download and try again please.
