### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tygh78071388** [xXKeyleXx/MyPet#1041]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** spigot-1.11.2

**MyPet Build/Version:** MyPet-2.3.1 

**Do you use the premium version? (this wont change anything for you)** no

**What is the expected result?**

**What happens instead of that?**

**Error:**

[crash-2017-08-24_21.05.44-server.txt](https://github.com/xXKeyleXx/MyPet/files/1248893/crash-2017-08-24_21.05.44-server.txt)

[crash-2017-08-24_20.55.41-server.txt](https://github.com/xXKeyleXx/MyPet/files/1248894/crash-2017-08-24_20.55.41-server.txt)

Updated to 2.3.1 after the continuous crash  .....

**Comment by xXKeyleXx** [comment]
Please update to the latest dev build: https://mypet-plugin.de/download
