### ISSUE TITLE
Java Script problem (?)

### ISSUE THREAD

**Issue by BolsaFamiliaBR** [xXKeyleXx/MyPet#1044]
** Bukkit / Spigot / Bungee Build / Version: **
1.7.2 R0.3
** MyPet Build / Version: **
1.1.7
** Do you use the premium version? (This will not change anything to you) **
No

-------------------------------------------------- ------------------
I tried to configurate my own exp system with JS, i copied and pasted the "exp, js" that I found on the Mypet site (https://github.com/xXKeyleXx/MyPet/blob/master/experience-scripts/exp.js)  just to test, when I join into the server to check, my pet (a blaze) has just disappeared

I went to Mypet records to find what happened, and I found this problem:
Https://pastebin.com/i5QcpzHM

How can i fix this?

**Comment by xXKeyleXx** [comment]
I'm sorry but I can not help you. The version you are using is more than 3 years old...
I have no idea what the problem was and I will not fix it.
