### ISSUE TITLE
MyPet crashing the server

### ISSUE THREAD

**Issue by PabloMA98** [xXKeyleXx/MyPet#1046]
https://pastebin.com/p5yB4JfZ

**Comment by xXKeyleXx** [comment]
Did you try the latest dev build?

**Comment by Julianvand** [comment]
We had the same problem on our server were MyPet crashed it around 8 times in 2 days. Updating from 2.3.1 to the latest dev build has resolved it (we haven't had a crash in the past 24 hours).

**Comment by PabloMA98** [comment]
Yes, it's fixed in latests dev builds.
