### ISSUE TITLE
Towny Hook doesn't work since MyPet 2.3

### ISSUE THREAD

**Issue by DevAmerok** [xXKeyleXx/MyPet#1048]
**Bukkit/Spigot/Bungee Build/Version:**
git-Paper-1196 (MC: 1.12.1)

**MyPet Build/Version:**
MyPet v2.3.0

**Do you use the premium version? (this wont change anything for you)**
NO

**What is the expected result?**
Towny hook working

**What happens instead of that?**
Last time Towny hook worked was with MyPet v2.2.9.
Since I upgraded to MyPet v2.3. Towny hook doesn't work anymore.

**Error:**

06-14-2017 17:35 [INFO] [MyPet] version 2.2.9-b1121 ENABLED
06-16-2017 01:34 [INFO] [MyPet] Disabling MyPet v2.2.9
06-16-2017 01:35 [INFO] [MyPet] Enabling MyPet v2.2.9                         **<==== Before Upgrade**
06-16-2017 01:35 [INFO] [MyPet] mcMMO (1.5.07-SNAPSHOT) hook activated.
06-16-2017 01:35 [INFO] [MyPet] PlaceholderAPI (2.7.1) hook activated.
06-16-2017 01:35 [INFO] [MyPet] ProtocolLib (4.2.1-SNAPSHOT-b353) hook activated.
06-16-2017 01:35 [INFO] [MyPet] PvPManager (3.3.3.2) hook activated.
06-16-2017 01:35 [INFO] [MyPet] Towny (0.91.4.0) hook activated.    **<====== last time towny hook worked**
06-16-2017 01:35 [INFO] [MyPet] Vault (1.5.6-b49) hook activated.
06-16-2017 01:35 [INFO] [MyPet] WorldGuard (6.1.3-SNAPSHOT;c904242) hook activated.
06-16-2017 01:35 [INFO] [MyPet] Compat mode for v1_11_R1 loaded.
06-16-2017 01:35 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
06-16-2017 01:35 [INFO] [MyPet]    added 'world' to 'default'
06-16-2017 01:35 [INFO] [MyPet]    added 'world_nether' to 'default'
06-16-2017 01:35 [INFO] [MyPet]    added 'world_the_end' to 'default'
06-16-2017 01:35 [INFO] [MyPet]    added 'temp' to 'default'
06-16-2017 01:35 [INFO] [MyPet]    added 'Heaven' to 'default'
06-16-2017 01:35 [INFO] [MyPet]    added 'El Inicio' to 'default'
06-16-2017 01:35 [INFO] [MyPet]    added 'oscuro ' to 'default'
06-16-2017 01:35 [INFO] [MyPet]    added 'oscuro' to 'default'
06-16-2017 01:35 [INFO] [MyPet]    added 'upsidedown' to 'default'
06-16-2017 01:35 [INFO] [MyPet] -------------------------------------------------
06-16-2017 01:35 [INFO] [MyPet] version 2.2.9-b1121 ENABLED
06-16-2017 01:55 [INFO] [MyPet] Disabling MyPet v2.2.9
07-10-2017 01:13 [INFO] [MyPet] Enabling MyPet v2.3.0         **<---- new version. Towny hook doesn't work anymore**
07-10-2017 01:13 [INFO] [MyPet] mcMMO (1.5.07-SNAPSHOT) hook activated.
07-10-2017 01:13 [INFO] [MyPet] PlaceholderAPI (2.8.1) hook activated.
07-10-2017 01:13 [INFO] [MyPet] PlotSquared (3.5.0-SNAPSHOT-95f8aaa) hook activated.
07-10-2017 01:13 [INFO] [MyPet] ProtocolLib (4.3.0) hook activated.
07-10-2017 01:13 [INFO] [MyPet] PvPManager (3.3.3.2) hook activated.
07-10-2017 01:13 [INFO] [MyPet] Compat mode for v1_12_R1 loaded.
07-10-2017 01:13 [INFO] [MyPet] --- Loading WorldGroups ---------------------------

**Comment by DevAmerok** [comment]
Solved with las version.

**Comment by xXKeyleXx** [comment]
Nothing has changed but OK xD I like it.
