### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by Bitconion** [xXKeyleXx/MyPet#1050]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
git-Spigot-edd0396-2a927e8 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**MyPet Build/Version:**
2.3.1

**Do you use the premium version? (this wont change anything for you)**
no

**What is the expected result?**
Ride chicken pets

**What happens instead of that?**
If a player gets into water while riding a chicken, server will crash

**Error:**
Details:
	Entity Type: null (de.Keyle.MyPet.compat.v1_12_R1.entity.types.EntityMyChicken)
	Entity ID: 5332
	Entity Name: §4 Jimmy§r
	Entity's Exact location: 5864.09, 82.00, 10178.60
	Entity's Block location: World: (5864,82,10178), Chunk: (at 8,5,2 in 366,636; contains blocks 5856,0,10176 to 5871,255,10191), Region: (11,19; contains chunks 352,608 to 383,639, blocks 5632,0,9728 to 6143,255,10239)
	Entity's Momentum: -0.10, -0.08, 0.08
	Entity's Passengers: [EntityPlayer['Nyoxs_TV'/5303, l='construcciones', x=5864.28, y=82.17, z=10178.45](Nyoxs_TV at 5864.275062110447,82.17499999105931,10178.450435993562)]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437)
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)

[crash-2017-09-04_15.08.50-server.txt](https://github.com/xXKeyleXx/MyPet/files/1279697/crash-2017-09-04_15.08.50-server.txt)

**Comment by xXKeyleXx** [comment]
Please use the latest dev build: https://mypet-plugin.de/download
