### ISSUE TITLE
No XP gain on a fresh install

### ISSUE THREAD

**Issue by xXKeyleXx** [xXKeyleXx/MyPet#1051]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.12.1

**MyPet Build/Version:**
2.3.1

**What is the expected result?**
Pets gain XP

**What happens instead of that?**
Pets gain no XP (admin command works tho)

**Comment by zerafox** [comment]
Need more information on the issue, config settings, error-logs, etc;

**Comment by xXKeyleXx** [comment]
Haha thanks for pointing that out but I think I know what I meant with that issue :P This ticket exists because I tend to forget about it ;)

**Comment by zerafox** [comment]
Oh. XD I did not realize this was a ticket you opened yourself. :P

**Comment by xXKeyleXx** [comment]
Do you get a mail for every new ticket?

**Comment by zerafox** [comment]
Yes I do :P

**Comment by zerafox** [comment]
Even replies and posts to tickets. Even if I don't use MyPet, I still keep
up with it :)
