### ISSUE TITLE
Crashes :(

### ISSUE THREAD

**Issue by Kirrasio** [xXKeyleXx/MyPet#1055]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
git-Spigot-65e8124-9e3636d (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
**MyPet Build/Version:**
 MyPet v2.3.1
**Do you use the premium version? (this wont change anything for you)**
no
**What is the expected result?**
not crashing the server
**What happens instead of that?**
server crashing
**Error:**
https://pastebin.com/VmBHU6jR

**Comment by xXKeyleXx** [comment]
Please use the latest dev build: https://mypet-plugin.de/download
