### ISSUE TITLE
MyPets are Invisible

### ISSUE THREAD

**Issue by p1ut0nium** [xXKeyleXx/MyPet#1056]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**

Thermos-1.7.10-1614-57

**MyPet Build/Version:**

MyPet-Premium-2.3.7-SNAPSHOT

**Do you use the premium version? (this wont change anything for you)**

Yes.

**What is the expected result?**

Pets should be visible.

**What happens instead of that?**

Pets spawn and come to me. I can hear them. But they are invisible. They can be killed by other mobs, and will respawn.

**Error:**

This error happens when Loading MyPet on server start; however, MyPet still loads and works fine other than the invisible issue.

[22:45:49 INFO]: [MyPet] Loading MyPet v2.3.7
[22:45:49 WARN]: [[0;32;22mMyPet[m] [mError occured while creating the de.Keyle.MyPet.api.util.service.types.EntityConverterService service.[m
[22:45:49 WARN]: java.lang.InstantiationException
[22:45:49 WARN]: 	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source)
[22:45:49 WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[22:45:49 WARN]: 	at java.lang.Class.newInstance(Unknown Source)
[22:45:49 WARN]: 	at de.Keyle.MyPet.api.util.service.ServiceManager.registerService(ServiceManager.java:59)
[22:45:49 WARN]: 	at de.Keyle.MyPet.compat.v1_7_R4.CompatManager.init(CompatManager.java:32)
[22:45:49 WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:136)
[22:45:49 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:348)
[22:45:49 WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
[22:45:49 WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138)
[22:45:49 WARN]: 	at net.minecraft.world.World.<init>(World.java:374)
[22:45:49 WARN]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162)
[22:45:49 WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375)
[22:45:49 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[22:45:49 WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[22:45:49 WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by p1ut0nium** [comment]
My Other Plugins:

[PlaceholderAPI] Loading PlaceholderAPI v2.6.0
[22:45:49 INFO]: [VoidWorld] Loading VoidWorld v1.0
[22:45:49 INFO]: [SpawnJoin] Loading SpawnJoin v1.0.6.1
[22:45:49 INFO]: [DeluxeTags] Loading DeluxeTags v1.7.1
[22:45:49 INFO]: [ItemRestrict] Loading ItemRestrict v2.3.2
[22:45:49 INFO]: [bPermissions] Loading bPermissions v2.10.8
[22:45:49 INFO]: [Skinit] Loading Skinit v0.1.3
[22:45:49 INFO]: [WorldEdit] Loading WorldEdit v6.1;no_git_id
[22:45:49 INFO]: [Nordic] Loading Nordic v0.3.0
[22:45:49 INFO]: [CityWorld] Loading CityWorld v2.992
[22:45:49 INFO]: [Essentials] Loading Essentials v2.13.1
[22:45:49 INFO]: [killStats] Loading killStats v3.0
[22:45:49 INFO]: [ClearLag] Loading ClearLag v2.9.3
[22:45:49 INFO]: [Passenger] Loading Passenger v0.1.2
[22:45:49 INFO]: [EasyBackup] Loading EasyBackup v2.1.1
[22:45:49 INFO]: [MCCore] Loading MCCore v1.64
[22:45:49 INFO]: [NightVision] Loading NightVision v1.0
[22:45:49 INFO]: [MVdWPlaceholderAPI] Loading MVdWPlaceholderAPI v1.0.0
[22:45:49 INFO]: [SignEdit] Loading SignEdit v3.3.10
[22:45:49 INFO]: [SerialKey] Loading SerialKey v0.2.1
[22:45:49 INFO]: [FeatherBoard] Loading FeatherBoard v3.23.0
[22:45:49 INFO]: [AntiDisconnectSpam] Loading AntiDisconnectSpam v1.0
[22:45:49 INFO]: [Vault] Loading Vault v1.5.6-b49
[22:45:49 INFO]: [Herochat] Loading Herochat v5.6.7-SNAPSHOT
[22:45:49 INFO]: [PlotSquared] Loading PlotSquared v3.5.0-SNAPSHOT-95f8aaa
[22:45:49 INFO]: [WorldGuard] Loading WorldGuard v6.1
[22:45:49 INFO]: [SkillAPI] Loading SkillAPI v1.48
[22:45:49 INFO]: [EssentialsProtect] Loading EssentialsProtect v2.13.1
[22:45:49 INFO]: [DynamicSigns] Loading DynamicSigns v3.28.0
[22:45:49 INFO]: [ServerSigns] Loading ServerSigns v4.4.1
[22:45:49 INFO]: [EZPrestige] Loading EZPrestige v1.2.2
[22:45:49 INFO]: [EZRanksPro] Loading EZRanksPro v1.5.0
[22:45:49 INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b691
[22:45:49 INFO]: [Citizens] Loading Citizens v2.0.13-SNAPSHOT (build 1156)
[22:45:49 INFO]: [Shopkeepers] Loading Shopkeepers v1.37
[22:45:49 INFO]: [UltimateBackpacks] Loading UltimateBackpacks v1.1.9
[22:45:49 INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.5-b699
[22:45:49 INFO]: [UltimateArena] Loading UltimateArena v2.7
[22:45:49 INFO]: [AntiVoidDeath] Loading AntiVoidDeath v1.5.1
[22:45:49 INFO]: [MythicMobs] Loading MythicMobs v4.0.1
[22:45:49 INFO]: [Multiverse-Inventories] Loading Multiverse-Inventories v2.5-b335
[22:45:49 INFO]: [Multiverse-SignPortals] Loading Multiverse-SignPortals v2.5-b665
[22:45:49 INFO]: [CommandNPC] Loading CommandNPC v1.9.1
[22:45:49 INFO]: [Denizen] Loading Denizen v0.9.5-SNAPSHOT (build 1525)
[22:45:49 INFO]: [PrisonMines] Loading PrisonMines v3.0.1
[22:45:49 INFO]: [PVP Arena] Loading pvparena v1.3.1.50
[22:45:49 INFO]: [BattleLevels] Loading BattleLevels v8.2.1
[22:45:49 INFO]: [Sentry] Loading Sentry v1.8.2
[22:45:49 INFO]: [LeaderHeads] Loading LeaderHeads v3.1.1
[22:45:49 INFO]: [MyPet] Loading MyPet v2.3.7
[22:45:49 INFO]: [Jobs] Loading Jobs v4.1.3
[22:45:49 INFO]: [MyPet-NPC] Loading MyPet-NPC v1.2.0
[22:45:49 INFO]: [BossShopPro] Loading BossShopPro v1.8.1
[22:45:49 INFO]: [PlayerShops] Loading PlayerShops v1.0.5
[22:45:49 INFO]: [EssentialsGUI] Loading EssentialsGUI v1.0.2

**Comment by p1ut0nium** [comment]
My Mods List (Client-side)

Minecraft Coder Pack (id: mcp, version: 9.05, authors: []) 
Forge Mod Loader (id: FML, version: 7.10.99.99, authors: [cpw, LexManos, Player]) 
Minecraft Forge (id: Forge, version: 10.13.4.1614, authors: [LexManos, Eloraam, Spacetoad]) 
DA3DSOUL ASM Fixes (id: da3dsoulASMFix, version: 0.1.0, authors: [da3dsoul]) 
AppliedEnergistics2 Core (id: appliedenergistics2-core, version: rv2-stable-10, authors: [AlgorithmX2]) 
Aroma1997Core (id: Aroma1997Core, version: 1.0.2.16, authors: [Aroma1997, Schillaa]) 
<CCTweaks ASM> (id: <CCTweaks ASM>, version: 1.1.1, authors: [SquidDev, ElvishJerricco]) 
CodeChicken Core (id: CodeChickenCore, version: 1.0.7.47, authors: [ChickenBones]) 
FastFlyBlockBreaking (id: fastflyblockbreaking, version: 0.1, authors: [Barteks2x]) 
1.2 (id: ivtoolkit, version: IvToolkit, authors: [Ivorius]) 
LambdaLib|Core (id: LambdaLib|Core, version: 1.2.3, authors: []) 
Not Enough Items (id: NotEnoughItems, version: 1.0.5.120, authors: [ChickenBones]) 
OpenComputers (Core) (id: OpenComputers|Core, version: 1.6.2.12, authors: [Sangar]) 
OpenModsCore (id: OpenModsCore, version: 0.9.1, authors: [Mikee, NeverCast, boq]) 
CoFH ASM (id: <CoFH ASM>, version: 000, authors: []) 
HxCKDMS Core ASM (id: HxCCore-ASM, version: 1.13.2, authors: [HxCKDMS]) 
FastCraft (id: FastCraft, version: 1.23, authors: [Player]) 
debug (id: debug, version: 1.0, authors: []) 
Familiars API (id: FamiliarsAPI, version: 1.7.10, authors: []) 
Mine & Blade Battlegear 2 - Bullseye (id: battlegear2, version: 1.7.10, authors: [nerd-boy, GotoLink, coolAlias]) 
CoFH Core (id: CoFHCore, version: 1.7.10R3.1.4, authors: [Team CoFH]) 
BuildCraft (id: BuildCraft|Core, version: 7.1.19, authors: [SpaceToad, BuildCraft Team]) 
BC Silicon (id: BuildCraft|Silicon, version: 7.1.19, authors: [SpaceToad, BuildCraft Team]) 
BC Transport (id: BuildCraft|Transport, version: 7.1.19, authors: [SpaceToad, BuildCraft Team]) 
Waila (id: Waila, version: 1.5.10, authors: []) 
WailaAddonBC (id: WailaAddonBC, version: 1.0.5.1, authors: []) 
KingCore (id: DC1, version: 3.4.2.19, authors: []) 
Fishing Nets (id: FishingNets, version: 1.2.1.5, authors: []) 
BC Energy (id: BuildCraft|Energy, version: 7.1.19, authors: [SpaceToad, BuildCraft Team]) 
BC Builders (id: BuildCraft|Builders, version: 7.1.19, authors: [SpaceToad, BuildCraft Team]) 
BC Factory (id: BuildCraft|Factory, version: 7.1.19, authors: [SpaceToad, BuildCraft Team]) 
IndustrialCraft 2 (id: IC2, version: 2.2.827-experimental, authors: [Alblaka, Player, RichardG, Thunderdark, GregoriusT, alexthesax, Drashian, Elementalist, Feanturi, Lurch1985, SirusKing, tahu44, Aroma1997]) 
Immibis Core (id: ImmibisCore, version: 59.1.4, authors: []) 
Liquid XP (id: LiquidXP, version: 59.0.2, authors: []) 
Baubles (id: Baubles, version: 1.0.1.10, authors: []) 
Thermal Foundation (id: ThermalFoundation, version: 1.7.10R1.2.6, authors: [Team CoFH]) 
Thermal Expansion (id: ThermalExpansion, version: 1.7.10R4.1.5, authors: [Team CoFH]) 
Additional Buildcraft Objects (id: Additional-Buildcraft-Objects, version: MC1.7.10-BC7.1release4.0.9, authors: [DA3DSOUL, Flow86, blakmajik, Others]) 
BC Robotics (id: BuildCraft|Robotics, version: 7.1.19, authors: [SpaceToad, BuildCraft Team]) 
ComputerCraft (id: ComputerCraft, version: 1.75, authors: []) 
Factorization Notification System (id: factorization.notify, version: 1.0, authors: []) 
Factorization Dimensional Slices (id: factorization.dimensionalSlice, version: 0.8.100, authors: []) 
Factorization (id: factorization, version: 0.8.100, authors: [neptunepink]) 
Hardcore Ender Expansion (id: HardcoreEnderExpansion, version: 1.8.6, authors: [Programmed by chylex | https://hee.chylex.com/authors]) 
Mantle (id: Mantle, version: 1.7.10-0.3.2.jenkins191, authors: []) 
Natura (id: Natura, version: 2.2.0, authors: []) 
Forestry for Minecraft (id: Forestry, version: 4.2.16.64, authors: [SirSengir]) 
Logistics Pipes (id: LogisticsPipes, version: 0.9.3.128, authors: []) 
Additional Pipes (id: additionalpipes, version: 4.7.0, authors: [Zeldo, DaStormBringer, MultipleMonomials, Additional Pipes Contributors]) 
Advanced Machines (id: AdvancedMachines, version: 59.0.2, authors: []) 
Advanced Solar Panels (id: AdvancedSolarPanel, version: 1.7.10-3.5.1, authors: [SeNtiMeL, Icedfire]) 
Ancient Warfare Core (id: AncientWarfare, version: 2.4.114-beta-MC1.7.10, authors: [shadowmage45]) 
Ancient Warfare Automation (id: AncientWarfareAutomation, version: 2.4.114-beta-MC1.7.10, authors: [shadowmage45]) 
Ancient Warfare NEI Plugin (id: AncientWarfareNEIPlugin, version: 2.4.114-beta-MC1.7.10, authors: []) 
Ancient Warfare NPCs (id: AncientWarfareNpc, version: 2.4.114-beta-MC1.7.10, authors: [shadowmage45]) 
Ancient Warfare Structures (id: AncientWarfareStructure, version: 2.4.114-beta-MC1.7.10, authors: [shadowmage45]) 
Applied Energistics 2 (id: appliedenergistics2, version: rv2-stable-10, authors: [AlgorithmX2]) 
Moving World (id: MovingWorld, version: 1.7.10-1.8.1, authors: [Darkevilmac, Large portions of code based on Archimedes' Ships]) 
Archimedes' Ships Plus (id: ArchimedesShipsPlus, version: 1.7.10-1.8.1, authors: []) 
Armourer's Workshop (id: armourersWorkshop, version: 1.7.10-0.46.0, authors: [RiskyKen]) 
Plushie Wrapper (id: plushieWrapper, version: 0.0.0, authors: [RiskyKen]) 
Aroma1997Core|Helper (id: Aroma1997CoreHelper, version: 1.0.2.16, authors: []) 
Aroma1997's Dimensional World (id: Aroma1997sDimension, version: 1.0, authors: []) 
Back in Slime Mod (id: bis, version: 3.1.6, authors: []) 
iChunUtil (id: iChunUtil, version: 4.2.3, authors: []) 
BackTools (id: BackTools, version: 4.0.0, authors: []) 
Battle Towers (id: BattleTowers, version: 1.5.1, authors: []) 
BiblioCraft (id: BiblioCraft, version: 1.11.5, authors: [Joseph 'Nuchaz' Sinclair]) 
Big Reactors (id: BigReactors, version: 0.4.3A, authors: [ErogenousBeef]) 
Binnie Core (id: BinnieCore, version: 2.0.22.7, authors: [Binnie]) 
Botany (id: Botany, version: 2.0.22.7, authors: [Binnie]) 
Extra Trees (id: ExtraTrees, version: 2.0.22.7, authors: [Binnie]) 
Genetics (id: Genetics, version: 2.0.22.7, authors: [Binnie]) 
Extra Bees (id: ExtraBees, version: 2.0.22.7, authors: [Binnie]) 
Equivalent Exchange 3 (id: EE3, version: 0.3.0.547, authors: [pahimar, x3n0ph0b3]) 
FullThrottle Alchemist (id: Project_Alchemy, version: 1.0.18, authors: [bluedart]) 
Railcraft (id: Railcraft, version: 9.12.2.0, authors: [CovertJaguar]) 
The Twilight Forest (id: TwilightForest, version: 2.3.7, authors: []) 
Forge Multipart (id: ForgeMultipart, version: 1.2.0.345, authors: []) 
Chisel 2 (id: chisel, version: 2.5.1.44, authors: [AUTOMATIC_MAIDEN, Pokefenn, Cricket, tterrag]) 
Carpenter's Blocks (id: CarpentersBlocks, version: 3.3.8.1, authors: [Mineshopper]) 
Caveworld 2 (id: caveworld, version: 2.3.2, authors: [kegare]) 
EnderStorage (id: EnderStorage, version: 1.4.7.38, authors: [ChickenBones]) 
MineFactory Reloaded (id: MineFactoryReloaded, version: 1.7.10R2.8.1, authors: [PowerCrystals, TehKrush, AtomicStryker, Feanorith, skyboy026]) 
MrTJPCore (id: MrTJPCoreMod, version: 1.1.0.33, authors: []) 
ProjectRed Core (id: ProjRed|Core, version: 4.7.0pre12.95, authors: []) 
ProjectRed Transmission (id: ProjRed|Transmission, version: 4.7.0pre12.95, authors: []) 
OpenComputers (id: OpenComputers, version: 1.6.2.12, authors: [Florian 'Sangar' Nuecke, Johannes 'Lord Joda' Lohrer, Everyone who contributed to the mod on Github - thank you!]) 
OpenMods (id: OpenMods, version: 0.9.1, authors: []) 
OpenPeripheralCore (id: OpenPeripheralCore, version: 1.3, authors: []) 
CCTweaks (id: CCTweaks, version: 1.1.1, authors: [SquidDev, ElvishJerricco]) 
ChickenChunks (id: ChickenChunks, version: 1.3.4.19, authors: [ChickenBones]) 
Chocolate Quest (id: chocolateQuest, version: 1.0, authors: []) 
ClayWorldGen (id: clayworldgen, version: v1.0.1, authors: []) 
Compact Lava Generator (id: CLG, version: 2.0.1, authors: [panda_2134]) 
ElecCore (id: ElecCore, version: 1.4.294, authors: [Elec332]) 
CMIP (id: CMIP, version: 1.0Beta.23, authors: [Elec332]) 
CompactWindmills (id: CompactWindmills, version: 1.0.3.1.b28, authors: []) 
CosmeticArmorReworked (id: cosmeticarmorreworked, version: 1.7.10-v6b, authors: [zlainsama]) 
CraftHeraldry (id: CraftHeraldry, version: 1.1.3, authors: []) 
CraftingTableIV (id: CraftingTableIV, version: 1.1Beta.93, authors: [Elec332]) 
CustomNpcs (id: customnpcs, version: 1.7.10d, authors: [Noppes, DarkSignal(AI), Foxz(Commands)]) 
D3Core (id: D3Core, version: 1.1.2.41, authors: [Dries007, Doubledoor team]) 
PTRModelLib (id: PTRModelLib, version: 1.0.0, authors: []) 
Decocraft (id: props, version: 2.3.6.1, authors: [RazzleberryFox]) 
Dirtbike Mod (id: Dirtbike, version: v1.2.0, authors: []) 
Dragon Realm (id: dragonrealm, version: 1.2a, authors: []) 
Enchanting Plus (id: eplus, version: 3.0.2-d, authors: []) 
Enchiridion (id: Enchiridion, version: 1.3, authors: []) 
Enchiridion 2 (id: Enchiridion2, version: 2.0.2a, authors: []) 
EnderCore (id: endercore, version: 1.7.10-0.2.0.39_beta, authors: [tterrag, CrazyPants]) 
Mekanism (id: Mekanism, version: 9.1.1, authors: []) 
Ender IO (id: EnderIO, version: 1.7.10-2.2.8.381, authors: [CrazyPants, tterrag]) 
Ender Spawn (id: enderspawn, version: 1.0.0, authors: [ShadCanard]) 
EnderTech (id: EnderTech, version: 1.7.10-0.3.2.405, authors: [voxelcarrot, Arkan]) 
Ender Utilities (id: enderutilities, version: 0.5.3, authors: [masa]) 
Et Futurum (id: etfuturum, version: 1.5.5, authors: [ganymedes01]) 
Ex Nihilo (id: exnihilo, version: 1.38-53, authors: [Erasmus Crowley]) 
Extra Utilities (id: ExtraUtilities, version: 1.2.12, authors: [RWTema]) 
Tinkers' Construct (id: TConstruct, version: 1.7.10-1.8.8.build988, authors: [mDiyo, fuj1n, ProgWML6, Sunstrike, Pillbox, boni]) 
Ex Astris Rebirth (id: exastrisrebirth, version: MC1.7.10-1.01-45, authors: [LoveHoly, MikeLydeamore]) 
§6Explosives§4++ (id: explosives_pp, version: 1.7b, authors: [§cminerguy31]) 
Extra Cells 2 (id: extracells, version: 2.3.14, authors: [M3gaFr3ak, DrummerMC]) 
Factorization Miscellaneous Nonsense (id: factorization.misc, version: 0.8.100, authors: []) 
Scrap (id: fz.scrap, version: 0.8.100, authors: []) 
Truth (id: factorization.truth, version: 0.8.100, authors: []) 
DefaultMobPack (id: DefaultMobPack, version: 1.7.10, authors: []) 
ExtendedFamPack (id: ExtendedFamPack, version: 1.7.10, authors: []) 
Fire Peripherals (id: FirePeripherals, version: 1.0, authors: [FireHead996]) 
§bFood Plus (id: FoodPlus, version: 3.2rS, authors: [§aJoseTheCrafter]) 
Forestry Fermenter Addon (id: ForestryFermenterAddon, version: 1.0.5, authors: []) 
Gany's End (id: ganysend, version: 1.11.3, authors: [ganymedes01]) 
Gany's Nether (id: ganysnether, version: 1.8.3, authors: [ganymedes01]) 
Gany's Surface (id: ganyssurface, version: 1.12.8, authors: [ganymedes01]) 
Gods' Weapons (id: godweapons, version: 4.0, authors: []) 
Harvest (id: Harvest, version: 1.7.10-1.0.0-2, authors: [TehNut]) 
HxC-Core (id: HxCCore, version: 1.13.2, authors: []) 
HxC Enchants (id: HxCEnchants, version: 2.5.0, authors: []) 
HxCLinkPads (id: HxCLinkPads, version: 1.5.1, authors: []) 
HxCPeripherals (id: hxcperipherals, version: 1.0, authors: [wiggle1000]) 
Nuclear Control 2 (id: IC2NuclearControl, version: 2.4.2a, authors: [Shedar, xbony2, Zuxelus, DMF444]) 
In-Game wiki Mod (id: IGWMod, version: 1.1.12-34, authors: [MineMaarten]) 
In-Game Account Switcher (id: IngameAccountSwitcher, version: 7.0.1, authors: [The_Fireplace, The_BrainStone]) 
LunatriusCore (id: LunatriusCore, version: 1.1.2.21, authors: [Lunatrius]) 
InGame Info XML (id: InGameInfoXML, version: 2.8.1.82, authors: [Lunatrius]) 
Inventory Tweaks (id: inventorytweaks, version: 1.59-dev-152-cf6e263, authors: []) 
Iron Chest (id: IronChest, version: 6.0.62.742, authors: []) 
JABBA (id: JABBA, version: 1.2.2, authors: [ProfMobius, Taelnia]) 
JourneyMap (id: journeymap, version: 5.1.4p2, authors: [techbrew, mysticdrew]) 
Just Another Spawner Compatibility Addon (id: JASCompatability, version: 1.2.0, authors: []) 
KnightPeripherals (id: knightperipherals, version: 1.7.10-1.3, authors: [KnightMiner]) 
LambdaLib (id: LambdaLib, version: 1.2.3, authors: [Lambda Innovation]) 
Loot Bags (id: lootbags, version: 2.0.17, authors: []) 
MFR Compat: Applied Energistics (id: MineFactoryReloaded|CompatAppliedEnergistics, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MFR Compat: BuildCraft (id: MineFactoryReloaded|CompatBuildCraft, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MFR Compat: Forestry (id: MineFactoryReloaded|CompatForestry, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MFR Compat: ForgeMicroblock (id: MineFactoryReloaded|CompatForgeMicroblock, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MFR Compat: IC2 (id: MineFactoryReloaded|CompatIC2, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
ProjectRed Exploration (id: ProjRed|Exploration, version: 4.7.0pre12.95, authors: []) 
MFR Compat ProjectRed (id: MineFactoryReloaded|CompatProjRed, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MFR Compat: Railcraft (id: MineFactoryReloaded|CompatRailcraft, version: 1.7.10R2.8.1, authors: [skyboy]) 
MFR Compat: Thermal Expansion (id: MineFactoryReloaded|CompatThermalExpansion, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MFR Compat: Tinkers' Construct (id: MineFactoryReloaded|CompatTConstruct, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MFR Compat: TwilightForest (id: MineFactoryReloaded|CompatTwilightForest, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MFR Compat: Vanilla (id: MineFactoryReloaded|CompatVanilla, version: 1.7.10R2.8.1, authors: [PowerCrystals]) 
MineTweaker 3 (id: MineTweaker3, version: 3.0.10, authors: [Stan Hebben]) 
MineTweakerRecipeMaker (id: MTRM, version: 1.0, authors: []) 
MoarSigns (id: MoarSigns, version: 1.2.4, authors: [Gory_Moon]) 
Simple Mod Lister (id: ModLister, version: 1.0, authors: [Dragon2488]) 
Mod Tweaker 2 (id: modtweaker2, version: 0.9.6, authors: [Jaredlll08]) 
Numina (id: numina, version: 0.4.1.104, authors: [MachineMuse]) 
MachineMuse's Modular Powersuits (id: powersuits, version: @VERSION@, authors: []) 
Morph (id: Morph, version: 0.9.3, authors: []) 
Mouse Tweaks (id: MouseTweaks, version: 2.4.4, authors: [YaLTeR]) 
§9MrCrayfish's Furniture Mod (id: cfm, version: 3.4.8, authors: [§8MrCrayfish]) 
More Swords 3 (id: MSM3, version: 3.0.0d, authors: [Darkhax]) 
NEI Integration (id: neiintegration, version: 1.1.2, authors: [tonius11]) 
Nether Ores (id: NetherOres, version: 1.7.10R2.3.1, authors: [PowerCrystals, TehKrush, AtomicStryker, skyboy026]) 
NoMoreRecipeConflict (id: recipehandler, version: 1.7.10, authors: [stimmedcow, GotoLink]) 
NotEnoughIDs (id: notenoughIDs, version: 1.4.3.4, authors: [fewizz, Player]) 
OpenBlocks (id: OpenBlocks, version: 1.5.1, authors: []) 
OpenLights (id: openlights, version: 0.1.0.22, authors: []) 
Open Modular Turrets (id: openmodularturrets, version: 2.2.8-231, authors: []) 
OpenPeripheralAddons (id: OpenPeripheral, version: 0.5.1, authors: []) 
OpenPeripheralIntegration (id: OpenPeripheralIntegration, version: 0.5, authors: []) 
OpenPrinter (id: openprinter, version: 0.1.0.132, authors: []) 
OpenRadio (id: openradio, version: 0.6.1, authors: [XDjackieXD]) 
OpenSecurity (id: opensecurity, version: 1.0.103, authors: []) 
OpenSensors (id: opensensors, version: 1.0.4, authors: [MichiyoRavencroft]) 
Ore Dictionary Converter (id: fodc, version: 1.6.1, authors: []) 
Pam's HarvestCraft (id: harvestcraft, version: 1.7.10j, authors: [Pamela Collins]) 
Pandora's Box (id: pandorasbox, version: 2.0.1, authors: []) 
Parachute Mod (id: parachutemod, version: 1.7.10, authors: [crackedEgg]) 
Parzi's Star Wars Mod (id: starwarsmod, version: 1.3.3, authors: [parzi, weaston]) 
Pet Bat (id: PetBat, version: 1.3.8, authors: []) 
Placeable Gunpowder (id: gunpowder, version: 1.1, authors: []) 
Placeable Items Mod (id: placeableitems, version: 2.0.1, authors: [Ferdz, Emx2000]) 
PlaceableTools (id: PlaceableTools, version: 1.2.0.33, authors: [Dries007, Doubledoor team]) 
PneumaticCraft (id: PneumaticCraft, version: 1.12.7-150, authors: []) 
Pocket Nether Link (id: pocketnether, version: 2.0, authors: [kandivia]) 
PortalGun (id: PortalGun, version: 4.0.0-beta-6, authors: []) 
Power Converters 3 (id: PowerConverters3, version: 1.7.10-2.11, authors: []) 
ProjectRed Transportation (id: ProjRed|Transportation, version: 4.7.0pre12.95, authors: []) 
ProjectRed Compatibility (id: ProjRed|Compatibility, version: 4.7.0pre12.95, authors: []) 
ProjectRed Integration (id: ProjRed|Integration, version: 4.7.0pre12.95, authors: []) 
ProjectRed Fabrication (id: ProjRed|Fabrication, version: 4.7.0pre12.95, authors: []) 
ProjectRed Illumination (id: ProjRed|Illumination, version: 4.7.0pre12.95, authors: []) 
ProjectRed Expansion (id: ProjRed|Expansion, version: 4.7.0pre12.95, authors: []) 
QuiverBow (id: quiverchevsky, version: b101c, authors: []) 
Random Things (id: RandomThings, version: 2.2.4, authors: [Lumien]) 
ReAuth (id: ReAuth, version: 3.2, authors: [TechnicianLP]) 
Recurrent Complex (id: reccomplex, version: 0.9.6.3, authors: [Ivorius]) 
Redstone Paste (id: RedstonePasteMod, version: 1.6.2, authors: []) 
libsandstone (id: libsandstone, version: 1.0.0, authors: []) 
Reliquary (id: xreliquary, version: 1.2, authors: [x3n0ph0b3, TheMike]) 
Roguelike Dungeons (id: Roguelike, version: 1.3.6.3, authors: [Greymerk]) 
Ropes+ (id: RopesPlus, version: 1.6.4, authors: []) 
Ruins Spawning System (id: AS_Ruins, version: 15.1, authors: []) 
Schematica (id: Schematica, version: 1.7.6.131, authors: [Lunatrius]) 
ShoulderSurfing (id: shouldersurfing, version: 1.0, authors: [Joshua Powers]) 
SkinPort (id: skinport, version: 1.7.10-v8c, authors: [zlainsama]) 
Slabcraft (id: slabcraftmod, version: 1.7, authors: []) 
Sound Filters (id: soundfilters, version: 0.8_for_1.7.X, authors: [Tmtravlr]) 
Soundless Background (id: SB, version: 1.0, authors: [Gliath]) 
Staircraft (id: staircraftmod, version: 1.7, authors: []) 
Steve's Workshop (id: StevesWorkshop, version: 0.5.1, authors: [Vswe]) 
Storage Drawers (id: StorageDrawers, version: 1.7.10-1.10.9, authors: []) 
Fisk's Superheroes (id: fiskheroes, version: 1.0.13, authors: [FiskFille]) 
Sync (id: Sync, version: 4.0.1, authors: []) 
The Kitchen Mod (id: kitchen, version: 1.3.23, authors: []) 
Thermal Dynamics (id: ThermalDynamics, version: 1.7.10R1.2.1, authors: [Team CoFH]) 
TiC Tooltips (id: TiCTooltips, version: 1.2.5, authors: [squeek]) 
TeeLuk's SpecialArmor (id: SpecialArmor, version: 1.7.10, authors: []) 
Tree Growing Simulator 2014 (id: treeGrowingSimulator, version: 0.0.3, authors: []) 
Tubestuff (id: Tubestuff, version: 59.0.4, authors: []) 
Waila Harvestability (id: WailaHarvestability, version: 1.1.6, authors: [squeek]) 
WAILA Plugins (id: wailaplugins, version: MC1.7.10-0.2.0-25, authors: [tterrag]) 
Warp Book (id: warpbook, version: 2.0.null, authors: [panicnot42]) 
WarStuff (id: warstuff, version: 1.4, authors: [bbProgrammer, estplayer]) 
What Are We Looking At (id: wawla, version: 1.3.1, authors: []) 
Waystones (id: waystones, version: 1.0.4, authors: [BlayTheNinth]) 
World-Tooltips (id: world-tooltips, version: 1.2.3, authors: [GenuineSounds]) 
WorldEdit CUI Forge Edition (id: WorldEditCuiFe, version: 1.0.7, authors: [yetanotherx, Mumfrey, Hexosse]) 
Yet Another Leather Smelting Mod (id: YALSM, version: 2.1.3, authors: []) 
Minecraft Multipart Plugin (id: McMultipart, version: 1.2.0.345, authors: []) 
ForgeRelocation (id: ForgeRelocation, version: 0.0.1.4, authors: []) 
MCFrames (id: MCFrames, version: 1.0, authors: []) 
RelocationFMP (id: RelocationFMP, version: 0.0.1.2, authors: []) 
Dense Ores (id: denseores, version: 1.0, authors: []) 
Just Another Spawner (id: JustAnotherSpawner, version: 0.17.7, authors: []) 
Thermal Recycling (id: recycling, version: 1.1.0.5, authors: [OreCruncher]) 
UniDict (id: UniDict, version: 1.7.10-2.9.2, authors: [WanionCane]) 
Forge Microblocks (id: ForgeMicroblock, version: 1.2.0.345, authors: [])

**Comment by xXKeyleXx** [comment]
I'm sorry but modded Minecraft servers are no supported by MyPet and therefore I can not help you :/
I would like to support them but I simply don't have the time to dig into Forge and how it works.

**Comment by p1ut0nium** [comment]
bummer. Ok I understand.
