### ISSUE TITLE
MyPetPremium Flight Skill

### ISSUE THREAD

**Issue by ScuroK** [xXKeyleXx/MyPet#1057]
Hey :) I have a feature request.
You might think its not important but i hope you take some time to think about it.
I bought MyPet Premium because i want to support the developement of MyPet. But the flight skill is of cource a nice extra. 
BUT: I realy wish there was a way to limit the flight duration and/or make it have some "cost" for example certain food for the pet or anything. Because on a survival server it is game breaking if players can nonstop fly with the pet.

Connecting a hunger system or similar would make the whole fly skill alot more RPG friendly and keep the game what it should be.

Without any option to limit the flight i would not give it to any players because it would destroy their gameplay.

Could you please add something? it could be any simple thing. Maybe just add a bossbar or action bar showing how much food is left. and if its empty the pet will float or fall down. of course a config option for distance/time would be cool but.

**Comment by xXKeyleXx** [comment]
You are right, the time a pet can fly should be limited somehow. It costs saturation atm but I don't think that can limit it enough.

I don't know when I will add a limit but I think it will happen someday :P

**Comment by ScuroK** [comment]
nice. i hope you can do something soon! i would rather take something simple less fancy than something "someday" ;)

**Comment by comonier** [comment]
so. i bought premium, what must i do to fly works ? players using ride but not flying, after type: fly habilites while riding just jumping.

**Comment by ScuroK** [comment]
Any news about this? :)
