### ISSUE TITLE
/petadmin create TheDeathLord3 EnderDragon or Wither Boss wont work

### ISSUE THREAD

**Issue by TheDeathLord3** [xXKeyleXx/MyPet#1060]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** Spigot

**MyPet Build/Version:** MyPet-2.3.2-b#1184

**Do you use the premium version? (this wont change anything for you)** no

**What is the expected result?** To give me the boss as a pet

**What happens instead of that?** noting happen, nothing pop up in chat or anything

**Error:** no errors were found

**Comment by xXKeyleXx** [comment]
- /petadmin create TheDeathLord3 EnderDragon
only works when ProtocolLib is installed but it is not usable anyways

- /petadmin create TheDeathLord3 Wither
is the correct command
