### ISSUE TITLE
Need help setting variant of pet for pet-shops.yml

### ISSUE THREAD

**Issue by notynote** [xXKeyleXx/MyPet#1063]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version: Spigot-99c2a37-9a82fa7 (MC: 1.12)

**MyPet Build/Version: MyPet-2.3.7-b#519

**Do you use the premium version? (this wont change anything for you)**
Yes

**What is the expected result?**
Set Variants of Pet (Parrot, Rabbit) in pet-shops.yml

**What happens instead of that?**
I do not know how to do it :(

**Error:**
none

**Comment by xXKeyleXx** [comment]
Is this still a problem?

**Comment by notynote** [comment]
Yes I still cant put variant on my pet-shop.yml

2017-10-10 0:20 GMT+07:00 Sebastian Comans <notifications@github.com>:

**Comment by xXKeyleXx** [comment]
variant:0
variant:1
variant:2
variant:3
variant:4

**Comment by notynote** [comment]
is it like this?

      parrot:
        Name: "Parrot"
        Description:
        - <green>It's a Parrot!
        PetType: Parrot
        EXP: 0
        Price: 5000
        Options:
          - variant:0

or


      parrot:
        Name: "Parrot"
        Description:
        - <green>It's a Parrot!
        PetType: Parrot
        EXP: 0
        Price: 5000
        variant:0

Thank you in advance

2017-10-10 4:15 GMT+07:00 Sebastian Comans <notifications@github.com>:

**Comment by xXKeyleXx** [comment]
the first one

**Comment by notynote** [comment]
ok got it thank you very much!

2017-10-10 4:18 GMT+07:00 Sebastian Comans <notifications@github.com>:
