### ISSUE TITLE
Ticket

### ISSUE THREAD

**Issue by Dani12342** [xXKeyleXx/MyPet#1065]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**Do you use the premium version? (this wont change anything for you)**

**What is the expected result?**

**What happens instead of that?**

**Error:**
**Im Not Summon Pet?Why?**

**Comment by xXKeyleXx** [comment]
Please provide more info than "it doesn't work"
