### ISSUE TITLE
PlaceholdersAPI

### ISSUE THREAD

**Issue by TMGaby** [xXKeyleXx/MyPet#1066]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**
MyPet 2.3.2*

**Do you use the premium version? (this wont change anything for you)**

**What is the expected result?**
Update the placeholders to work with latest PlaceholdersAPI version, pls

**What happens instead of that**
https://cdn.discordapp.com/attachments/278852118377398272/363387488233979907/unknown.png

**Comment by xXKeyleXx** [comment]
Nothing has changed with the latest PAPI version. It has other reasons it didn't work.
