### ISSUE TITLE
Cannot find older versions of MyPet.

### ISSUE THREAD

**Issue by Zilacon** [xXKeyleXx/MyPet#1067]
I run modded servers which run on 1.5.2 and 1.6.4. I used to have MyPet on these servers a while back and wanted to re-add it but cannot find the versions for it. All files are removed from the bukkit page and spigot only shows support for 1.7+.

Could you please direct me to a place to download older versions?
I am aware older versions are not supported, but still want to run them on my servers.

**Comment by xXKeyleXx** [comment]
I archived them but I hope you can still download them:

https://dev.bukkit.org/projects/mypet/files/756871/download
https://dev.bukkit.org/projects/mypet/files/716198/download

**Comment by Zilacon** [comment]
![screenshot_16](https://user-images.githubusercontent.com/3002248/31172479-8defbdf2-a8b8-11e7-84ad-b71773fe9142.png)
Nope.

**Comment by Zilacon** [comment]
Thank you. So 1.1.0 = 1.5.2 and 1.1.6 = 1.6.4?

**Comment by xXKeyleXx** [comment]
Yup

**Comment by Zilacon** [comment]
Great, thanks again!
