### ISSUE TITLE
When I call the pet (more than 20 health), the pet's health is back to 20.0 automatically.

### ISSUE THREAD

**Issue by rirubear** [xXKeyleXx/MyPet#1072]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
spigot 1.12.2

**MyPet Build/Version:**
premium 2.3.7

**Do you use the premium version? (this wont change anything for you)**
YES

**What is the expected result?**

**What happens instead of that?**

**Error:**
When I call the pet (more than 20 health), the pet's health is back to 20.0 automatically.
Is it bug?

**Comment by xXKeyleXx** [comment]
No this can be done in the SkilltreeCreator.
