### ISSUE TITLE
MyPet PlaceholderAPI (XP)

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#1075]
Hello there @xXKeyleXx ,

I just want to improve your PAPI for **%mypet_exp%** because it's to long or can you add this 

**%mypet_exp_fixed%**

Instead of this is what I see
![2017-11-22_10 43 13](https://user-images.githubusercontent.com/13610530/33107423-2cf33b2e-cf72-11e7-8513-2cd95c340d5a.png)

Then it should be **23** and **not 23.05755852242284** 

**Please?**

**Comment by xXKeyleXx** [comment]
done
