### ISSUE TITLE
Swimming Or Dive Support ?

### ISSUE THREAD

**Issue by barbzz** [xXKeyleXx/MyPet#1078]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version: spigot

**MyPet Build/Version: latest build

**Do you use the premium version? (this wont change anything for you) no

**What is the expected result?**

**What happens instead of that?**

**Error: mypet.Do you have Swimming Support for Guardian mobs ?

**Comment by zerafox** [comment]
Two Questions:
1. What is "Latest Build" ?
2. What do you mean exactly "Swimming Support"?

**Comment by barbzz** [comment]
Im sure it is the build out as of dec 1. i mean when we capture guardian
they cant swim anymore auto dismount when we go on water above 2 blocks

**Comment by xXKeyleXx** [comment]
The dismount is forced by the client not the server so there is not much I can do about it.
