### ISSUE TITLE
Purchase a Pet (Suggestion)

### ISSUE THREAD

**Issue by LoociM00** [xXKeyleXx/MyPet#1079]
**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.11.2

**MyPet Build/Version:**
2.2.9

**Do you use the premium version? (this wont change anything for you)**
No

**Suggestion**
Hi there!

I think it would be awesome to add an option for players to be able to buy the tamed pet and automatically have it tamed. I would love this feature because a lot of mobs are disabled on my server (being a Zombie Apocaylpse theme, we don't have creepers and such) and this way players can have access to all the mob types without them needing to spawn them in.

The command would be like /petpurchase [type] and the price could be set in config. It would give the player the same level pet as when they first tamed it.

Thanks for reading, and I hope you consider this!
-- Lucy

**Comment by xXKeyleXx** [comment]
There is such a feature in the premium version of MyPet.

**Comment by LoociM00** [comment]
Okay awesome! Thanks for the quick reply!

**Comment by LoociM00** [comment]
I had a look at the premium's setup, and you can only buy pets from other players? What I meant was being able to buy a pet from an Admin store, rather than selling pets to one another?

(Sorry if you already can, I couldn't see it anywhere in the Wiki).

**Comment by xXKeyleXx** [comment]
Check the pet-shops.yml in the Mypet folder. Look in there and if you still need help setting them up just ask.

**Comment by LoociM00** [comment]
Okay - thanks again! Sorry I couldn't see it on the wiki and I was debating if I should buy the premium plugin is all. :)
