### ISSUE TITLE
Cant open npc storage menu.

### ISSUE THREAD

**Issue by PabloMG123** [xXKeyleXx/MyPet#1081]
Bukkit/Spigot/Bungee Build/Version:

 Spigot 1.12

MyPet Build/Version:

 Mypet 2.3.2 + Mypet-NPC 1.2

Do you use the premium version? (this wont change anything for you)

No

What is the expected result?

Open the pet storage menu trough an npc.

What happens instead of that?

If you are not OP you get this message:

You are not allowed to do this!

Error:

You are not allowed to do this!

In some older versions i could open the npc storage menu, but now i cant, and i just dont know why because i have the exact permissions i had.

I use permissionex and these are the permissions i have:
 
    - MyPet.npc.storage.max.3
    - MyPet.npc.storage
    - MyPet.petstorage.limit.3
    - MyPet.shop.storage
    - MyPet.command.release
    - MyPet.command.respawn
    - MyPet.command.name
    - MyPet.command.name.color
    - MyPet.command.switch
    - -mypet.leash.Ghast
    - -mypet.leash.Blaze
    - -mypet.leash.EnderDragon
    - -mypet.leash.Guardian
    - mypet.leash.chicken
    - mypet.leash.cow
    - mypet.leash.donkey
    - mypet.leash.horse
    - mypet.leash.IronGolem
    - mypet.leash.Llama
    - mypet.leash.Mooshroom
    - mypet.leash.Ocelot
    - mypet.leash.parrot
    - mypet.leash.PolarBear
    - mypet.leash.sheep
    - mypet.leash.slime
    - mypet.leash.wolf
    - mypet.leash.bat
    - mypet.leash.pig

**Comment by xXKeyleXx** [comment]
pex has commands to check if a player has a specific permission.
Please check `MyPet.petstorage.limit.3` and `MyPet.shop.storage`
