### ISSUE TITLE
MyPet Shop

### ISSUE THREAD

**Issue by DerVerlorene** [xXKeyleXx/MyPet#1083]
Hallo ich habe die neueste MyPet Version und wenn ich den MyPet shop aufmachen möchte und es geht nicht Da mir immer angezeigt wird diesen befehl gibt es nicht wo ran kann das liegen?

**Comment by xXKeyleXx** [comment]
Das Template von den Issues hat schon so seinen Sinn... Wenn du eine Hilfreiche Antwort willst mach bitte ein neues Ticket auf und beantworte die Fragen so wie sie da stehen.
