### ISSUE TITLE
MyPet API Enhancement

### ISSUE THREAD

**Issue by Rocologo** [xXKeyleXx/MyPet#1084]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version: 1.12.2

**MyPet Build/Version: 2.3.3 B1199

**Do you use the premium version? (this wont change anything for you)**
No

I need a new MyPetEvent for better integration with MobHunting. I need a MyPetPickUpItem event, which is called when the MyPet picks up an Item. I only need access to the ItemStack which was picked up and be able to cancel the pickup event.

In this case it is the BagOfGold items I have made. When the MyPet picks up the BagOfGold Item the Item must be converted to money. So I need to catch the event, cancel it, remove it from ground and then pay then deposit some money to the player(MyPet owner) instead of the item.

Is this something you can make for me?

**Comment by xXKeyleXx** [comment]
MyPet calls a PlayerPickupItemEvent when it picks up an item. Is that not enough?

**Comment by Rocologo** [comment]
Ahh, I was not aware of that, i will try the event and see if i can detect if it was a mypet who actually picked up the item. I'll test this and get back to you.

**Comment by xXKeyleXx** [comment]
I don't think you can detect if the pet was the one who picked up the item but it shouldn't matter if the owner or the pet picked it up, right?

**Comment by Rocologo** [comment]
Hmmm, yes i guess you are right, let me test this and see if it works...

**Comment by Rocologo** [comment]
The thing is I already use PlayerPickupItemEvent so if you were right it should work now, but it doesnt so i have to do some debugging to see were it goes wrong

**Comment by xXKeyleXx** [comment]
It would be nice to know what's going wrong. But I can also add the event if you want.

**Comment by Rocologo** [comment]
It would be a lot better with a MyPet event so I was able to get the MyPet entity and tell the player that his pet picked up a BagOfGold (money).

Im still at work so I have had time to check the PlayerPickupEvent... in SpigorMC1.12  a ned event was created EntityPickupItemEvent the would be better than PlayerPickupItemEvent, except it would only support MC 1.12+

**Comment by Rocologo** [comment]
Thanks. I have found MyPetPickupEvent in build 1201 and have tested it. I looks perfect. I can get both the Item, the Owner and the MyPet !!!

Thank you for a great plugin!
