### ISSUE TITLE
SuperVanish NPE

### ISSUE THREAD

**Issue by shaady91** [xXKeyleXx/MyPet#1085]
Spigot 1.12.2-R0.1-SNAPSHOT  (Spigot-7754231-94b0980)
**MyPet Build/Version:**  Version: 2.3.2

Free Version

Most of the time when players use the command /petcall an error apperas on my console

The plugin still works perfectly, don't know what's causing the Error.

Error :[Server] INFO Could not pass event MyPetCallEvent to MyPet v2.3.2
07.01 16:16:19 [Server] INFO org.bukkit.event.EventException: null
07.01 16:16:19 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
07.01 16:16:19 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins%20v1.1.0.jar:?]
07.01 16:16:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:464) [MyPet.jar:?]
07.01 16:16:19 [Server] INFO at de.Keyle.MyPet.listeners.PlayerListener$4.run(PlayerListener.java:347) [MyPet.jar:?]
07.01 16:16:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot131.jar:git-Spigot-7754231-94b0980]
07.01 16:16:19 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
07.01 16:16:19 [Server] INFO Caused by: java.lang.NullPointerException
07.01 16:16:19 [Server] INFO at de.myzelyam.api.vanish.VanishAPI.isInvisible(VanishAPI.java:51) ~[?:?]
07.01 16:16:19 [Server] INFO at de.Keyle.MyPet.util.hooks.SuperVanish.on(SuperVanish.java:54) ~[?:?]
07.01 16:16:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor1278.invoke(Unknown Source) ~[?:?]
07.01 16:16:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
07.01 16:16:19 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
07.01 16:16:19 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120) ~[?:?]
07.01 16:16:19 [Server] INFO ... 13 more

**Comment by xXKeyleXx** [comment]
What version of SuperVanish do you use?

**Comment by shaady91** [comment]
SuperVanish: Version: 6.0.4

**Comment by xXKeyleXx** [comment]
It's either a problem with SuperVanish or it can be ignored ;)
