### ISSUE TITLE
[Question] How to create 

### ISSUE THREAD

**Issue by Tiplish** [xXKeyleXx/MyPet#1086]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.12.2
**MyPet Build/Version:**
MyPet-NPC-1.2
MyPet 2.3.2
**Do you use the premium version? (this wont change anything for you)**
Yes
**What is the expected result?**
Create a Pet Shop Npc 
**What happens instead of that?**
I don't know how to create the config :( 
**Error:**

I've try to use */mypetnpcconfig shop* after assign the trait but it doesn't work. 

After reading the different issues, i've understand that the pet-shop.yml missed. So how i can build it? I haven't seen anywhere on the wiki how to do this :( 

Any help? Thx :)

**Comment by xXKeyleXx** [comment]
Even tho you said you are using the premium edition of MyPet you are using MyPet 2.3.2 with suggest you are using the free version. The free version doesn't have the shop feature.

**Comment by Tiplish** [comment]
Ok thx the fast answer, i close the ticket until i have the problem again with the right .jar ;)
