### ISSUE TITLE
Feature Request [Custom Pets with Custom Resource Packs]

### ISSUE THREAD

**Issue by promorrom** [xXKeyleXx/MyPet#1087]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.9
**MyPet Build/Version:**
#534
**Do you use the premium version? (this wont change anything for you)**
Yes
**What is the expected result?**
I just want to pull for a feature request
**What happens instead of that?**
Nothing, is just a feature request
**Error:**
Nothing here

I want to request this: I am a 3D Modeler, and in my server I want to add new things for minecraft with just resource packs and plugins, instead of creating a server with mods.

Right now I am creating the 3D models of the pets, but to make it possible with Spigot/Bukkit, this is how this works: I create (for example) a Hamster 3D Model that replaces the diorite block, so what I need is to create this pet, bot how? My Pet has PvP and PvE features, then, to make this possible, the Diorite Block (The Hamster) will be set like a Hat for an Invisible Armor Stand, because the Armor Stand has a hitbox for PvP and PvE, or it is not necessary to be an armor stand, maybe an invisible zombie. So, what this can be done?

A new .yml file that is called "custom pets", where you can set the things for that pet, for example: The type of block that will be the Hat, the Health, the speed, and the other stats and stuff, and to let the users create a permission to allow people to use the pet.

Example of the custompets.yml:

1
 name: Hamster
  defaultname: &dHamster
   canchangename: true/false
  health: 6 (this is in half hearts, so 20 of health is 10 hearts)
  speed: 1
  food: wheat
  leashflags: lowhp
  customrespawntimefactor: 0
  customrespawntimefixed: 0
  leashitem: 420

2
 name: Turtle
  defaultname: &2Turtle
   canchangename: true/false
  health: 12 (this is in half hearts, so 20 of health is 10 hearts)
  speed: 0.7
  food: sugarcane
  leashflags: lowhp
  customrespawntimefactor: 0
  customrespawntimefixed: 0
  leashitem: 420

**Comment by xXKeyleXx** [comment]
I have to say no for now :/
