### ISSUE TITLE
EXP OF PET

### ISSUE THREAD

**Issue by Tomodu** [xXKeyleXx/MyPet#1089]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** Spigot 1.12

**MyPet Build/Version:** 2.3.7

**Do you use the premium version? (this wont change anything for you)** Yes

**What is the expected result?**I would like my players' pets skills to reach the maximum only when they are at the maximum level; Because he is hardly 10 that he has all the skills ...

**Comment by xXKeyleXx** [comment]
https://wiki.mypet-plugin.de/skilltrees
