### ISSUE TITLE
spigot 1.8.8

### ISSUE THREAD

**Issue by 1425115471** [xXKeyleXx/MyPet#1091]
spigot 1.8.8 
Hello, newly installed plug-ins, these problems appear.
Message. No. Haspet
![upload_2018-1-26_13-12-49](https://user-images.githubusercontent.com/29402452/35426209-31258622-029c-11e8-81e4-5bb64ec43193.png)

**Comment by xXKeyleXx** [comment]
I need the lines you cut off at the top

**Comment by 1425115471** [comment]
![_cy11ox9 cd320_ i5 ji8j](https://user-images.githubusercontent.com/29402452/35435366-62d2350c-02c5-11e8-9fd3-78496c12a66f.jpg)
![i mcqvda wj7dvo i 3 t](https://user-images.githubusercontent.com/29402452/35435369-67ac9d38-02c5-11e8-92d6-db09c2fbcae8.jpg)
![z b5rwg34jpm1gqkddu ud7](https://user-images.githubusercontent.com/29402452/35435370-6a42d972-02c5-11e8-9856-f65f5f1646f9.png)

**Comment by 1425115471** [comment]
spigot-1.8.8

**Comment by 1425115471** [comment]
![z5f lpz 8qy0i s _tt](https://user-images.githubusercontent.com/29402452/35435598-5030b8fa-02c6-11e8-8408-e4812a9dd583.png)

**Comment by 1425115471** [comment]
[2018-01-26-7.log](https://github.com/xXKeyleXx/MyPet/files/1667487/2018-01-26-7.log)

**Comment by xXKeyleXx** [comment]
You are using a very old version of MyPet. Please download the latest version from here: https://mypet-plugin.de/download

**Comment by 1425115471** [comment]
Hello, I bought it here (www.spigotmc.org), isn't it the latest version?

**Comment by 1425115471** [comment]
![image](https://user-images.githubusercontent.com/29402452/35440086-d95fa5ac-02d8-11e8-9c33-34a15169653f.png)

**Comment by 1425115471** [comment]
How can I download the download button? No download button is found in https://mypet-plugin.de/download.
       I use the translation software, sorry.

**Comment by 1425115471** [comment]
I have not received the activation code

**Comment by xXKeyleXx** [comment]
Send me message on Spigotmc.org please and I will send you the key.
