### ISSUE TITLE
this is not bug just want to ask somthing was not sure where to ask it

### ISSUE THREAD

**Issue by greensabob** [xXKeyleXx/MyPet#1095]
so i tryed renaming a villager and zombie pig man but it say cant name this mob i was trying to with a name tag and when i turn mypets off then i can rename the mobs with name tags is there way i can make it so i can rename mobs with nametags or no?

**Comment by xXKeyleXx** [comment]
I have no idea what you want...
Is english your native language?

**Comment by greensabob** [comment]
![wjuwjzd8rj2uozhwdjz6aq](https://user-images.githubusercontent.com/30241711/36104052-efd62d52-0fde-11e8-8f4e-94df478a0071.png)
but if i turn off mypets plugin it lets me rename the pets, i didn't know if theirs away i can fix this or not

**Comment by xXKeyleXx** [comment]
What MC version are you on?

**Comment by greensabob** [comment]
1.12.2

**Comment by xXKeyleXx** [comment]
It doesn't happen to me so it might be caused by something else... Could you upload the latest log please.

**Comment by greensabob** [comment]
[logs.zip](https://github.com/xXKeyleXx/MyPet/files/1720168/logs.zip)
logs

**Comment by xXKeyleXx** [comment]
I did not found anything that might give me a hint what's causing it. MyPet does not have a message like this so the source must be another plugin :/

**Comment by greensabob** [comment]
i turn mypets off, and it lets me use nametags on mobs idk

**Comment by xXKeyleXx** [comment]
I can'r reproduce it :/ If you want to, you can ZIP the whole server and upload it for me.

**Comment by greensabob** [comment]
http://www.mediafire.com/file/nwm86245uayb0bn/server.zip told me it was to big so i upload it to mediafire 
![sgvva0hqr_kszl1s_lllaw](https://user-images.githubusercontent.com/30241711/36160911-661dee9c-10b0-11e8-82b4-5f132ce97186.png)

**Comment by xXKeyleXx** [comment]
Will check it out as soon as I can

**Comment by greensabob** [comment]
ok thanks

**Comment by xXKeyleXx** [comment]
OK I tested it and it doesn't matter for me if MyPet is installed or not. So it's definetly not a MyPet problem.

**Comment by xXKeyleXx** [comment]
That message comes from MythicMobs.
