### ISSUE TITLE
MyPet actively kills tamed wolfs, ocelots and parrots under aggressive mode.

### ISSUE THREAD

**Issue by k-jiang** [xXKeyleXx/MyPet#1099]
**Bukkit/Spigot/Bungee Build/Version:** 1.12.2

**MyPet Build/Version:** 2.3.3

**Do you use the premium version? (this wont change anything for you)** no

**What is the expected result?**
A MyPet should never actively attacks or kills any vanilla tamed pets, like wolfs(dogs), ocelots(cats) or parrots. People need vanilla pets as well. We have lots of players complain about their household dogs/cats/parrots being killed accidentally. Also, some people would like to have their MyPet works with vanilla pets as well.

**What happens instead of that?**
Under aggressive mode, MyPet actively kills tamed wolfs, ocelots and parrots without orders.

**Comment by xXKeyleXx** [comment]
Not sure if I understood it correctly. Do you mean

1. pets kill the dogs/cats/parrots of his owner
2. pets kill the dogs/cats/parrots of other players

?

**Comment by k-jiang** [comment]
=> pets kill the dogs/cats/parrots of his owner <=
Sorry for the late response.
