### ISSUE TITLE
Server restart - pets gone!

### ISSUE THREAD

**Issue by iWessa** [xXKeyleXx/MyPet#1103]
Please provide the following info.
**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.12.2

**MyPet Build/Version:**
Mypet 2.3.3

**Do you use the premium version? (this wont change anything for you)**
No

**What is the expected result?**
After restart pets should be saved!

**What happens instead of that?**
After server is restarted the pets are gone, when I type: /petcall it says: you don't have a pet!

**Error:**
No errors in CLI

I hope you can help me out!

**Comment by xXKeyleXx** [comment]
Did this happened once or does this happen all the time?

**Comment by iWessa** [comment]
I happens all the time.. Do you know how to fix this?

**Comment by xXKeyleXx** [comment]
First off, please give me access to one of your logfiles (gist or pastebin please) from runs where it happened. Even if there are no errors it might help me identify the problem.

**Comment by iWessa** [comment]
Alright. I will show you some pastebins:
Mypet logfile: [Pastebin1](https://pastebin.com/2nuxCNg8)
CLI startup: [Pastebin2](https://pastebin.com/tnJxNy0G)

In the second pastebin there are some errors, which I don't know how to fix, but those are not for MyPet. I know I've got a lot of plugins installed :x

**Comment by xXKeyleXx** [comment]
That's nothing xD I've seen way more.

The log you uploaded only shows the start of a server but not the shutdown. Would you be so kind to start the server, get a MyPet, then stop the server and then give me the log of this run?

**Comment by iWessa** [comment]
Well okay, but that's the only thing that shows up in the logfile? What do you mean by 'this run'? The CLI or the mypet logfile?

**Comment by xXKeyleXx** [comment]
With `run` I meant one iteration of start/do/stop and CLI would be nice.

**Comment by iWessa** [comment]
[There you go](https://pastebin.com/YtXWSGJ6)

**Comment by xXKeyleXx** [comment]
Well your logs didn't gave me much insight xD 

Is there a pets.db file in the MyPet folder? If so could you upload this file here?

**Comment by iWessa** [comment]
https://mab.to/TQkYsN0b8
There you go.

**Comment by xXKeyleXx** [comment]
So the database contains 3 pets from iWessa so they are not gone. When you join the server and have no pet, what happens when you type `/petswitch`?

**Comment by iWessa** [comment]
eh... Okay for some reason they showed up indeed. I'm sorry for this issue. But I'm pretty sure they didn't before I created this comment

**Comment by xXKeyleXx** [comment]
So can I close this issue? If it happens again please tell me about it.

**Comment by iWessa** [comment]
Yes. Thank you very much for your time! I will contact you when it happens again
