### ISSUE TITLE
mypet placeholderapi warning

### ISSUE THREAD

**Issue by 0xC1A551C** [xXKeyleXx/MyPet#1106]
30.03 17:39:39 [Server] WARN [de.Keyle.MyPet.MyPetPlugin] [MyPet] "MyPet v2.3.3" has registered a listener for me.clip.placeholderapi.events.PlaceholderHookUnloadEvent on method "public void de.Keyle.MyPet.util.hooks.PlaceholderApiHook.on(me.clip.placeholderapi.events.PlaceholderHookUnloadEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Keyle].

On startup with the latest placeholderapi / paperspigot.

**Comment by xXKeyleXx** [comment]
Already fixed in the latest dev build: https://mypet-plugin.de/download
