### ISSUE TITLE
LLama

### ISSUE THREAD

**Issue by ColorsASD** [xXKeyleXx/MyPet#1109]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** PaperSpigot-1.12.2-b1384

**MyPet Build/Version:**  MyPet-2.3.4-SNAPSHOT

**Do you use the premium version? (this wont change anything for you)** No!

**What is the expected result?** Capture LLama with lasso.

**What happens instead of that?** The server collapses.

**Error:** https://pastebin.com/bbJU2Gkz

**Comment by ColorsASD** [comment]
Always with every mob as it turned out.

**Comment by ColorsASD** [comment]
Not mypet is the only plugin that crashes and a suspicion of sqlite.

**Comment by ColorsASD** [comment]
an interesting host, skynode

**Comment by xXKeyleXx** [comment]
So you don't think MyPet is the cause?

**Comment by ColorsASD** [comment]
I really hope not.
