### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to MyPet v2.3.4

### ISSUE THREAD

**Issue by huynhqtienvtag** [xXKeyleXx/MyPet#1110]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.12.2
**MyPet Build/Version:**
2.3.4-Lastest Dev-Build
**Do you use the premium version? (this wont change anything for you)**
No
**What is the expected result?**
Spam the console
**What happens instead of that?**
Don't know
**Error:**
https://hastebin.com/wutexuyoko.vbs

**Comment by xXKeyleXx** [comment]
This  is not a bug of MyPet but of EnchantmentAPI. But as EnchantmentAPI seems no to be in development anymore I will make a change that catches this error.
