### ISSUE TITLE
Pets cant use Behavior?

### ISSUE THREAD

**Issue by AshtonMemer** [xXKeyleXx/MyPet#1112]
**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.11.2

**MyPet Build/Version:**
MyPet Version 2.3.4

**Do you use the premium version? (this wont change anything for you)**
No.

**What is the expected result?**
I would like regular players to use Behaviors. I want their pets to attack when a mob is attacked (Normal behavior mode) as well as be able to switch to other behavior modes.

**What happens instead of that?**
The players are told "Your pet does not know the skill Behavior" and cannot change their pet's behavior. Their pets do not attack when they attack a mob. I have it set to where Combat is the only skilltree, and the Skilltree is automatically assigned.

**Error:**
There is no error in the console, just the message saying "Your pet does not know the skill Behavior".

**Comment by xXKeyleXx** [comment]
It's because the pet simply doesn't have the skill. You should lookup how the skill system in MyPet works: 

- https://wiki.mypet-plugin.de/skilltrees
- https://wiki.mypet-plugin.de/skilltreecreator
