### ISSUE TITLE
Disconnecting 1.8 players

### ISSUE THREAD

**Issue by LinsaFTW** [xXKeyleXx/MyPet#1117]
1.12.2 Paper 1410 and Hexacord v130. (Using ViaRewind)

Mypet 2.3.4

No premium version.

Expected:
To open the menu with /petswitch in 1.8 clients.

What happens:
Crashes with [Proxy] disconnected and only works on 1.12 clients.

No errors in the log.

**Comment by xXKeyleXx** [comment]
I don't have a test setup like this. Could you provide some configs and links to what you used?
Also are there any errors in the logs?

**Comment by xXKeyleXx** [comment]
I found the problem but I'm not sure if I would say it's a MyPet problem or a ViaVersion problem.

The problem is caused by the `AttributeModifiers` tag (that MyPet adds to ALL items used by the item menus) on the item which is not converted/removed correctly by ViaVersion.
