### ISSUE TITLE
Factions Hook Bug

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#1118]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.12.2-r0.1-SNAPSHOT
**MyPet Build/Version:**
 MyPet-Premium-2.4.0-SNAPSHOT
**Do you use the premium version? (this wont change anything for you)**
Yes
**What is the expected result?**
Unable to hurt pets in same faction
**What happens instead of that?**
Pets are damaged, and attack same faction ally;
This was discovered while not on faction territory, however FriendlyFire is unallowed in Wilderness as well.
Same Faction players can not harm one another, but pets can be attacked/damaged and do retaliate when struck by a Faction-mate
**Error:**
none

**Comment by zerafox** [comment]
I don't know what was wrong, but it's working fine now. o.o

**Comment by zerafox** [comment]
Okay I take that back.
I forgot we were in an MCMMO party and we couldn't hurt pets.
But the Faction team, on or off Faction Land doesn't make a difference.

**Comment by xXKeyleXx** [comment]
What's your username on the MyPet website?

**Comment by xXKeyleXx** [comment]
fixed in c14df3d92e3dda38553ddcb22eb2d0109ef5b433

**Comment by zerafox** [comment]
Zera_Fox I believe is the name I use there.
