### ISSUE TITLE
你好，请问1.7.2水龙头可以使用吗

### ISSUE THREAD

**Issue by 1425115471** [xXKeyleXx/MyPet#1121]
![image](https://user-images.githubusercontent.com/29402452/39763207-17dbebac-530f-11e8-8a72-dc4df66a0f92.png)

**Comment by Sprungente** [comment]
That has nothing to do with mypet 

No further information here

Vote for closing

**Comment by ScuroK** [comment]
Its not mypet.
Its „clue scrolls“

Close pls

**Comment by ScuroK** [comment]
Btw use english. We dont speak chinese

**Comment by xXKeyleXx** [comment]
Minecraft 1.7.2 is not supported.
