### ISSUE TITLE
Bug: Ranged attack and Shift+RMB clicking

### ISSUE THREAD

**Issue by ArtNRG** [xXKeyleXx/MyPet#1123]
**Bukkit/Spigot/Bungee Build/Version:**
git-Paper-1416 (MC: 1.12.2)
**MyPet Build/Version:**
MyPet 2.3.5 Build: 1229
**Do you use the premium version? (this wont change anything for you)**
Nope
**What is the expected result?**
Shift+RMB only forces the pet with a ranged attack to stay where it is or become moving.
https://youtu.be/CkG-D1Ltutg
**What happens instead of that?**
The pets with a ranged attack skill can shoot without any delay when the user is rapidly clicking Shift+RMB.
**Error:**
There are no console errors.

**Comment by zerafox** [comment]
You don't tell a pet to attack this way.
Shift + RMB is to tell the pet to Stay, not to tell the pet to fire.

The pet can only shoot it's Ranged Attack as quickly as their skill allows them to in their Skill Tree.

**Comment by ArtNRG** [comment]
@zerafox here is the video proof: https://youtu.be/CkG-D1Ltutg

**Comment by zerafox** [comment]
I misunderstood what you were trying to say, I apologize.
Check to be sure this is still an issue in version 2.3.5 Build# 1230 please.

**Comment by ArtNRG** [comment]
2.3.5 Build# 1230 is checked, there is the bug.
