### ISSUE TITLE
Pets Disappear 

### ISSUE THREAD

**Issue by Death1030** [xXKeyleXx/MyPet#1126]
**Bukkit/Spigot/Bungee Build/Version:**
1.12.2

**MyPet Build/Version:**
2.3.4

**Do you use the premium version? (this wont change anything for you)**
No

**What is the expected result?**
I expected that when my players capture a pet or purchase a pet, that when they log off it would be there when they logged back in. 

**What happens instead of that?**
The pets disappear when the user logs off in all cases, regardless of who has it.

**Comment by zerafox** [comment]
What method of saving are you using?
