### ISSUE TITLE
Error Experience fo JavaScript

### ISSUE THREAD

**Issue by KeuponWolf71** [xXKeyleXx/MyPet#1129]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
 Bukkit 1.12.2

**MyPet Build/Version:** 
2.3.4

**Do you use the premium version? (this wont change anything for you)**
 No :/

**What is the expected result?** 
Change experience of pet levels

**What happens instead of that?**
 exp.js does not work

**Error:**
I do not know where this error comes from
![capture](https://user-images.githubusercontent.com/40276430/41432280-c090ddca-7015-11e8-8f82-a76d5e85d312.JPG)
![capture2](https://user-images.githubusercontent.com/40276430/41432281-c0b038be-7015-11e8-8132-f625d14bfc21.JPG)

THX.

**Comment by xXKeyleXx** [comment]
Please the name the rhino jar to `rhino.jar` and try again.

**Comment by KeuponWolf71** [comment]
I do not understand what you want to talk about ?

**Comment by KeuponWolf71** [comment]
Thank you, it works !!!
