### ISSUE TITLE
Players cant store pets or use MyPet NPCs

### ISSUE THREAD

**Issue by hackharvester** [xXKeyleXx/MyPet#1132]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.12.2 R0.1
**MyPet Build/Version:**
2.3.4
**Do you use the premium version? (this wont change anything for you)**
No
**What is the expected result?**
A player should be able to use the npc to store their pets, or use the command to. All permissions are correct.
**What happens instead of that?**
"You are NOT allowed to do that."
**Error:**
Not Available. No error, No log.

**Comment by zerafox** [comment]
What permissions have you given your players?

**Comment by xXKeyleXx** [comment]
If you get that message your permissions are NOT correct.

**Comment by hackharvester** [comment]
I found the problem, turns out an other plugin had corrupted a few files. Apologies. For others, the issue was apparently caused by a bad ProtocolLib jar that scrambled the player's data.
