### ISSUE TITLE
There are no skilltrees available

### ISSUE THREAD

**Issue by Kindogrec** [xXKeyleXx/MyPet#1134]
Please provide the following info.

**I Use Spiggot**

**Version 2.3.4**

**Not Premium**

**My Admins And Other Players Can't Choose Pet Skilltree**

**It Says Something Like This: "There are no skilltrees available for (Pet Name)**

**Any Kind Of Help Is Appreciated**
//Edit* Even Admins Can't Choose Skilltree Even With Every Single Permission They Have

**Comment by xXKeyleXx** [comment]
can OPs choose one?

**Comment by Kindogrec** [comment]
If you mean /op then yes

**Comment by xXKeyleXx** [comment]
Show me your permissions please.

**Comment by Kindogrec** [comment]
- MyPet.admin

and then i tried to add these too

     - MyPet.command.info.other
    - MyPet.command.capturehelper
    - MyPet.command.release
    - MyPet.command.respawn
    - MyPet.command.name
    - MyPet.command.name.color
    - MyPet.command.switch
    - MyPet.command.trade.offer.<MyPet-Type>
    - MyPet.command.trade.receive.<MyPet-Type>
    - MyPet.shop.access.<shopname>
    - MyPet.shop.storage
    - MyPet.petstorage.limit.<limit>
    - MyPet.leash.<MyPet-Type>
    - MyPet.leash.*
    - MyPet.skilltree.<skilltreename>
    - MyPet.extended.feed
    - MyPet.extended.beacon
    - MyPet.extended.behavior.friendly
    - MyPet.extended.behavior.aggressive
    - MyPet.extended.behavior.farm
    - MyPet.extended.behavior.raid
    - MyPet.extended.behavior.duel
    - MyPet.extended.inventory
    - MyPet.extended.ride
    - MyPet.extended.control
    - MyPet.extended.pickup
    - MyPet.extended.equip
    - MyPet.extended.nametag

**Comment by zerafox** [comment]
This permission node here:

> - MyPet.skilltree.<skilltreename>

needs to be replaced with the actual name(s) of the skilltrees:

> - MyPet.skilltree.combat

And so forth, or:

>- MyPet.skilltree.*

If you have made your own custom skilltrees, of course you'll have to use the names you gave your own skilltrees instead of the defaults such as "combat".

**Comment by Kindogrec** [comment]
Thank you SO SO SO MUCH!!!
