### ISSUE TITLE
PetCaptureHelper Command ERROR

### ISSUE THREAD

**Issue by YumeMugen** [xXKeyleXx/MyPet#1136]
Spigot 1.12.2:

MyPet 2.3.4:

Can use /PetCaptureHelper (/pch) Command

Command /PetCaptureHelper (/pch) become unknown command, can't find /PetCaptureHelper (/pch) Command and can't get any pet.

**Comment by zerafox** [comment]
Try updating to the Development build:
MyPet 2.3.5 and see if it resolves your issue.
https://mypet-plugin.de/download
If it does not, please list your permission nodes.

**Comment by xXKeyleXx** [comment]
The free version of the plugin has no CaptureHelper.

**Comment by zerafox** [comment]
I had forgotten there wasn't Capture Helper in the Free Version, it was always there prior to Premium being an option and it must've slipped my mind.

However, being unable to capture a pet must be permission based if anything.

**Comment by xXKeyleXx** [comment]
I removed it some time ago as the free version of it wasn't really helpful 😅
