### ISSUE TITLE
Ride skill - glitching through walls

### ISSUE THREAD

**Issue by ArtNRG** [xXKeyleXx/MyPet#1138]
Players can use pets with ride skills to glitch through walls. 

**Bukkit/Spigot/Bungee Build/Version:**
git-Paper-1475 (MC: 1.12.2)

**MyPet Build/Version:**
MyPet-2.3.5-SNAPSHOT-b#1238

**Do you use the premium version? (this won't change anything for you)**
No

**What is the expected result?**
Players must stay at that position where they were dismounted from their ride pet.

**What happens instead of that?**
Players can glitch through blocks when he dismounting from a pet.

How to reproduce: 
1. Mount your pet. It's easier to reproduce with a small pet like baby chicken or vex.
2. Ride in front of a wall (leave W pressed).
3. Jump and then dismount rapidly.

video: https://youtu.be/6hE-XNVGYo0

Tested with fences, glass panels, iron bars, glass blocks, and even stone blocks in rare case.

**Error:**
There are no console errors.

**Comment by xXKeyleXx** [comment]
I fixed that already but only in the 3.0 beta version this might take some time until I release it :/
