### ISSUE TITLE
mysql cannot connect

### ISSUE THREAD

**Issue by 6700150** [xXKeyleXx/MyPet#1139]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:1.10.2**

**MyPet Build/Version:2.3.4**

**Do you use the premium version? (this wont change anything for you) ：yes！**

**I want to be able to connect to the MySQL database**

**The MySQL database cannot be used**

**Error:**

Sorry, I'm from China, I can't speak English, my MySQL database is not connected. I'd like you to help me see if I have a problem with my configuration, if you understand it.

  Repository:
    Type: MySQL
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      Database: mypet
      TablePrefix: ''
      Host: localhost
      Password: '454841167'
      User: mc
      Port: 3306
      MaxConnections: 64

This is my configuration file，I'm not a novice on the server.I hope you can see that it took me a long time to solve it.

**Comment by xXKeyleXx** [comment]
Are there any errors if you start the server?

**Comment by 6700150** [comment]
Yes, error: Too many connections, but the maximum number of connections for my MySQL configuration is 16384.

**Comment by xXKeyleXx** [comment]
Will close this in favour of #1150
