### ISSUE TITLE
Pets can't be Ridden

### ISSUE THREAD

**Issue by JackWisdom** [xXKeyleXx/MyPet#1141]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.13
**MyPet Build/Version:**
3.0
**Do you use the premium version? (this wont change anything for you)**
yes
**What is the expected result?**
Riding on my pet
**What happens instead of that?**
Nothing happened after I use ride item with my pet(I added Ride skill and it reached right level and I have permissions)
**Error:**
none

**Comment by xXKeyleXx** [comment]
Mounting works fine for me but dismount does not 🤔

**Comment by JackWisdom** [comment]
First I edit the skill tree
then I enabled both fly and riding skill in skilltree on leve1
then restated my server
then Nothing happened after I use the Pet-Ridding item to my pet

**Comment by xXKeyleXx** [comment]
Is it listed under /petskill?
Did you check the "active" checkbox in the SkilltreeCreator?
