### ISSUE TITLE
[Request] Disabling pet riding from CMI

### ISSUE THREAD

**Issue by mercurialmusic** [xXKeyleXx/MyPet#1145]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT
**MyPet Build/Version:**
MyPet-2.4.0-SNAPSHOT-b#574
**Do you use the premium version? (this wont change anything for you)**
Yes
**What is the expected result?**
We have riding pets disabled since we have only wolf, ocelot, and parrot available to all members and the rest of the pet types are "premium". Riding certain pets like bats enables players to fly or hover slightly and endermites allow people to fit through very small spaces (the gaps between stacked chests). We don't want to mess with it so we disable it completely. 
**What happens instead of that?**
A third plugin, CMI, has a /ride command that still allows players to ride their pets. I'm not sure if this should be reported/requested of you or CMI, but it would be useful to have some sort of hook between the two to disallow riding pets.

Strangely, the CMI /ride command does not typically allow the riders to control their mounts except for mobs that are meant to be ridden in vanilla (horses), but when using the CMI /ride command on a MyPet they are able to control the pet.

I know both of these plugins are busy updating to 1.13 right now, so I'm not in a hurry to have this corrected. In the meantime we have limited the CMI /ride command to only a few entity types until we have a solution, but it would be nice to have a full resolution eventually. Thanks for your consideration!

**Error:**
No console errors.

**Comment by xXKeyleXx** [comment]
Could you provice me with a link to the CMI plugin?

**Comment by xXKeyleXx** [comment]
If it is this one

- https://www.spigotmc.org/resources/cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

please upload it here

- https://nextcloud.keyle.de/s/KQ4rGTREERX7Dx9

so I can test it

**Comment by mercurialmusic** [comment]
That's the one.
