### ISSUE TITLE
please add feature to SkilltreeCreator

### ISSUE THREAD

**Issue by JackWisdom** [xXKeyleXx/MyPet#1146]
skilledit->addupgrade>dynamic if I only write "Until level" then Add
it wil lbecome "LEVEL_RULE_EVR.ERY_LEVEL_END" it will only work fine when I fill both "Start from" and "Until level" so why not make it when "Until level" is only filled it means from 0 to where it ends?

**Comment by xXKeyleXx** [comment]
This is just a missing translation. It means every level starting at level 1.
