### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Misio12320** [xXKeyleXx/MyPet#1147]
Hello. I have a suggestion to Plugin MyPet: Edit the Pet HP etc, list of new skilltrees and equipment like hat for small Zombie elytra etc. + MyPet zombie on chicken editable equipment head clothes etc sword/helmet etc

**Comment by zerafox** [comment]
You can create your own skilltrees, and change the pet HP via configuration files already.

You can also equip your pets with items by holding it in your hand and shift+click.
Just remember that even though you put armor on your Zombie, it doesn't help keep him safer. It's only for looks!

**Comment by Misio12320** [comment]
Hmm so suggestion to tame every mob spawned by /summon... I spawned Zombie with Elytra, glass helmet and doesn't worked... :/. Hmm suggestion to create GUI which show the mob like steve and option's  armor sword right hand left hand :thinking:

**Comment by xXKeyleXx** [comment]
Sneaking and rightclicking works fine in 1.12.2

**Comment by Misio12320** [comment]
Ye nvm this. But add support to tame summoned mobs without customing it to normal pls...

**Comment by Misio12320** [comment]
@xXKeyleXx @zerafox why you don't add option to tame custom mob spawned by /summon? ...

**Comment by xXKeyleXx** [comment]
The plugin is not designed to support that.
