### ISSUE TITLE
Start-up Error

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#1149]
So, obviously I use the Premium Version.
And I'm not sure what the cause of this particular error is, it never occurred prior to now.

https://pastebin.com/V3S2Zy6G

This comes up on Plugin-Start.
Except my version number is 2.4.0 in my server. Not sure why this is saying 3.0. o.O
If you remember correctly, I cannot use 3.0 due to inability of inheritance or random skilltree assigning on capture options. Otherwise my whole system just kinda 'carps out'.

We did manage to tie into MyPet to achieve certain functionalities we were looking for, setting targets and all that. But never edited anything else, nor touched MyPet directly as far as editing the plugin itself.

Any ideas would be helpful.

**Comment by xXKeyleXx** [comment]
Are you sure you are not on 3.0? The latest dev builds are on 3.0 now so it might have happened that you (or the auto updater) updated the plugin.

But I will check what might have caused the error.

**Comment by zerafox** [comment]
Whatever version it is, it must've replaced my jar that says MyPet-Premium-2.4.0-SNAPSHOT to do it then.
I can't get anything ingame to work, not even to check the ingame version, though /plugins says it's running.

Also I suppose if the latest dev-builds are intended for 1.13 Minecraft that may be why it's stopped working altogether. Or because I've only got old trees loaded to the server itself?

> MyPet:
  Update:
    Check: true
    Download: true
    ReplaceOld: true
    Token: TOKENHERE
    In-Background: false

**Comment by xXKeyleXx** [comment]
You set `ReplaceOld` to `true` that might be why your 2.4.0 file got overwritten.
If you don't want to use 3.0 yet (as it doesn't fit your skilltree needs) you can use the latest stable release.
