### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#1150]
Upon disabling the auto-updater and returning back to 2.4.0 MyPet Premium I started getting an error related to MySQL.
[https://pastebin.com/PUjYktZf](url)

I wasn't having this problem prior to 'downgrading' MyPet to work again.
It also appears that the NPC has stopped working properly as well. It was working before though.

I am reaching out to multiple plugins in my list to find the source and find a resolution.

**Comment by xXKeyleXx** [comment]
This error occours when there are too many connections to your database server so it's not a downgrade problem ;) 

Could you run this query on your MySQL server (`SHOW PROCESSLIST`) and tell me the output?

**Comment by zerafox** [comment]
I'm not certain how to perform this on a server host.
The MySQL server comes with my Minecraft Server through a hosting service.

**Comment by xXKeyleXx** [comment]
Do you have access to your database through phpmyadmin or some other interface?
