### ISSUE TITLE
NPE on latest build when trying to capture a pet.

### ISSUE THREAD

**Issue by mercurialmusic** [xXKeyleXx/MyPet#1152]
I know you're still working on these, and thanks for your hard work! Just testing to help us get ready for an update and found the following:

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.13 (git-Spigot-fe3ab0d-bfb9131)
**MyPet Build/Version:**
MyPet 3.0 b#592
**Do you use the premium version? (this wont change anything for you)**
Yes
**What is the expected result?**
Capture a pet by hitting it with a lead.
**What happens instead of that?**
The mob takes damage, nothing happens.
**Error:**
https://pastebin.com/Ug9Txu3N

**Comment by xXKeyleXx** [comment]
did you change some of the `LeashRequirements`?

**Comment by mercurialmusic** [comment]
Yes, but only to 'None' (most passive mobs), 'Impossible' (for the ones we wanted to disable), or 'LowHP' (most aggressive mobs). I'm not able to access the pet-config.yml at the moment but I can upload that once I'm home from work tonight.

**Comment by xXKeyleXx** [comment]
The thing is there is no `None` flag anymore 😋 and I didn't add a check for invalid flags. The latest build should fix that.

**Comment by mercurialmusic** [comment]
I tried again with build 594 on the most recent spigot (git-Spigot-fe3ab0d-3418f8d), removing all the 'None' Leash flags and replacing them with brackets. my pet-config.yml here: https://pastebin.com/CuK292H2

Same result, nothing happening when I hit the mob, but no error printed in console this time. 

I also tried toggling the MythicMob hook, no luck either way.

**Comment by zerafox** [comment]
I do believe you actually have to have some kind of leash flag.
Like Keyle said "none" or "[]" isn't a thing anymore.

**Comment by xXKeyleXx** [comment]
Empty brackets should work fine as it should have the same result as the old `None` leash flag  🤔 Will test it again when I get back home

**Comment by mercurialmusic** [comment]
This persists in build 598 without console errors at least, but now I've noticed when trying to enable the pet capture helper it says "You already have a pet" even when there is no pet active. /petsendaway results in "[pet name] has already been sent away." pet-config.yml is unchanged from the one linked above.

**Comment by xXKeyleXx** [comment]
/petsendaway is just to despawn the pet. You have to /petstore the pet to get another one.

**Comment by mercurialmusic** [comment]
Ah, so... yeah. Yeah that was the issue. I'm a moron. My apologies.
