### ISSUE TITLE
enderman crashes server randomly

### ISSUE THREAD

**Issue by SirAbeyance** [xXKeyleXx/MyPet#1154]
1.13, enderman pet crashed server twice now.

https://pastebin.com/8Ls7cCBi

**Comment by xXKeyleXx** [comment]
What build of MyPet are you on?

**Comment by SirAbeyance** [comment]
3.0 snapshot b#1250

**Comment by xXKeyleXx** [comment]
the do please upgrade your MyPet build to the latest...
