### ISSUE TITLE
*BUG* Can't disable pets flying ability

### ISSUE THREAD

**Issue by DrunkIrishPotato** [xXKeyleXx/MyPet#1157]
Please provide the following info.

**Spigot-Version**
Spigot-2440e186304ccd 
Minecraft 1.13.1

**MyPet Build/Version:**
Premium 3.0 SNAPSHOT

**Do you use the premium version? (this wont change anything for you)**
Yes

**What is the expected result?**
Toggle flying off for mobs

**What happens instead of that?**
Random mobs like polar bears and fish can fly and can't find a way to toggle it off

**Error:**

**Comment by zerafox** [comment]
Did you double check within the skilltree editor that Flying for these pets wasn't checked/toggled on?

**Comment by DrunkIrishPotato** [comment]
How did i not see that, thank you so much for the help.
