### ISSUE TITLE
WG: Creature Spawn Event 

### ISSUE THREAD

**Issue by EduBRz** [xXKeyleXx/MyPet#1158]
Spigot 1.13

MyPet-Premium-3.0-SNAPSHOT    #598  

ERROR Could not pass event CreatureSpawnEvent to WorldGuard v7.0.0-SNAPSHOT

https://pastebin.com/RmUdWKLb

Mypet-log https://pastebin.com/6PtcfrhR

[MyPet.log](https://github.com/xXKeyleXx/MyPet/files/2346495/MyPet.log)

**Comment by zerafox** [comment]
This is a World Guard Error that must be resolved on their end. 
Keyle has already reported it to WG team, but there is nothing that MyPet can do for this error.

**Comment by xXKeyleXx** [comment]
https://dev.enginehub.org/youtrack/issue/WORLDGUARD-3971
