### ISSUE TITLE
PetBeacon not working

### ISSUE THREAD

**Issue by miniharry** [xXKeyleXx/MyPet#1159]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**

git-Spigot-2440e18-60d7982 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**MyPet Build/Version:**

Latest dev build

**Do you use the premium version? (this wont change anything for you)**

Yes

**What is the expected result?**

/petbeacon -> opens the beacon menu

**What happens instead of that?**

Your pet doesnt know this skill

**Error:**

Using default config. Looked through and can't find where to fix this. Thanks for the help, I'm probably missing something.

**Comment by zerafox** [comment]
You won't find this in a config file.
Check the Skilltrees for the Beacon Skill.

It's likely you are using a Skilltree that doesn't have it.
