### ISSUE TITLE
Can't set custom lore food spigot 1.13.1

### ISSUE THREAD

**Issue by ValerianV** [xXKeyleXx/MyPet#1160]
Please provide the following info.

Item in game

![image](https://user-images.githubusercontent.com/42415928/45520616-6d477600-b7ba-11e8-8358-24fb6aebdf0c.png)

Config 

![image](https://user-images.githubusercontent.com/42415928/45520668-ba2b4c80-b7ba-11e8-87ea-27ac973ef080.png)

**Bukkit/Spigot/Bungee Build/Version:** Spigot 1.13.1

**MyPet Build/Version:** 3.0 dev build

**Do you use the premium version? (this wont change anything for you)** Yes

**What is the expected result?** Pet accept custom food with lore

**What happens instead of that?** It doesn't accept the food

**Error:** No Logs

**Comment by xXKeyleXx** [comment]
Please try:
`minecraft:beef {display:{Name:"Wolf Food",Lore:["Tasty wolf food","Tastes like banana"]}}`

**Comment by ValerianV** [comment]
I tried and when i do this it accept a beef without the lore
a simple beef
+ it doesn't accept the one with good lore
So this  syntax doesn't work neither : - minecraft:beef {display:{Name:"1",Lore:["2","2"]}}
(i changed the name and lore for simplicity )

**Comment by xXKeyleXx** [comment]
try download the latest build and try this again:
`minecraft:beef {display:{Name:"{\"text\":\"Wolf Food\"}",Lore:["Tasty wolf food","Tastes like banana"]}}`
