### ISSUE TITLE
Pets destroy protected turtle eggs walking

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1168]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-332 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**MyPet Build/Version:**
MyPet version 3.0

**Do you use the premium version? (this wont change anything for you)**
Yes

**What is the expected result?**
Pets destroy protected turtle eggs walking (PlotSquared, WorldGuard)

**What happens instead of that?**
Pets no destroy protected turtle eggs walking (PlotSquared, WorldGuard)

**Error:**

**Comment by yannicklamprecht** [comment]
It seems that you swapped the expected and instead. 

Expected -> what should it do
Instead -> what happened that should not happen.
