### ISSUE TITLE
1.13.1 error/bug

### ISSUE THREAD

**Issue by ErlinaEzka** [xXKeyleXx/MyPet#1169]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
--Spigot 1.13.1 
**MyPet Build/Version:**
--2.3.5
**Do you use the premium version? (this wont change anything for you)**
--no
**What is the expected result?**
--the plugin working like the tutorial(https://www.youtube.com/watch?v=mrNVmP5v8go)/description 
**What happens instead of that?**
--command wont get any respond 
**Error:**
-- is it because it isnt compatible yet or there is somthing wrong with the server/plugin?

**Comment by Sprungente** [comment]
Maybe try the 3.0 Devbuild 

but beware 3.0 is in development and is very experimental. The Skillcreater has been redone. 
So try out. If you have any questions you can ask the mypetcommunity in discord and/or check mypet-wiki

**Comment by xXKeyleXx** [comment]
MyPet 2.3.5 is not compatible with 1.13+
Use the 3.0 dev builds instead: https://mypet-plugin.de/download
