### ISSUE TITLE
Create a pet with custom speed

### ISSUE THREAD

**Issue by Tiplish** [xXKeyleXx/MyPet#1171]
Hi,

I would know if it's possible to custom the speed more precisly than the same speed for every TYPE. 

For example : 
White horse, speed at 50
Black horse, speed at 100.

I'm not sure that it is already implemented.

**Comment by xXKeyleXx** [comment]
This is not possible atm and I don't think I will add that :/

**Comment by Tiplish** [comment]
Ok thanks for this fast answer :) i will just use Donkey < mule < horse speed o/
