### ISSUE TITLE
Help solve the problem :)

### ISSUE THREAD

**Issue by GoodGameMesti** [xXKeyleXx/MyPet#1172]
Hello, I communicate with the help of an interpreter, so I apologize for the mistakes.
Install your plugin My Pet, everything works great , except for one. Players can't choose the profession Pets, I'm with op can, but playing like the player writes "no skills pet name" , how to fix it and to include their skills?

**Comment by xXKeyleXx** [comment]
Add `MyPet.skilltree.*` to your permissions:
https://wiki.mypet-plugin.de/permissions
