### ISSUE TITLE
[Bug]The mount speed doesn't change

### ISSUE THREAD

**Issue by Tiplish** [xXKeyleXx/MyPet#1175]
**Bukkit/Spigot/Bungee Build/Version:**
spigot 12.2
**MyPet Build/Version:**
2.3.5
**Do you use the premium version? (this wont change anything for you)**
no
**What is the expected result?**
Change the speed of my mount when i set speed at 5% for the ride skilltree
**What happens instead of that?**
the speed is alwas the same, even if i change the speed by set or add number in the Ride skill for pet level 1.
**Error:**
No error in console :(

**Comment by xXKeyleXx** [comment]
This bug was fixed in the latest 3.0 dev build but as this changes quite a lot (skilltree wise) it's up to you to upgrade. This bug will not be fixed in 2.X versions
