### ISSUE TITLE
[Question] Using MythicMob

### ISSUE THREAD

**Issue by Tiplish** [xXKeyleXx/MyPet#1176]
Hi,

I've seen here : https://wiki.mypet-plugin.de/plugins/premium30
That you will allow to use Mythicmob as pet type. Is that true? Skilltree will be available with MM too? 

Thanks :)

**Comment by xXKeyleXx** [comment]
You have more control about which MM mobs you can make a pet but they will still be converted to normal pets, so don't get too excited 😛

**Comment by Tiplish** [comment]
mmmh ok so, what the compatibility with MM add? i'm not sure to have understand :(

**Comment by xXKeyleXx** [comment]
It will allow you to specify exactly what MM mobs can be made a pet

**Comment by xXKeyleXx** [comment]
So they don't try to make a uber boss a pet and get disappointed

**Comment by Tiplish** [comment]
So for example, is it possible to have a specific mount speed for a specific MM mob? For example a white horse MM ? ^^"

**Comment by xXKeyleXx** [comment]
No it just say which MM mobs CAN be captured and which NOT

**Comment by Tiplish** [comment]
haaaa ok i understand o/

**Comment by Tiplish** [comment]
So i will close this, thanks for your help :)
