### ISSUE TITLE
Horse mob type affect Donkey and Mule

### ISSUE THREAD

**Issue by Tiplish** [xXKeyleXx/MyPet#1177]
**Bukkit/Spigot/Bungee Build/Version:**
Spigot 12.2
**MyPet Build/Version:**
 MyPet-3.0-SNAPSHOT #1280  
**Do you use the premium version? (this wont change anything for you)**
No
**What is the expected result?**
Only Horse are impacted when i select mob type "horse" for a skilltree
**What happens instead of that?**
Mule and Donkey get the horse skilltree too. 
**Error:**
No error in console

**Comment by xXKeyleXx** [comment]
Are you sure you selected only the horse because it works fine for me 🤔 Could you attach your skilltrees?

**Comment by Tiplish** [comment]
[Equitation3.st.zip](https://github.com/xXKeyleXx/MyPet/files/2498170/Equitation3.st.zip)

Yes i'm sure, i've checked the file :(

**Comment by xXKeyleXx** [comment]
Did you properly reload the skilltrees?
Could you attach the whole MyPet folder?

**Comment by Tiplish** [comment]
[MyPet.zip](https://github.com/xXKeyleXx/MyPet/files/2498215/MyPet.zip)

**Comment by Tiplish** [comment]
I've reload the serv and /petadmin reload ^^"

**Comment by xXKeyleXx** [comment]
It still works perfectly fine 🤷‍♂️ all 3 pets have a Equitation skilltree but all of them have different numbers.

**Comment by Tiplish** [comment]
Wtf :'(

**Comment by xXKeyleXx** [comment]
Do you have a server I can join?

**Comment by Tiplish** [comment]
Ok i've done many changes with the config and now it works. Don't know what happend :s thanks for your help :)
