### ISSUE TITLE
Looping Error Crashes Server

### ISSUE THREAD

**Issue by nexlemav** [xXKeyleXx/MyPet#1178]
Please provide the following info.

spigot-1.13.2-R0.1-SNAPSHOT-b1962.jar

MyPet-Premium-3.0-SNAPSHOT.jar # 624

Premium version

Server crash occurs when players try to run certain /mypets commands. Log linked below
[latest.log](https://github.com/xXKeyleXx/MyPet/files/2510790/latest.log)

**Comment by xXKeyleXx** [comment]
against your infos you are not using MyPet-Premium-3.0-SNAPSHOT.jar # 624.
it even says in the logs that a new version is available...

```
######################################
#  A new build is available: 3.0-SNAPSHOT #624   #
#  https://mypet-plugin.de/download                   #
######################################
```
