### ISSUE TITLE
1.8.8spigot, EnderDragon can't ride

### ISSUE THREAD

**Issue by 1425115471** [xXKeyleXx/MyPet#1179]
Hello, author。
1.8.8spigot, EnderDragon can't ride。
MyPet-Premium-2.3.9.jar

**Comment by xXKeyleXx** [comment]
I know about that and it will never change in pre 3.0 builds.

**Comment by 1425115471** [comment]
Is version 3.0 ready to ride

**Comment by xXKeyleXx** [comment]
yes
