### ISSUE TITLE
MyPet GUI suggestion

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#1180]
While you plan to make a GUI on pet right click in the future, I might have another idea.

I made my own GUI and maybe it would be nice to link it thru the configuration.

command_on_right_click: "/pet"

This would then open my own made pet menu (made in BossShopPro)

**Comment by xXKeyleXx** [comment]
Yeah that's what I planned. Plus I want to add custom rewards (for BossShopPro) so you don't have to rely on commands to execute correctly.

**Comment by xXKeyleXx** [comment]
#818

**Comment by Sikatsu** [comment]
Awesome. Hope it will be implemented soon xD
