### ISSUE TITLE
Help plugin empty 1.13

### ISSUE THREAD

**Issue by amtaroletueur** [xXKeyleXx/MyPet#1182]
I can not run the MYPET plugin in 1.13 indeed it starts correctly in green etc but no command produced something like if the plugin was empty I really like this plugin I need your help
no error on console just nothing and no powerful

**Comment by xXKeyleXx** [comment]
Could you please provide me with a server log?

**Comment by amtaroletueur** [comment]
Hello a have resolve the probleme i have take the snapshot it’is powerfull thx my friend


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Sebastian Comans <notifications@github.com>
Envoyé : Wednesday, November 7, 2018 8:33:09 PM
À : xXKeyleXx/MyPet
Cc : amtaroletueur; Author
Objet : Re: [xXKeyleXx/MyPet] Help plugin empty 1.13 (#1182)


Could you please provide me with a server log?
