### ISSUE TITLE
/petskill not support format codes (skill name)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1184]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-447 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**MyPet Build/Version:**
[MyPet] MyPet-3.0-SNAPSHOT-b#633

**Do you use the premium version? (this wont change anything for you)**
yes

**What is the expected result?**
work color and format codes

**What happens instead of that?**
not work color and format codes

**Error:**
![jegyzet 2018-11-16 230127](https://user-images.githubusercontent.com/8324198/48649760-fc0f8380-e9f3-11e8-9763-4f64b62707e5.jpg)

**Comment by zerafox** [comment]
Formatting Skilltree names is not possible.
Formatting is for pet names.

**Comment by andris155** [comment]
This format works perfectly on /pcst gui. Why not possible?

**Comment by zerafox** [comment]
Not possible because it wasn't designed that way.
It wasn't intended to format Skilltree names in this manner.

You can try using the & color codes to see if it works, but like I said I don't believe it was written or designed to do so.
In which case, makes it not a bug. :P

**Comment by xXKeyleXx** [comment]
It should work so it might just be a missing translation of the codes. will fix this
