### ISSUE TITLE
legacy Skilltree importer not import petbeacon Buffs

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1185]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-447 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**MyPet Build/Version:**
[MyPet] MyPet-3.0-SNAPSHOT-b#633

**Do you use the premium version? (this wont change anything for you)**
yes

**What is the expected result?**
legacy Skilltree importer import petbeacon  Buffs

**What happens instead of that?**
legacy Skilltree importer not import petbeacon  Buffs

**Error:**

**Comment by xXKeyleXx** [comment]
Do you have a skilltree file for me?

**Comment by xXKeyleXx** [comment]
fixed in the latest dev build
