### ISSUE TITLE
[Website] Premium Particles not works perfectly (translator + premium mypet)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1186]
If you bought mypet and help translate mypet Premium Particles name setting not works perfectly.
Open site:
![jegyzet 2018-11-16 231153](https://user-images.githubusercontent.com/8324198/48650050-0aaa6a80-e9f5-11e8-94a8-c12dbe52891a.jpg)
Click save (Not edited names)
![jegyzet 2018-11-16 231247](https://user-images.githubusercontent.com/8324198/48650090-27df3900-e9f5-11e8-8931-b10125d9f83a.jpg)
Click save again (not edited names)
![jegyzet 2018-11-16 231316](https://user-images.githubusercontent.com/8324198/48650118-3f1e2680-e9f5-11e8-9287-5c809cb28fc1.jpg)

**Comment by xXKeyleXx** [comment]
Where does Babi comes from? Was it a name you entered before? Or does it just pop up?

**Comment by andris155** [comment]
I entered Babi name before.
