### ISSUE TITLE
How to set pets not to fly.

### ISSUE THREAD

**Issue by 1425115471** [xXKeyleXx/MyPet#1188]
I found someone riding a spider that can fly, level 16

**Comment by xXKeyleXx** [comment]
There is a reason for the template:

Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**Do you use the premium version? (this wont change anything for you)**

**What is the expected result?**

**What happens instead of that?**

**Error:**
