### ISSUE TITLE
What is capturehlper

### ISSUE THREAD

**Issue by Gartentrulla** [xXKeyleXx/MyPet#1192]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
spigot1.13.2

**MyPet Build/Version:**
640 Premium
**Do you use the premium version? (this wont change anything for you)**
yes
**What is the expected result?**
nothing, It say's capturehelper is on.
**What happens instead of that?**
nothing
**Error:**
no error

I don't know, what the capturehelper makes. I activated it ingame, but nothing happend. Please can you explain, what it makes. Thank you. Sorry my bad english, I'm German.  Greets from Gartentrulla

**Comment by xXKeyleXx** [comment]
It shows particles above the head of mobs:
green -> hit it and it will be your pet
red -> some requirement is not yet met

**Comment by Gartentrulla** [comment]
Thanks very much for your help
