### ISSUE TITLE
Problem with (mypet-deny flag) in WorldGuard 6.1

### ISSUE THREAD

**Issue by FabioPretti** [xXKeyleXx/MyPet#1196]
**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.8.8

**MyPet Build/Version:**
MyPet 2.3.5

**Do you use the premium version? (this wont change anything for you)**
No

**What is the expected result?**
(mypet-deny flag) works in WorldGuard 6.1

**What happens instead of that?**
Does not work in WorldGuard 6.1

**Error:**
Error not

**Comment by xXKeyleXx** [comment]
WorldGuard 6.1 has no custom flag support as far as I know

In case you use 6.2 I fixed something related to this.

**Comment by xXKeyleXx** [comment]
I would say creating this issue was way more efficent than your review 🤷‍♂️
