### ISSUE TITLE
No write full petname chat

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1197]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/2689427/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-477 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**MyPet Build/Version:**
[MyPet] MyPet-3.0-SNAPSHOT-b#652

**Do you use the premium version? (this wont change anything for you)**
yes

**What is the expected result?**
Write full pet name chat.

**What happens instead of that?**
No write full petname chat

**Error:**
![50109051-0dd48880-0237-11e9-9462-4ee23f078bbf](https://user-images.githubusercontent.com/8324198/50139410-f2529780-02a1-11e9-80a4-6a3a81c3f4db.png)

**Comment by xXKeyleXx** [comment]
Does this happen for all names or just that one?

I tried it and it seems to work for me 🤔 
![2018-12-18_21 28 34](https://user-images.githubusercontent.com/631504/50181200-08953d80-030c-11e9-95f4-37b82fd8bb56.png)

**Comment by andris155** [comment]
Just that one

**Comment by xXKeyleXx** [comment]
Could you show me the command you used to set the name?

**Comment by andris155** [comment]
/petname &4&lH&c&le&4&lr&c&lm&4&la&c&le&4&lu&c&ls &4&lM&c&lo&4&lr&c&la

**Comment by xXKeyleXx** [comment]
You should have told me that it attaches the last r to the nametag instead of it missing in the chat 😛
