### ISSUE TITLE
Party Data?

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#1201]
Is there something in the API that allows another Plugin's Party Mechanics to be registered?

I ask for purposes of making MyPet's Beacon and other "Party Related" functions to work properly with a custom plugin.
If it does exist, if you could direct me to where in the API I could find this information, that would be great!
If not, would it be possible to add one?

**Comment by xXKeyleXx** [comment]
The easiest way is to look at the mcmmo hook:
https://github.com/xXKeyleXx/MyPet/blob/master/modules/Plugin/src/main/java/de/Keyle/MyPet/util/hooks/McMMOHook.java

This hook must be registered like this: https://github.com/xXKeyleXx/MyPet/blob/master/modules/Plugin/src/main/java/de/Keyle/MyPet/MyPetPlugin.java#L447

**Comment by zerafox** [comment]
Even if this plugin is a private plugin?
I haven't asked for the support as this is not a plugin anyone else will ever be using. :o

**Comment by xXKeyleXx** [comment]
In this case you should do it yourself 😇 
But I will improve the API for you so it's easier to register hooks.

**Comment by zerafox** [comment]
Very much appreciated! Thank you!
<3
