### ISSUE TITLE
/petrelease reset Villager Career

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1209]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/2773305/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-500 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**MyPet Build/Version:**
[MyPet] MyPet-3.0-SNAPSHOT-b#697

**Do you use the premium version? (this wont change anything for you)**
yes

**What is the expected result?**
/petrelease no reset Villager Career

**What happens instead of that?**
/petrelease reset Villager Career

**Error:**

**Comment by xXKeyleXx** [comment]
I just tried it and it seems to work fine for me. What type of villager did you try?

**Comment by andris155** [comment]
![jegyzet 2019-01-18 205714](https://user-images.githubusercontent.com/8324198/51410164-1684eb00-1b64-11e9-9c25-8b8467857233.jpg)
Blue = MyPet save perfectly and no reset /petrelease
Green = MyPet not save this and reset /petrelease

**Comment by xXKeyleXx** [comment]
ahhhh I see....

**Comment by xXKeyleXx** [comment]
I tried it again and still the same result for me.

I leashed a sheperd and after releasing it multiple times it stayed a sheperd 🤔 

Do you have any plugins that modify villagers?

**Comment by andris155** [comment]
ShopKeepers

**Comment by andris155** [comment]
I tested with latest version, and fixed this.
