### ISSUE TITLE
Vex does not show angry appearance

### ISSUE THREAD

**Issue by OpalMoonstride** [xXKeyleXx/MyPet#1214]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.

**Bukkit/Spigot/Bungee Build/Version:** 
Paper Spigot 1.13.2
**MyPet Build/Version:** 
3.0 snapshot b#733
**Do you use the premium version? (this wont change anything for you)** 
Yes

**What is the expected result?** Would you be able to add the angry-vex appearance, to the aggressive-mode vex pet? Assuming this isn't a bug, although I do see it in the image in this report: https://github.com/xXKeyleXx/MyPet/issues/937#issue-196451614

**What happens instead of that?** Image below is the normal, and angry, vex. I only see the normal when it's set to aggressive. I notice the enderman shakes and screams when aggressive.

[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/2830872/ticket.zip)
![image](https://user-images.githubusercontent.com/39387146/52255001-9807a780-28de-11e9-9ed3-b89ecbf215b3.png)

**Comment by xXKeyleXx** [comment]
Great idea!

**Comment by OpalMoonstride** [comment]
I saw the commit made to the free version, but I use the premium. Will it be added there, too? I didn't want to lose some of the premium features for the vex skin. If it's safe to inject the update, for 3.0 premium, though, I can do that. 

Thanks so much!

**Comment by xXKeyleXx** [comment]
oops 😅
