### ISSUE TITLE
PetInventory DUPLICATION BUG

### ISSUE THREAD

**Issue by relucaXIV** [xXKeyleXx/MyPet#1215]
I'm sorry I can't use /petadmin ticket command but I will explain how the bug works:
**Build:** MyPet-3.0-SNAPSHOT#1385
**ServerVersion:** PaperSpigot 1.13.2
**Do you use the premium version? (this wont change anything for you):** No
1. Open the PetInvenotry, insert the item you want to duplicate, close the inventory and left the game.
2. Join the game, take the item from the inventory, change world, left the game.
3. Join the game, come back to the first world, open the inventory and you will find the item like if you din't take it. So you have 1 item you took from the inventory before change world and left, and another one into the inventory, like if you have never taken it.

P.S. The second world I guess has to have MyPets disabled.

**Comment by relucaXIV** [comment]
I edited the steps, now is right

**Comment by relucaXIV** [comment]
Another thing: it could work not only with Disabled Worlds, but with World Groups: this is only an hypotesis

**Comment by xXKeyleXx** [comment]
Hey there Sorry for the super late response. I finally got the time to look into this problem but I can't reproduce the problem. Could you tell me a bit more about your server setup?

**Comment by Zytan27** [comment]
Something that appears extremely similar to this is occurring on our server. The bug still seems to be happening. Is there any other information I can provide that may help?

**Comment by zerafox** [comment]
Sure, a new ticket with the information you have.
This is an old bug, with old information using an old version.
