### ISSUE TITLE
MyPet /petstore

### ISSUE THREAD

**Issue by CircusCow** [xXKeyleXx/MyPet#1228]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.

Players cannot use the /petstore command. I've tried every permission I can think of but cant find the exact permission node anywhere. 

 Spigot 1.13

MyPet 3.0

No

Allowed permission

No permission

[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/2949701/ticket.zip)

**Comment by xXKeyleXx** [comment]
Have you tried `MyPet.command.switch` and  `MyPet.petstorage.limit.<limit>` (replace limit with the number of pet the player should be able to store)?
