### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by polo002** [xXKeyleXx/MyPet#1229]
**Hi, upon starting the plugin. this error occurs:**

13.03 11:35:01 [Server] INFO [MyPet] Loading MyPet v2.3.5
13.03 11:35:01 [Server] ERROR sun.reflect.annotation.EnumConstantNotPresentExceptionProxy initializing MyPet v2.3.5 (Is it up to date?)
13.03 11:35:01 [Server] INFO java.lang.ArrayStoreException: sun.reflect.annotation.EnumConstantNotPresentExceptionProxy
13.03 11:35:01 [Server] INFO at sun.reflect.annotation.AnnotationParser.parseEnumArray(AnnotationParser.java:744) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:533) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at java.lang.Class.createAnnotationData(Class.java:3521) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at java.lang.Class.annotationData(Class.java:3510) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at java.lang.Class.getAnnotation(Class.java:3415) ~[?:1.8.0_191]
13.03 11:35:01 [Server] INFO at de.Keyle.MyPet.util.ConfigurationLoader.setDefault(ConfigurationLoader.java:193) ~[?:?]
13.03 11:35:01 [Server] INFO at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:110) ~[?:?]
13.03 11:35:01 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:320) [spigot-1.13.jar:git-Spigot-fe3ab0d-bfb9131]

**Comment by zerafox** [comment]
Is there a reason you completely ignored the ticket formatting?

We need more than an error to be able to help you.

**Comment by xXKeyleXx** [comment]
Don't try to load MyPet 2.3.5 on MC 1.13+. Use the latest dev build for that!
