### ISSUE TITLE
FAWE Worldguard Error

### ISSUE THREAD

**Issue by JohnS19** [xXKeyleXx/MyPet#1231]
**Bukkit/Spigot/Bungee Build/Version:**    Paper 559

**MyPet Build/Version:**   2.3.5

**What is the expected result?**  Worldguard to pass event normally.

**What happens instead of that?** Worldguard freaks out

**Error:**
https://hastebin.com/ruqaxiqilo.sql

**Comment by xXKeyleXx** [comment]
If you stay on 2.3.5 you have to live with that error. It doesn't affect the server at all.
You could upgrade to 3.0 and the error should be gone.
