### ISSUE TITLE
BossShop cannot display placeholder

### ISSUE THREAD

**Issue by ProjectSky** [xXKeyleXx/MyPet#1236]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.

**Spigot Version: 1.13.2**

**MyPet Version: 3.0**
**BossShop Version: 2.0.2**

**What is the expected result?**
display placeholder

**What happens instead of that?**
not display placeholder

**Error:**
no error

**Comment by xXKeyleXx** [comment]
Do you talk about PlaceholderAPIs placeholders?

**Comment by ProjectSky** [comment]
> Do you talk about PlaceholderAPIs placeholders?

Yes.
