### ISSUE TITLE
Custom items format not working

### ISSUE THREAD

**Issue by jeannen** [xXKeyleXx/MyPet#1238]
I'm trying to set a custom item (name/lore) as leash item, but it doesn't seems to work. I can use the "normal" item AND the item with custom name/lore, it's the same

I used https://wiki.mypet-plugin.de/setup/configurations/configitems to configure the leash item in my file 

Any idea of how can I fix it ? ^^

------------------------

Ticket.zip: https://www.mediafire.com/file/vtmc4if6zt3dzjc/ticket.zip/file

Spigot version: http://prntscr.com/n4paw5

MyPet version: 3.0 12725

Not being able to tame a pet with a default item

I was able to tame the pet

No error message

**Comment by xXKeyleXx** [comment]
Could youI don't know why but the new wiki had the old content which was not updated for MyPet 3.0. Please try it again with the latest instructions.

**Comment by jeannen** [comment]
Hello,

It seems like it's not working at all now :(


`      LeashItem: iron_pickaxe {display:{Name:"{\"text\":\"Pierremax\"}"},Damage:1,Unbreakable:1}
`

**Command:** /give @p minecraft:iron_pickaxe{display:{Name:"{\"text\":\"Pierremax\"}"},Damage:1,Unbreakable:1} 1

It just kill the mob


If I use this instead, a normal iron pickaxe without the name works too.
`      LeashItem: iron_pickaxe {display:{Name:"{"text":"Pierremax"}"},Damage:1,Unbreakable:1}
`

**Comment by xXKeyleXx** [comment]
The check actually works but the plugin does check a little but too strict. It works when you add a `b` to the 1 of unbreakable:
`LeashItem: iron_pickaxe {display:{Name:"{\"text\":\"Pierremax\"}"},Damage:1,Unbreakable:1b}`

I added a command to the latest version that helps with that. It shows the item in you hand in the server logs: `/petadmin info item`

**Comment by jeannen** [comment]
I just tested with a renamed poratoe, it doesn't works, even after copy/paste the `/petadmin info item`

**Comment by xXKeyleXx** [comment]
Show me the items you want to use and I will try to help you

**Comment by jeannen** [comment]
> Show me the items you want to use and I will try to help you

I'm using this one as a test: LeashItem: glowstone_dust{"display":{"Name":"[{\"text\":\"&fPowder\"}]"}} 1

But no matter what I do it doesn't seems to work anyway :(

I tried the /petadmin info item copy/paste doesn't work either

**Comment by xXKeyleXx** [comment]
As I said it works perfectly fine. Your config is just not correct:
`glowstone_dust {display:{Name:'{"text":"§fPowder"}'}}`

**Comment by jeannen** [comment]
Yeah but it also works with normal glowstone...

**Comment by jeannen** [comment]
Yeah, but it also works with normal glowstone...

**Comment by xXKeyleXx** [comment]
No it does not.

**Comment by xXKeyleXx** [comment]
I just tried it myself...

**Comment by jeannen** [comment]
For some reason it wasn't working after the /petadmin reload, it seems like it's foxed now, thanks ^^
Does it also check the new Custom Texture option from 1.14 ?

**Comment by xXKeyleXx** [comment]
It should as it is part of the NBT data 🤔

**Comment by jeannen** [comment]
Yeah that's cool, I'm going to make capture pods instead of just a leash ^^

**Comment by xXKeyleXx** [comment]
Could you send me an image when you are done?

**Comment by jeannen** [comment]
Sure ! Idk when it will be done however, I have tons of things to configure :P

**Comment by jeannen** [comment]
I'm making some tests atm, the formating is really hard to use to be honest, especially since the /petadmin infoitem isn't working...

Any way you could add a classic and full YAML on-demand-formating, like in BossShopPro ?

If I want something basic:
```
#Default
LeashItem: CARROT_ON_A_STICK
    Name: "&eCapture pod"
```

If I want something advanced:
```
#Advanced
LeashItem: CARROT_ON_A_STICK
    Name: "&eCapture pod"
    Lore: 
        - "&aWow, that looks &cPokecool"
        - "&3You can capture mobs with this"
    CustomModelData: 3
   
```
