### ISSUE TITLE
Version not loading

### ISSUE THREAD

**Issue by IGDT** [xXKeyleXx/MyPet#1239]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue. 

I can't due to the plugin not starting up

**Bukkit/Spigot/Bungee Build/Version:** paperspigot 1.13.2

**MyPet Build/Version:** latest

**What is the expected result?** to work on 1.13.2

**What happens instead of that?** the plugin won't start up

**Error:**
[error.txt](https://github.com/xXKeyleXx/MyPet/files/3080647/error.txt)

**Comment by xXKeyleXx** [comment]
Mypet 2.3.5 doesn't work with MC 1.13+. Use the latest devbuild!
