### ISSUE TITLE
Errors/Warnings about mysql spamming console

### ISSUE THREAD

**Issue by IITFA** [xXKeyleXx/MyPet#1240]
Today it seems out of nowhere I started getting generic warnings in the console. After some investigation, it seems to be related to MyPet.

https://hastebin.com/afadateliz.sql

**Bukkit/Spigot/Bungee Build/Version:**
Paper version git-Paper-622 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**MyPet Build/Version:**
MyPet-3.0-SNAPSHOT.jar (1408)

**Comment by xXKeyleXx** [comment]
Append `?useSSL=false` to the database name in the config.
