### ISSUE TITLE
My pet HELP!

### ISSUE THREAD

**Issue by RomanSoldier0008** [xXKeyleXx/MyPet#1241]
*Spigot 1.12.2
*MyPet Build/Version: #MyPet 2.3.5
  
My pets works when you are in OP but not with the default range. I commented that if the permits are enabled. To the default range it says (when hitting the rope with anything except animals): "You are not allowed to do that." Are you in the right mode? My server is from Towny ...

When killing a mob with a rope, it does not become a pet.

**Comment by xXKeyleXx** [comment]
When you can do things when you are OP but not without your permission setup is not correct.
Please look at the wiki for more info: https://wiki.mypet-plugin.de/v/legacy/setup

**Comment by RomanSoldier0008** [comment]
But it's obvious, that I install it correctly

**Comment by xXKeyleXx** [comment]
There is no file called like this. This is a config option in config.yml

Does your pet has the ride skill?
