### ISSUE TITLE
Equipment can not be changed

### ISSUE THREAD

**Issue by Gartentrulla** [xXKeyleXx/MyPet#1244]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.
https://www.katzebiggi.de/downloads/ticket.zip
**Bukkit/Spigot/Bungee Build/Version:**
spigot 1.13.2
**MyPet Build/Version:**
mypet dev build 3.0#1417
mypet dev builld 3.0#1416
**What is the expected result?**
nothing
**What happens instead of that?**
nothing
**Error:**
nohing

Hello keyle, as I had the premium version of mypet I bought a Pet and changed the equip. Now you integrated it in the free version, and I don't can switch the equip.  On my local Server I tried the Version 1417 and on my online Server the 1416. Both are not working.
What can I do? I found a permission in your plugn.yml with mypet.extendet.equip, but this doesn't work also.
As you changed from premium to free I gerneratet all files new.
How can I change now the equip of my pet?

Thanks a lot for your help and sorry my englisch, I'm German.

With best regards your Gartentrulla

**Comment by Gartentrulla** [comment]
Sorry the wrong Link.
https://www.katzebiggi.de/download/ticket.zip

**Comment by xXKeyleXx** [comment]
> As you changed from premium to free I gerneratet all files new.
Das war nicht nötig

Ich kann dir leider so nicht sagen woran es liegen könnte und ob es ein Problem in MyPet ist. Ich schau mir das später mal an wenn ich wieder zuhause bin.

**Comment by Gartentrulla** [comment]
Vielen Dank für die schnelle Rückmeldung (in Deutsch)
Grüsse von Gartentrulla

**Comment by xXKeyleXx** [comment]
Ich habs jetzt mal mit Zombies ausprobiert und bei mir gehts ohne Probleme 🤔 Duckst du dich auch bevor du den Rechtsklick machst?

**Comment by Gartentrulla** [comment]
Vielen Dank, das hatte ich glatt vergessen nach fast 1 Jahr. Getestet und funktioniert.
Grüße von Oma Gartentrulla
