### ISSUE TITLE
Question: permission to store pet not working on 1.14.1

### ISSUE THREAD

**Issue by comonier** [xXKeyleXx/MyPet#1245]
Server version: git-Spigot-4f661b2-d06991d (MC: 1.14.1)
Plugin version: MyPet-3.0-SNAPSHOT.jar [latest build]

I already have permissions up but players cant use store comand: /pst
all other commands and function working, while op i have permission to use pst

**Comment by comonier** [comment]
Same problem to leash panda pet, the player group already have permissions
    - MyPet.leash.Panda

but they still cant tame it, the kill it but they can tame others 1.13.2 pets... noramlly
i have * all permissions so i can tame panda pet normally.

**Comment by xXKeyleXx** [comment]
Please use the template!

Do they have the `MyPet.command.store` permission?
If you can catch something your players can't it's aproblem with your permission setup not the plugin.
Do the `/petadmin ticket` command and attach the zip file from the MyPet folder.
