### ISSUE TITLE
MyPet errors in 1.14.1

### ISSUE THREAD

**Issue by Gartentrulla** [xXKeyleXx/MyPet#1246]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.
https://www.katzebiggi.de/download/ticket.zip
**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.14.1 from today
**MyPet Build/Version:**
mversion 3.0-SNAPSHOT-b1421
**What is the expected result?**
Lot of errors after login
**What happens instead of that?**
only mypet errors
**Error:**
look in the latest.log, it's too much

Hello xXKeyleXx,
I'm sorry, that I'm back again, but mypet has a lot of Errors, after I logged in. It is the same on my local as on my online Server. No update has changed anything. MyPet ist working, but the errorfile never stops.
Please can you help? I don't know if this is my mistake or yours. If I delete the mypet.jar, everything ist fine and no errors. I generated all new, but also this makes no differnce.

Thank you very much. I love your plugin. It's greate.
Your Gartentrulla form Germany

**Comment by xXKeyleXx** [comment]
same as #1247
