### ISSUE TITLE
Spammed errors in console

### ISSUE THREAD

**Issue by Aero4K** [xXKeyleXx/MyPet#1247]
**Bukkit/Spigot/Bungee Build/Version:**
Paper 1.14.2, version 51

**MyPet Build/Version:**
MyPet 3.1, #1430

**What is the expected result?**
No errors in console

**What happens instead of that?**
A large amount of errors, appears to be the same error spammed over and over in console

**Error:**
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/3227413/ticket.zip)

_**28 May edit:**_ Updated info as the issue is still present. Updated the ticket.zip as well.

**Comment by xXKeyleXx** [comment]
Have you tried upgrading ProtocolLib?

**Comment by Gartentrulla** [comment]
Thanks a lot, it was protocollib. Now it works, but I habe no prices if i use bossshop pro. Vault is the latest 1.7.2. And there are no new pets. No Errors. Can you help again?
Your Gartentrulla

**Comment by xXKeyleXx** [comment]
Please create a new issue for that.

**Comment by Aero4K** [comment]
Keyle,
Yes. I am using the latest dev build of Protocol Lib. I'm still getting that console spam.

**Comment by xXKeyleXx** [comment]
Please download the latest one again and tell me about the results:
http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/

**Comment by andris155** [comment]
The latest protocollib not work perfectly with 1.14.1.

**Comment by Aero4K** [comment]
Keyle,
I am now on 1.14.2. I tried deleting the ProtocolLib that I had and downloading the latest version, and I'm still getting the console spam. I guess we'd need to contact the author of ProtocolLib for a fix?

**Comment by xXKeyleXx** [comment]
http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastSuccessfulBuild/
