### ISSUE TITLE
Rainbow sheep

### ISSUE THREAD

**Issue by DjeyMute** [xXKeyleXx/MyPet#1248]
I had the idea to add a rainbow sheep ^^
I think it would be a pretty cool idea.

**Comment by xXKeyleXx** [comment]
You can alway create a rainbow sheep by using the name `jeb_`. Otherwise I don't think I will add it 🤔

**Comment by DjeyMute** [comment]
Hello, yes but this name jeb_ is going to be above his head, it's not very pretty ^^'
