### ISSUE TITLE
No Price for pets

### ISSUE THREAD

**Issue by Gartentrulla** [xXKeyleXx/MyPet#1249]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
spigot 1.14.1
**MyPet Build/Version:**
website: https://www.spigotmc.org/resources/mypet.12725/

**What is the expected result?**
No new pets and no prices
**What happens instead of that?**
nothing
**Error:**
nothing

Dear xXKeyleXx,
I downloaded the dev build  and the spam stopped, but now there are no prices for the pets and it gives no new one. In the pet-shop.yml are all prices, but they were not shown.

I testet it with bosshop pro and with command /petshop, and I generated for testing all files new, but the result is the same.
In your .jar I see the api for 1.13 maybe that this is the Problem?

Thanks for your help.
Your Gartentrulla

**Comment by zerafox** [comment]
Please provide an actual build number, linking to the Spigot Page does not tell us what version you are running.
Use the _/petadmin build_ command.

**Comment by Gartentrulla** [comment]
I'm using MyPet-3.0-b#1422
