### ISSUE TITLE
pet-shop dosn't work

### ISSUE THREAD

**Issue by Gartentrulla** [xXKeyleXx/MyPet#1251]
Please provide the following info.

Please use the `/petadmin ticket` command and attach the generated `ticket.zip` to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.14.1
**MyPet Build/Version:**
https://www.spigotmc.org/resources/mypet.12725/

**What is the expected result?**
old pet-shop
**What happens instead of that?**
nothing
**Error:**
nothing

Hi Keyle, sorry, today I tested both, the dev build and the regular pet.jar, but no Price and no new pets in the pet-shop. The pets are in the pet-config.yml. I generated all new, but the pet-shop will not be updatet.

Thanks for your help.
Your Gartentrulla

**Comment by zerafox** [comment]
Duplicate bug-report to #1249 
Closing Ticket
