### ISSUE TITLE
Bug when riding turtle

### ISSUE THREAD

**Issue by xaw3ep** [xXKeyleXx/MyPet#1253]
**Bukkit/Spigot/Bungee Build/Version:**
1.14.1
**MyPet Build/Version:**
Mypet 3.1, #1437
**What is the expected result?**
Eject from turtle when it died, player moves normally.
**What happens instead of that?**
Get stuck, can't move unless rejoin the server.

**Comment by xXKeyleXx** [comment]
There is nothing I can do about that :( this is a client side problem I can't fix.

**Comment by zerafox** [comment]
What if for now anyway:
Catch the death event and cancel it for the pet. Eject player from riding said pet, perform check for rider (if no, continue) kill pet.
I understand it's a client issue where the client is confused but if we can force the player off pet entity before the actual removal of the pet maybe the religious isn't needed.
It's not a pretty solution, but maybe one that could work?

**Comment by xaw3ep** [comment]
I think we just teleport the player to the location player is standing when the pet died(tested several times).
