### ISSUE TITLE
No acces to /petshop

### ISSUE THREAD

**Issue by ReimannMC** [xXKeyleXx/MyPet#1254]
# Explain your question

Hi there,

I've been spending an hour now trying to setup the permissions for the mypet plugin. 
Bottom line is, no matter what permission I add to the group (Using PEX),  it will always give the notification "You are not allowed to use this" except for when you are op.

I have no idea if this is something I am doing wrong?

**Comment by xXKeyleXx** [comment]
Show me your permissions and I might be able to help you.

**Comment by ReimannMC** [comment]
> Show me your permissions and I might be able to help you.

Hi Keyle, my apologies for the late response.
I've uploaded a GIF to Imgur to visualise the problem. 

Note: The pets in /petswitch were bought when I opped myself. 

https://imgur.com/a/AF3Zffz

**Comment by xXKeyleXx** [comment]
You misspelled your permission 😅 
You wrote `mypet.shop.acces.all` instead of `MyPet.shop.access.all`
Do you see the missing s in your permissions?

**Comment by ReimannMC** [comment]
> You misspelled your permission 😅
> You wrote `mypet.shop.acces.all` instead of `MyPet.shop.access.all`
> Do you see the missing s in your permissions?

LOL. I am such a fucking noob.

Thanks Keyle, I'm genuinely feeling like an idiot now! Can't believe I didn't see that myself.
Big thanks anyway for even taking the time to respond to this.

See ya hopefully not in the next super dumb question thread 👀 

Tantillus
