### ISSUE TITLE
Edit Skills on Editor

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#1260]
Allow editing Skills already added to the Skilltree Editor.

Currently skills can be created and adjusted in their standard Values.
However, when a mistake is made or a change is needed to something for example say the Levels of a Dynamic progression or Listed Levels the skill must be deleted and recreated entirely.

A way to modify these within the Editor would be ideal to ensure smooth transistions/updates needed to SkillTrees without having to delete and recreate the skill itself.

**Comment by xXKeyleXx** [comment]
Do you mean this part?
![upgrades](https://user-images.githubusercontent.com/631504/59198104-3bb9da80-8b93-11e9-8f9b-75c6517ea0e0.png)

**Comment by zerafox** [comment]
After you've pressed to submit that, whether it's "Fixed" or "Dynamic" it will list what you've chosen.
But you cannot change your mind and edit those values without deleting the skill entirely.

So enter some random values there, say for example set it all to "1".
Well, now you can't change it, you have to delete it and start over.

**Comment by xXKeyleXx** [comment]
I changed that already. With the latest Dev build you can change the level rule. The edit button is next to the delete button now.

**Comment by zerafox** [comment]
Oh! Huzzah!
Thank you :P
