### ISSUE TITLE
Auto updater doesn't seem to work.

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#1266]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

The auto updater doesn't seem to work or update at all. It does only notify me on every login.

https://pastebin.com/33DjTSjn

Currently using build 1447.

**Comment by xXKeyleXx** [comment]
Could you also append the server log please

**Comment by Sikatsu** [comment]
This morning: https://pastebin.com/h11fvURd

Running build 1447, it found update 1450.

A couple of days back, it was also on 1447 and it said it downloaded 1448, but it never did as I was still running 1447.

https://pastebin.com/HYTkC7df

**Comment by xXKeyleXx** [comment]
I just fixed a problem on the serverside that might be the cause of this 🤔

**Comment by xXKeyleXx** [comment]
Still a problem?

**Comment by Sikatsu** [comment]
Seems to be fixed.
