### ISSUE TITLE
Failed to leash message

### ISSUE THREAD

**Issue by MelchiorDahrk** [xXKeyleXx/MyPet#1268]
Is it possible to give a message to players when they fail to meet leash requirements? I am using the mcMMO hook and it'd be nice to be able to tell players what the rank requirement is for certain mobs.

**Comment by xXKeyleXx** [comment]
The templates are there for a reason ;)

The idea itself is good but I'm not sure how to implement it 🤔

**Comment by zerafox** [comment]
Shouldn't the Capture Helper already indicate this?

**Comment by xXKeyleXx** [comment]
It only indicated ready or not ready

**Comment by zerafox** [comment]
Oh, I assumed it checked all requirements against the mob's requirements.
That included the hooks for the other plugin requirements as well. 😲 
Personally I wouldn't think it'd be a bad idea to maintain that idea with the PCH honestly.
If the player wasn't going to meet the McMMO skill requirement of the mob, or the MMobs requirement, the indicator wouldn't be green.

Considering I always assumed Green meant it was possible to tame/catch it.

**Comment by xXKeyleXx** [comment]
Yeah it does but in case of the mcMMO hook there is no way for players to see what the requirements are.
The cooldown is a thing I considered to for some other messages 🤔

**Comment by zerafox** [comment]
Why not expand on it though? I mean, you're already checking that the requirements are met before the mob is taken on the leash, so why not print to the player which requirements fail the check?
This can be done with all possible requirements in this way.

**Comment by xXKeyleXx** [comment]
The latest dev build containts this request. Please try it out and tell me if it fits your needs.
It requires the capture helper to be active.

**Comment by MelchiorDahrk** [comment]
I just tested it out and that's very helpful! I was thinking it'd be a custom message per mob, but this is even better - more universal. Thank you for the quick update!
