### ISSUE TITLE
Pet Storage limit not recognizing limit above 44

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#1269]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Pet Storage isn't recognizing permissions

## To Reproduce

1.  Apply the following permissions to the player:
> - mypet.command.store
> - mypet.petstorage.limit.<anything between 45-54>
> - mypet.npc.storage

2. Attempt to interact with Storage NPC or the /petstore command.

## Expected behavior

Be able to store anywhere between 45-50 pets via command or NPC

## Actual behaviour

Unable to store any pets if the limit permission is higher than 44.

**Bukkit/Spigot/Bungee Build/Version:**
Confirmed on Spigot 1.14.2-R0.1
Reported also for Spigot 1.13.2

**MyPet Build/Version:**
3.3 #1454
Confirmed 3.4 #1455

**Error:**
 No errors to report.

**Temporary solution provided to players**
Reduce the permission _Mypet.petstorage.limit.<limit> to somewhere between 1 and 44_

**Comment by xXKeyleXx** [comment]
What is your `Max-Stored-Pet-Count` setting set to in the config?

**Comment by zerafox** [comment]
Oh I didn't realize that was a thing. xD
45.
But that doesn't explain why it has to be 44 (can't be 45).

**Comment by xXKeyleXx** [comment]
45 works fine for me and 46 doesn't work as expected 🤔

**Comment by zerafox** [comment]
I tried each value myself counting down from 50.
So I'm not sure what went wrong there.

**Comment by xXKeyleXx** [comment]
He said it works now and it works for me so I'm closing this 😛
