### ISSUE TITLE
Pets attack tethered horses

### ISSUE THREAD

**Issue by MelchiorDahrk** [xXKeyleXx/MyPet#1270]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Pets attack horses when you tether them to post.

## To Reproduce

Same as description.

## Expected behavior

Pets should only aggro horses when the player attacks them.

## Actual behaviour

Pets aggro horses when the player tethers them to post.

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue:

https://drive.google.com/open?id=1Z4IGU6WC6ecGczk5pScp818VlOgzXGgE

**Bukkit/Spigot/Bungee Build/Version: Spigot 1.14 

**MyPet Build/Version: 3.4 snapshot B1457

**What is the expected result? ""

**What happens instead of that? ""

**Error:**
None

**Comment by zerafox** [comment]
What behavior is your pet set to when this occurs?

**Comment by MelchiorDahrk** [comment]
Normal

**Comment by xXKeyleXx** [comment]
I can't reproduce this. Could you make a small video?

**Comment by MelchiorDahrk** [comment]
Well, after restarting the server and swapping pets, the behavior went away. I'll close this issue and if it happens again, I'll try to capture it next time. Not sure what changed aside from this being a different horse, but I don't see why that'd matter unless the AI got weird after teleporting around for a while attacking various things while travelling. Sorry about that.
