### ISSUE TITLE
1.14.3 Pet dies and respawns over and over

### ISSUE THREAD

**Issue by TDStewart** [xXKeyleXx/MyPet#1271]
In 1.14.3  When you bring out a pet it dies and respawns over and over again.

25.06 09:52:59 [Server] WARN Entity threw exception at world:-820.3308949744116,70.0,116.41403807552445
25.06 09:52:59 [Server] WARN java.lang.NoSuchMethodError: de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.de()Z
25.06 09:52:59 [Server] WARN at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.movementTick(EntityMyPet.java:926)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2317)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275)
25.06 09:52:59 [Server] WARN at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.tick(EntityMyPet.java:1250)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.World.a(World.java:933)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1188)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060)
25.06 09:52:59 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)
25.06 09:52:59 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.06 09:52:59 [Server] ERROR [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - de.Keyle.MyPet.compat.v1_14_R1.entity.types.EntityMyPolarBear} did not stopTiming)
25.06 09:52:59 [Server] INFO java.lang.Throwable: null
25.06 09:52:59 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:52:59 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:52:59 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:52:59 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:52:59 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1188) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:52:59 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:52:59 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:52:59 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:52:59 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
25.06 09:53:00 [Server] WARN Entity threw exception at world:-820.3308949744116,70.0,116.41403807552445
25.06 09:53:00 [Server] WARN java.lang.NoSuchMethodError: de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.de()Z
25.06 09:53:00 [Server] WARN at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.movementTick(EntityMyPet.java:926)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2317)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275)
25.06 09:53:00 [Server] WARN at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.tick(EntityMyPet.java:1250)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.World.a(World.java:933)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1188)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060)
25.06 09:53:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)
25.06 09:53:00 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.06 09:53:00 [Server] ERROR [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - de.Keyle.MyPet.compat.v1_14_R1.entity.types.EntityMyPolarBear} did not stopTiming)
25.06 09:53:00 [Server] INFO java.lang.Throwable: null
25.06 09:53:00 [Server] INFO at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:53:00 [Server] INFO at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:53:00 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:945) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:53:00 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:53:00 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1188) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:53:00 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:53:00 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:53:00 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.3.jar:git-Paper-110]
25.06 09:53:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
25.06 09:53:01 [Server] WARN Entity threw exception at world:-820.3308949744116,70.0,116.41403807552445
25.06 09:53:01 [Server] WARN java.lang.NoSuchMethodError: de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.de()Z
25.06 09:53:01 [Server] WARN at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.movementTick(EntityMyPet.java:926)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2317)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:275)
25.06 09:53:01 [Server] WARN at de.Keyle.MyPet.compat.v1_14_R1.entity.EntityMyPet.tick(EntityMyPet.java:1250)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.World.a(World.java:933)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1188)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060)
25.06 09:53:01 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)
25.06 09:53:01 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by xXKeyleXx** [comment]
It is clearly a bug. Why didn't you use the bug option?

**Comment by TDStewart** [comment]
Thought thats what I was doing, sorry.

**Comment by xXKeyleXx** [comment]
Hm... OK thanks for pointing this out 👍 I will close this in favor of #1272 as it is the same problem.
