### ISSUE TITLE
1.14.3 Paper Errors

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#1272]
It seems to throw a lot of errors on paper 1.14.3: https://pastebin.com/Q5Q7Q40C

**Comment by xXKeyleXx** [comment]
What MyPet build do you use?

**Comment by Sikatsu** [comment]
How to see?

**Comment by xXKeyleXx** [comment]
You are on a release and a release will only search for new releases. Did the updater updated to that release?

**Comment by Sikatsu** [comment]
Yeah it did, maybe there is an option to allow snapshots too?

**Comment by xXKeyleXx** [comment]
Will add that.

**Comment by xXKeyleXx** [comment]
I just saw that the plugin will not download releases on a devbuild and vice versa 🤔

**Comment by Sikatsu** [comment]
Hmm, is that fixed on the latest build? Changelog wasn't updated :)

**Comment by xXKeyleXx** [comment]
It was part of the 1.14.3(-pre4) support. Therefore it was fixed in build 1461

**Comment by Sikatsu** [comment]
I meant the updater ^^

**Comment by xXKeyleXx** [comment]
Ah 😅 There was nothing to fix as I think it is fine the way it works right now. When I said I that I would add it I didn't know exactly wheather it updated from snapshot to release.
