### ISSUE TITLE
mypet ?

### ISSUE THREAD

**Issue by OtakuLoveAnime** [xXKeyleXx/MyPet#1274]
# Question about MyPet

_Please describe what is on your mind. If possible also provide a context and your end goals._

* [x] I have asked for help on other places like Discord ord the discussion on spigotmc.org

**Comment by OtakuLoveAnime** [comment]
sao tôi ko cai mypet dc vay

**Comment by xXKeyleXx** [comment]
No idea what you need/want

**Comment by zerafox** [comment]
Stop mypet?
Are you trying to get it to stop attacking something?
/ps or /petstop
