### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by gabriel262m** [xXKeyleXx/MyPet#1275]
[MyPet.log](https://github.com/xXKeyleXx/MyPet/files/3342108/MyPet.log)

I get this error in my Paper Server
i not see errors in game only in console

29.06 12:41:03 [Server] ERROR Could not pass event CreatureSpawnEvent to WorldGuard v7.0.0;02b731f
29.06 12:41:03 [Server] INFO java.lang.NullPointerException: null
29.06 12:41:03 [Server] INFO at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:338) ~[?:?]
29.06 12:41:03 [Server] INFO at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:639) ~[?:?]
29.06 12:41:03 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor161.execute(Unknown Source) ~[?:?]
29.06 12:41:03 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:479) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:399) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at net.minecraft.server.v1_13_R2.World.addEntity(World.java:1095) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:942) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at de.Keyle.MyPet.compat.v1_13_R2.entity.EntityRegistry.spawnMinecraftEntity(EntityRegistry.java:129) ~[?:?]
29.06 12:41:03 [Server] INFO at de.Keyle.MyPet.entity.MyPet.createEntity(MyPet.java:536) ~[?:?]
29.06 12:41:03 [Server] INFO at de.Keyle.MyPet.util.player.MyPetPlayerImpl.schedule(MyPetPlayerImpl.java:481) ~[?:?]
29.06 12:41:03 [Server] INFO at de.Keyle.MyPet.api.util.Timer.lambda$startTimer$2(Timer.java:62) ~[?:?]
29.06 12:41:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-636]
29.06 12:41:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by xXKeyleXx** [comment]
What WorldGuard version do you use (as exact as possible)?

**Comment by gabriel262m** [comment]
World Guard 7.0.0
I continue having the same issue, sorry for late anwer
