### ISSUE TITLE
More specific message when Skilltree is invalid

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#1276]
In my Console it prints this on startup:

[23:12:14] [Server thread/WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] Error in Leuchtfeuer.st.json -> Skilltree not loaded.
[23:12:14] [Server thread/WARN]: [de.Keyle.MyPet.MyPetPlugin] [MyPet] null

-> I Did not find anything with this skilltree, could it be possible to print out more details of the catched exception? (Stacktrace, Exception class)

**Comment by xXKeyleXx** [comment]
Could I get the skilltree file? I would like to knw where the error comes from in the first place.
Do you use MyPet 3.4+?

**Comment by Phreag** [comment]
I was using MyPet 3.4.
Newver versions also fixed the skilltree, it loads now.
