### ISSUE TITLE
MyPet cause very big memory leak 1.14.x EntityMetadataStore

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1277]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug
MyPet cause very big memory leak 1.14.x

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Use MyPet on 1.14.x

## Expected behavior
MyPet no cause memory leak

_A clear and concise description of what you expected to happen._

## Actual behaviour
MyPet cause memory leak

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
Paper Build 118

**MyPet Build/Version:**
 MyPet 3.5 SNAPSHOT B1466

**Error:**
![Annotation 2019-07-01 142041](https://user-images.githubusercontent.com/8324198/60454136-5aac0980-9c33-11e9-86e3-df87a457591b.png)

**Comment by andris155** [comment]
8+  million entries
![Screenshot_20190701-191406_Microsoft_Remote_Desktop](https://user-images.githubusercontent.com/8324198/60454673-b1661300-9c34-11e9-809d-296f1c7446cc.png)

**Comment by andris155** [comment]
I tested.
Server with MyPet after 4 hours - very big lags
Server without MyPet after 4 hours - works perfectly without lags

**Comment by xXKeyleXx** [comment]
Any change I could I get that hprof file?

**Comment by andris155** [comment]
I will start to upload the file.

**Comment by andris155** [comment]
http://mc.oldcrafters.net/heap.hprof

**Comment by xXKeyleXx** [comment]
Please try the latest dev build and tell me if it got better.

**Comment by andris155** [comment]
I tested, and not better.

**Comment by xXKeyleXx** [comment]
Could you disable the `DamageWeightedExperienceDistribution` and try it again? I still need to figure out where that comes from...

**Comment by andris155** [comment]
I try tomorrow morning.

**Comment by andris155** [comment]
I tested again with disable DamageWeightedExperienceDistribution and not better. :(

**Comment by LoneDev6** [comment]
Any news?

**Comment by andris155** [comment]
I analysed again memory leak, and maybe cause this the SpawnReason entity meta.
I used this for disable exp gain for spawner mobs. Maybe Mypet not remove this entity meta if mobs killed or unloaded.
<img width="562" alt="Annotation 2019-08-25 115256" src="https://user-images.githubusercontent.com/8324198/63648373-2e8e9f80-c72f-11e9-95ab-28e6ad9d601d.png">

**Comment by LoneDev6** [comment]
Mmhhh interesting, surely this will help @xXKeyleXx fixing the problem, I hate memory leaks..

**Comment by andris155** [comment]
I disabled PreventFromSpawnReason for spawner mobs fixed this memory leak.

**Comment by LoneDev6** [comment]
how?
I already have this:
`    Gain:
      PreventFromSpawnReason: []`

**Comment by andris155** [comment]
You analysed your server memory leak? Really MyPet cause your memory leak if have?

**Comment by xXKeyleXx** [comment]
Please try the latest dev build and tell me if it got better

**Comment by andris155** [comment]
Leash randomly lost from players hand. @xXKeyleXx 
But memory leak fixed.

**Comment by andris155** [comment]
Works perfectly

**Comment by xXKeyleXx** [comment]
Great!

**Comment by TKwSni** [comment]
This memory leak is back on, it started on the release of 1.16.1 I believe.

MyPet-3.11-SNAPSHOT-B1562 
Paper-152  1.16.2

![imagen](https://user-images.githubusercontent.com/9063912/91648909-7aa7aa80-ea3b-11ea-8fe1-6d6af0207b0b.png)

**Comment by xXKeyleXx** [comment]
Please open a new issue for that
