### ISSUE TITLE
Please listen to my problem.

### ISSUE THREAD

**Issue by thetopthailand** [xXKeyleXx/MyPet#1278]
I choose skills: /pcst

pvp, combat

After the pet starts to cause damage, it will report an error.

I started using: spigot-1.8.8-R0.1-SNAPSHOT.jar | MyPet v3.4

![p15060](https://user-images.githubusercontent.com/44319574/60622845-7a962580-9e0b-11e9-8169-658a8c7e9f49.jpg)

**Comment by zerafox** [comment]
Please don't delete the format, it's there for a reason. :\
