### ISSUE TITLE
Pet Ridning and sending away

### ISSUE THREAD

**Issue by BlitzGamer-88** [xXKeyleXx/MyPet#1279]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Basicly what is happening is that when i ride a pet and send it away while i am still rinding it bugs my player and i have to reconnect every time

## To Reproduce

1. Chose the bat as your pet.
2. Chose the ride skilltree for the bat.
3. Ride the pet.
4. Use the /psa or /petsendaway while you are ridding the pet

## Expected behavior

Well i expect there to be a message sent when trying to use the /psa or /petsendaway while rinding it that says that i am not allowed to send it away while ridding it and also not letting me send it away.

## Actual behaviour

Well my characters just bugs in the sit mode and also the pet looks like its under me and after i reconnect i spawn inside a block.

## Additional context

I just want to point out that i tried this with 7 other pets and only worked with the bat so far.

**Comment by xXKeyleXx** [comment]
It is the same problem as #1253 and I still have no idea how to fix this 😢
