### ISSUE TITLE
Support new Ocelot types (easy fix)

### ISSUE THREAD

**Issue by LoneDev6** [xXKeyleXx/MyPet#1280]
# Feature request

What part of MyPet needs this?
- [x] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

## Is your feature request related to a problem? Please describe

_For now MyPets seems to support only 0-3 types of ocelots, Minecraft 1.13 added a lot of ocelot types, so the ID should not be limited by the plugin_

## Describe the solution you'd like

_Remove ID check here https://github.com/xXKeyleXx/MyPet/blob/843d90101b547e5e7e0854c81de67dd2d5d8d9d9/modules/Plugin/src/main/java/de/Keyle/MyPet/commands/admin/CommandOptionCreate.java#L515 _

## Describe alternatives you've considered

_None_

## Additional context

_None_

**Bukkit/Spigot/Bungee Build/Version:**
1.14.3
**MyPet Build/Version:**
3.4

**Comment by xXKeyleXx** [comment]
Use the `type` instead of `cat`

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/61127609-08c77700-a4b0-11e9-92c6-2ce3ed704b90.png)
![image](https://user-images.githubusercontent.com/27242001/61127618-10871b80-a4b0-11e9-9355-c7af014de520.png)


Seems not to be working, am I missing something?

**Comment by LoneDev6** [comment]
Changing PetType to "Cat" fixed the issue, thanks
