### ISSUE TITLE
Offline UUID support

### ISSUE THREAD

**Issue by xion87** [xXKeyleXx/MyPet#1285]
# Question about MyPet

I would like to know if you can use offline UUID from spigot/bungeecord instead generating itselfuuid (is the only plugin that have this decision on uuid generating)
Example the nickname Malachiel is saved on mypet_players with uuid "
instead the uuid should be generated by spigot that is "{"players":[{"username":"Malachiel","uuid":"019b3f01-9c76-3d3d-909c-d1d6b9e9576f"}]}"

* [x] I have asked for help on other places like Discord ord the discussion on spigotmc.org

**Comment by zerafox** [comment]
You never mentioned if you had Bungeecord hook enabled in your configuration.

**Comment by xion87** [comment]
I have this
    BungeeCord:
      UUID-Mode: offline

**Comment by xXKeyleXx** [comment]
I don't see the point in changing that. These UUIDs are for internal usage only, to support online and offline mode. If you want to adjust a player just change the name or the Mojang UUID.

**Comment by xion87** [comment]
wait so i have just to change the owner name on table?

**Comment by xion87** [comment]
oooh it worked
