### ISSUE TITLE
Behavior not work

### ISSUE THREAD

**Issue by VeInArDiS** [xXKeyleXx/MyPet#1287]
Spigot 1.14.4 (build_time": "2019-07-19T09:24:08+00:00)
MyPet 3.7
EssentialsX-2.17.1.0
LuckPerms-Bukkit-4.4.1 (or with OPerator rights)
All permisions enable
if you attack a pet in a friendly mode the pet attacks in response.
Or when the pet is in raid mode if you attack he attacks in response.
How to make sure that the pet is not attacked players in friendly mode?
And that would not attack the pet players in raid mode if I accidentally hit?

**Comment by zerafox** [comment]
Turn off the ability for players to damage pets, and pets to damage players.

>   OwnerCanAttackPet: false
  DisablePetVersusPlayer: true

**Comment by VeInArDiS** [comment]
But I want Pets and players to be able to fight when they're told to.
I can only provide a screenshot.
There will be several answers:
Here shown that I had included pet friendly mod
![-yl94VxuPaU](https://user-images.githubusercontent.com/54110605/63049792-32762280-bee2-11e9-9ffa-c766543b6961.jpg)
![Hzt9UjWhIMQ](https://user-images.githubusercontent.com/54110605/63049826-49b51000-bee2-11e9-88d7-57d618369046.jpg)

**Comment by VeInArDiS** [comment]
Then I hit the player and the pet stood on the site.
But if I hit the player, the pet will attack.
![e4QacAmbMLw](https://user-images.githubusercontent.com/54110605/63049997-b16b5b00-bee2-11e9-8ee8-32112b1ae637.jpg)

**Comment by VeInArDiS** [comment]
If the player attacks the pet, the pet starts attacking the player
![PYswbPUDCBg](https://user-images.githubusercontent.com/54110605/63050070-d9f35500-bee2-11e9-8964-7228d91f09f0.jpg)
![yaM9RR6VHEQ](https://user-images.githubusercontent.com/54110605/63050074-db248200-bee2-11e9-80dc-46a8bebffa47.jpg)
![f8jxcn6AG9E](https://user-images.githubusercontent.com/54110605/63050075-dc55af00-bee2-11e9-8683-d1209f44df4e.jpg)

**Comment by VeInArDiS** [comment]
Server data about mod
![2-lsHJHET_c](https://user-images.githubusercontent.com/54110605/63050264-5ab25100-bee3-11e9-8ee3-45415d75df82.jpg)
![1y374IVpBvc](https://user-images.githubusercontent.com/54110605/63050265-5ab25100-bee3-11e9-90aa-4d7cd807162b.jpg)

**Comment by VeInArDiS** [comment]
I found many bugs and errors.
Lightning damage only works in close combat, but lightning strikes at long range without causing damage.
Damage in the skilltrees are written in percent. Must be in numbers.
![gZmKHCqWSmw](https://user-images.githubusercontent.com/54110605/63069776-f8784100-bf20-11e9-9c0c-0c0cde2ff586.jpg)
The petstore command does not work. All permissions are correctly set (screenshot above). Petstore works only with OP privileges. Without the rights of the operator writes "you can not do it."
---------------------------------------------------------------------------------------------------------
When a pet picks up an EXP experience, it disappears somewhere, there is no experience in the pet's inventory.
---------------------------------------------------------------------------------------------------------
What is it?
Why can't shots in sec?
Why are these complex calculations in which it is difficult to make fine tuning?
![1iOoLBQqViU](https://user-images.githubusercontent.com/54110605/63070122-93254f80-bf22-11e9-8ff8-121f388b803f.jpg)

**Comment by VeInArDiS** [comment]
> You can turn off the ability for players to damage pets, and pets to damage players. If you don't want any interactive damage between pets and players.
> 
> > OwnerCanAttackPet: false
> > DisablePetVersusPlayer: true
> 
> Can you provide screenshots or a video-clip of this wrong behavior.
> Where a Friendly behavior pet will retaliate against an attacker, etc;?

**Comment by VeInArDiS** [comment]
Can I get any answer?
Is it accepted for viewing or not?
