### ISSUE TITLE
Lightning hits the enemy, but deals damage only at close range.

### ISSUE THREAD

**Issue by VeInArDiS** [xXKeyleXx/MyPet#1290]
MyPet-3.8-SNAPSHOT-B1493.jar
Extended permissions still don't let you fly, and lightning strikes always, but without damage at long distances.
MyPet-3.8-SNAPSHOT-B1494.jar
Ahaha pet pet kills himself with lightning.
Lightning deals damage not in the mob but in a radius of 1 block (mb2).
Extended permissions still don't let you fly/
![image](https://user-images.githubusercontent.com/54110605/63228787-f48a3e80-c200-11e9-9c2e-a86c642f0d73.png)

**Comment by xXKeyleXx** [comment]
Is flying enabled in the skilltrees?

**Comment by VeInArDiS** [comment]
Sure it is. I turned it on and off - Extended permissions. 
Riding is allowed.

**Comment by VeInArDiS** [comment]
The player can drive but not fly.

**Comment by VeInArDiS** [comment]
MyPet-3.8-SNAPSHOT-B1495
The lightning works, THX <3
Extended permissions still don't let you fly/
