### ISSUE TITLE
petadmin ticket produces tons of empty lines in console

### ISSUE THREAD

**Issue by Andre601** [xXKeyleXx/MyPet#1292]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug
When you run `/petadmin ticket` (either in-game or in console) will MyPet post numerous empty lines in the console (See screenshot).

## To Reproduce
1. Either run `/petadmin ticket` in-game or `petadmin ticket` in console
2. Check console

## Expected behavior
There shouldn't be tons of empty lines in the console. Instead no such messages (or if it was supposed to be a progress bar, then the actual progress)

## Actual behaviour
The console gets flooded with empty lines

## Additional context
Here's the [ticket.zip](https://github.com/xXKeyleXx/MyPet/files/3513515/ticket.zip) I created that (ironically) was made to check this bug.

Here is also a screenshot of it
![image](https://user-images.githubusercontent.com/11576465/63229734-e1c53900-c203-11e9-9309-6c21b481d5d8.png)

**Bukkit/Spigot/Bungee Build/Version:**
PaperMC 167 (MC 1.14.4)

**MyPet Build/Version:**
MyPet-3.8-SNAPSHOT-b#1494

**Comment by xXKeyleXx** [comment]
This was introduced in march 2014 😂😂😂 Nobody complained about this since them 😂😂😂
