### ISSUE TITLE
Flying and swimming.

### ISSUE THREAD

**Issue by VeInArDiS** [xXKeyleXx/MyPet#1294]
Flying and swimming.
During the flight there is no function to fly down. Only with the cursor. There is no down key. 
Sea pets are not working properly. They can't be near you underwater, they rise upward. You can not dive when riding on sea pets. 
Why Sea pets don't get damaged on the ground? Ordinary Pets are damaged under water.
MyPet-3.8-SNAPSHOT-B1495

**Comment by zerafox** [comment]
Flying with a Pet shouldn't be any different than flying with Creative.
"Sea Pets" aren't exactly a thing, all pets are the same. You can't dive underwater with any pet because all pets are the same entity, just different appearances.
The "Damaged under-water" is the pet drowning, all pets can and will drown if stuck underwater.

**Comment by VeInArDiS** [comment]
But underwater Pets don't drown..
Maybe I'm wrong..
Strange why Pets are not different. 
Can add underwater parameter to pet-config.yml?
Why shouldn't flying be different from creativity?

**Comment by zerafox** [comment]
No, I mean the controls are the same as Creative Flight.
Space (Jump) to go up, Shift (Sneak) to go down.

Why is it strange that pets aren't different? They all use the Same-AI (The vanilla Wolf Pet), they can all use the same skills, features, etc; The only differences being Chickens can Lay Egg, Cows can't, etc;

Swimming, is the same as Flying. There's no AI for it, so there isn't any "Swimming Pets" for the same reason there aren't any Flying ones.

No pets retain any of their Vanilla Mob features. That includes the Flying, Swimming, Exploding, Burning, etc; mobs.
Fish don't swim, Creeper don't explode, Zombie don't burn, etc;
They aren't "mobs" anymore, they're pets.

This isn't a bug, it's intended.

**Comment by VeInArDiS** [comment]
Ok.
Shift (Sneak) to go down.  Get off with pet, not on land, as in creativity.

**Comment by VeInArDiS** [comment]
I understand well.
I'll close bug.
The habits of some mobs remain with them but not all their functions.
