### ISSUE TITLE
Extended permissions still don't let you fly/

### ISSUE THREAD

**Issue by VeInArDiS** [xXKeyleXx/MyPet#1295]
MyPet-3.8-SNAPSHOT-B1495
Is flying enabled in the skilltrees? YES
I turned it on and off - Extended permissions.
Riding is allowed.
If Extended permissions off - players can can drive and fly.
If Extended permissions on - players can drive but NOT fly.
P.S.
If the pet has a limit on flight, the flight is not restored on the water. Is that okay?

![GAgJnYB2vXg](https://user-images.githubusercontent.com/54110605/63358663-19eb8980-c374-11e9-8455-eee4b51b8519.jpg)
![dvcYo76EVAc](https://user-images.githubusercontent.com/54110605/63358673-1ce67a00-c374-11e9-9fd4-33bb352f597a.jpg)

**Comment by zerafox** [comment]
Try adding the permission:
**mypet.extended.ride.fly**
