### ISSUE TITLE
RU localization incorrectly.

### ISSUE THREAD

**Issue by VeInArDiS** [xXKeyleXx/MyPet#1297]
Sorry for the many bug reports.
Pet raid mode.
raid - рейд (attack\roundup)
ride - езда (drive\riding)
![image](https://user-images.githubusercontent.com/54110605/63359259-199fbe00-c375-11e9-93b0-44db9a31a2bd.png)
![image](https://user-images.githubusercontent.com/54110605/63359271-1f959f00-c375-11e9-89ae-d89e03e8fb96.png)

**Comment by xXKeyleXx** [comment]
Please change it yourself:
https://translation.mypet-plugin.de/translate/ru
