### ISSUE TITLE
The effect of the rate of fire on the chance of being struck by lightning?

### ISSUE THREAD

**Issue by VeInArDiS** [xXKeyleXx/MyPet#1300]
How is the chance of being struck by lightning determined?
I noticed that the higher the rate of fire of shells the more often lightning strikes. Is it? 
If so, please correct this.
You can't adjust the speed of a close attack. And with the same setting of Melee and ranged, ranged combat will use lightning more often. 
But I can put a chance of lightning for long-range attacks - less.

**Comment by xXKeyleXx** [comment]
Every hit has the chance you set via the skilltrees. So ofc the higher the rate of fire the more lightnings appear.

**Comment by VeInArDiS** [comment]
Thank u <3

**Comment by VeInArDiS** [comment]
Can you make a lightning bolt as a separate strike?
