### ISSUE TITLE
Option to not have MyPet despawn on release

### ISSUE THREAD

**Issue by wolfgangvc** [xXKeyleXx/MyPet#1302]
# Feature request
Add a config option to have MyPet's convert back to a regular mob, when releasing them.
(Maybe convert wolves/ocelots/etc back to the tamed versions of them)

What part of MyPet needs this?
- [x] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

## Additional context
Player on server hit the pet limit and would like to release a wolf they had as a MyPet, but keep the dog as a regular tamed wolf mob.

**MyPet Build/Version:**
3.7

**Comment by xXKeyleXx** [comment]
This should be the default behavior. 3.7 has the bug that it is inverted. Just download the latest dev build and it should work like you want it.
