### ISSUE TITLE
Wither BUG

### ISSUE THREAD

**Issue by VeInArDiS** [xXKeyleXx/MyPet#1303]
Hi bro <3
Not sitting correctly in the drive (hard to see around).
VERY loud sound of shots "Wither skull".
![zieWlAKGmqU](https://user-images.githubusercontent.com/54110605/63879682-e09ac580-c9d4-11e9-908f-4200791cc14e.jpg)
![kYiioQrN6zI](https://user-images.githubusercontent.com/54110605/63879690-e2fd1f80-c9d4-11e9-991d-7df5dee534c1.jpg)

**Comment by xXKeyleXx** [comment]
Nothing I can do about :/

**Comment by VeInArDiS** [comment]
Why? :(

**Comment by xXKeyleXx** [comment]
It's a clientside thing

**Comment by VeInArDiS** [comment]
That's too bad.
I thought you could raise how many blocks a player would be taller. 
And that you can adjust the sound too.
But thanks anyway!
