### ISSUE TITLE
Rate of fire (snap 1495 vs 1498)

### ISSUE THREAD

**Issue by VeInArDiS** [xXKeyleXx/MyPet#1304]
Hi bro <3
Not changing skilltrees, not changing config files, not changing individual. I change only the "MyPet-3.8-SNAPSHOT-B 1495" to "MyPet-3.8-SNAPSHOT-B 1498". 
Rate of fire in version 1498 is getting smaller at the same settings.

**Comment by xXKeyleXx** [comment]
try setting `MyPet.Entity.Skip-Movement-AI-Ticks` to 0

**Comment by VeInArDiS** [comment]
Now working! (probably the same)
What exactly do the settings: "Skip-Movement-AI-Ticks: 0" and "Skip-TargetAI-Ticks: 1" ?

**Comment by xXKeyleXx** [comment]
To increse server TPS I added two config options that will decrese the amount of ticks a MyPet will search for a target. But the movement one reduces the attacks and also makes pets "slower" 😅
