### ISSUE TITLE
Pets Disappear

### ISSUE THREAD

**Issue by SakiBear** [xXKeyleXx/MyPet#1305]
Hello,

I'm working with all of the original files non-edited for MyPet 3.7, and even if I give the permission MyPet.*, whenever a pet is "tamed" on my server, the mob just disappears. No experience is dropped like it is killed, and there is also no pet. The other plugins I'm running are LuckPerms, EssentialsX, and Vault. This is just a small server for friends so they all have bukkit.*, essentials.*, and vault.*. 

If you have any idea how to fix this issue it'd be appreciated!

Thanks!
Kara G.

**Comment by SakiBear** [comment]
Also this error is generated in Console:

29.08 18:01:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
29.08 18:01:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
29.08 18:01:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
29.08 18:01:20 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [Spigot.jar:git-Spigot-a596182-edd8fdf]
29.08 18:01:20 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot.jar:git-Spigot-a596182-edd8fdf]
29.08 18:01:20 [Server] INFO at de.Keyle.MyPet.repository.types.SqLiteRepository$8.run(SqLiteRepository.java:557) ~[?:?]
29.08 18:01:20 [Server] INFO java.lang.NullPointerException: null
29.08 18:01:20 [Server] Craft Scheduler Thread - 16/WARN Plugin MyPet v3.7 generated an exception while executing task 296

**Comment by xXKeyleXx** [comment]
Please do `/petadmin ticket` and attach the ticket.zip file from the MyPet folder here.

**Comment by SakiBear** [comment]
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/3557866/ticket.zip)

**Comment by xXKeyleXx** [comment]
That error happens because your server is not setup properly. The permissions on the /tmp folder are not set correctly and therefore the temporary library file can not be loaded.
