### ISSUE TITLE
Need 1.5.2 and 1.6.4 version.

### ISSUE THREAD

**Issue by Zilacon** [xXKeyleXx/MyPet#1307]
I had this plugin in the past but ive looked everywhere for an older version and cant find it. Can you provide it or tell me where to get versions for 1.5.2 and 1.6.4?

**Comment by xXKeyleXx** [comment]
Look on BukkitDev

**Comment by Zilacon** [comment]
@xXKeyleXx I did. It would help if there was any files on dev.bukkit...
https://dev.bukkit.org/projects/mypet/files

**Comment by xXKeyleXx** [comment]
Well in this case I can't do much. I don't have them anymore.
