### ISSUE TITLE
petrelease reset villager proffession and trades

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1310]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._
/petrelease reset villager proffession and trades

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Catch villager pet with professions and trades.
2. Release villager
...

## Expected behavior

_A clear and concise description of what you expected to happen._
/petrelease not reset villager proffession and trades

## Actual behaviour

_If applicable, add screenshots to help explain your problem._
/petrelease reset villager proffession and trades

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-186 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**MyPet Build/Version:**
MyPet-3.8-SNAPSHOT-b#1504

**What is the expected result?**
/petrelease not reset villager proffession and trades

**What happens instead of that?**
/petrelease reset villager proffession and trades

**Error:**
https://www.youtube.com/watch?v=kiGJ4vpZwtw

**Comment by andris155** [comment]
<img width="566" alt="Annotation 2019-09-14 205935" src="https://user-images.githubusercontent.com/8324198/64912648-933b8980-d732-11e9-8f75-41912cb65aae.png">
How to download fixed version?

**Comment by xXKeyleXx** [comment]
The build failed. It should be up in about 10min.
