### ISSUE TITLE
Major item duplication / item loss bug - pet inventory

### ISSUE THREAD

**Issue by ArtNRG** [xXKeyleXx/MyPet#1315]
# Bug report
* [+] I have checked other issues to make sure this is not a duplicate.

## Describe the bug
Players are able to duplicate all content of pet inventory or lose all pet inventory stuff 

## To Reproduce
1. Get 3 shulker boxes and fill them with something.
2. Place them into the pet inventory.
3. Type /psa and wait some time to save the data to the database. I was waiting a few hours.
4. When it will be 1 minute till server restart, take all the stuff from the pet inventory, then /psa the pet.
5. Log in after the server started and find you stuff both in your and pet inventory.

## Expected behavior
The items must be or in the player inventory or in the pet inventory exclusive.

## Actual behaviour
The items are duplicated and stored both in the player and the pet inventory.

## Additional context
`/petadmin ticket` https://www.dropbox.com/s/1rt3yjp9w6y4jml/ticket.zip?dl=0

**Bukkit/Spigot/Bungee Build/Version:**
Paper version git-Paper-647 (MC: 1.13.2)
Waterfall version git:Waterfall-Bootstrap:1.14-SNAPSHOT:9e17ca3:294
**MyPet Build/Version:**
MyPet-3.9-SNAPSHOT-B1510

**Error:**
No errors

**Comment by xXKeyleXx** [comment]
How does the server gets restarted?

**Comment by ArtNRG** [comment]
Daily restart with Minecraft_RKit wrapper.

**Comment by xXKeyleXx** [comment]
Does it do a clean shutdown?

**Comment by ArtNRG** [comment]
Yes, with kicking all players and waiting for all plugins.

**Comment by ArtNRG** [comment]
By the way, while searching and cleaning all duplicated stuff on my server the main thing I dreamed about was an ability to look the pet inventory of an offline player and the ability to look each pet inventory from the stored pets of both offline and online players. Please add this ability.

**Comment by ArtNRG** [comment]
Is this bug confirmed?

**Comment by kotarobo** [comment]
Proliferation could be reproduced.

Put an item in the pet inventory → Log out / log in from the server → Take out the item from the pet → Enter the world that is disabled in the world group → Return to the enabled world → Taken when opening the pet inventory There are still items to be.

**Comment by kotarobo** [comment]
use multiverse-core

**Comment by xXKeyleXx** [comment]
Please try the latest dev build and give me some feedback

**Comment by kotarobo** [comment]
Thank you for your patience.
I've done some light testing and the glitch I reproduced seems to be fixed!
Thank you :D
