### ISSUE TITLE
question about horses

### ISSUE THREAD

**Issue by Darigsey** [xXKeyleXx/MyPet#1316]
it is possible with the command /petadmin create

create horses with horse armor

and there is a possibility to remove armor and saddle again from pets

Please answer me I love the plugin

and sorry for my english i am german

**Comment by zerafox** [comment]
I don't believe you can spawn in a horse with a saddle and armor.
You can remove these things (including held items) from pets using shears.

**Comment by xXKeyleXx** [comment]
Benutzt die Autovervollständigung (TAB). Wenn da keine Option aufgelistet ist, dann gehts auch nicht.

**Comment by Darigsey** [comment]
you can spawn horses with saddle and then put on a horse's armor
just thought that it was possible that also over command

just as it is possible donkey with saddle and box

but thanks that with the shears I knew not 

there seems to be a bug Horses saddle remove with shears disappears the shears but the saddle is still on the horse

**Comment by xXKeyleXx** [comment]
Ja es kann sein, dass ich die neue Rüstung noch nicht implementiert habe 🤔 Ich denke ich habe den Sattel bei Babypferden nicht implementiert weil das einfach vom Client her nicht möglich war.

Du kannst ruhig weitere Antworten auf deutsch schreiben wenn das einfacher für dich ist.

**Comment by Darigsey** [comment]
Ok Ja Deutsch ist einfacher^^

also mit /petadmin create kann man sie mit Sattel erstellen und auch die Esel und Maultiere gehen als Baby mit Sattel und Kisten wäre das dann auch Möglich einzustellen das man Baby die Baby versionen wie die Großen Sachen abringen

habe gerade getestet Zombie und Skeletpferde da geht Sattel und auch Baby Version kann man Satteln und auch Entfern beim Pferd geht Sattel nicht da verschwindet die schere
