### ISSUE TITLE
Pet Shop don't working

### ISSUE THREAD

**Issue by SakizciAdam** [xXKeyleXx/MyPet#1317]
I setuped plugin succesfully when I try to open the shop its working
But I just only changed pet prices and I restarted the full of the server and when I try to open It says
`You are not allowed to use this` but I have every perm

**Comment by xXKeyleXx** [comment]
I need the config

**Comment by SakizciAdam** [comment]
Config:
# #################################################################
#            This is the main configuration of MyPet              #
#              You can find more info on the wiki:                #
#   https://wiki.mypet-plugin.de/setup/configurations/config.yml  #
# #################################################################

MyPet:
  Update:
    Check: true
    Download: false
    ReplaceOld: false
    In-Background: false
    OP-Notification: true
  Leash:
    Consume: false
    AllowRanged: true
  OwnerCanAttackPet: false
  DisablePetVersusPlayer: false
  RetainEquipmentOnTame: true
  Make-Pet-Invisible-When-Owner-Is-Invisible: true
  Log:
    Level: INFO
    Report-Errors: true
    Unique-ID: 51fb8b35-6977-44e0-9067-863c6e5d9c52
  Max-Stored-Pet-Count: 45
  Throw-PlayerMoveEvent-While-Riding: true
  Disable-All-Actionbar-Messages: false
  OverwriteLanguages: ''
  Right-Click-Command: ''
  Entity:
    Skip-Target-AI-Ticks: 0
    FollowStartDistance: 7.0
  Repository:
    Type: SQLite
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      Database: mypet
      TablePrefix: ''
      Host: localhost
      Password: ''
      User: root
      Port: 3306
      MaxConnections: 16
      CharacterEncoding: utf8
    MongoDB:
      Database: mypet
      CollectionPrefix: ''
      Host: localhost
      Password: ''
      User: ''
      Port: 27017
  Respawn:
    Time:
      Disabled: false
      Default:
        Factor: 5
        Fixed: 0
      Player:
        Factor: 5
        Fixed: 0
    EconomyCost:
      Fixed: 0.0
      Factor: 1.0
  Permissions:
    Enabled: true
    Extended: false
    Legacy: false
  LevelSystem:
    CalculationMode: Default
  HungerSystem:
    Active: true
    Time: 60
    SaturationPerFeed: 6.0
    Affect-Ride-Speed: true
    Affect-Beacon-Range: true
  Skilltree:
    AutomaticAssignment: false
    RandomAssignment: false
    ChooseOnce: false
    PreventLevellingWithout: true
    SwitchFee:
      Fixed: 0.0
      Percent: 5
      Admin: false
  Name:
    Filter:
    - whore
    - fuck
    - bitch
    - fck
    - btch
    MaxLength: 32
    Tag:
      Show: true
      Prefix: <aqua>
      Suffix: ''
  Exp:
    DamageWeightedExperienceDistribution: true
    Passive:
      Always-Grant-Passive-XP: true
      PercentPerMonster: 25
    Loss:
      Percent: 0
      Fixed: 0.0
      Drop: true
      Allow-Level-Drowngrade: false
    Gain:
      PreventFromSpawnReason: []
    LevelCap: 100
    Disabled-Worlds: []
    Modifier:
      Global: 1.0
      Use-Permissions: false
  Skill:
    Control:
      Item: lead
    Backpack:
      Creative: false
      DropWhenOwnerDies: false
    Beacon:
      HungerDecreaseTime: 100
      Party-Support: true
    Ride:
      Item: lead
      HungerPerMeter: 0.01
      Prevent-Teleportation-While-Riding: false
  Info:
    Wiki-URL: https://wiki.mypet-plugin.de
​Pet-shop
#####################################################################
#             This is the shop configuration of MyPet               #
#               You can find more info on the wiki:                 #
#  https://wiki.mypet-plugin.de/setup/configurations/pet-shops.yml  #
#####################################################################

Shops:
  all:
# When Default is set to true /petshop will open the sop instead of the shop selection GUI
    Default: true
    Name: "All Pets"
    Balance:
      Type: Private
    Position: 0
    Icon:
      Material: "chest"
      Glowing: false
    Pets:
#      a_unique_name:
#        Position: 0
#        Name: "Ingame Name"
#        Description:
#        - <green>This is a description!
#        PetType: PetTypeName
#        EXP: 0
#        Price: 100
#        Skilltree: "skilltreename"
#        Options:
#          - baby
#          - saddle
      bat:
        Name: Bat
        Description:
          - <green>It's a Bat!
        PetType: Bat
        EXP: 0
        Price: 100
      blaze:
        Name: Blaze
        Description:
          - <green>It's a Blaze!
        PetType: Blaze
        EXP: 0
        Price: 20000
      cavespider:
        Name: CaveSpider
        Description:
          - <green>It's a CaveSpider!
        PetType: CaveSpider
        EXP: 0
        Price: 1000
      chicken:
        Name: Chicken
        Description:
          - <green>It's a Chicken!
        PetType: Chicken
        EXP: 0
        Price: 250
      cow:
        Name: Cow
        Description:
          - <green>It's a Cow!
        PetType: Cow
        EXP: 0
        Price: 500
      creeper:
        Name: Creeper
        Description:
          - <green>It's a Creeper!
        PetType: Creeper
        EXP: 0
        Price: 1250
      donkey:
        Name: Donkey
        Description:
          - <green>It's a Donkey!
        PetType: Donkey
        EXP: 0
        Price: 750
      elder_guardian:
        Name: Elder Guardian
        Description:
          - <green>It's an Elder Guardian!
        PetType: ElderGuardian
        EXP: 0
        Price: 1400
      enderman:
        Name: Enderman
        Description:
          - <green>It's an Enderman!
        PetType: Enderman
        EXP: 0
        Price: 1500
      endermite:
        Name: Endermite
        Description:
          - <green>It's an Endermite!
        PetType: Endermite
        EXP: 0
        Price: 1300
      evoker:
        Name: Evoker
        Description:
          - <green>It's an Evoker!
        PetType: Evoker
        EXP: 0
        Price: 1210
      guardian:
        Name: Guardian
        Description:
          - <green>It's a Guardian!
        PetType: Guardian
        EXP: 0
        Price: 1100
      horse:
        Name: Horse
        Description:
          - <green>It's a Horse!
        PetType: Horse
        EXP: 0
        Price: 950
      iron_golem:
        Name: IronGolem
        Description:
          - <green>It's a IronGolem!
        PetType: IronGolem
        EXP: 0
        Price: 10000
      illusioner:
        Name: Illusioner
        Description:
          - <green>It's an Illusioner!
        PetType: Illusioner
        EXP: 0
        Price: 9000
      llama:
        Name: Llama
        Description:
          - <green>It's a Llama!
        PetType: Llama
        EXP: 0
        Price: 800
      magmacube:
        Name: MagmaCube
        Description:
          - <green>It's a MagmaCube!
        PetType: MagmaCube
        EXP: 0
        Price: 6000
        Options:
          - size:2
      mooshroom:
        Name: Mooshroom
        Description:
          - <green>It's a Mooshroom!
        PetType: Mooshroom
        EXP: 0
        Price: 700
      mule:
        Name: Mule
        Description:
          - <green>It's a Mule!
        PetType: Mule
        EXP: 0
        Price: 100
      ocelot:
        Name: Ocelot
        Description:
          - <green>It's an Ocelot!
        PetType: Ocelot
        EXP: 0
        Price: 200
      parrot:
        Name: Parrot
        Description:
          - <green>It's a Parrot!
        PetType: Parrot
        EXP: 0
        Price: 1000
      pig:
        Name: Pig
        Description:
          - <green>It's a Pig!
        PetType: Pig
        EXP: 0
        Price: 450
      pigzombie:
        Name: PigZombie
        Description:
          - <green>It's a PigZombie!
        PetType: PigZombie
        EXP: 0
        Price: 1000
      polarbear:
        Name: PolarBear
        Description:
          - <green>It's a PolarBear!
        PetType: PolarBear
        EXP: 0
        Price: 2100
      rabbit:
        Name: Rabbit
        Description:
          - <green>It's a Rabbit!
        PetType: Rabbit
        EXP: 0
        Price: 450
      sheep:
        Name: Sheep
        Description:
          - <green>It's a Sheep!
        PetType: Sheep
        EXP: 0
        Price: 500
      silverfish:
        Name: Silverfish
        Description:
          - <green>It's a Silverfish!
        PetType: Silverfish
        EXP: 0
        Price: 500
      skeleton:
        Name: Skeleton
        Description:
          - <green>It's a Skeleton!
        PetType: Skeleton
        EXP: 0
        Price: 1000
      skeleton_horse:
        Name: Skeleton Horse
        Description:
          - <green>It's a Skeleton Horse!
        PetType: SkeletonHorse
        EXP: 0
        Price: 1500
      slime:
        Name: Slime
        Description:
          - <green>It's a Slime!
        PetType: Slime
        EXP: 0
        Price: 5000
        Options:
          - size:2
      snowman:
        Name: Snowman
        Description:
          - <green>It's a Snowman!
        PetType: Snowman
        EXP: 0
        Price: 700
      spider:
        Name: Spider
        Description:
          - <green>It's a Spider!
        PetType: Spider
        EXP: 0
        Price: 700
      squid:
        Name: Squid
        Description:
          - <green>It's a Squid!
        PetType: Squid
        EXP: 0
        Price: 300
      stray:
        Name: Stray
        Description:
          - <green>It's a Stray!
        PetType: Stray
        EXP: 0
        Price: 100
      witch:
        Name: Witch
        Description:
          - <green>It's a Witch!
        PetType: Witch
        EXP: 0
        Price: 10000
      wither:
        Name: Wither
        Description:
          - <green>It's a Wither!
        PetType: Wither
        EXP: 0
        Price: 40000
      wither_skeleton:
        Name: Wither Skeleton
        Description:
          - <green>It's a Wither Skeleton!
        PetType: WitherSkeleton
        EXP: 0
        Price: 4500
      wolf:
        Name: Wolf
        Description:
          - <green>It's a Wolf!
        PetType: Wolf
        EXP: 0
        Price: 200
        Options:
          - tamed
      vex:
        Name: Vex
        Description:
          - <green>It's a Vex!
        PetType: Vex
        EXP: 0
        Price: 100
      villager:
        Name: Villager
        Description:
          - <green>It's a Villager!
        PetType: Villager
        EXP: 0
        Price: 980
      vindicator:
        Name: Vindicator
        Description:
          - <green>It's a Vindicator!
        PetType: Vindicator
        EXP: 0
        Price: 100
      zombie:
        Name: Zombie
        Description:
          - <green>It's a Zombie!
        PetType: Zombie
        EXP: 0
        Price: 700
      zombie_horse:
        Name: Zombie Horse
        Description:
          - <green>It's a Zombie Horse!
        PetType: ZombieHorse
        EXP: 0
        Price: 1250
      zombie_villager:
        Name: Zombie Villager
        Description:
          - <green>It's a Zombie Villager!
        PetType: ZombieVillager
        EXP: 0
        Price: 10000
#      enderdragon:
#        Name: EnderDragon
#        Description:
#        - <green>It's an EnderDragon!
#        PetType: EnderDragon
#        EXP: 0
#        Price: 100
#      ghast:
#        Name: Ghast
#        Description:
#        - <green>It's a Ghast!
#        PetType: Ghast
#        EXP: 0
#        Price: 100
#      giant:
#        Name: Giant
#        Description:
#        - <green>It's a Giant!
#        PetType: Giant
#        EXP: 0
#        Price: 100
  babies:
    Name: "Baby Shop"
    Balance:
      Type: Private
    Position: 1
    Pets:
      baby_chicken:
        Name: "Chicken"
        Description:
          - <green>It's a baby Chicken!
        PetType: Chicken
        EXP: 0
        Price: 100
        Options:
          - baby
      baby_cow:
        Name: "Cow"
        Description:
          - <green>It's a baby Cow!
        PetType: Cow
        EXP: 0
        Price: 300
        Options:
          - baby
      baby_donkey:
        Name: Donkey
        Description:
          - <green>It's a bab Donkey!
        PetType: Donkey
        EXP: 0
        Price: 500
        Options:
          - baby
      baby_horse:
        Name: "Horse"
        Description:
          - <green>It's a baby Horse!
        PetType: Horse
        EXP: 0
        Price:700
        Options:
          - baby
      baby_llama:
        Name: Llama
        Description:
          - <green>It's a baby Llama!
        PetType: Llama
        EXP: 0
        Price: 650
        Options:
          - baby
      baby_mooshroom:
        Name: "Mooshroom"
        Description:
          - <green>It's a baby Mooshroom!
        PetType: Mooshroom
        EXP: 0
        Price: 250
        Options:
          - baby
      baby_mule:
        Name: Mule
        Description:
          - <green>It's a baby Mule!
        PetType: Mule
        EXP: 0
        Price: 50
        Options:
          - baby
      baby_ocelot:
        Name: "Ocelot"
        Description:
          - <green>It's a baby Ocelot!
        PetType: Ocelot
        EXP: 0
        Price: 100
        Options:
          - baby
      baby_pig:
        Name: "Pig"
        Description:
          - <green>It's a baby Pig!
        PetType: Pig
        EXP: 0
        Price: 150
        Options:
          - baby
      baby_pig_zombie:
        Name: "PigZombie"
        Description:
          - <green>It's a baby PigZombie!
        PetType: PigZombie
        EXP: 0
        Price: 1000
        Options:
          - baby
      baby_polar_bear:
        Name: "Polar Bear"
        Description:
          - <green>It's a baby Polar Bear!
        PetType: PolarBear
        EXP: 0
        Price: 400
        Options:
          - baby
      baby_rabbit:
        Name: "Rabbit"
        Description:
          - <green>It's a baby Rabbit!
        PetType: Rabbit
        EXP: 0
        Price: 175
        Options:
          - baby
      baby_sheep:
        Name: "Sheep"
        Description:
          - <green>It's a baby Sheep!
        PetType: Sheep
        EXP: 0
        Price: 200
        Options:
          - baby
      baby_skeleton_horse:
        Name: Skeleton Horse
        Description:
          - <green>It's a baby Skeleton Horse!
        PetType: SkeletonHorse
        EXP: 0
        Price: 800
        Options:
          - baby
      baby_villager:
        Name: "Villager"
        Description:
          - <green>It's a baby Villager!
        PetType: Villager
        EXP: 0
        Price: 500
        Options:
          - baby
      baby_wither:
        Name: "Wither"
        Description:
          - <green>It's a baby Wither!
        PetType: Wither
        EXP: 0
        Price: 35000
        Options:
          - baby
      baby_wolf:
        Name: "Wolf"
        Description:
          - <green>It's a baby Wolf!
        PetType: Wolf
        EXP: 0
        Price: 175
        Options:
          - tamed
          - baby
      baby_zombie:
        Name: "Zombie"
        Description:
          - <green>It's a baby Zombie!
        PetType: Zombie
        EXP: 0
        Price: 1000
        Options:
          - baby
      baby_zombie_horse:
        Name: Zombie Horse
        Description:
          - <green>It's a baby Zombie Horse!
        PetType: ZombieHorse
        EXP: 0
        Price: 1200
        Options:
          - baby
      baby_zombie_villager:
        Name: Zombie Villager
        Description:
          - <green>It's a baby Zombie Villager!
        PetType: ZombieVillager
        EXP: 0
        Price: 1300
        Options:
          - baby
      ghast:
        Name: Ghast
        Description:
        - <green>It's a Ghast!
        PetType: Ghast
        EXP: 0
        Price: 5000
        Options:
          - baby
________________________________
Gönderen: Sebastian Comans <notifications@github.com>
Gönderildi: 5 Ekim 2019 Cumartesi 00:06
Kime: xXKeyleXx/MyPet <MyPet@noreply.github.com>
Bilgi: SakizciAdam <durulozcan@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [xXKeyleXx/MyPet] Pet Shop don't working (#1317)


I need the config

**Comment by xXKeyleXx** [comment]
When you say every perm do you mean you are OP? if not could you please show me your permissions please.

**Comment by SakizciAdam** [comment]
I have '*'(all perms) and op but I deleted MyPet folder and restart the server and its working succesfully now. Every player can use shop now.

Android için Outlook<https://aka.ms/ghei36>'u edinin

________________________________
