### ISSUE TITLE
Pets deleted once we store.

### ISSUE THREAD

**Issue by DynastyNetwork** [xXKeyleXx/MyPet#1319]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```
So once my player stores a pet /petstore it also disapears we can not do /petrelease

**Comment by zerafox** [comment]
You **cannot** do /petrelease on a pet put in /petstore!
You **must** first have the pet with you, where you can use /petcall to have the pet next to you, before /petrelease will do anything.


Also, please don't avoid/skip/remove/ignore the template.
It's there so we can better understand what's wrong and help you.

**Comment by DynastyNetwork** [comment]
You don't understand when I do /petstore the pet is automatically released so when i do /petcall or /petrelease it says I dont have a pet even?

**Comment by xXKeyleXx** [comment]
You don't understand what she said. /petstore stores the pet. Can you spend money that you stored in your cellar when you are at the store? Spoiler: you can't.

**Comment by DynastyNetwork** [comment]
how do I release the pet once you stored it so it appears beside you again.

**Comment by xXKeyleXx** [comment]
`/petswitch`
