### ISSUE TITLE
Players get permissions error message for /PetStore when I've confirmed they have the permission node?

### ISSUE THREAD

**Issue by BigScary** [xXKeyleXx/MyPet#1320]
# Question about MyPet

I'm struggling with the /PetStore command.  All of my players are reporting the error message "You are not allowed to use this!".  Of course I can use it, because I am an operator.  But on my secondary non-operator account, I can reproduce the issue.  I am not having trouble with other MyPet commands.  

I am using PermissionsBukkit, which has a command to check whether a player has a specific permission node.  I have confirmed that players who get the error message above DO have the permission node "MyPet.command.store" set to true:

Command: /permissions check MyPet.command.store Bad_Asteroid
Result: "Player Bad_Asteroid sets MyPet.command.store to true."

I also looked through your latest source code and don't see a problem.  I'm 100% stumped on this!  I hope you can help.

I have NOT asked for help in other places, only here.
[MyPet.log](https://github.com/xXKeyleXx/MyPet/files/3705460/MyPet.log)

**Comment by xXKeyleXx** [comment]
Do you gave them the storage limit permission?
`MyPet.petstorage.limit.<limit>`
(`<limit>` need to be replace with the amout of pet the player should be able to store)

**Comment by BigScary** [comment]
Yes, thank you!  If I may offer a suggestion – an update to the setup part of the wiki explaining that many features are off until permissions are given, and especially calling out this permission would help server owners get going faster and I would guess reduce the number of questions you have to answer.  Thank you so much for making this!  In my opinion, you should be charging for it.  Many of my players are very excited.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by xXKeyleXx** [comment]
Yeah I know that I need to improve the wiki.
It was a premium resource before but I don't have the time to maintain 2 versions of the plugin so I made it free 🤷‍♂
