### ISSUE TITLE
Players cannot have more than one pet even with node

### ISSUE THREAD

**Issue by DatSquidFTW** [xXKeyleXx/MyPet#1322]
I have given my players the mypet.petstorage.30 node. However, they still cannot tame any new pets. Even if they sent away the pet. I have tried it myself and can only get more pets if I do /petadmin. I'll drop the ticket.zip here as well. 

https://www.dropbox.com/s/biog4z8kccp54op/ticket.zip?dl=0

**Comment by zerafox** [comment]
The node is
Mypet.petstorage.limit.<limit>

**Comment by DatSquidFTW** [comment]
Oh sorry. I forgot the limit part. It People still can't get their pets

**Comment by xXKeyleXx** [comment]
Sending them away is not enough. You have to store them (`/petstore`) if you want more pets
