### ISSUE TITLE
Frage Bezüglich Max-Stored-Pet-Count

### ISSUE THREAD

**Issue by Darigsey** [xXKeyleXx/MyPet#1326]
Hallo ich hätte eine frage wenn ich Max-Stored-Pet-Count auf 45 habe ist das beabsicht das der Petadmin create command trozdem neue Pets erstellen kann? man kann scheinbar weiter Pets erstelllen damit aber nicht mehr einlagern wenn das Limit erreicht ist wenn das nicht gewollt ist kann man das deaktiveren also das wenn limit erreicht ist auch der comand keine neuen erstellt

es nimmt da auch keine Rücksich die Permission ist auch auf 45 eingestellt es aber kann scheinbar unendlich neue Pets Createn 

Ps.Großes Lob das man hier immer schnell fix andere plugins reagieren nicht so schnell

**Comment by zerafox** [comment]
The admin command doesn't store a pet for a player before giving the player a new pet.
The admin command can either give a pet to a player who doesn't have one, or over-write a pet they already have.

Players can only store their permission given amount of pets. So if 45 is their max storage, the player cannot use /petstore to put away more than 45 pets. That's 45 Pets put away and 1 they can have with them.

The admin command does not give them unlimited pets in any way.

**Comment by xXKeyleXx** [comment]
@zerafox that's not really correct :P

Da es nach wie vor ein Admin Befehl ist, ist es kein Fehler dass dieser das Limit ignoriert. Die neuen pets werden normal eingelagert. Wenn das Limit überschritten wird können keine neuen Pets mehr eingelagert werden aber je nach permission kann noch zwischen den Pets gewechselt werden.

**Comment by zerafox** [comment]
Now I'm confused.

So can the admin command cause someone to go over the limit or not?

**Comment by xXKeyleXx** [comment]
Yes that is possible. The limit will not be checked when using the admin command.

**Comment by zerafox** [comment]
But it doesn't force pets into a storage system? Or does it? o.o

**Comment by xXKeyleXx** [comment]
That's what the `-f` parameter is for.

**Comment by zerafox** [comment]
I thought that just overwrote the existing pet, deleted the old one and made a new one in it's place. Haha!
