### ISSUE TITLE
Riding crash

### ISSUE THREAD

**Issue by logan310** [xXKeyleXx/MyPet#1327]
# Bug report

## Describe the bug
If i ride a mob, i can't going down. If i going down, the server crash.

**Bukkit/Spigot/Bungee Build/Version:**
version 1.13.1
**MyPet Build/Version:**
version 3.8

**Error:**
https://pastebin.com/qUHGfiGN

**Comment by xXKeyleXx** [comment]
Why aren't you use 1.13.2? 1.13.1 is not supported.

**Comment by logan310** [comment]
oh, thanks
