### ISSUE TITLE
Villager create Fehler

### ISSUE THREAD

**Issue by Darigsey** [xXKeyleXx/MyPet#1328]
Hallo ich mal wieder ^^'

beim befehl /petadmin create für Villager ist fehler beim erstellen vom Arbeitsloser und Kartograf dafür gibt es Bibliothekar und Nichtsnutz dobbelt
profession:5 =Nichtsnutz
profession:11 =Nichtsnutz 

profession:1 =Bibliothekar
profession:9 =Bibliothekar

Anmerkung:

bei denn ZombieVillager type:0 profession:0 command erscheint immer ein andere da scheint die zuordnung nicht zugehen 

ich Hoffe es hilft wenn ich solche fehler finde^^

**Comment by xXKeyleXx** [comment]
Bitte fülle das nächste mal die Vorlage aus. Die gibt's aus nem guten Grund ;)
Aber Danke fürs reporten. Habs gefixt.
