### ISSUE TITLE
Skill GUI can copy game items

### ISSUE THREAD

**Issue by GreenChennai** [xXKeyleXx/MyPet#1330]
developer
When my friend uses your plugin.
He found that other players can use the plugin's vulnerability to copy game items.
How to copy and how to trigger him is not known, but the only known vulnerability GUI for items that can be copied is located in the skill GUI.
IF you can, please fix him!
Mypet 
ver3.8

**Comment by xXKeyleXx** [comment]
Use the template! If I don't know how to do it I can't fix it. I need a detailed description.
