### ISSUE TITLE
I can't call Pets

### ISSUE THREAD

**Issue by imJoncen** [xXKeyleXx/MyPet#1331]
I dowloadet MyPets, created yesterday 2 Pets to check if it's working and everything was right.
Today I came online and since that I can't call them anymore.
Ater that I delete the MyPets folder and resinstall it, restart the server but nothing changed.

So now my Question:
Why can I create a Pet, see them in /petswitch but if I want to click on it the chat awnser:
Pets are not allowed here!

But I doesn't changed anything everything is like i downloadet it
For example:

worldgroups.yml

# ######################################################################
#           This is the world group configuration of MyPet             #
#                 You can find more info on the wiki:                  #
#   https://wiki.mypet-plugin.de/setup/configurations/worldgroups.yml  #
# ######################################################################

Disabled:
- example_world
Groups:
  default:
  - Skyblock
  - bskyblock_world
------------------------------------------

MyPet.log

11-19-2019 16:15 [INFO] [MyPet] Error-Reporter ENABLED
11-19-2019 16:15 [INFO] [MyPet] Enabling MyPet v3.8
11-19-2019 16:15 [INFO] [MyPet] No Update available.
11-19-2019 16:15 [INFO] [MyPet] Custom entity registry found: net.minecraft.server.v1_14_R1.RegistryBlocks
11-19-2019 16:15 [INFO] [MyPet] Compat mode for v1_14_R1 loaded.
11-19-2019 16:15 [INFO] [MyPet] Exp calculation mode: MyPet
11-19-2019 16:15 [INFO] [MyPet] Current Exp-Cache is invalid, it will be recalculated.
11-19-2019 16:15 [INFO] [MyPet] Loading WorldGroups...
11-19-2019 16:15 [INFO] [MyPet]    added Skyblock to 'default' group.
11-19-2019 16:15 [INFO] [MyPet]    added bskyblock_world to 'default' group.
11-19-2019 16:15 [INFO] [MyPet] Default skilltree files created.
11-19-2019 16:15 [INFO] [MyPet] Connect to SQLite database...
11-19-2019 16:15 [INFO] [MyPet] SQLite connection successful.
11-19-2019 16:15 [INFO] [MyPet] ProtocolLib (4.5.0-SNAPSHOT) hook activated.
11-19-2019 16:15 [INFO] [MyPet] SuperVanish (6.1.3) hook activated.
11-19-2019 16:15 [INFO] [MyPet] Vault (1.7.2-b107) (Economy: Essentials Economy) (Permissions: LuckPerms) hook activated.
11-19-2019 16:15 [INFO] [MyPet] version 3.8-b1505 ENABLED

Our Server is on the 1.14.4
If you want you can add me on Discord: Joncen#4703
I really like your Plugin, just can't call the Pets <.<

**Comment by xXKeyleXx** [comment]
Are you vanished?

**Comment by wuc656** [comment]
same

**Comment by zerafox** [comment]
> same

Saying "Same" without providing information doesn't help us help you.
There wasn't enough information for us to help the original author of this ticket.

You are also running a 1.14.4 server with a 3.8 MyPet version?
All your settings are 100% default?

What about the question of "Are you vanished"?

**Comment by wuc656** [comment]
I found the source of the problem
RPGInventory internal player data error and Mypet has dependencies on it
So Mypet is not allowed to generate pets
I forced to remove the pet slot of RPGInventory and delete its player data
The problem is solved
I use Google Translate to translate the above text. I am Taiwanese. My language is Chinese.
