### ISSUE TITLE
Dropping Item Given to Pet

### ISSUE THREAD

**Issue by EmmLey** [xXKeyleXx/MyPet#1338]
# Question about MyPet

_Please describe what is on your mind. If possible also provide a context and your end goals._

* [ ] I have asked for help on other places like Discord ord the discussion on spigotmc.org
Hello! I am Emm and the server I work for is using MyPet, I can't figure out how to make a pet drop an item, you give an item to it using shift-right click but when I try again it makes it stop following you. How do I get my pet to take the item out of it's hand?

-Emm

**Comment by xXKeyleXx** [comment]
It is answered in the FAQ.

**Comment by EmmLey** [comment]
Oh ok thankyou
Where is that?

**Comment by EmmLey** [comment]
Oh, found it, thanks for your time sorry to bother you.
