### ISSUE TITLE
I have the MyPet plugin and my server is on 1.15 version. Every time I try to use a command, it says "An internal error occurred while attempting to perform this command". I tried removing and installing it again, resetting the config but it didn't change. I've read on the reviews that it works on 1.15.1 and that it's been recently updated as of last wednesday. How can i make this work on my server? 

### ISSUE THREAD

**Issue by eevee1268** [xXKeyleXx/MyPet#1342]
# Explain your question

* [x] I have checked existing issue and found none that could answer my question.

_Describe your question as detailed as possible. If possible include context, source of the problem and end goal that you have, to make it easier for me to understand your question._

> I encourage you to try and make an issue with one of the other templates before submitting the general form.

**Comment by xXKeyleXx** [comment]
Wrong template, bad title, no info.
