### ISSUE TITLE
Shop permissions

### ISSUE THREAD

**Issue by Benjamin1630** [xXKeyleXx/MyPet#1347]
# Explain your question
I was setting up permissions for the plugin so players can use it properly, when I noticed the shop permissions wouldn't show up. It only works if I give mypet.admin permissions, which for obvious reasons I don't want to. I have even tried manually adding the mypet.shop.access.<shopname> to the permissions, but that didn't work. Is there something I'm missing?

* [ X] I have checked existing issue and found none that could answer my question.
Found nothing relating to this.

_Describe your question as detailed as possible. If possible include context, source of the problem and end goal that you have, to make it easier for me to understand your question._
I'm just trying to allow players to access the shop, without giving them admin access. Currently it is not possible as the shop permissions will not show up when I enter them into LuckPerms.

**Comment by zerafox** [comment]
The permission node you'd need to give players is: `MyPet.shop.access.<shopname>`
Where <shopname> is the name of the shop you've created.
For example:
`Shops:
  <shop-id>:
        Name: My Shop
`
`Shops:
  Shop1:
        Name: My Shop
`
Would need the permission node: `MyPet.shop.access.Shop1`.

**Comment by Benjamin1630** [comment]
Alright, so what I've done now is set it to MyPet.shop.access.Shopets as well as having renamed the first shop in pet-shops.yml to Shopets, but the same message pops up telling players "You are not allowed to use this!"

**Comment by zerafox** [comment]
Make sure there isn't an error in your shops.yml file itself.
If there's an error in syntax somewhere it won't load at all, which would be a reason that LuckPerms wouldn't find a permission for it in the first place too. :P

**Comment by Benjamin1630** [comment]
![Uploading Capture.PNG…]()
Here is the pet-shops.yml. To me it seems everything is right...

**Comment by zerafox** [comment]
> Here is the pet-shops.yml. To me it seems everything is right...

Run it through an online parser, it will find any errors for you.
That link/file doesn't work.

**Comment by Benjamin1630** [comment]
![Capture](https://user-images.githubusercontent.com/45171463/74092095-922b4000-4ab7-11ea-99ed-7b081954d2d9.PNG)
Here, sorry. I tried running it through an online parser, but since I don't know much about plugins, I couldn't determine much from it, other than it looks like it should work.

**Comment by zerafox** [comment]
It's not the "name" you need to permission. It's the "All"

"all" is the ID of the shop.
As seen in my example before:
```
Shops:
  <shop-id>:
        Name: My Shop
```

"My Shop" is not the permission. <shop-id> is.

**Comment by Benjamin1630** [comment]
Yes, my bad! That's fixed it. 
Thank you so much for the help!!
