### ISSUE TITLE
Pet Farming Skill Tree

### ISSUE THREAD

**Issue by Benjamin1630** [xXKeyleXx/MyPet#1348]
# Explain your question
I wanted to ask how the Farm skilltree works. A player on my server only wants to farm so he captured a villager and chose the farm skill, but he is confused on how it works and so am I.

* [ ] I have checked existing issue and found none that could answer my question.
I have tried reading the documentation on the official website as well as trying to find similar questions on github, couldn't find anything.

_Describe your question as detailed as possible. If possible include context, source of the problem and end goal that you have, to make it easier for me to understand your question._
Just want to know how it works, as it currently does nothing, even when next to a farm plot.

**Comment by zerafox** [comment]
This is not an actual "Farming" skilltree.
Pets cannot interact with Crops, or blocks in this way (or any other way for that matter).

You can inspect the Pre-Built Example Skilltrees by opening them with the built-in editor for a better understanding of the Example Skilltrees.
These Skilltrees were only intended to be examples, as the plugin is designed to be customized to your servers needs.
As such, I cannot say that I am overly familiar with the default examples provided within the plugin itself, but I can safely say that the "Farm" skilltree has absolutely nothing to do with actual Minecraft farming.

**Comment by Benjamin1630** [comment]
Alright, glad that got cleared up. I'll attempt to do some changes.
Thanks by the way, you've been a great help!

**Comment by zerafox** [comment]
Glad to be of help!
If you have any further questions, you know where to find us. ;P
