### ISSUE TITLE
Permission not work MyPet

### ISSUE THREAD

**Issue by ShotCraft3x** [xXKeyleXx/MyPet#1349]
Hello! I have been testing your mypet plugin and I find it fantastic but I still can't find the necessary permissions to be able to use the command for the behavior of the pet, I am an administrator with op and still it tells me that I do not have permissions to access the /pb duel command, for example. what will happen?

**Comment by ShotCraft3x** [comment]
My server is in version 1.14.4

**Comment by zerafox** [comment]
The templates are there for a reason, it makes it incredibly difficult for us to determine what may or may not be a problem if you don't properly fill it out.
