### ISSUE TITLE
Permissions does not work

### ISSUE THREAD

**Issue by ShotCraft3x** [xXKeyleXx/MyPet#1350]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Hello! sorry, for not publishing the template but I'm new here and I just created the account.
I have been testing your mypet plugin and I find it fantastic but I still can't find the necessary permissions to be able to use the command for the behavior of the pet, I am an administrator with op and still it tells me that I do not have permissions to access the /pb duel command, for example. what will happen?-
I am trying with a pet pig, in this link https://wiki.mypet-plugin.de/skills/behavior the command / petbehavior if it works, I have tried until I put mypet.admin permission that supposedly gives me all the permissions of the plugin, but still tells me that: "you are not allowed to use this" 

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

I hoped I could access the behaviors of each pet, but I tried several and it still doesn't let me.

## Actual behaviour

I do not think it is necessary to add a photo, since there is no error in the console or anything, it just tells me that I do not have permissions

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by xXKeyleXx** [comment]
The behavior command is part of the `Behavior` skill. Does your pet have this skill (`/petskill)`?

**Comment by ShotCraft3x** [comment]
It does not have any, I have tried to raise it to level 100 by means of command but it still does not have, how can it obtain skills?

**Comment by xXKeyleXx** [comment]
You have to select a skilltree: `/pcst` or `/petchooseskilltree`
