### ISSUE TITLE
Pet Giving (not admin)

### ISSUE THREAD

**Issue by loler08vn** [xXKeyleXx/MyPet#1351]
# Feature request

What part of MyPet needs this?
- [x] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

## Is your feature request related to a problem? Please describe

this is a problem with this plugin... my friend in a server have a horse... he want to give it to me (the server im playing need to donate to have pet) but this plug-in doesn't have any command to give pet to another player...

## Describe the solution you'd like

A command (like, /petgift [player])
This command will open a GUI when the player can chosse the pet that they want to send to the another player.
_/petgift Player1 of /pgift Player 1_

## Describe alternatives you've considered

_A clear and concise description of any alternative solutions or features you've considered._

## Additional context

If that successful, its will say "Your pet was gifted to [player] !"
If the player that is the target (in [player]), it'll say "The player is not online. Please try again when that player online."

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**Comment by xXKeyleXx** [comment]
The plugin has a command to do this (`/pettrade`)

**Comment by loler08vn** [comment]
thx
