### ISSUE TITLE
Some GUI Changes

### ISSUE THREAD

**Issue by ironleather** [xXKeyleXx/MyPet#1353]
Make /pcst, petbeacon, and petinventory GUI-display-name editable
Make pet beacon GUI editable
Make /petskill and /petinfo chat-display editable

**Comment by zerafox** [comment]
You can edit language/locale to get most of these to display exactly what you'd like to already.
You will need to download/extract your desired locale and edit the file, upload to your server.

Pet Beacon is the exact same Beacon as the Vanilla Beacon, we cannot edit this without a mod.
