### ISSUE TITLE
Beacon-Partikel auch für "versteckte" Spieler

### ISSUE THREAD

**Issue by M1904** [xXKeyleXx/MyPet#1359]
# Bug report

* [ x ] I have checked other issues to make sure this is not a duplicate.

Hallo,

Die Spieler meines Servers erfreuen sich gerade sehr an den Haustieren, da wir sie für die Farmwelt freigegeben haben. Vielen Dank für das Plugin. Bis jetzt funktioniert schon einmal alles super, allerdings ist mir ein kleiner Bug aufgefallen. Wenn ein Spieler den Leuchtfeuereffekt für jedermann aktiviert, bekommen diesen auch Spieler, die sich im Vanish befinden (sogar im gm3) und produzieren Partikel, mit denen sie enttarnt werden. Macht sich bei Kontrollbesuchen schlecht. Wir nutzen Premiumvanish. Das Verhindern, dass die eigenen Pets erscheinen, funktioniert auch wunderbar. Wenn die Partikel im Vanish auch noch verborgen werden können, würde das unsere Arbeit etwas erleichtern.

Viele Grüße
Chris

**Comment by xXKeyleXx** [comment]
Ist im aktuellen DEV build integriert

**Comment by M1904** [comment]
Vielen Dank für die schnelle Bearbeitung :)
