### ISSUE TITLE
Pet backpack has a chance to read the last time archive

### ISSUE THREAD

**Issue by GreenChennai** [xXKeyleXx/MyPet#1360]
# 错误报告
# Bug report

* Pet backpack has a chance to read the last time archive

## Describe the bug

* Pet backpack has a chance to read past archives
* The archive read is about a few seconds to 1 minute ago
* Open the pet backpack after the owner dies
* Most pets can be realized in the actual measurement, and there is no error in the background

## To Reproduce

```
1.Put items in your pet backpack
2.Remove some items from your pet backpack
3.Here is the pet or the player died, he didn't say clearly
I'm not sure who died,This trigger method was told by a player
4.Recalling Pets Open Backpack
5.Pet backpack has a chance to read the state before taking out the item
```

* There is only a chance that it is not 100% triggered

## Expected behavior

* Some players can use him to copy items

## Actual behaviour

* Players use this bug to copy items

## Additional context

MC Ver 1.12.2
Core Paper spigot
MyPet Ver 3.9

##错误代码
**Error:**
```
NULL
```

**Comment by xXKeyleXx** [comment]
Have you tried the latest dev build?
https://mypet-plugin.de/download

**Comment by GreenChennai** [comment]
Sorry, did not try dev build
Based on one hour test
This bug did not appear in dev build

Sorry
