### ISSUE TITLE
Server crashes when I try to capture a pet

### ISSUE THREAD

**Issue by Ihabar** [xXKeyleXx/MyPet#1362]
When I try to pet a mob with the lead the whole server crashes

**Bukkit/Spigot/Bungee Build/Version:**

12.2 Spigot
**MyPet Build/Version:**

3.9

PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```
A fatal error has been detected by the Java Runtime Environment:

#

# SIGSEGV (0xb) at pc=0x000000000000a786, pid=1, tid=0x00007fe305f55b10

#

# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)

# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)

# Derivative: IcedTea 3.12.0

# Distribution: Custom build (Sat May 4 17:33:35 UTC 2019)

# Problematic frame:

# C 0x000000000000a786

#

# Core dump written. Default location: /home/minecraft/core or core.1

#

# An error report file with more information is saved as:

# /tmp/hs_err_pid1.log

#

# If you would like to submit a bug report, please include

# instructions on how to reproduce the bug and visit:

# https://icedtea.classpath.org/bugzilla

**Comment by zerafox** [comment]
This is a Java crash, not a crash-report we can work with.

Also please use the appropriate format, it helps no one when you delete it.

**Comment by Ihabar** [comment]
Where do i find the crash report you need?
And sorry,didnt know how to use the format

**Comment by zerafox** [comment]
In your console log.
Your console is what tells you all the information you need to know about your server.

**Comment by Ihabar** [comment]
Thats what I got on my server console

**Comment by zerafox** [comment]
No, that's what came up after Java Crashed.
Your server Console is still part of a running Java environment.

Relaunch your server. Watch what comes up in that black (sometimes white) box and see how it will say something about your plugins starting, etc etc;
THAT is your console.
