### ISSUE TITLE
warn 1.15.2 bug move...

### ISSUE THREAD

**Issue by Bricec6** [xXKeyleXx/MyPet#1363]
Hello i find bug movement all mobs, follow & attack (1.15.2)
Last version paper, mypet 3.9 & last build test

plugins, in video
no config.yml change & all file..

video youtube: 
https://www.youtube.com/watch?v=3RGr_GdN9jY

please debug this plugin..

**Comment by zerafox** [comment]
Please fill out a proper report using the template, including errors and actual information that isn't "latest".

We can't do anything with the word "latest" and can't do anything without an Error Log either.
