### ISSUE TITLE
The playerhead in the Petbeacon GUI lagging the server in China

### ISSUE THREAD

**Issue by GailKabala** [xXKeyleXx/MyPet#1367]
# Bug report

## Describe the bug

        There is the bug happening in China. When any player use /petbeacon , the server will lag for some time (10-30 seconds).  This is because the China Network has a Greate Firewall preventing to connect foreign network, when server use mojang api to get player textures (such as skulls).
       The server getting player_head's texture is not async code. It will lag until the skull texture is downloaded complete.

## To Reproduce

1.  Go to China
2. Use /petbeacon
...

## Expected behavior

Use a simple config to stop using player textures skull.

## Additional context

Any versions of Mypet.

Any versions above 1.7.10.

(The bug has nothing to do with the versions, and it is because of our native network.)

I hope to add a config to disable the playerskull in the petbeacon GUI.

Thank you!!!

**Comment by engineer1109** [comment]
+1.
It is a serious problem in China.
The player skull (has texture) will lag server.
Disable the playerskull (Or use a normal playerskull  , no owner NBT) will solve the problem.

**Comment by xXKeyleXx** [comment]
Try the latest dev build please

**Comment by GailKabala** [comment]
Thanks it works.
