### ISSUE TITLE
Cannot access to MySQL's data

### ISSUE THREAD

**Issue by Hiobi** [xXKeyleXx/MyPet#1368]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_MyPet is connect to MySQL database but it cannot access to datas_

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Configure MyPet
2. Launch PaperMC server
3. MyPet connect with success to database

...

## Expected behavior

1. MyPet's table named `mypet_info` table have column  `version` with the right MyPet version  : `3.10 SNAPSHOT mypet_build 1534`
2. When a player connect to server, MyPet output error (see below)

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:** Paper 1.15.2 R0.1 #161 (with our own docker image)

**MyPet Build/Version:** 3.10 #1534

**What is the expected result?** Should access to data and pets

**What happens instead of that?** No data

**Error:**

When a player connect to server, MyPet output errors :+1: 

```
[16:04:14] [Craft Scheduler Thread - 24/WARN]: java.util.zip.ZipException: Not in GZIP format
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at de.Keyle.MyPet.util.nbt.TagStream.readTag(TagStream.java:30)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at de.Keyle.MyPet.repository.types.MySqlRepository.resultSetToMyPetPlayer(MySqlRepository.java:818)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at de.Keyle.MyPet.repository.types.MySqlRepository.access$200(MySqlRepository.java:54)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at de.Keyle.MyPet.repository.types.MySqlRepository$12.run(MySqlRepository.java:929)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[16:04:14] [Craft Scheduler Thread - 24/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

```

Thanks Keyle ! 😊

**Comment by xXKeyleXx** [comment]
Did you change something at or inside the database?

**Comment by Hiobi** [comment]
No, I don’t think so. Not in MyPet’s table.

**Comment by xXKeyleXx** [comment]
Does this happen for all players or just specific?

**Comment by Hiobi** [comment]
For all players.
We can use MyPet in game, have a pet, etc but when the server restart we "loose" all pets.
Nothing seems to be saved into `pets.db`.


I regenerated a default config and re-add our database infos (with or without `?useSSL=false`), same error. I didn't try with a complete reset of datas, but I think it should be ok.

```
# #################################################################
#            This is the main configuration of MyPet              #
#              You can find more info on the wiki:                #
#   https://wiki.mypet-plugin.de/setup/configurations/config.yml  #
# #################################################################

MyPet:
  Update:
    Check: true
    Download: false
    ReplaceOld: false
    In-Background: false
    OP-Notification: true
  Leash:
    Consume: false
    AllowRanged: true
  OwnerCanAttackPet: false
  DisablePetVersusPlayer: false
  RetainEquipmentOnTame: true
  Make-Pet-Invisible-When-Owner-Is-Invisible: true
  Log:
    Level: INFO
    Report-Errors: true
    Unique-ID: <uid>
  Max-Stored-Pet-Count: 45
  Throw-PlayerMoveEvent-While-Riding: true
  Disable-All-Actionbar-Messages: false
  OverwriteLanguages: ''
  Right-Click-Command: ''
  Entity:
    Skip-Target-AI-Ticks: 0
    FollowStartDistance: 7.0
  Repository:
    Type: MySQL
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      Database: <database>?useSSL=false
      TablePrefix: mypet_
      Host: <host>
      Password: <password>
      User: <user>
      Port: <port>
      MaxConnections: 8
      CharacterEncoding: utf8
    MongoDB:
      Database: mypet
      CollectionPrefix: ''
      Host: localhost
      Password: ''
      User: ''
      Port: 27017
  Respawn:
    Time:
      Disabled: false
      Default:
        Factor: 5
        Fixed: 0
      Player:
        Factor: 5
        Fixed: 0
    EconomyCost:
      Fixed: 0.0
      Factor: 1.0
  Permissions:
    Enabled: true
    Extended: false
    Legacy: false
  LevelSystem:
    CalculationMode: Default
  HungerSystem:
    Active: true
    Time: 60
    SaturationPerFeed: 6.0
    Affect-Ride-Speed: true
    Affect-Beacon-Range: true
  Skilltree:
    AutomaticAssignment: false
    RandomAssignment: false
    ChooseOnce: false
    PreventLevellingWithout: true
    SwitchFee:
      Fixed: 0.0
      Percent: 5
      Admin: false
  Name:
    Filter:
    - whore
    - fuck
    MaxLength: 32
    Tag:
      Show: true
      Prefix: <aqua>
      Suffix: ''
  Exp:
    DamageWeightedExperienceDistribution: true
    Passive:
      Always-Grant-Passive-XP: true
      PercentPerMonster: 25
    Loss:
      Percent: 0
      Fixed: 0.0
      Drop: true
      Allow-Level-Drowngrade: false
    Gain:
      PreventFromSpawnReason: []
    LevelCap: 100
    Disabled-Worlds: []
    Modifier:
      Global: 1.0
      Use-Permissions: false
  Skill:
    Control:
      Item: lead
    Backpack:
      Creative: false
      DropWhenOwnerDies: false
    Beacon:
      HungerDecreaseTime: 100
      Disable-Head-Textures: false
      Party-Support: true
    Ride:
      Item: lead
      HungerPerMeter: 0.01
      Prevent-Teleportation-While-Riding: false
  Info:
    Wiki-URL: https://wiki.mypet-plugin.de
```

**Comment by zerafox** [comment]
`pets.db` is only used if you set it to use SQL saving, not MySQL.

Just to clarify, you are filling out the MySQL information correct, you're not actually leaving it looking just like this:

>   Repository:
    Type: MySQL
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      Database: <database>?useSSL=false
      TablePrefix: mypet_
      Host: <host>
      Password: <password>
      User: <user>
      Port: <port>
      MaxConnections: 8
      CharacterEncoding: utf8

**Comment by Hiobi** [comment]
> pets.db is only used if you set it to use SQL saving, not MySQL.

Yeah I known it's for SQL, I checked it and mentionned it to be sure that the MySQL settings aren't bypassed.


> Just to clarify, you are filling out the MySQL information correct, you're not actually leaving it [...]

Of course, I just masked connection settings for the paste. MyPet is connected to my database, at launch and it seems to be writeable (correct version in table `mypet_info`).

**Comment by Hiobi** [comment]
For tests purpose, I dropped mypet's tables after a mysqldump, then I started the server, MyPet created tables without issue and added data. I checked the tables structure, it seems to be the same.

**Comment by zerafox** [comment]
It sounds like it had become corrupted somehow previously.

**Comment by Hiobi** [comment]
At first, I thought so too !

I made some checks, `mysqlcheck / check TABLE` just return **OK**, nothing to repair.

```
minecraft_mypet.mypet_info                         OK
minecraft_mypet.mypet_pets                         OK
minecraft_mypet.mypet_players                      OK
```

I don't known if MyPet can resolve this, for the moment we just dropped our *MyPet* tables to restarted from scratch.

**Comment by xXKeyleXx** [comment]
I will add a fix that will irgnore the corrupted data later today
