### ISSUE TITLE
Is there a way to disable pets colision with everything ?

### ISSUE THREAD

**Issue by KKFireLoL** [xXKeyleXx/MyPet#1370]
# Question about MyPet

_Please describe what is on your mind. If possible also provide a context and your end goals._

* [ ] I have asked for help on other places like Discord ord the discussion on spigotmc.org

Hi I Just want to know If there is a way to remove the colisions of the pets Can you help me pls ?

**Comment by zerafox** [comment]
If you mean have it so pets can walk through things, or so that players can walk through pets.
No, there is no way to do this.
