### ISSUE TITLE
Message.DeathMessage is not returning the correct message.

### ISSUE THREAD

**Issue by FabioPretti** [xXKeyleXx/MyPet#1380]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

Personally, I had already reported many months ago, but there was a lack of information.

## Describe the bug

_Message "Message.DeathMessage" is not working, has changed several times and always shows the message from the country checker._

## To Reproduce

_Let a player kill your pet, when the message appears that the pet died will return the message from the country checker from minecraft_

## Expected behavior

_Just make the Message.DeathMessage message work._

## Actual behaviour

![image bug](https://user-images.githubusercontent.com/33943962/84579776-4a8b2c80-ada7-11ea-865c-b24ecaa821e8.png)

## Additional context

> [ticket.zip](https://github.com/xXKeyleXx/MyPet/files/4775543/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:** Spigot 1.8.8

**MyPet Build/Version:** MyPet-3.10-b#1542

**What is the expected result?** Just make the Message.DeathMessage message work

**What happens instead of that?** It simply does not return the .properties message

**Error:**
```
No console errors.
```

**Comment by zerafox** [comment]
Duplicate to #1262
