### ISSUE TITLE
 How can aquatic organisms swim in water?

### ISSUE THREAD

**Issue by Tatado2020** [xXKeyleXx/MyPet#1384]
# Question about MyPet

 For example, I caught a puffer fish as my pet, I want it to give me the effect of breathing underwater so I can stay in the water longer... But when I'm deep in the sea, my puffer fish pet can' t be summoned.
 I hope all aquatic pets can swim in the sea, not just float on the sea, so what do I do?

**Comment by zerafox** [comment]
This actually isn't possible because pets don't swim.
There isn't anything that can be done about this either.

Pets behave just like Vanilla Wolves, after all they use the same AI.
