### ISSUE TITLE
Auto Feed for Pets

### ISSUE THREAD

**Issue by TheBlankSlate** [xXKeyleXx/MyPet#1392]
# Feature request

What part of MyPet needs this?
- [✓] the plugin itself
- [✗ ] the Skilltree Creator
- [✗] the website

## Is your feature request related to a problem? Please describe
_A clear and concise description of what you want and what your use case is._
Not really. This is more of a convenience request.

## Describe the solution you'd like
_A clear and concise description of what you want to happen._
I think it would be cool if you made it where if there is food in the pet's inventory it would auto eat instead of you having to feed it manually. For example, if you have a skeleton pet and you put bones in its inventory then it will take the bones out the inventory and eat it.

## Describe alternatives you've considered
_A clear and concise description of any alternative solutions or features you've considered._
You could also make it a skill for the pet,

## Additional context
_Add any other context or screenshots about the feature request here._
no

**Bukkit/Spigot/Bungee Build/Version:**
Paper 1.16.1

**MyPet Build/Version:**
MyPet-3.11-SNAPSHOT-b#1556

**Comment by zerafox** [comment]
Duplicate #1077
