### ISSUE TITLE
Mypet cause other plugin to hook other plugin.

### ISSUE THREAD

**Issue by ChrisFlyer7** [xXKeyleXx/MyPet#1394]
# Bug report

* [ ] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```
MyPet will cause skillspro plugin can't to hook kingdoms, mypet, residense plugins.
https://www.spigotmc.org/resources/skills-pro.8981/

**Comment by zerafox** [comment]
Properly fill out the template instead of just skipping it all.
We need information to actually do anything, "doesn't work" or "it's broken" statements are useless.
