### ISSUE TITLE
broken skillspro to hook other plugins

### ISSUE THREAD

**Issue by ChrisFlyer7** [xXKeyleXx/MyPet#1395]
# Bug report

server have mypet. please check row 1298 and 1301
https://pastebin.com/cNTMq0D7

server no mypet. please check row 1420 and 1423
https://pastebin.com/VETGavPF

if you have time please try to fix it.thank.

**Paper Version:**
Paper 1.16.1 version131

**MyPet Build/Version:**
MyPet-3.11-SNAPSHOT-B1558

**Comment by zerafox** [comment]
You need to be more descriptive of what is going on. These logs don't show us anything outside of "Mypet is installed" or "No MyPet"

There are no errors, no other differences that we see.
Don't delete the template.. It's there for a reason!
