### ISSUE TITLE
Allow players to change plugin messages

### ISSUE THREAD

**Issue by PotatoIQ** [xXKeyleXx/MyPet#1408]
# Feature request

What part of MyPet needs this?
- [x] the plugin itself
- [ ] the Skilltree Creator
- [ ] the website

_A clear and concise description of what you want and what your use case is._

I want to be able to edit the messages that show to players for the plugin to my own custom messages.

## Describe the solution you'd like

Allow the plugin to read language file from locale, instead of only reading it from the plugin itself.

**Bukkit/Spigot/Bungee Build/Version:**

git-Paper-160 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**MyPet Build/Version:**

MyPet-3.11-SNAPSHOT-B1566

**Comment by xXKeyleXx** [comment]
What do you think is the locales folder for... Just extract the file you want to edit and put it there.
