### ISSUE TITLE
beacon

### ISSUE THREAD

**Issue by elaineandsparky** [xXKeyleXx/MyPet#1410]
when i type the command /petbeacon it says my pet doesn't know the skill beacon. The only thing i can find on becons in the config is this:
 Beacon:
      HungerDecreaseTime: 100
      Disable-Head-Textures: false
      Party-Support: true

and this from the wiki which doesn't tell me how to setup the beacon skill in the config:
https://wiki.mypet-plugin.de/skills/beacon#beacon-buff-selection-menu

what am i doing wrong? do pets have to be a certain level to use the beacon skill? where is all the config on petbeacons? and how do i get to the beacon buff selection menu as shown in the wiki?

**Comment by xXKeyleXx** [comment]
https://wiki.mypet-plugin.de/systems/skilltrees
https://wiki.mypet-plugin.de/systems/skilltrees/skilltreecreator
https://wiki.mypet-plugin.de/skills/beacon
