### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by LadyRayvyn** [xXKeyleXx/MyPet#1411]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate. Yes I have

## Describe the bug
I gave everyone permissions and they are not working. I have read every page available. rechecked twice. still they only work for me as Owner/OP. Also the pets that are supposed to collect items do not collect anything.

_A clear and concise description of what the bug is._

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. 
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/5237169/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by xXKeyleXx** [comment]
It's not a bug when you did not setup your permissions correctly.
All available permissions are on the wiki page: https://wiki.mypet-plugin.de/setup/permissions

**Comment by LadyRayvyn** [comment]
each permission is copied exactly what is on that site. yet they are not working. I will continue to look..however what about the collectors not collecting?
