### ISSUE TITLE
Dev build crashes server repeatedly: "Could not pass event InventoryClickEvent to MyPet v3.11"

### ISSUE THREAD

**Issue by BigScary** [xXKeyleXx/MyPet#1424]
# Bug report

Yes, I have checked other issues to make sure this is not a duplicate.

## Describe the bug

I updated to the latest dev build today.  My server crashed and autorestarted 16 times today with this message filling the logs:

https://pastebin.com/jcbsQvt8

When I tried the current release version instead, I get this message during startup and none of the commands work:

This version of MyPet is not compatible with "v1_16_R2". Is MyPet up to date?

I fully understand this may be my fault for mismatching plugin version with server version.  What's my best option for keeping my server online and also having the plugin work?  Is there a build for 1.16.2 servers that I can get from somewhere?

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Install current dev build on a 1.16.2 server.
2. (This is a guess) Try to access a pet's inventory?

## Expected behavior

Inventory access and manipulation.

## Actual behaviour

See paste above.  It might be caught in some infinite loop or something like it, because that message repeats forever in my logs until the server eventually reboots.

**Comment by ScuroK** [comment]
Maybe try to update your server to 1.16.3?

**Comment by xXKeyleXx** [comment]
v1_16_R2 is not supported anymore
