### ISSUE TITLE
Plugin build not work maven and jenkins

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#1427]
I want to build or download from Jenkins the plugin but it doesn't work.
https://pastebin.com/zwKaaWpb
https://ci.codemc.io/job/ThirdParty/job/MyPet/55/

@TitanDevX

**Comment by xXKeyleXx** [comment]
Does it still happen?

**Comment by andris155** [comment]
yes

**Comment by xXKeyleXx** [comment]
Then it's a problem with your build setup and not the plugin
