### ISSUE TITLE
1.16.4 Pet inventories duplicating

### ISSUE THREAD

**Issue by Punkred** [xXKeyleXx/MyPet#1429]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Pet inventories are rolling back to whatever was in the inventory before the plugin update to 1.16.4 when a player logs off and logs back in. 

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Player logs in
2. Player checks /pi and clears contents
3. Player logs off then back on
4. Inventory has been rolled back even if contents was altered or emptied

## Expected behavior

Pet inventory should be left how it was on log out

## Actual behaviour

Pet inventory is rolling back

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
https://www.dropbox.com/s/hf2snb6xt01l1vq/ticket.zip?dl=0

**Bukkit/Spigot/Bungee Build/Version:**
git-Tuinity-"52f4d08" (MC: 1.16.4)

**MyPet Build/Version:**
MyPet-3.11-SNAPSHOT-B1583.jar

**Error**
https://pastebin.com/raw/68uzBEat

**Comment by mercurialmusic** [comment]
Confirming, I'm getting this too with b1583 on Paper 263 (1.16.4)

Error: https://gist.github.com/mercurialmusic/53a791b766328114cfd1c77e11fa4bbe

And also, thanks for keeping this maintained!

**Comment by franxyk** [comment]
Is bug is present in #1586?

**Comment by Punkred** [comment]
As of latest version this issue has been fixed for me 👍

**Comment by mercurialmusic** [comment]
Same for me. This can probably be closed.
