### ISSUE TITLE
baby llama's

### ISSUE THREAD

**Issue by elaineandsparky** [xXKeyleXx/MyPet#1430]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_A clear and concise description of what the bug is._

Baby Llamas do not turn into pets when killed with a lead but die instead.

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. Kill baby llama with a lead
2.
...

## Expected behavior

_A clear and concise description of what you expected to happen._

Baby llama turn into a pet

## Actual behaviour

_If applicable, add screenshots to help explain your problem._

baby llama dies

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

Tested with mooshroom baby which worked fine.

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**
3.10 and dev build  MyPet-3.11-SNAPSHOT-B1586.jar

**What is the expected result?**

**What happens instead of that?**

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by xXKeyleXx** [comment]
Does it work with adult Llamas?

**Comment by elaineandsparky** [comment]
we have it setup that tameable mobs need to be tamed first. so an untamed adult llama dies but a tamed llama becomes a pet as expected.
So i believe the issue is that baby llamas can't be tamed and so as there is no seperate config for baby llamas the config treats all llamas the same and so wants you to tame them first which isn't possible and so kills them instead of turning them into pets.

**Comment by xXKeyleXx** [comment]
This is eaxactly what I would have answered if you answered yes to my question :P

Adult and baby Llamas are the same pet type and therefore share the same config.

**Comment by elaineandsparky** [comment]
is there a way to fix this or are baby Llamas as pets a no go?

**Comment by xXKeyleXx** [comment]
The "tamed" requirement is the problem here. All requirements must be met otherwise they don't get converted into pets

**Comment by elaineandsparky** [comment]
would you be able to add the baby llama as a seperate pet type? 
if not, no taming it is! :)

**Comment by xXKeyleXx** [comment]
I'm not adding new features anymore as I'm done with MyPet myself. But maybe @TitanDevX will add this in the distant future so I guess no taming it is (at least for now)

**Comment by elaineandsparky** [comment]
ok thank you for your help
