### ISSUE TITLE
Database backend support

### ISSUE THREAD

**Issue by xXKeyleXx** [xXKeyleXx/MyPet#182]
Add database backend support to store pets in databases like MySQL or MongoDB

**Comment by astr1al** [comment]
Was wondering myself if SQLite or MySQL integration was in the works. My server crashes a few times a month, and when it does My.Pets file gets wiped. I have routine backups but restoring manually all the time isn't very efficient. Have been wanting to do a pet battle arena, but it's hard to keep players interested in pets when the one they've been training for the last few weeks goes missing. Please add sql soon. :)

**Comment by zerafox** [comment]
I'd be more concerned with why your My.Pets file was getting wiped in the
first place, rather than a replacement database added.
Double check for errors you have in your console on crashing, startup, and
in the MyPet.log.

What version is your server running and what version of MyPet are you on?

I've personally never had an issue with My.Pets getting wiped, even with a
crash.. So if it's happening for you, we need to know why.

**Comment by astr1al** [comment]
Here is a log which includes the last time a DB with pets was saved, then on a server load MyPet was unable to find the UUID for the players. Sorry for the absurdly long pastie http://pastebin.com/31NAbfDp

Running Spigot build 952179b-bc03b6f 1.8 R0.1 Snapshot (Fairly recent, but this problem existed in the 1.7 days)

Running the latest Dev version of MyPet for 1.8 v1.2.1

Thanks for maintaining this awesome plugin!

**Comment by zerafox** [comment]
This appears to be a UUID issue, have you switched your server from online to offline mode?
I'm not overly familiar with how it all works myself, but I would assume that by going from one to the other, MyPet stops checking for UUID's and/or starts checking, and when it can't find a match, deletes the data.
Having MySQL or SQL isn't going to resolve that sort of issue, as it's still saving the same data, and would still have trouble finding the needed data to load properly.

**Comment by Darkool** [comment]
Hello xXKeyleXx what about use MYSQL but using BLOB ?
check this please, thanks in advance.
http://www.mysqltutorial.org/php-mysql-blob/

**Comment by xXKeyleXx** [comment]
The how is not that big of a deal. The when is more the problem ;)

**Comment by xXKeyleXx** [comment]
see #582
