### ISSUE TITLE
Health Bar

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#315]
Perhaps a configuration to enable/disable a health bar underneath the pets name?

It gets kind of annoying or trouble some to check a pets health via command all the time. I know with my server showing both mobs and player's health, having the ability to see the MyPet's health just by looking at them would be nice.

I have configured to show the pet's level on their Name Tag and players adored it! It stopped the constant "what level is your pet?". I feel this addition would help players out too!

Some deeper thoughts on this:
The plugin I use for player health display has it configureable how it will appear above the players head.
*They've made it possible to display a heart system like on the game's UI that empties as health is lost.
*They provide a number option with either an HP or a Heart displayed next to it. (I like this one, keeps it simple)
*They do a color system of ||||||| where green | are healthy and red | are missing health

I bring this up to appear below the pet's name tag to avoid pet's name tag appearance from being far too long above their heads.

I am not sure if this is possible to add another bar above the pet's head or not, but some way to enable health regardless would wonderful!

**Comment by xXKeyleXx** [comment]
implemented in 9630f16b99693984130d7fed85b57cbf72df2d91
