### ISSUE TITLE
Support for conquestia mobs plugin?

### ISSUE THREAD

**Issue by moistgreentoast** [xXKeyleXx/MyPet#401]
I use the plugin conquestia mobs on my server and when I tried installing the latest dev build of MyPet for 1.8 it turned off the levels of the conquestia mobs (http://dev.bukkit.org/bukkit-plugins/conquestiamobs/)

**Comment by zerafox** [comment]
I have been recently doing some testing to update my own server to 1.8 in the past couple of days. I'm finding no issues what-so-ever with Conquestia and MyPet. Both using pets along-side the leveling mobs, as well as taming mobs that spawn in with Conquestia's levels, are working 100% on both my test server at home, and my live server.

However, Conquestia appears to be having it's own issues that I have pointed out to the Developer there. If you're having level spawning issues with Conquestia, double check with that plugin. It appears the 1.8 release has it's own problems that need fixing and it may not be MyPet at all.
