### ISSUE TITLE
Random skilltree assignment

### ISSUE THREAD

**Issue by Boosik** [xXKeyleXx/MyPet#403]
Hi,
i'd like some option to automatically assign random skilltree to pet. Something like AutomaticAssignment, but with random skilltree selection (not only first one).

**Comment by zerafox** [comment]
Something like this would be nice, for setting up some kind of randomization of taming. Tame Bunny A and get random tree 1.
With disabling the ability for players to change trees, you could have a system that would require players to keep trying to tame Bunnies until they got the setup they were looking for. Making each 'Bunny' different in terms of this randomization technique.

Personally, I like the idea!
I think the AutoAssignment should be configurable though, as in which trees could come up in the randomization, for those who may want the random stats, but still allow players to change to a different tree later on, expanding on those random stats in an "upgrade" fashion. (kind of like what I've done with my server. xD)
