### ISSUE TITLE
Changing speed of pets

### ISSUE THREAD

**Issue by Jakzor12** [xXKeyleXx/MyPet#405]
I see that this is an option in the config... But when I edit the value I notice that it's only really noticeable  when you increase it higher, I cannot seem to change it so that mobs are slower than actual human speed, even when the config looks like this: 

    Cow:
      CanGiveMilk: true
      GrowUpItem: 373
      HP: 15.0
      Speed: 0.05
      Food: '296'
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 45
      LeashItem: 420

The pet is still reasonably fast.

I have tried editing the skilltree for riding also, to lower the riding speed value. but this also is not making the animals slower! It is quite frustrating as i have been trying for about an hour now D:

Help would be very much appreciated :)

Edit: Iron golems look kind of ridiculous walking as fast as a sprinting ocelot

**Comment by xXKeyleXx** [comment]
I looked into it and noticed that I change the speed (that the plugin get from the config) in the lowest possible instance (the same used by map makers using NBT) so there is nothing I could do about it :/
