### ISSUE TITLE
Upgrade to UUIDs

### ISSUE THREAD

**Issue by FabioZumbi12** [xXKeyleXx/MyPet#410]
Hello!
I already use this plugin since 1.7 and with player names. The problem is i always have used in offline mode, and now, when i try to use in online mode, all pets are deleted.

Can have an option to choose if use player names or UUIDs? O only upgrade option to use player names, them use UUIDs after upgrade?

**Comment by xXKeyleXx** [comment]
it SHOULD work when the owner of the pet has a valid Minecraft account. Could you upload you My.Pets file so I can test what's going wrong.

**Comment by FabioZumbi12** [comment]
No, still deleting all pets with premium and not premium players. here my My.pets file: https://www.mediafire.com/?srne4h2trjjjxkp
