### ISSUE TITLE
Unable to ride Pets

### ISSUE THREAD

**Issue by maginka** [xXKeyleXx/MyPet#415]
Hi, Using latest version of Mypet, and most recent Build Of Spigot, players are unable to ride pets with the Ride skill tree.

No errors to report from the console to work with sadly.

**Comment by zerafox** [comment]
We cannot do anything with "the latest", please provide build numbers, and what actions you are taking in an attempt to ride the pets.
What item is set in the configuration for use with the Ride Skill as well?

**Comment by maginka** [comment]
Im using build #655 of mypet, and spigot for 1.8, version: git-Spigot-081dfa5-7658819.

The pets in question have the ride skilltree selected, and as always, we use the leash, by right clicking to ride the pet. 

All was working fine until a recent spigot update, i sadly cannot remember what build it stopped working on.

**Comment by ScuroK** [comment]
i have the same problem!

**Comment by ScuroK** [comment]
there was a worldguard update. could it be a worldguard bug?

**Comment by ScuroK** [comment]
did you find the bug?

**Comment by ScuroK** [comment]
Any solution? is it spigot or is it mypet?

**Comment by zerafox** [comment]
I am sure Keyle is working best he can to resolve this issue.
Please be patient, he will let us know when he's got a fix.

**Comment by ScuroK** [comment]
shore. i was just wondering if i could downgrade mypet to fix it. maybe i try

**Comment by ScuroK** [comment]
downgrading did not help :(

**Comment by anyperson** [comment]
Duplicate? 

Support GP 10.*.* and Factions 2.7.5

import com.massivecraft.factions.listeners.FactionsListenerMain;
import me.ryanhamshire.GriefPrevention.Configuration.WorldConfig;

Is to old. Pets kills everyone in claims. Please update support for plugins.

**Comment by ScuroK** [comment]
When will you have time to fix it?

**Comment by zerafox** [comment]
Keyle will have it fixed as soon as he is able, please be patient. ^.^

**Comment by ScuroK** [comment]
I asked because he wrote me that he wants to do it this week. im wondering if he has some troubles fixing it.

**Comment by ScuroK** [comment]
does anyone know what version of spigot whas the last compatible one?

**Comment by xXKeyleXx** [comment]
Sorry, I had less time than expected :/

**Comment by zerafox** [comment]
Oh Keyle, you've no reason to be sorry at all. After all you owe no one anything. :P You do fabulous work, and when you're able to get to the bugs and errors, I know you will. ^.^
In the meantime, people can either be patient or move on. You do the best that you can already.

**Comment by ScuroK** [comment]
schleimer ^^ nene er hat schon recht. :)
