### ISSUE TITLE
Requesting compatibility for SkillAPI & Magic Spells

### ISSUE THREAD

**Issue by Ruthuin** [xXKeyleXx/MyPet#419]
Hello,

Is it possible that you could add compatibility for these two RPG plugins?
Ensure SkillAPI experience applies to MyPets.  SkillAPI skills work perfectly already in terms of them not being damaged by owners or other players in non-PVP situations and being damaged appropriately while in PVP.
Link to SkillAPI:  http://dev.bukkit.org/bukkit-plugins/skillapi/

And ensure that Magic Spells created spells won't damage pets in non-PVP situations.  Currently, MagicSpells spells damage MyPets, even if they're cast by their owner.
Link to Magic Spells:  http://dev.bukkit.org/bukkit-plugins/magicspells/

**Comment by charlie1990** [comment]
I too would very much like to see this. Those are two of the most used plugins out there.
