### ISSUE TITLE
PvPChecker.java Support GP 10.* and Factions 2.7.5

### ISSUE THREAD

**Issue by anyperson** [xXKeyleXx/MyPet#421]
Support GP 10.. and Factions 2.7.5

import com.massivecraft.factions.listeners.FactionsListenerMain;
import me.ryanhamshire.GriefPrevention.Configuration.WorldConfig;

Is to old. Pets kills everyone in claims. Please update support for plugins.

**Comment by zerafox** [comment]
#420

**Comment by zerafox** [comment]
If there are any errorlogs when these PvP checks fail, please provide them in this ticket.

**Comment by anyperson** [comment]
No errors, but support don't working for these plugins, so everyone can kill via pet on spawn many-many newbies. I tried to recompile with new versions Factions and GP, but still have errors.

de/Keyle/MyPet/util/support/PvPChecker.java:[33,42] error: cannot find symbol
de/Keyle/MyPet/util/support/PvPChecker.java:[48,52] error: package me.ryanhamshire.GriefPrevention.Configuration does not exist
de/Keyle/MyPet/util/support/PvPChecker.java:[163,23] error: cannot find symbol
de/Keyle/MyPet/util/support/PvPChecker.java:[343,73] error: method getPlayerData in class DataStore cannot be applied to given types;
de/Keyle/MyPet/util/support/PvPChecker.java:[344,73] error: method getPlayerData in class DataStore cannot be applied to given types;
de/Keyle/MyPet/util/support/PvPChecker.java:[351,20] error: cannot find symbol
de/Keyle/MyPet/util/support/PvPChecker.java:[351,67] error: cannot find symbol

import com.massivecraft.factions.listeners.FactionsListenerMain;
import me.ryanhamshire.GriefPrevention.Configuration.WorldConfig;

old import's and errors

                EntityDamageByEntityEvent sub = new EntityDamageByEntityEvent(attacker, defender, EntityDamageEvent.DamageCause.CUSTOM, 0.);
                return FactionsListenerMain.get().canCombatDamageHappen(sub, false);

                PlayerData defenderData = pluginGriefPrevention.dataStore.getPlayerData(defender.getName());
                PlayerData attackerData = pluginGriefPrevention.dataStore.getPlayerData(attacker.getName());

                if (pluginGriefPrevention.getDescription().getVersion().equals("7.8")) {
                    WorldConfig worldConfig = pluginGriefPrevention.getWorldCfg(defender.getWorld());

**Comment by anyperson** [comment]
Factions 2.7.5 GP 10.5.3
