### ISSUE TITLE
MyPet ERROR Log

### ISSUE THREAD

**Issue by Faller10** [xXKeyleXx/MyPet#422]
Please help! I don't know why this happens to me all the time!!
http://pastebin.com/t50AzXzS

**Comment by zerafox** [comment]
More information is going to be needed I'm afraid.
There isn't a stack-trace, nor do I see what is going on here exactly other than apparently Spigot is having problem with MyPet.

Are there other error logs you can provide? The My.Pet log, or other error logs from your console?

**Comment by Faller10** [comment]
MyPet.log Is alright I think...Look:
MyPet.log: http://pastebin.com/e1cUChtV

But somehow, mypet keeps having troubles and crashing my server!

**Comment by zerafox** [comment]
Is there another error in your console you haven't shared? The crash log?
Every little bit helps us find out what's wrong.

**Comment by Faller10** [comment]
Full log of the crash!!!
It has other plugins involved, but i fixed them all... only MyPet that keeps giving me this crashes!

Full log: http://pastebin.com/7tM18QhY

**Comment by Faller10** [comment]
Anything?

**Comment by zerafox** [comment]
Please be patient, Keyle is very busy sometimes and will get to your ticket soon as he is available to. ^.^
I'm personally not so great with error-logs, though admittingly haven't given it too much of a look-over. Bukkit is my deal, Spigot not so much.. So you'll need Keyle to look over your errors and get back to you.

I am just a ticket manager, I can help with basic things, not so much an error in the plugin with server's just yet. :P Some day though!

**Comment by Faller10** [comment]
Ok thanks zerafox for the explanation!

**Comment by xXKeyleXx** [comment]
I was busy the last weeks but I should be able to start fixing bugs tomorrow :D

**Comment by Faller10** [comment]
Thanks!!! Just to make sure my server is on 1.7.X so the bug is in old versions of the plugin!! I was using 1.1.8 than i tried 1.1.9

**Comment by xXKeyleXx** [comment]
Do you know the player iSchiffer on your server? He set the exp of his pet to 1e+72 (a one folowed by 72 zeroes) and the calculation of the level of his pet takes so long that the server hung up xD
