### ISSUE TITLE
Pets can kill mobs in Towny towns

### ISSUE THREAD

**Issue by david1104** [xXKeyleXx/MyPet#424]
Hi, i'm using towny v0.89.2.0
when i try to attack a mob in a town obviously i can't because of towny protection, but still my pet can kill him(even when in aggressive mode),can you do something about that?

**Comment by zerafox** [comment]
If there is an error that comes up in console please paste it to pastebin and share the link.
It also doesn't hurt to include the My.Pet log file too.

Also, please share with us the version of MyPet and your server as well.
We can't do much without this information. ^.^

**Comment by david1104** [comment]
sorry forgot about that ^^
no error comes up when this happen, anyways i'm using
MyPet-1.8-1.2.1-SNAPSHOT.jar and Spigot 1.8-R0.1-SNAPSHOT
here's 
MyPet.log http://pastebin.com/q1757gnJ

**Comment by xXKeyleXx** [comment]
Is the towny hook enabled in the config?

**Comment by david1104** [comment]
of course, anyways i updated it to the latest build (661) and the problem persist

**Comment by xXKeyleXx** [comment]
Well it's works fine for me. I can't fix something I can't reproduce :/

**Comment by david1104** [comment]
maybe this can explain better (i'm inside a town)
https://www.dropbox.com/s/7pbou53augo4q01/mypet.gif?dl=0
here's my config as well, maybe i'm doing something wrong
http://pastebin.com/QY32wvDJ

**Comment by xXKeyleXx** [comment]
see #496
