### ISSUE TITLE
Need "1.7.5 spigot" compatibility

### ISSUE THREAD

**Issue by JavituRec** [xXKeyleXx/MyPet#429]
Hello, I need you to add compatibility with version 1.7.5 spigot. You do not have this version ?. I can provide at this link -> http://www.mediafire.com/download/znh9y6avusw8wq1/spigot-1387.jar
or if you prefer in this website you can download -> http://tcpr.ca/spigot
Please I need this support, I use this on my server version and not use "1.7.2 craftbukkit" because I need to find possible timings lag spikes plugins. I hope you can work on this. I would be very grateful.

**Comment by xXKeyleXx** [comment]
http://build.keyle.de/job/MyPet%20(Bukkit%201.7.5)/593/
