### ISSUE TITLE
More Pets / Factions

### ISSUE THREAD

**Issue by KudonLP** [xXKeyleXx/MyPet#431]
Dear dev team of the amazing MyPet plugin,
I think you might already have received some request of this kind, but I would love it for our server to have the possibility to own more than one pet in a world at a time.

Those should not stand around at the same time though, but should be swappable (maybe through a command like /petswitch <name>). This would allow players to try out several skill trees and also level up their pet in several skilltrees.

Furthermore it would be amazing if MyPet would support Factions integration, meaning: MyPets won't attack members of the same clan, which would support clan wars a lot.

Hoping that you consider my request...

gracefully, KudonLP

**Comment by zerafox** [comment]
Mypet is already capable of Faction support, you can find this in the configuration file.
If you install both Citizens and MyPetNPC you can also allow players to have multiple pets through this stable system as well.

**Comment by KudonLP** [comment]
Yes we Know the config.. Factions Support is true, but that makes no
Difference to False.
And I've got another question. How Does the config has to be, when normal
players want to change their Skilltree? ChooseOnce true or false?
Am 02.02.2015 02:26 schrieb "Foxtail" <notifications@github.com>:

**Comment by zerafox** [comment]
If having Factions support set to True, and players are still able to be hurt by pets, there may be something else in the config that is allowing it? Or that that part is currently bugged and broken? What version of MyPet are you using and your server's version/build?

As far as the Skilltree, I am not entirely sure. I have always personally made it so players had to go through an alternative setup to "purchase" changes, but I would think ChooseOnce would have to be false, to allow them to change their tree.
