### ISSUE TITLE
 [MyPet] Can't get UUID for "xxxx"! Pets may not be loaded for this player!

### ISSUE THREAD

**Issue by jiongjionger** [xXKeyleXx/MyPet#432]
When I set BugeeCord:false to true and ip_forward:false to true,MyPet cannot load the pets.
This problem may be caused by UUID.
I'm sorry for my poor English.

MyPet #644
Spigot 1.7.10
BugeeCord 1.8:"61d2765":1039
offine-mode

**Comment by jiongjionger** [comment]
I change the code,and it work fine.
public static boolean isInOnlineMode() {
       /* if (bungee == null) {
            try {
                bungee = SpigotConfig.bungee;
            } catch (NoClassDefFoundError ignored) {
                bungee = false;
            }
        }
        return bungee || Bukkit.getOnlineMode();
        */
    	return false;
    }

at de.Keyle.Mypet.util.BukkitUtil.java

**Comment by xXKeyleXx** [comment]
This may work for you but it not a solution! I will look into it.
