### ISSUE TITLE
Spigot porblem

### ISSUE THREAD

**Issue by MrXrayPvP** [xXKeyleXx/MyPet#435]
I have a porblem with mypet an spigot beta
here ist the log14.02 17:20:50 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
14.02 17:20:50 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
14.02 17:20:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.Packet
14.02 17:20:50 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
14.02 17:20:50 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot1-8.jar:git-Spigot-d0d1d87-bc03b6f]
14.02 17:20:50 [Server] INFO at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:138) ~[?:?]
14.02 17:20:50 [Server] INFO at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:175) ~[?:?]
14.02 17:20:50 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/Packet
14.02 17:20:50 [Server] ERROR Error occurred while enabling MyPet v1.2.0 (Is it up to date?)

**Comment by xXKeyleXx** [comment]
MyPet v1.2.0 is for Minecraft 1.7.9 and not for 1.8.1. Please use the devbuilds for 1.8!
