### ISSUE TITLE
My Pet Add-On Commands

### ISSUE THREAD

**Issue by PhillyCheezsteak** [xXKeyleXx/MyPet#436]
Hello, so I have a few commands that would help the plugin a lot.
My Pet Commands
/MyPet Heal (Health Amount) This would heal you current pet out that is not dead
/MyPet HealAll (Health Amount) Heal all pets you have that is not dead
/MyPet Revive (If a pet dies, this will reset the cooldown and calls the pet to you (like a revive))
/MyPet ReviveAll (Resets Cooldown for all of your pets (revives all pets))

My Pet NPC Commands
/MyPet Deposit (Pet Name) Deposits Pet
/MyPet Retrieve (Pet Name) Retrieves Pet
/MyPet DepositCurrent (Deposits current pet out)

*Each command will have its own permission node

These commands would be very helpful for servers and would be great to use with other plugins like citizens.

**Comment by zerafox** [comment]
There are already commands to respawn your pet, despite the cool-down. :P

**Comment by PhillyCheezsteak** [comment]
Oh neat. Thank you, I did not know that :)

**Comment by PhillyCheezsteak** [comment]
Thank you , I did not know that :) Sorry I closed the thread and I reopened it by mistake xD

**Comment by zerafox** [comment]
Come to think of it, the other commands however would be a great addition for multiple other functions servers can add.
I can a think of a few for my own server later down the line. :P
