### ISSUE TITLE
How to join in wiki korean translation?

### ISSUE THREAD

**Issue by hjhj3686** [xXKeyleXx/MyPet#438]
http://mypet.keyle.de/doku.php?id=ko:start

this korean translate almost google translated.

i can modify this wiki in korean translate.

**Comment by xXKeyleXx** [comment]
I need am email address and a username so I can create an account for you.

**Comment by hjhj3686** [comment]
nettermhell@gmail.com / rokodorokodo

**Comment by xXKeyleXx** [comment]
I created the account for you. You should have received an email containing the password.

**Comment by hjhj3686** [comment]
i get my password. thx
