### ISSUE TITLE
Spigot 1.8.3 incompatability

### ISSUE THREAD

**Issue by frizzbee30** [xXKeyleXx/MyPet#440]
Hi, just to let you know that the new Spigot 1.8.3 release appears to prevent mypet from loading. Thanks

**Comment by fatdog66** [comment]
yes i comfirm !

**Comment by justin393** [comment]
Confirmed. It seems that all plugins using NMS code broke with the upgrade to 1.8.3
Should be an easy enough fix, just recompile with Spigot API 1.8.3 and change a few class names. I'll look into doing that here in a minute.

**Comment by Sketaful** [comment]
This is why people should always check the issue-list before writing a ticket. This is exactly what I wanted to say as well, luckily I read these tickets so no I just leave this here ;)

**Comment by xXKeyleXx** [comment]
please try the latest build

**Comment by frizzbee30** [comment]
Hi, that seems to work great!  Thanks   :)

**Comment by RFSMassacre** [comment]
I have the same issue with MyPet failing to load on Spigot 1.8.3. I used the latest dev build for MyPet but it still does not want to run.

**Comment by xXKeyleXx** [comment]
@RFSMassacre Are there any errors in the server log?

**Comment by RFSMassacre** [comment]
@xXKeyleXx There is no error that comes up. It just doesn't respond one bit.

**Comment by xXKeyleXx** [comment]
You don't use the latest Spigot build or the wrong Mypet build for your Spigot version.
