### ISSUE TITLE
MyPet DeathMessages

### ISSUE THREAD

**Issue by PabloM98** [xXKeyleXx/MyPet#445]
The latest buids of the plugin MyPet uses the mobs (pets) like player entities, this break the deathmessages of some plugins like DeathMessages (http://dev.bukkit.org/bukkit-plugins/death-messages). Please fix this, thanks.

Build of the plugin tested: #669
Server: Spigot 1.8 latest build

**Comment by xXKeyleXx** [comment]
I did not changed anything so this is not my problem. They need to fix that.
