### ISSUE TITLE
My Pet Health Bar (plugin config option)

### ISSUE THREAD

**Issue by PhillyCheezsteak** [xXKeyleXx/MyPet#446]
Here is my idea. In the MyPet config file, there can be a config option to display your MyPet's health bar. If the config option is set to true and if a player has a MyPet out, a Boss Health Bar will appear (like a Wither Health Bar) with the pet's name. To prevent any bugs, this would turn off all other boss health bars (wither, ender dragon, etc) except for the owner's MyPet. For example if I have a MyPet Pig out and if someone next to me has a MyPet Wither out, I will only be able to see the boss health bar of my MyPet Pig. This way it will not effect the pet's name, and this would be a solution for players to be able to see their MyPet's health and be a solution to the 1.8 changes.

Note: The MyPet health bar will constantly show as long as the MyPet is out and active. If the MyPet dies, sent away, etc, the health bar will go away.

**Comment by xXKeyleXx** [comment]
I like the idea but as long as you need to spawn a dragon to accomplish that I will not do it this way :/

**Comment by zerafox** [comment]
Personally, I think a second or additional display on the MyPet's name tag would be better.
Whether it is display in numbers, IE: 20/20 or in hearts :heart::heart::heart:
Similar to what McMMO does for mobs.

**Comment by PhillyCheezsteak** [comment]
@xXKeyleXx  @zerafox   Well there is a second idea that I have. There is a plugin called Action Bar Health http://www.spigotmc.org/resources/action-bar-health.2661/
It displays a mob's health above the player's exp bar. What you can do is "mimic" that plugin but only have it show the MyPet's health that is currently out.

**Comment by xXKeyleXx** [comment]
@PhillyCheezsteak This is something I could do ;) The only drawback (or maybe feature) is that the health bar will disappear after a few seconds because of the nature of chat messages. But it will show every time the health is updated.

**Comment by xXKeyleXx** [comment]
I would look like this and fades after about 2 seconds
![2015-03-15_11 32 57](https://cloud.githubusercontent.com/assets/631504/6655658/38a0fe10-cb07-11e4-8f34-a03f7fa9a4f1.png)

**Comment by PhillyCheezsteak** [comment]
Would there be a way for the health bar to stay up without fading away? Because I know that is an issue now with 1.8. That looks awesome by the way :)

**Comment by zerafox** [comment]
Is this always active? I can foresee an issue with other plugins that use this space to display things as well is why I ask.

I don't see an option to disable it in config and I cannot see anywhere that there is a command or anything else to toggle it's function on/off.

**Comment by xXKeyleXx** [comment]
there are 2 modi:
1.: always show the "healthbar"
2.: show it for ~2sec when the health changes

You can toggle between them with this command:
/petoption healthbar
