### ISSUE TITLE
Not generating config files.

### ISSUE THREAD

**Issue by thelime** [xXKeyleXx/MyPet#448]
Before I explain, I am very inexperienced in this kind of thing, this is literally my first post on github as I couldn't find anywhere else to get help.

So here's my issue. I use the 1.8 dev-builds from Jenkins, and when I start my server with the .jar in my plugins folder, it generates the config folders like locale and skilltrees, but nothing in them, no config or anything. I don't know what I'm doing wrong. Any idea? The commands also show up in game with /help, but don't show anything when I use them.

**Comment by zerafox** [comment]
What server version are you running, and which 1.8 dev build?

**Comment by thelime** [comment]
I'm on 1.8 Spigot, (not sure which exact build) and as for dev build I tried #676, and one other.
Here's some console errors I found: (I'm not sure if it's all of them, but I tried to get most of it)

18.03 00:46:29 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.Packet
18.03 00:46:29 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_51]
18.03 00:46:29 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-952179b-2f50138]
18.03 00:46:29 [Server] INFO at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:142) ~[?:?]
18.03 00:46:29 [Server] INFO at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:174) ~[?:?]
18.03 00:46:29 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/Packet
18.03 00:46:29 [Server] ERROR Error occurred while enabling MyPet v1.2.1 (Is it up to date?)
18.03 00:46:29 [Server] INFO Enabling MyPet v1.2.1

**Comment by zerafox** [comment]
From what I can see here, it appears you're running a version of MyPet too high for your Spigot?
676 is for a 1.8.3 server, and it appears you may be running a 1.8.2? or 1.8.1?
I'm not overly great at reading these to be honest, but that's my guess. I would suggest downgrading MyPet to a dev build 669 or lower and see if it loads up then. From this log, MyPet isn't finding the files it needs from Spigot.

So give that a try and let us know how it goes.

**Comment by thelime** [comment]
Okay I will try that! Thank you for the advice :) I'm using an auto spigot installer provided by my host, so that could very well be it.

**Comment by thelime** [comment]
It worked! Thank you so much! I could not figure it out for the life of me. Thanks again! :D

**Comment by zerafox** [comment]
Glad I could help you getting MyPet functioning for your server. ^.^ Enjoy. If you have any other questions, feel free to open another ticket.
