### ISSUE TITLE
Mythic Mob Compatibility

### ISSUE THREAD

**Issue by PhillyCheezsteak** [xXKeyleXx/MyPet#449]
Since the latest update of MyPet, Mythic Mobs can no longer attack My Pets. I was wondering if you can please re-add the compatibility for Mythic Mobs to attack My Pets?

**Comment by xXKeyleXx** [comment]
I would say it's more the other way around. I didn't changed anything. What mob types don't attack MyPets?

**Comment by PhillyCheezsteak** [comment]
Any Mythic Mob does not attack My Pets now. I am not sure if it is because of the new health bar update, but all updates before that worked. I have had the same config and it has worked for the previous versions.

Mythic Mob Config
http://pastebin.com/da0dW6xd

I basically forced the AI to attack My Pets when they attack. Now it does not work sadly.

**Comment by xXKeyleXx** [comment]
It's very unlikely that the health bar update caused this. Mythic Mobs has an updater, maybe the plugin updated and that caused it. Did you contacted the Mythic Mob dev too?

**Comment by PhillyCheezsteak** [comment]
So I've sent a message to the main dev of MythicMobs about this issue and I created a ticket about it, so I am going to wait and see on the response.

I have tried downgrading MythicMobs and MyPet to previous versions to see if it works and I have had no luck so far. When I get a reply from the main dev of MythicMobs, I will update this Ticket.
