### ISSUE TITLE
Mypet kicking people

### ISSUE THREAD

**Issue by thepotatoarmyhd** [xXKeyleXx/MyPet#451]
Hi,

If someone gets a baby mushroom cow it seems to kick everyone in the area with this error 
http://gyazo.com/9e273c5ef910a688e632b5788faea0a3

Can you make a quick fix in a build where this baby mushroom cant be a pet

**Comment by zerafox** [comment]
How about telling us the version of your server, the version of MyPet your using, and any console error logs instead?

A "Quick Fix" to prevent taming of a baby mooshroom is just silly, so why not provide the information we need to see what's going on so that it can be fixed, instead.

**Comment by thepotatoarmyhd** [comment]
Here are your errors....
http://gyazo.com/408b01c21efbf54c0b6ee99b0667bcde

And here is the build im running
http://gyazo.com/d4c5c9ed0eb53b0a6c9198ddff0df4fe

**Comment by xXKeyleXx** [comment]
You are using 1.8 which is not supported by MyPet anymore. Update to 1.8.3 and everything will work fine.

**Comment by thepotatoarmyhd** [comment]
I Can't update to 1.8.3 because a lot of my plugin break :/  What dev build can i use for 1.8?

**Comment by xXKeyleXx** [comment]
You are lucky, I fixed it before the 1.8.3 update:

http://build.keyle.de/job/MyPet/669
