### ISSUE TITLE
Additional Horse Patterns?

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#452]
So I was doing some experimenting with the petadmin commands to spawn different varieties of the pets available.

I discovered that only so many horses are available this way, and it may be true for other mobs as well.
Here is the list of the horse patterns i was able to come up with using the petadmin command.

Horse:
  Variant:
   1: L.Brown
   2: L.Brown w/Saddle Patch
   3: Brown w/Black Mane
   4: Black
   5: Grey
   6: Brown
   7: White
  Horse:
   1: Donkey
   2: Mule
   3: Undead
   3: Skeleton

Now, I spawned a wild horse in with a spawn-egg and got a Brown Horse with White Spots. I was unable to find a way to get this variant with the petadmin command.
Is there an additional step I am missing to get these other variants? Anything over 7 seems to just keep giving me white horses, and adding a 0.# or a 0-# again only gives me white horses. Combing both Variant with Horse, over-rides the Variant variable altogether and gives me a different horse.

Am I doing something wrong, or are those the only variants of horse petadmin can give?

**Comment by xXKeyleXx** [comment]
http://minecraft.gamepedia.com/Horse?cookieSetup=true#Data_values
