### ISSUE TITLE
Some mobs disappear when looking slightly above them

### ISSUE THREAD

**Issue by Favorlock** [xXKeyleXx/MyPet#456]
I was testing out some mobs and noticed that when look just above the head of the Wither and Enderman they would disappear as if they had turned invisible. I'm not sure if this is a 1.8.3 bug or just simply something with MyPet in particular, but this is the first time I've ever noticed the issue.

**Comment by xXKeyleXx** [comment]
It's a Minecraft thing ;) the game thinks it is outside of your view and stops rendering it. It's the reason Minecraft can run so """"""""smoothly""""""".
