### ISSUE TITLE
EnderDragon

### ISSUE THREAD

**Issue by Favorlock** [xXKeyleXx/MyPet#457]
Are there any plans to add support for the EnderDragon?

**Comment by zerafox** [comment]
The Enderdragon has been attempted to be added multiple times before, the problem with the enderdragon, is by default he flies backwards.
The issue at hand, is getting him to turn around front-ways in MyPet.

**Comment by Favorlock** [comment]
I haven't noticed the Ender Dragon facing the wrong direction in my fork, although I've yet to find a way to make it fly in a sufficient manner. Additionally the Ender Dragon may be a bit too big to spawn in most places.

**Comment by zerafox** [comment]
I think that is a main reason most servers don't use the larger mobs for pets, like the ghast and giant.

**Comment by xXKeyleXx** [comment]
As zerafox already said, the last time I checked the enderdragon it faced backwards when I applied the normal AI to them. When it works in your fork open a pull request and I will add it to the main branch.

**Comment by CraftZera** [comment]
Olá !! eu coloquei o Mypet em meu servidor porém não consigo usar o enderDragon como pet !! alguém pode me ajudar ?

**Comment by zerafox** [comment]
> Hello !! I put Mypet on my server but I can not use enderDragon as a pet !! Can someone help me ?

https://wiki.mypet-plugin.de/misc/faq
