### ISSUE TITLE
Cant create Mypet, Is this player online

### ISSUE THREAD

**Issue by maginka** [xXKeyleXx/MyPet#458]
Just tried the latest dev build, and as per the title, Players are unable to access pets. 

As admin, i get the above message when trying to use /petadmin create <player> <mob>

Server is running on bungeecord, as of todays build tools version.

**Comment by maginka** [comment]
Ahh, Just noted you removed bungee support for now.

Any news when they may be readded ?

**Comment by xXKeyleXx** [comment]
My problem is that everything works fine in my small test environment but I heard from some of my users that it doesn't work for them. I would love to add it back but I have no real environment to test my changes on so I can't fix it :/

**Comment by maginka** [comment]
well, thats a pity, I am on bungee, and was working well for me, prior to you removing the support. I, and my players would love to see it back, but i understand your issue, and, well, thanks for the work you have done on it sofar. I will check back to see if by chance you were able to get it working with bungee again. If i can be any help, let me know, i can put any builds on a small server connected to bungee, and help you test if that is a viable option for you.

Either way, thanks for providing this great resource in the first place, its been a huge asset and enjoyed by all my players.

**Comment by NoHoPeLess** [comment]
Yes ... its very sad we use it for a soo long time but now we cant use it anymore...all players ask all 30sec about mypet and i can do nothing...
