### ISSUE TITLE
MyPet 1.2.1 does not work in Cauldron 1.7.10

### ISSUE THREAD

**Issue by VipMasterPrimo** [xXKeyleXx/MyPet#460]
I use a Cauldron 1.7.10 (Cauldron-MCPC-Plus version git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)). MyPet is the best plugin for create pet's system on the server. I start plugin with default settings and types of pets. Plugin does not work with cauldron. The matter is that several commands do not work. When I use /pc or /psa I give message in red: "An Internal error occurred while attempting to preform this command". Could you make version of MyPet for Cauldron 1.7.10? Thanks you!
This is log of error: http://pastebin.com/Ph6x2Yka
This is MyPet log: http://pastebin.com/NcknpnVf

**Comment by xXKeyleXx** [comment]
Sorry but it's not planned to make it compatible with Cauldron.
