### ISSUE TITLE
Item attached damage?

### ISSUE THREAD

**Issue by Tan90is** [xXKeyleXx/MyPet#462]
for example, if a pigman has a diamond sword, it deals 8.0 damage. You get the idea. Can you add this.

**Comment by zerafox** [comment]
But equipment doesn't effect the pet's damage or defense in anyway, why would you want the items to take damage on the pet if they aren't actually being used?

**Comment by xXKeyleXx** [comment]
Equipment affects just the visual appearance of the pets. I will not change that.
