### ISSUE TITLE
Plugin not responding

### ISSUE THREAD

**Issue by Ponderavita** [xXKeyleXx/MyPet#464]
So someone told me this was a good plug in to use. But when i installed it on the LATEST spigot 1.8.3 build its not letting me capture a pet! I hasnt generated a log. i get nothing in the console. I mean its interesting i hit the subject with item 420 and it just vanishes that it... am i doing it wrong ?

( ive tested version 1.2.1 and 1.2.2)

**Comment by zerafox** [comment]
Please post your Server Startup with the MyPet startup log.

Have you tried using /petcall to summon your pet? Pets don't "just disappear" when tamed, but they do "poof" with a message "will make a good MyPet"

**Comment by Ponderavita** [comment]
There are no Logs from your plugin and The Startup log just says  it was 
enabled.  The commands work they just say i have no pet. I take a leash 
and smack a pig with it about 10 times and it vanishes. no message or 
nothing.  Now i do have what looks to be pet data in one of the plugins 
files.

Could i be missing some required dependency ? Or could the Latest spigot 
1.8.3 be the problem ?

**Comment by zerafox** [comment]
We don't know if there is a problem with compatibility without some kind of log.
Without a startup log or any kind of error messages we cannot help you.

Nothing happens when you type /petcall? Do you get ANY message at all when you try to use this command?

When the Pig "vanishes" is it as if it Died normally, or does it literally just "poof" out of existence?

Sometimes, a plugin will say that it is enabled, but will later state that there is some kind of error, despite that the plugin enabled.

**Comment by TemplarKnite** [comment]
Question for the OP. Are you on a bungee network? If so I'm pretty sure that is the issue. I'm experiencing the same events, but when testing on my test server running by itself I have no issues.

**Comment by zerafox** [comment]
IF this is a Bungee related issue, Bungee support has been removed temporarily.
So running MyPet on a Bungeecord server is going to experience some issues due to the current lack of compatibility with the function.

**Comment by TemplarKnite** [comment]
zerafox:  I understand that bungee support has been removed, but was that removed from maven or the actual library that was imported. 
My question, is there a version that still currently works with a bungee setup. I hope that made sense, to me it does, but I somethings have an odd way of describing my thought process.

**Comment by xXKeyleXx** [comment]
http://build.keyle.de/job/MyPet/687/
