### ISSUE TITLE
Pets loosing inventory

### ISSUE THREAD

**Issue by fennectech** [xXKeyleXx/MyPet#466]
every so often pets seem to loose there inventoy 
https://www.dropbox.com/s/0z38jkz4t8koufk/ticket.zip?dl=0
heres my ticket.zip :) chears

**Comment by fennectech** [comment]
also im wondering if i can restrict features to certain worlds

**Comment by zerafox** [comment]
Please post error logs to Pastebin, we cannot download a file from every ticket created. We'd simply have no room on our PCs and I can't say I personally want to run the risk of downloading a virus...

As far as restricting features to certain worlds, if you have different Permissions set for different worlds, you can restrict anything you'd like in this manner. If you don't want players riding their pets in World B but they can in A, just turn on extended permissions in config, and give the node only to A World's permissions files.

**Comment by xXKeyleXx** [comment]
@zerafox the ticket.zip is a file created by a command (/petadmin ticket) I added a while ago ;)

@fennectech Are there any pet types who tend to do this more often than others?

**Comment by fennectech** [comment]
i havent noticed it with anything other than wolves   allmost everyone on
my world has wolves as pets xD

On Fri, Apr 24, 2015 at 9:07 AM, Sebastian Comans <notifications@github.com>
wrote:

> @zerafox <https://github.com/zerafox> the ticket.zip is a file created by
> a command (/petadmin ticket) I added a while ago ;)
>
> @fennectech <https://github.com/fennectech> Are there any pet types who
> tend to do this more often than others?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/xXKeyleXx/MyPet/issues/466#issuecomment-95944146>.
>



-- 
Fennec

**Comment by fennectech** [comment]
ive got an external plugin to prevent commands from plugins from working on
different worlds    but it doesnt stop the petpickup    i will investigate
it in the extended permissions :)

On Fri, Apr 24, 2015 at 4:08 PM, Fennec Fox <fennectech@gmail.com> wrote:

> i havent noticed it with anything other than wolves   allmost everyone on
> my world has wolves as pets xD
>
> On Fri, Apr 24, 2015 at 9:07 AM, Sebastian Comans <
> notifications@github.com> wrote:
>
>> @zerafox <https://github.com/zerafox> the ticket.zip is a file created
>> by a command (/petadmin ticket) I added a while ago ;)
>>
>> @fennectech <https://github.com/fennectech> Are there any pet types who
>> tend to do this more often than others?
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xXKeyleXx/MyPet/issues/466#issuecomment-95944146>.
>>
>
>
>
> --
> Fennec
>



-- 
Fennec
