### ISSUE TITLE
Do not load pets anymore?

### ISSUE THREAD

**Issue by Bonkozorus** [xXKeyleXx/MyPet#467]
I recently switched to 1.8.3, i updated MyPet and i do not touched anything from there, since that, everyone do not longer have any pet, but it looks like it loads pets as long as logs tell me that "there's 243 pet loaded".

Thanks for your help.

**Comment by zerafox** [comment]
Are you running a Bungeecord Server, or anything of that kind?
What type of server are you running, Spigot, Craftbukkit, etc?
And any logs you can provide?

**Comment by Bonkozorus** [comment]
I'm running BungeeCord server
Spigot 1.8.3

My logs are regular startup mypet logs.

**Comment by zerafox** [comment]
BungeeCord support has been temporarily been removed, this may be your issue.

**Comment by Bonkozorus** [comment]
Could you add it again please? :(

**Comment by zerafox** [comment]
I am sure Keyle will readd Bungee support when he is able, but for the time being, there is no support for the Bungeecord functions I'm afraid.

**Comment by Bonkozorus** [comment]
But i don't want any bungeecord function, i just want to have MyPet on my server. :/

**Comment by zerafox** [comment]
So remove BungeeCord from your server?
At this point in time, that is your option... Until Keyle is able to restore BungeeCord support to MyPet, it is either BungeeCord or MyPet on your server.

**Comment by Bonkozorus** [comment]
My server is linked to a bungeecord instance, but, i mean it has nothing to do with MyPet normally

**Comment by zerafox** [comment]
I am assuming something with BungeeCord is interfering with MyPet. But without some sort of errorlog or something else during the instances that MyPet isn't functioning, can't exactly tell you what your problem is...

I can however suggest that you /remove/ your server from any sort of BungeeCord at all, and see if that resolves your issue. Outside of that, I'm afraid I can't offer you anymore help.
So it stands to reason, that again your option are either your server functions with BungeeCord or with MyPet, until support for it can be restored.

**Comment by Bonkozorus** [comment]
http://pastebin.com/bzkTEJux

Here's my logs

**Comment by zerafox** [comment]
This is just the MyPet log, displaying pets loading and unloading. I'm unable to see what is going on with the server itself and all the other plugins that may be interfering with it.

Have you at any point switched your server from online to offline mode?
I'd need your server's console logs, when a player attempts to Call or Use a pet in any way. The startup log for your server and any errors/notices in Server's Console when using those commands.

**Comment by NoHoPeLess** [comment]
I can confirmed that, we have the same issue, yes we use bungecord as well.

Please help?

**Comment by NoHoPeLess** [comment]
Ok same as https://github.com/xXKeyleXx/MyPet/issues/458 i think the deleted bungee support comes never back... sad 
So for over 3 years a good plugin and now its death for 1.8.3+ bungee owners :(

**Comment by xXKeyleXx** [comment]
@NoHoPeLess It will come back ;) But I need to figure out how to make it work with Bungee first xD

**Comment by NoHoPeLess** [comment]
Ok puuhhhh... i was thinking it comes never back... huurraayy
Yes i dont know how to help you? We usr BungeeCord as well but we have no errors or something from mypet...
The only thing its confusing me is that i can not use /petadmin command ... maybe it helps?

**Comment by xXKeyleXx** [comment]
Could you provide me your configuration (Spigot/Bungee/IP Forwarding, e.g.)?

**Comment by NoHoPeLess** [comment]
yes just wait a moment

**Comment by NoHoPeLess** [comment]
Server:
Spigot Config: http://pastebin.com/j5qWq2ug
Bukkit config: http://pastebin.com/2cLq92eC
Server Config: http://pastebin.com/sYs54V8R

BungeeCord:
BungeeCord Config: http://pastebin.com/Jda8hBBF

**Comment by xXKeyleXx** [comment]
Would you mind to test this?: https://dl.dropboxusercontent.com/u/23957620/crap/MyPet-1.2.2-SNAPSHOT.jar

**Comment by NoHoPeLess** [comment]
Sry atm im not at home... Tomorrow i will test it instant and thanks for all at this point

**Comment by Bonkozorus** [comment]
I'm trying this right now.

**Comment by NoHoPeLess** [comment]
Thanks man :)

**Comment by xXKeyleXx** [comment]
You may need this to set it up propperly: http://mypet.keyle.de/doku.php?id=en:configfile#bungeecord

**Comment by NoHoPeLess** [comment]
Some infos about the test? I can test it in 3 hours then im at home :)

**Comment by xXKeyleXx** [comment]
Just start it up and test if players have their pets (according to the configs you posted here you don't need to change anything)

**Comment by Bonkozorus** [comment]
xXKeyleXx: They don't. And i can't catch some too. :/

**Comment by NoHoPeLess** [comment]
Not working...

i try it with:

  Hooks:
    BungeeCord:
      UUID-Mode: online

and:

  Hooks:
    BungeeCord:
      UUID-Mode: offline

I see some strange things here :D at the 1.7.10 : http://pastebin.com/GgCLkrgH

@ 1.8.3 this: http://pastebin.com/sMZcht2A

And i cant do /petadmin

**Comment by xXKeyleXx** [comment]
@NoHoPeLess 1.7.10 shouldn't work at all with the build I sent you

Damn.... I forgot to init the bungee support >.<
please try it again: https://dl.dropboxusercontent.com/u/23957620/crap/MyPet-1.2.2-SNAPSHOT.jar

**Comment by maginka** [comment]
Wooot, that last version lets you get pets again,

Running it on a test server. Just seeing some odd messages in chat, like  Message.Skilltree.selectionprompt, Message.Leash.Add, Message.spawn.Despawn, and others,

Will continue to test :)

**Comment by xXKeyleXx** [comment]
It's because my test build has no translations included. you can fix that by extracting them from a normal build and put then into a folder called locale

**Comment by NoHoPeLess** [comment]
Thanks @ xXKeyleXx it works now :D but the command /petadmin does not work...?

**Comment by xXKeyleXx** [comment]
http://build.keyle.de/job/MyPet/687/

@NoHoPeLess Please make sure you have the correct permissions (MyPet.admin). What option did you try to use?

**Comment by NoHoPeLess** [comment]
I am the Owner/OP ( '*' ) (PEX) :D i try to test /petadmin
Other commands still work but only the /petadmin command does not work.

**Comment by xXKeyleXx** [comment]
You have to use it like this: /petadmin <subcommand> <parameters>
http://mypet.keyle.de/doku.php?id=en:commands

**Comment by NoHoPeLess** [comment]
Oh i see i try for example: /petadmin exp NoHoPeLess 100
and it works lol im silly i was thinking /petadmin = output /commands examples etc.

LOL ok sry for that my mistake
