### ISSUE TITLE
Bevahior Duel

### ISSUE THREAD

**Issue by xion87** [xXKeyleXx/MyPet#468]
This behavior never worked for me i got factions server with 1.8.3... 
both player with pet in duel mode and pvp arena... pet do nothing

**Comment by zerafox** [comment]
Double check your configuration that pvp arena is enabled.
Also are the pets within 5 blocks of one another? If the pets are farther apart than this, they don't "see eachother" and duel.

**Comment by xion87** [comment]
yeah pets are close close, worldguard region got pvp allow flag, pets do nothing....

**Comment by zerafox** [comment]
What type of server are you running (CraftBukkit/Spigot/etc;), are there any error logs or messages, and do both pets have a damage skill?

Things pets need to be able to duel:
* Damage Skill
* PvP enabled space
* Duel Behavior Enabled
* Within 5 Blocks of another pet with Duel active

**Comment by xion87** [comment]
Working fine now, i just missed skill damage (i used ranged damage) and now work perfect! thank you!
