### ISSUE TITLE
[GriefPrevention] Mypets can attack protected pets

### ISSUE THREAD

**Issue by Feeriix** [xXKeyleXx/MyPet#469]
Players can attack and capture GriefPrevention protected mobs. 
Using Spigot 1.8.3 and GriefPrevention v11.5.
Pet behavior is on normal.

Can you please look into this? Thanks!

**Comment by xXKeyleXx** [comment]
could you please execute the "/petadmin ticket" command and upload the plugins/MyPet/ticket.zip for me?

**Comment by Feeriix** [comment]
https://dl.dropboxusercontent.com/u/22474190/ticket.zip

**Comment by xXKeyleXx** [comment]
What are you pets protected by (pvp immune / claim)? 
Has the attacker the __griefprevention.nopvpimmunity__ permission?

**Comment by Feeriix** [comment]
The pet is protected by Griefprevention's own pet protection system, which also protects pets outside of claims (if it was claimed before).

The attacker does not have that permission.
