### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by hmmcrunchy** [xXKeyleXx/MyPet#471]
HI There 

im using the 1.7.10 version on the spigot 1.8 hack (carbon) when pets appear near players or a player calls a pet to them their minecraft clients all crash. 

have you heard of this one before at all?

**Comment by xXKeyleXx** [comment]
Yes I do but I can't fix it. Both Minecraft versions expect something different so you I can support either 1.7.10 clients or 1.8 clients.

**Comment by hmmcrunchy** [comment]
No worries, thanks for reply ill try and get the server up to 1.8 only 

thanks for awesome plugin by the way :)
