### ISSUE TITLE
Plugin not working on Spigot

### ISSUE THREAD

**Issue by julikihd** [xXKeyleXx/MyPet#473]
Hi sir,

I tried to install your plugin in a Spigot 1.7.x and 1.8.x (API version 1.7.10-R0.1-snapshot) but the plugin and commands are not working (folder is created) No other plugins running. I tried all versions from the bukkit page (1.2.1 to 1.1.7) and no one worked

http://pastebin.com/syeYGqe8
Any help or suggestion?
Thank you so much for your time

**Comment by zerafox** [comment]
MyPet 1.1.7 for 1.7.2 Jan 17, 2014
1.1.7 is for CraftBukkit 1.7.2. It will not work on on a 1.7.10 server like your report says you tried. ;P

You need version 1.2.0 or so to run MyPet on a 1.7.10 server, or 1.2.1 to run on a 1.8 server.

If you are having issues running the correct version of MyPet for your server, we need the error logs for those.
However the report you've given is a mismatched version type.

If you are attempting to run the Protocol Hack version of Spigot, MyPet will not run on the Hacked Server at all. Either upgrade your server to 1.8 completely or run a version that isn't cracked.
