### ISSUE TITLE
Error loading my pet

### ISSUE THREAD

**Issue by WasdCat** [xXKeyleXx/MyPet#474]
Hello, I've got a problem with the last version of "mypet" when the plugin load write it in the console:

17:57:48 [INFO] [MyPet] Enabling MyPet v1.2.2
17:57:48 [ERROR] Error occurred while enabling MyPet v1.2.2 (Is it up to date?)
17:57:48 java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/Packet
17:57:48 at de.Keyle.MyPet.util.Configuration.setDefault(Configuration.java:180) ~[?:?]
17:57:48 at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:143) ~[?:?]
17:57:48 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
17:57:48 Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.Packet
17:57:48 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-13716d9-0899683]
17:57:48 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_05]
17:57:48 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_05]
17:57:48 ... 13 more

And no create a MyPet.log. Thanks and sorry my english

**Comment by zerafox** [comment]
"latest" isn't a version... An actual version number is what we need when telling us what version of things you have.

What is your server version?
What kind of server do you have?

**Comment by xXKeyleXx** [comment]
Use a 1.8.3 build of Spigot/Craftbukkit.
