### ISSUE TITLE
Wolfs chasing skellet

### ISSUE THREAD

**Issue by Rocologo** [xXKeyleXx/MyPet#476]
Everytime I enter MobArena the wolfes start to chase the skellet instead of chasing players?

I have tried to disable PetsInArena, but it does not seem to work?
    MobArena:
      PvP: true
      DisablePetsInArena: true

**Comment by xXKeyleXx** [comment]
This doesn't has anything to do with MobArena. Pets will not attack a player as long as the owner gets no damage from other players.

**Comment by Rocologo** [comment]
Hi Keyle. I just realized this standard Minecraft 1.8, so now it more like a problem in MobArena...
