### ISSUE TITLE
Mi Mypet Doesn't Work

### ISSUE THREAD

**Issue by dimasaurio** [xXKeyleXx/MyPet#478]
CraftBukkit version git-Bukkit-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Mi plugins are:
AntiCheatPlus
AuthMe-3.5-SNAPSHOT
BlockCommand
BuyRegion
BlockHunt_v0.2.0_BETA_B5
ChestShop
CrackShot
CreateYourOwnMenus-0.5.9
Essentials-2.x-SNAPSHOT
EssentialsChat-2.x-SNAPSHOT
EssentialsSpawn-2.x-SNAPSHOT
FirstJoinPlus
Itemizer
LibsDisguises
MyPet-1.2.1
OtherDrops
PermissionsEx
ProtocolLib
RandomBox
rpgitems
Shopkeepers
SiegeLadders-0.5
Simple-Autosave
Tim
UserPrefix
uSkyblock
Vault
worldedit-bukkit-6.0
worldguard-6.0.0-beta-05

Descripcion: When I start the server there's no error, but when I type /mypet I do nothing, and when I try to capture a pet it do nothing too, help me please. Sorry for mi bad english im spanish.

**Comment by xXKeyleXx** [comment]
1. there is no /mypet command
2. http://mypet.keyle.de/doku.php?id=en:permissions
