### ISSUE TITLE
MyPET NPC Trait problem & I want to know the perms for MyPet

### ISSUE THREAD

**Issue by KevinHendrews** [xXKeyleXx/MyPet#479]
Hey guys, When I installed mypet, newly, I didnt saw any perms, I came to default group and I couldn't take pet on leash but when I gave myself op and tried then I was able to, Please tell me the permissions and my second problem.

I also have MyPET NPC 0.04 and Citizens, I installed citizens etc and when I created npc and I was setting its trait using /trait add or /trait set when I typed /trait add mypet.storage and mypet and mypetnpc it didnt work, Trait not found, I tried these all I listed.
Plz help fast

**Comment by zerafox** [comment]
http://mypet.keyle.de/doku.php?id=en:permissions

http://mypet.keyle.de/doku.php?id=en:plugins:npc

**Comment by KevinHendrews** [comment]
Thanks, The trait worked too
 THANK YOU VERY MUCH!
