### ISSUE TITLE
MyPet shows You can not use now in Default group /pcst

### ISSUE THREAD

**Issue by KevinHendrews** [xXKeyleXx/MyPet#480]
Whats the problem? As the title says.
I have MyPet.customskilltree.*
and MyPet.user.customskilltree.* on the permissions
I am using Essentials Group Manager

**Comment by xXKeyleXx** [comment]
Group Manager doesn't support * permissions for unregistered permissions like the the ones for the skilltrees, so it's a GM problem.

**Comment by KevinHendrews** [comment]
So how can I?
Tell me plz

**Comment by xXKeyleXx** [comment]
Use another permission plugin or add every single skilltree permission

http://mypet.keyle.de/doku.php?id=en:permissions
