### ISSUE TITLE
Quest support?

### ISSUE THREAD

**Issue by kleinesgumi** [xXKeyleXx/MyPet#483]
can you make hook for Quests?
when my pet kill the Quest mob it not counting for my quest.

**Comment by zerafox** [comment]
Double check that this is an actual mypet issue. Tame a normal wolf and let that wolf kill your Quest Mob.
Many Questing plugins don't consider pets or extensions of players at all...

Also double check to make sure that the "PlayerDamageEntityEvent" is set to True in your configuration file. It could be as simple as turning that on too.

Ultimately it isn't MyPet saying "don't count this as a kill" it's the Quest plugin.

**Comment by kleinesgumi** [comment]
mhh not counting :(

**Comment by zerafox** [comment]
The Normal Minecraft Wolf doesn't count for the kill objectives either?

So then it is definitely your Quest plugin with the issue, not MyPet

**Comment by kleinesgumi** [comment]
i dont normal wolfes, i mean Mypet Pets killed mobs and it doesn't count

**Comment by zerafox** [comment]
But you also need to test if normal wolves are counted too.
To narrow down if it is infact JUST a mypet issue. Many quest plugins don't count ANY additional means of a mob dying, that includes normal Wolves or Crushed by a piston, etc;

You need to rule that out completely, before you try pointing fingers at MyPet.
Also, did you double check that configuration setting I mentioned?

**Comment by kleinesgumi** [comment]
i have check all configs..

**Comment by zerafox** [comment]
...

PasteBin your config file, and let us know the results of testing a VANILLA wolf kill on your Quest mob...

**Comment by kleinesgumi** [comment]
when a vanilla mob kill the mob it dont count.

**Comment by zerafox** [comment]
Then it is, once again, not a MyPet issue. It is a Quest Plugin issue, where your Quest Plugin does not accept an outside means of the mob dying. Report this to the Quest plugin to have the issue resolved.
