### ISSUE TITLE
Somes suggestions

### ISSUE THREAD

**Issue by jeannen** [xXKeyleXx/MyPet#485]
Hey ! :)
Can you add an option for saving the metadata (Name, equiped items...) when a pet is tamed, and an option to prevent player from changing pet's stuff ? :)

Ah do you think it will be possible to link MyPet and MagicSpell, so the pet can use MagicSpell Spells ? :D

**Comment by xXKeyleXx** [comment]
# this should already happen, if not I don't know why Bukkit/Spigot is doing that :/
# is already possible look into the config
# It may be possible but I will not add that sry

**Comment by jeannen** [comment]
When my player tame a pet all stuff and name disapared :/
And is there a way to trade pets ? :)

**Comment by zerafox** [comment]
Double check your configuration, there is a setting to remove/keep Items on a pet when the mob is tamed.
Unique named mobs like a Zombie named Steve, are not going to keep the name Steve, but will keep the name Zombie.
No, there is no way to trade pets.

As far as linking MyPet with MagicSpell, that would be incredibly difficult I would think with the way MyPet allows you configure the skill trees with it's outside program. Personally I think it would take a whole lot of extra work to accomplish this, and not a whole lot of people use the two together (I think). Besides, Pets are already capable of so much without MagicSpells plugin too. ;P
