### ISSUE TITLE
[Bug] Pet with too much XP is crashing the server

### ISSUE THREAD

**Issue by austinv2006** [xXKeyleXx/MyPet#488]
Is there any way you can set a hard limit to the xp a pet can have? Also is there a way I can send you my My.Pets file to have you delete a pet from a user? Every time they try to enter the server it results in a crash before I can use "/petadmin remove <username>"

**Comment by xXKeyleXx** [comment]
No there is no way to limit that but maybe I should add that :P 

I can fix it but it depends on the amount of pets whether I want that.

**Comment by austinv2006** [comment]
It is only one pet that must be removed.

**Comment by xXKeyleXx** [comment]
What I meant is that I don't want to remove 1 pet in a 1000 pets file ;)
Just upload it and I will see what I can do.

**Comment by austinv2006** [comment]
Ok, only images can be uploaded to this website but I uploaded it to filehosting.org

http://www.filehosting.org/file/details/491937/My.Pets

Thank you heaps for the help.  If it is of any use the pet is named Frosty, is a snowman, and is owned by a player with UUID: 8d4dcc03-b30d-49d1-ae51-3aae12d4b5d0

**Comment by xXKeyleXx** [comment]
Here you go: https://dl.dropboxusercontent.com/u/23957620/crap/My.Pets

**Comment by austinv2006** [comment]
Thank you very much!
