### ISSUE TITLE
MyPet Plugin Wont Work in General

### ISSUE THREAD

**Issue by Bowbuck2** [xXKeyleXx/MyPet#489]
Hello So i have my pets on my server and let me say i LOVE it but that was on my home ported server now i transferred to a server host and when i transferred all of my files to this server hosted one Everything worked instead of My Pets all Permissions are in place i tried re-downloading it and im using the same version of Craftbukit as before,I just got gitHub for this and probally will never come back on here so if you could contact me via Contacts below that would be great!

Email: deathdrone64@gmail.com
Email: TimberghostGaming@gmail.com
Skype: timberghost22
and my minecraft server 1.8                                 AirshipWars.ddns.net:25717

**Comment by zerafox** [comment]
An error log is needed for startup or any other locations, such as MyPet.log or anything else before any assistance can be given.
Also, I'm not sure about Keyle.. But tracking down someone through an e-mail or skype vs using the provided Ticketing function specifically for a plugin is not ideal and I cannot say that I would bother my time with it.

If you're seeking help for a plugin, or any other subject for that matter, it's best to use the resources provided as that is much easier and much less of a hassle for those you're trying to reach.
Can't say it's anyone's job to track down some random user, or multiple users for that matter, for an issue their having if they have no interest in using the service provided to obtain that help. ;P

**Comment by Bowbuck2** [comment]
Where are Error Logs At And should be able to use gitHub

**Comment by zerafox** [comment]
Error Report in your Console on startup?
MyPet.Log in your MyPet folder?

**Comment by Bowbuck2** [comment]
MyPet does work now i Basically Reinstalled everything and it all works well
I guess third time a charm right?
