### ISSUE TITLE
Issue with PVP areas

### ISSUE THREAD

**Issue by PabloM98** [xXKeyleXx/MyPet#493]
When a user is within an area NO-PVP and shoots with a bow to another that is in a PVP area, the pet attacks him without that can defend itself.
I use WorldGuard 6.1 with Spigot 1.8.7 and the dev build #688 of the plugin MyPet.

**Comment by PabloM98** [comment]
Look at this: https://www.youtube.com/watch?v=LTrEBg703ko

**Comment by xXKeyleXx** [comment]
Sorry for the late response, will try to fix this today.
