### ISSUE TITLE
Pets don't respect Towns protect

### ISSUE THREAD

**Issue by kotkew** [xXKeyleXx/MyPet#496]
Hello.
I have a problem.
My server have plugin the Towny and it have protect some areas to prevent destroy blocks, kill mobs etc
But if players attack some mobs in protected place it's will prevent damage but player's pet start attack too and it will not prevent damage.
So with this method they can kill mobs at private places.

**Comment by tara81** [comment]
This issue is only with towny, no other plugins protect animals with land management as far as I know.

**Comment by tara81** [comment]
It may just require towny to fix it , not pets

**Comment by csorrows** [comment]
uSkyblock does protect animals but I have not yet tested it with MyPet
