### ISSUE TITLE
Enderman holding item

### ISSUE THREAD

**Issue by triarry** [xXKeyleXx/MyPet#497]
Hey there,

Player on my server wants to know how to prevent his enderman from picking up materials.
I didn't see anything on the wiki, config, or github for this, except you confirming this is a feature back in January or something.
Would also be nice to know a way to swap out the item he is holding.
Thanks!

**Comment by triarry** [comment]
On a hunch, had him shift + right click with shears as thats how armor is removed, and it worked. How about preventing it?

**Comment by zerafox** [comment]
Enderman shouldn't just be randomly picking up blocks. They hold blocks you
give them, just like you equip armor and saddles to other pets.
If Enderman is actually picking up blocks on it's own, it's a bug. Unless
it was infact changed, which I cannot see why it would be added/changed.
If it was, double check the config file, for a setting under Enderman,
(it'd be just like the setting for lay-egg for chickens) and see if there
is a setting there.

**Comment by triarry** [comment]
I didn't see such a setting. Perhaps he shift right clicked the enderman with a block by accident.

**Comment by xXKeyleXx** [comment]
They don't pick up blocks on their own. The owner must have given him the block by accident.
