### ISSUE TITLE
Pets can't attack!

### ISSUE THREAD

**Issue by Faller10** [xXKeyleXx/MyPet#498]
Hi, so all my players are worried about their pets because when they hit someone, the pet doesn't attack! It doesn't matter if the pet is Combat or PvP it still doesn't attack the target! And changing the behaviour also does not make him attack! Please help!
Thanks!

**Comment by zerafox** [comment]
Please try to follow this guideline so that we can help you. :P
 https://github.com/xXKeyleXx/MyPet/blob/master/CONTRIBUTING.md

**Comment by Faller10** [comment]
Spigot Build: Protocol Patch
MyPet Version: 1.2.1 SNAPSHOT

MyPet.log: http://www.mediafire.com/download/kb7oorzxnh3lkho/MyPet.log

There is no console error being presented buy the plugin. But players are unable to make pets attack!
Doesn't matter if they are with pvp/combat skill!

**Comment by zerafox** [comment]
There is no MyPet build for the Protocol Hacked Server Builds. Please use an actual release build for your server and not the protocol hack, if you wish to use MyPet.

**Comment by Faller10** [comment]
Ok, I changed the build to Spigot 1.7.10
But they still don't attack the target...
