### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by Dysthymic** [xXKeyleXx/MyPet#499]
Can you update the latest version you have on the dev server for 1.8.7 to be more easy with on join and on quit events? They cause a bit of lag on my server with a good amount of players on. The timings reports are pretty scary and end up at around 500% and 100+ms response times. I've tried older version and they do the same as well.

**Comment by xXKeyleXx** [comment]
Your setup would be very interesting. Could you run the "/petadmin ticket" command and uploaded the zip file for me.

**Comment by Dysthymic** [comment]
I recently had to disable MyPet on my server. We have had several crashes over the past few days and there are no crash logs or errors in the logs. The last command before crash is usually /petcall or /petsendaway or something related to MyPet, leading us to believe that it is MyPet causing the crashes. Our timings for MyPet are very weird, they are fine most of the time and they spike to the crazy numbers I posted before.

I think something is corrupt. We sometimes get "corrupt" pets.. but RARELY. It is weird. When it happens, a pet gets "poisoned" and they are hungry. We try to feed them but they won't get fed. They just stay hungry. The only fix we've came across is to delete the pet, make a new pet for the player, and assign the same levels. 
https://www.dropbox.com/s/erasul8ba37s9lq/ticket.zip?dl=0

Hope you can figure this out, as this is our players favorite plugin and we love it. Thank you for all you've done!

**Comment by xXKeyleXx** [comment]
I see you reseted the pets, it would be nice to get the My.Pets file with the 435 pets ;)
