### ISSUE TITLE
Pets can't attack!

### ISSUE THREAD

**Issue by Faller10** [xXKeyleXx/MyPet#500]
OBS: Changed mu Spigot build!

Hi, so all my players are worried about their pets because when they hit someone, the pet doesn't attack! It doesn't matter if the pet is Combat or PvP it still doesn't attack the target! And changing the behaviour also does not make him attack! Please help!

Spigot Build: 1.7.10
MyPet Version: 1.2.1 SNAPSHOT

MyPet.log: http://www.mediafire.com/download/kb7oorzxnh3lkho/MyPet.log

There is no console error being presented buy the plugin. But players are unable to make pets attack!
Doesn't matter if they are with pvp/combat skill!

**Comment by zerafox** [comment]
I'm going to assume that would be build number 644? Cause you know, Build Number is a good idea to provide when using Dev Builds. ;P There are a lot of 1.2.1 versions, and many of them are actually for 1.8 servers.

Okay so the log says you are using 644 which is good. :P Are you sure you're not using the Protocol Hack anymore? The one that lets 1.8 Clients connect to a 1.7.10 server? Because that's kind of a really big deal!

I'm not seeing anything in the recent recordings of your MyPet.log file, outside of it loading pets and players, and shutting down. Which is normal, I think.. I also see that you are running in offline mode, which is important to know...

There is nothing in console on startup for MyPet, and nothing in console when players call/dismiss or anything with their pets at all?

I'm afraid if you don't anything else for *me* to look at, you'll have to wait for Keyle to help you out. :P I have not a clue otherwise what would be causing your issue. I do not remember when multiverse or whatever support was disabled, but I don't think it was in that version. As I think it wouldn't let you even summon pets at all. ;P

**Comment by Faller10** [comment]
Yes I'm sure i'm not using the protocol patch!
http://prntscr.com/7p6br5

I'm not sure what build number Is my MyPet! I don't remember, there is another way I can see the build number?

I will upload a most recent log file to see If there is something new!
http://www.mediafire.com/download/rvw55sa9fako21x/MyPet.log

Yeah there is basic info in Console! But what i'm saying is that there is no error log that points some mistakes in something that would tell me why pets are not attacking!

Thanks for the help!

**Comment by xXKeyleXx** [comment]
Do you have NoPvP Regions where this happened?

**Comment by Faller10** [comment]
No! I tested in __global__! 

Here is a list of my plugins:
http://prntscr.com/7pgmjx

Thanks!

**Comment by zerafox** [comment]
Your global setting could very well be a NoPvP area too.. >.>
Did you have pets attacking once before, and this is a new problem? Or has
this problem been around since you installed the plugin?

**Comment by Faller10** [comment]
I already saw if my global region is a nopvp area! It's not!
Yes i had my pets attacking normally once before!

Thanks!

**Comment by zerafox** [comment]
What changes have you made to your server recently, since the pets have
stopped attacking?
Something triggered it somewhere, a setting in a plugin perhaps?

**Comment by Faller10** [comment]
I used the plugin with no permissions recently! But i thought that could be the reason of the problem so I turned the permissions on! This was the only change I made! 
Thanks!

**Comment by xXKeyleXx** [comment]
So it works when the permissions are not eneabled? If the answer is yes you should look into the permissions page in the wiki.

**Comment by Faller10** [comment]
No! I always used the plugin with the permissions disabled! But when it started to give me this problem of the pets not attacking, I thought it was something with the permissions, but it was not! Just this! But the problem started when the permissions were not enabled! Turning permissions On was a change I made to try to fix the pets attacking problem!

**Comment by zerafox** [comment]
Okay, so what change did you make BEFORE the pets stopped attacking?
Changes afterwards aren't going to help you find the problem, unless you
manage to figure out what changed, to make it "break" in the first place.

**Comment by Faller10** [comment]
I did not change anything at all! At least I don't remember changing anything! Neither adding new plugins!

**Comment by zerafox** [comment]
It had to have been something, plugins don't just typically randomly decide
to stop working for no reason at all.
If it was a setting you changed in the server's main setting file, a change
made to MyPet config or the Skilltrees? Permissions? Anything at all?
Do pets still work for OP's and not players, or not for anyone at all?

**Comment by Faller10** [comment]
I'll try to remember!! 
No sometimes it does not work even for OP's! I'll try to upload a video!!

**Comment by zerafox** [comment]
If it's "sometimes" then it's something to do with location and settings.
Certain areas must be restricting the pets, double check the areas it's not
working and the settings in both the MyPet config file and the locations
"flags" for damage vs players or mobs.

**Comment by Faller10** [comment]
Ok! I just donwloaded #644 again and reseted my config!
I think it fixed!

**Comment by zerafox** [comment]
If your pets are attacking now, it was your configuration file that changed
that made them stop. xD
Whatever it was that was changed, it was something to do with area checks,
or some setting disallowing the pets to something altogether.

Hope it worked out for you either way though. Might I advise taking note of
any changes you make to your server in the future. So when something like
this happens again, you can go back and look at what was changed recently.
