### ISSUE TITLE
Hi, need 1.8.1 spigot

### ISSUE THREAD

**Issue by hsndmrts** [xXKeyleXx/MyPet#501]
hi mypet creators, i need mypet for 1.8.1 version spigot please i need quickly, this spigot link:
http://tcpr.ca/download/spigot/spigot-1.8-R0.1-SNAPSHOT-latest.jar

please, i need it but need last version

**Comment by zerafox** [comment]
Check the development Builds, you can find versions of MyPet for 1.8.1 there...

**Comment by hsndmrts** [comment]
unfortunetly, there isnt actionbar health for 1.8.1 :/

**Comment by zerafox** [comment]
Then you'll have to update your server to work with that update of MyPet?
Updating Old Versions isn't going to happen. It's pointless and time consuming to do so, not to mention it would open the door for updating for EVERY release of Minecraft, everytime MyPet adding something new... And I'm sure you can see where that wouldn't be ideal.

I'm afraid you'll have to use the 1.8 versions as they are on your server, or update your server.
