### ISSUE TITLE
Support for Mo Creatures

### ISSUE THREAD

**Issue by FoxyFullmoon** [xXKeyleXx/MyPet#502]
Recently I've been playing with Cauldron servers, and I always use Mo Creatures. MyPet is one of my favorite plugins, but when using it with Mo Creatures, there's a wide variety of mobs that can't be tamed. It makes the game seem inconsistent. I just wanted to request compatibility for all the extra mobs that are added.

There's also mods like the Twilight Forest that add mobs too. It'd be nice to have a wider range of options when using mods.

**Comment by xXKeyleXx** [comment]
MyPet doesn't even support Cauldron servers (even if it may works), so no I will not add that. Sorry.
