### ISSUE TITLE
MyPet neu übersetzen

### ISSUE THREAD

**Issue by jworx** [xXKeyleXx/MyPet#503]
Hallo,

ich versuche nun schon länger vergeblich das MyPet-Plugin neu zu übersetzen.
Aber leider bekomme ich schon beim Importieren des Maven-Projektes einige Fehler/Warungen angezeigt, die ich nicht "wegbekomme".

Z.B. den Fehler "Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:ideauidesigner-maven-plugin:1.0-beta-2:javac2 (execution: default, phase: process-classes)	pom.xml	/mypet	line 476	Maven Project Build Lifecycle Mapping Problem"

Gibt es eine Anleitung (Tutorial), wie ich das Plugin importieren und neu erstellen kann?

Ich nutze Eclipse 4.5 (Mars).

Für jeden Hinweis wäre ich sehr dankbar.

Viele Grüße
Oliver

**Comment by xXKeyleXx** [comment]
Also bei Eclipse kann ich die leider gar nicht helfen, ich benutzte nur IntelliJ.

Was gefällt dir an der Übersetzung nicht? :o

**Comment by jworx** [comment]
Hmm... schade. :)
Evtl. versuche ich es dann mal mit IntelliJ.

Das Plugin ist klasse - keine Frage - aber ich wollte mal sehen, ob es auch serverübergreifend einzusetzen ist.
Sprich die daten, die das Plugin speichert, in eine Datenbank zu packen. MySql zum Beispiel.

So wie ich es sehe, hast du dafür keine Unterstützung implementiert.
Korrigiere mich, wenn ich falsch liege. :)

Jedoch lässt sich die NBT-Struktur auch nicht einfach in eine (oder mehrere) Datebank-Tabellen portieren.

Aber dafür müsste ich erstmal in der Lage sein, dein Plugin überhaupt neu compilieren zu können.

Gibt es eine Anleitung für IntteliJ? 
Denn damit habe ich noch gar nicht gearbeitet.

Viele Grüße
Oliver

**Comment by xXKeyleXx** [comment]
Übersetzen ist bei deinem Vorhaben nicht ganz der richtige Begriff, deshalb war ich auch ein wenig verwirrt was du eigentlich wolltest ;)

Ich habe schon mehrfach damit angefangen das Ganze in eine Datenbankfähige Struktur zu bringen, aber das hat sich als schwerer herausgestellt als mir lieb war (deshalb bis jetzt auch nicht implementiert :P). An sich sollte es aber kein Problem darstellen aber das Plugin wurde nie darauf ausgerichtet in diese Richtung zu Arbeiten.

NBT hatte ich gewählt da z.B. Items von Minecraft selber schon im NBT Format vorlagen und ich damit keinen Mehraufwand betreiben musste aber sonst ist es eher hinderlich :P JSON wäre da schon eine bessere Alternative.

Anders Thema: wie gut sind deine Programmier/Java Kenntnisse? Wie sieht's mit Maven aus? Bevor du das Plugin compilieren kannst, ist ein bisschen was an Vorarbeit zu leisten. IntelliJ sieht vielleicht auf den ersten Blick komplizierter aus, aber wer effizient mit Java arbeiten will kommt fast nicht drum herum ;)

Wenn dein "Können" ausreicht und du wirklich was am Plugin machen willst können wir uns auch mal auf meinem TS treffen und ich helf dir ein wenig ;)

**Comment by jworx** [comment]
So. 
IntelliJ ist nun installiert und dein Plugin importiert.
Soweit klappt alles hervorragend, aber...

Wie komme ich jetzt an das JAR-File?
Wenn ich unter "Project Structure" ein "Artifact" anlege und als main-class die MainGUI-Klasse angebe, bekomme ich zwar ein Build hin, aber das JAR-File lässt sich nicht starten. ?!

Beim Versuch das neu erstellte JAR-File als Plugin unter Spigot laufen zu lassen ergibt die Fehlermeldung, dass die Version nicht kompatibel ist.
Ein Blick in das Log von Spigot zeigt mir, dass die "Platzhalter" für die Versionen (die im pom.xml) definiert werden) nicht durch diese ersetzt werden.

Hmm... Also irgendwie habe ich da noch einen (oder meherer) Fehler in der Bearbeitung. ;)
Oder die Vorarbeiten, die du erwähnst, waren noch nicht genug. ;)


Meine Java-Kenntnisse halten sich in Grenzen - schon mal probiert, aber nicht tiefgehend.
Ich komme eher aus der Richtung C/C++ und C# und noch PHP.
Es sollte aber kein großes Problem sein, dass ich mich in Java zurechtfinde.

**Comment by xXKeyleXx** [comment]
Du kannst das Plugin nicht einfach so bauen, das es so compiliert ist schon ein Wunder xD

Du musst das Ganze über Maven machen. Theoretisch sollte Maven in IntelliJ schon mit drin sein, falls ja gut, falls nein musst du das vorher noch installieren. Anschließend musste noch Craftbukkit und Spigot in das lokale Repo hizufügen. Dannach sollte dann alles so funktionieren wie es vorgesehen ist.

OK dann sollte Java an sich kein Problem für dich sein, höchsten die Bukkit API.

Für alles Weitere sollten wir vllt auf ein anderes Kommunikationsmedium wechseln, hast du Skype oder TeamSpeak?

**Comment by jworx** [comment]
In die Bukkit API habe ich schon früher einen Blick geworfen. 
Für die Version 1.5 (1.6?) versuchte ich mal ein Bank/Chest Plugin - zur privaten Nutzung und aus berufl. Interesse! :)
Aber solche Plugins gab es da schon zuhauf.

Prinzipieller Aufbau eines Plugins ist bekannt. Nur den Funktionsumfang der API habe ich nicht im Kopf. ;)

Verfolge mal deinen Ansatz, es über Maven zu erstellen.

Skype habe ich, aber TS wäre besser!
Bin jedoch im Büro - ein wenig Geld verdienen :) - aber Abends geht's.
Ab morgen ist bei mir auch Urlaub angesagt, dann bin ich flexibler...

**Comment by xXKeyleXx** [comment]
Naja da du bei deinem Vorhaben eh weniger mit der Bukkit API zu tun hast ist das auch nicht so schlimm.

Wenn du irgendwelche Probleme oder Fragen hast kannst du ja dann einfach bei mir aufm TS Server vorbei schauen: ts.keyle.de (PS. beim draufgehen nicht über den Namen wundern ;) )

**Comment by jworx** [comment]
:) Okay.

Ach so... Jetzt hat's funktioniert! 
Über "Run Maven Build" werden alle benötigten Files erzeugt und die JAR-Datei lässt sich auch ausführen und ich bekomme deinen "Skill-Tree-Creator" zu sehen. :)
Die 1.2.2 Version des PlugIns funktioniert auch.
Jetzt noch auf dein aktuelles Dev-Build wechseln (da Bukkit 1.8.7 im Einsatz) und dann sollte es das gewesen sein. 
TS Server habe ich jetzt ja - für alle Fälle. ;)

Deine Hilfe war wirklich klasse und ohne hätte ich mir wahrscheinlich einen "Wolf gesucht"! :)
Hätte Anfangs nicht gedacht, dass du dich meldest. Dafür einen "Daumen hoch"!!!

Nochmals vielen Dank dafür...

Soll ich dich auf dem Laufenden halten? ;)

**Comment by xXKeyleXx** [comment]
Ich suche immer Hilfe fürs Plugin :D in den 4 Jahren in denen ich es Entwickelt habe, habe ich noch nicht eine Anfrage in Richtung Hilfe bekommen ;) Und da ich im Moment nicht wirklich Lust und Zeit dafür habe kommst du da sehr gelegen :D

Klar, du kannst mich gerne auf dem Laufenden halten =)
