### ISSUE TITLE
/petrelease command, and playerquit event lagg

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#507]
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/8874580/87803a56-3212-11e5-9056-b043366e858f.PNG)
![kepkivagasq1](https://cloud.githubusercontent.com/assets/8324198/8874581/8ab066a6-3212-11e5-822a-b2dbc0465dd1.PNG)

**Comment by xXKeyleXx** [comment]
please try to disable the PetStorage.OnPetRelease option in the config and report the results

**Comment by andris155** [comment]
/petrelease lag fixed Thanks!
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/8890570/2da4a1ee-3306-11e5-9472-dd5b705ee800.PNG)
Player quit lag not fixed.
![kepkivaghas](https://cloud.githubusercontent.com/assets/8324198/8890572/3a5a4600-3306-11e5-87c4-194b2f5d69d4.PNG)

**Comment by xXKeyleXx** [comment]
Well then you should disable the corresponding option in the config ;)

**Comment by andris155** [comment]
Disable PetStorage.OnPlayerQuit?
No lost pets and information in player quit?

**Comment by xXKeyleXx** [comment]
No, the pets are saver periodically too, so as long as the server doesn't crash no pets are lost ;)

**Comment by andris155** [comment]
Thanks again. :) :+1:
