### ISSUE TITLE
My.Pets file doesn't contains all data

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#515]
MyPet database error, how to fix, and no lost Pets?
http://pastebin.com/JFSfnT4H

**Comment by xXKeyleXx** [comment]
You My.Pets file would be interesting.

**Comment by andris155** [comment]
https://drive.google.com/file/d/0B_j1jjP8UeXxWjBVd01ScHRQbDA/view?usp=sharing

**Comment by xXKeyleXx** [comment]
Ok something went terribly wrong while saving the pets...  There is a backups folder inside the MyPet folder that contains some backups. Just rename the latest to My.Pets and replace the broken one with it. Could you please look through your server log and search the error that happened when it went wrong (not the one in your OP, this is just the result of this ;) )

**Comment by andris155** [comment]
MyPet backups folder empty. :(

**Comment by xXKeyleXx** [comment]
Well then you are fucked :/ But you must have disabled the backups, otherwise you had them.

**Comment by andris155** [comment]
Request server host rollback mypet folder.
And enabled backup.
