### ISSUE TITLE
MyPet Level

### ISSUE THREAD

**Issue by MadzzUp** [xXKeyleXx/MyPet#516]
Hello,
First, thanks for that awesome plugin. My ticket isn't really an issue. When you level up a pet, it gets better stats, new skills, higher life ... but level 10 is the last one where you get Something new, then only the spawn time get higher and higher, and honestly, that's not fun to wait 300 secs for a pet to come back. So, here's my question : how can we add new stats like from 1-10, but after the level 10 ?
Once again, thanks for the plugin.

**Comment by xXKeyleXx** [comment]
Doubleclick the MyPet.jar in the plugins folder. This will bring up the MyPet skilltree creator ;)

**Comment by MadzzUp** [comment]
Didn't know about that. Thanks a lot !
