### ISSUE TITLE
Pet wont PvP

### ISSUE THREAD

**Issue by GothkittyGirl** [xXKeyleXx/MyPet#522]
im was thinking pvpmanage was the issue but removed it and still wont pvp. any idea why? something im missing in config?

**Comment by zerafox** [comment]
Is the Pet in a PvP allowed area?
Can the player successfully hit the other player and deal damage? If a
player cannot attack another player, the pet won't be able to either.
Does the pet have a Damage Trait?
What behavior is the pet set on?

**Comment by GothkittyGirl** [comment]
i feel so dumb right now... but yes it is i just found that it means in plugin type pvp areas (mobarena/SG/minigames) not regions that allow pvp and duel behavior and pvp /pcst skill. i thought pvp meant anywhere i had a region for pvp... not just for minigame type pvp games

**Comment by GothkittyGirl** [comment]
players are able to deal dmg to other players but the pet cant deal dmg in the regions i have set as pvp zone

**Comment by zerafox** [comment]
If players are able to deal damage to other players, the pet should be able
too. I believe there was a configuration setting on whether the pet should
be able to do this or not (somewhere near the top?) but I cannot recall.

So long as a player can attack another player, the pet should be able to as
long as it has the Damage Trait. If you are using World Guard, make sure
compatibility for it is turned on in the config too.

**Comment by GothkittyGirl** [comment]
ohhh i see ok checking the worldguard as well. the region is set with that ill get back to you

**Comment by GothkittyGirl** [comment]
Regios: true this or in the worldguard itself? (not sure if this a typo or not is why im asking)

**Comment by GothkittyGirl** [comment]
ok not seeing anything about this in worldguard...

**Comment by GothkittyGirl** [comment]
ok disregard plz this pvpzone was set up a while back and forgot i had set mob damage to false :/. thx for the help in fixing this :)

**Comment by zerafox** [comment]
So you got it working alright now then?
Kind of silly the mob damage would stop Pets from attacking, but it makes
perfect sense.. Kind of.
Personally I thought the pets were more treated like the player, but then
again I am not the developer/coder so it was just my own assumption. :P

Learn something new everyday huh? ^.^

**Comment by GothkittyGirl** [comment]
yup works fine now i had forgot about that flag i set til i look at the wordlguard region pvp and see it. thx for help me out  :)

**Comment by zerafox** [comment]
Glad you got it working properly then. ^.^
