### ISSUE TITLE
Pet battling

### ISSUE THREAD

**Issue by GothkittyGirl** [xXKeyleXx/MyPet#523]
is there a way to send my pet to battle another without hitting the other pet first?

**Comment by zerafox** [comment]
Pets need to have the Duel Behavior selected and within 5/7 blocks radius
of another pet with the same behavior active.

**Comment by GothkittyGirl** [comment]
well then.. lol ty still learning this plugin

**Comment by GothkittyGirl** [comment]
is there s scoreboard for the battles to see who is winning alot of the battles and kinda like a comptition thing?

**Comment by zerafox** [comment]
There isn't a function like this actually (currently, you could try
requesting an addon for MyPet though).

MyPet doesn't log which pet wins a duel or not, nor stores data of that
nature. However, owners of the pet should be seeing the HP totals of the
pet (I think that was newly added not too long ago) and of course the
defeated pet "dies".

**Comment by GothkittyGirl** [comment]
how would see this? and how would i request this addon for it?

**Comment by zerafox** [comment]
Depending on what version of MyPet you are running, if i recall there were
little notices just above the player's HotBar on the Pet's Health updates.

As far as Requesting another addon/plugin for MyPet, just make another
ticket with the request of what sort of things you'd like it to do. Like a
"MyPet Arena" with the ability to track pet vs pet battles and things. :P
Though keep in mind, that Keyle already has MyPet, MyPet-NPC and possibly
other Plugins to update/maintain and futher plugin/feature requests of this
nature may be rejected.

**Comment by GothkittyGirl** [comment]
im running most recent build and wow... ok well you read my mind on the "Mypet Arena" bit and ill watch for the msg on the hotbar next time i send mypet to fight another

**Comment by zerafox** [comment]
It should appear anytime the pet takes damage or heals. :P You don't have
to wait for the pet to be battling another pet.

Also there may be a configuration for it to display or not, i would double
check your config file just incase for this.
I cannot say that i have used MyPet in some time now.

**Comment by GothkittyGirl** [comment]
do you know the name of the setting? i dont see it when my pet heals

**Comment by zerafox** [comment]
I'm afraid I don't, I'm not even sure if there is a setting for it to be
enabled or not.
I would imagine that it would be documented in the config documentation
however if one existed.

**Comment by GothkittyGirl** [comment]
ok its cool ive looked up and down and i dont see anything about it. but thx for trying to help me out :)

**Comment by zerafox** [comment]
It should be active already then, there MAY be a command for it to toggle
per player?

Try /MyPet in-game for the list as I don't see it on the wiki. But it
should be there, so long as you are using a 1.8 version. Unless for some
reason it got removed.
