### ISSUE TITLE
MyPet incompatible with AutoIn 2

### ISSUE THREAD

**Issue by Epicnicity2016** [xXKeyleXx/MyPet#525]
Hello, in a previous post I had talked a bug that when an original player registered by AutoIn come in and try to get a pet, the pet disappears of nowhere, I had upgraded to Craftbukkit (I wore spigot) and had solved the problem, I come say the problem returned ;-;
I'm using snapshot 695

**Comment by xXKeyleXx** [comment]
Should work since 0ac4b768d412a4b58a8f8f4aadfb01a7a6d3ff7a
