### ISSUE TITLE
Mypet Not Working [Spigot 1.8.8]

### ISSUE THREAD

**Issue by IzayaAkihiko** [xXKeyleXx/MyPet#531]
How Fix This?
Mypet Enabled but command not working
i already use 1.2.1 and 1.2.2 snapshot, but still not working
http://pastebin.com/8JeYjWxH

- Sorry if my english Bad

**Comment by xXKeyleXx** [comment]
You are not using Spigot 1.8.8, that's the problem ;)

**Comment by IzayaAkihiko** [comment]
i use it

**Comment by xXKeyleXx** [comment]
the error says something different
