### ISSUE TITLE
equipped with weapons/armour，Can't save the lore!

### ISSUE THREAD

**Issue by nozuo** [xXKeyleXx/MyPet#537]
Where pets that are equipped with weapons/armour,Players quit the game,Can't save the lore!
My servers uses the Soulbound plugin.

**Comment by nozuo** [comment]
![07](https://cloud.githubusercontent.com/assets/8280703/10195291/83042f7c-67bf-11e5-8aff-0cb5a7bcb54d.png)
![08](https://cloud.githubusercontent.com/assets/8280703/10195300/8b50d6b2-67bf-11e5-9613-df5305eb9321.png)
![09](https://cloud.githubusercontent.com/assets/8280703/10195302/91a4f228-67bf-11e5-9816-629e5063ee43.png)

**Comment by xXKeyleXx** [comment]
Server version? Plugin build/version? What types of pets do this (zombie/skeleton/pigzombie)?

**Comment by nozuo** [comment]
@xXKeyleXx Hello,Server version is paperspigot 1.7.10,Plugin build/version is MyPet-1.2.1-SNAPSHOT , I only tested the zombie pets.

**Comment by xXKeyleXx** [comment]
I tried to reproduce this problem but I had no luck yet :/ Could you upload a MyPet logfile and your My.Pets file for me?

**Comment by nozuo** [comment]
@xXKeyleXx   Hello, I solved it, the error is due to the use of the paperspigot, after the replacement of all normal spigot-1.7.10-R0.1,Sorry for my English,Thank you for your help. XD~

**Comment by nozuo** [comment]
@xXKeyleXx  Thank you. I've already solved it. Soulbound equipment can not equip!

**Comment by xXKeyleXx** [comment]
What was the problem?
