### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by hamsterfat** [xXKeyleXx/MyPet#538]
Nothing happens when i do /mypet from console even ingame.
No error log and the log folder of the mypet plugin is empty -_- and also all folders are empty.

minecraft ver. 1.8.7 spigot
my plugins:
02.10 23:15:18 [Server] INFO [23:15:18 INFO]: Plugins (38): CoreProtect, WorldEdit, Essentials, TokenShop, ClearLag, AutoBroadcaster, Buycraft, Votifier, ZombieDay, WorldGuard, ProtocolLib, NoCheatPlus, SpectatorDisabler, SkinsRestorer, ObsidianBreaker, PermissionsEx, AntiJoinBot, RandomBox, CS-CoreLib, GAListener, Vault, EssentialsSpawn, AntiUserSteal, MassiveCore, CustomTab, QuestWorld, AuthMe, ObsidianAuctions, MobArena, MagicLoot, Translate, Factions, Hotels, ServerSigns, ChatEx, MyPet, CombatLog, ShareControl

**Comment by zerafox** [comment]
What version of MyPet are you running?
