### ISSUE TITLE
Pet invincible under worldguard region

### ISSUE THREAD

**Issue by Skulz89** [xXKeyleXx/MyPet#540]
Hello, when using a pet under a worldguard region it can't be killed. pvp flag is set on On and in Mypet configuration worldguard is hooked. Maybe there is some flag that I need to add? We tried more without success.

**Comment by xXKeyleXx** [comment]
Bukkit version? MyPet Build? I'm not sure what your problem is but when the owner is invincible in this WG region the pet is invincible too.

**Comment by Skulz89** [comment]
Both last versions. I found the problem btw. I had to add the animal interact flag in the worldguard region.

**Comment by xXKeyleXx** [comment]
so is problem gone?

**Comment by Skulz89** [comment]
yeah
