### ISSUE TITLE
SurvivalGames support not work.

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#541]
Used plugin: http://dev.bukkit.org/bukkit-plugins/ultimatesurvivalgames/
DisablePetsInGames: true not work. :(

**Comment by xXKeyleXx** [comment]
Bukkit version? MyPet version? what doesn't work?

**Comment by andris155** [comment]
Spigot 1.8.8 and MyPet 1.2.2-SNAPSHOT  #701
DisablePetsInGames: enabled, and not work.

**Comment by xXKeyleXx** [comment]
So pets can enter survival games?

**Comment by andris155** [comment]
Yes, and DisablePetsInGames: enabled

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=aZlQpyfTPM4&feature=youtu.be

**Comment by xXKeyleXx** [comment]
A temp fix (when the arena is in another world) is to move the world into a different world group.

**Comment by andris155** [comment]
Current worldgroups config:
Groups:
  default:
  - world
  - world_nether
  - world_the_end
  - plotworld
  - SurvivalGames
How to disable MyPet SurvivalGames world?

**Comment by xXKeyleXx** [comment]
default:
  - world
  - world_nether
  - world_the_end
  - plotworld
other:
  - SurvivalGames

**Comment by xXKeyleXx** [comment]
http://mypet.keyle.de/doku.php?id=en:multiworld

**Comment by andris155** [comment]
Tkanks temp fix!

**Comment by andris155** [comment]
Thanks!
