### ISSUE TITLE
Switchable chest pet

### ISSUE THREAD

**Issue by Biskabos** [xXKeyleXx/MyPet#542]
Автор очень прошу пожалуйста сделай возможность в настройках включить/выкключить функцию переключения сундука из креативного режима в выживание! Это очень нужно на моем сервере так как там стоит плагин Креатив контроля, и игроки могут из креатива перекладывать вещи в сундук питомца, а потом забирать их для выживания! Пожалуйста помоги откликнись прошу! Чтоб был разный инвентарь в разных режимах игры у питомцев!

**Comment by zerafox** [comment]
Disable accessing Pet inventory while in creative. This will resolve your
issue.

2015-10-14 13:18 GMT-04:00 Biskabos <notifications@github.com>:
