### ISSUE TITLE
support with griefprevention

### ISSUE THREAD

**Issue by thelicwolf** [xXKeyleXx/MyPet#543]
This failing with griefprevention causing neutral pets attack mobs in protected áreas.

Without warning.

Thank you for your attention.

MyPet-1.2.2-SNAPSHOT

**Comment by zerafox** [comment]
Neutral Pets don't attack anything unless the player attacks something, or
the player is attacked.
Are you sure the pets are on Neutral? And/Or that the mobs within the
GriefPrevention zones are protected?
