### ISSUE TITLE
Flight flying mobs

### ISSUE THREAD

**Issue by Biskabos** [xXKeyleXx/MyPet#544]
1) А можно сделать так чтобы летающие мобы летали, а не просто парили над землей? Например Летучая мышь или Ифрит с Иссушителем? 2) А ещё можно спросить, можете ли вы добавить в плагин Дракона края?  3)  Последнее что я хотел спросить могу ли я помочь с переводом на русский язык, так как некоторые мобы называются неправильно на русском языке например Blaze называют Пламя а правильный перевод Ифрит)))! Спасибо вам за такой плагин вы молодцы без этого плагина не интересно играть, удачи вам в разработке)))!

**Comment by zerafox** [comment]
There is no Flying AI, so Pets cannot fly.
Dragon is difficult to add, as it flies backwards by default. It has been
requested, and attempted many times already.

I'm personally not familiar with how to submit translations for MyPet,
sorry. I am sure Keyle can direct you properly though.

2015-10-15 9:01 GMT-04:00 Biskabos <notifications@github.com>:

**Comment by xXKeyleXx** [comment]
http://mypet.keyle.de/doku.php?id=en:translations
https://github.com/xXKeyleXx/MyPet-Translations
