### ISSUE TITLE
Can not ride pets in Build #702 

### ISSUE THREAD

**Issue by ScuroK** [xXKeyleXx/MyPet#547]
Since Build #702  the ride function is broken. Players can not ride pets. when i click it with leash it will leash the pet instead of ride it.

**Comment by tara81** [comment]
Same here, I also tried to change it to saddle .  I am on the latest build.

**Comment by tara81** [comment]
I reverted and it works

**Comment by xXKeyleXx** [comment]
so 701 works? ot to wich build did you revert?

**Comment by ScuroK** [comment]
ye. build 701 works. but all builds after 701 are broken.

**Comment by ScuroK** [comment]
thanks
