### ISSUE TITLE
Visual Skilltrees (or at least text based)

### ISSUE THREAD

**Issue by Legendaryx** [xXKeyleXx/MyPet#548]
Hi,

Is there a way to see a skilltree unlockable thing.
So players know what they unlock with their pet at each level of the skill tree?

If its not possible yet, this would be nice!

**Comment by xXKeyleXx** [comment]
As skilltrees the skilltree bundled with MyPet are just examples and new ones SHOULD be made by server owners this is something that doesn't really lies in my responsibility.

I could change that if you provide a nice (and dynamic) web design where I just need to fill in values but I doubt that this will happen :P So you need to do it by yourself.

**Comment by zerafox** [comment]
If you're talking in-game, when you create your own SkillTrees you can set
it up to display in-chat what a pet has learned when it reaches a certain
level/skill. (If I recall that was possible already)

**Comment by Legendaryx** [comment]
haha okay,

Well Wouldnt it be possible if a person would type something like: /petskilltreeinfo Combat
It checks that skilltree and shows it in chat?

Or at the very least you can do: /petlevelinfo
and it shows which things it has learned so far?

**Comment by tara81** [comment]
ya petskill already does this ;D
