### ISSUE TITLE
Dont understand HP regeneration skill

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#549]
decrease / set health interval , what does this mean ??
If i set Health increase to 1 heal,
And I then set the health interval to 10 , does it mean the pet gains 1 health every 10 seconds?
And I set the heath interval to decrease 10, does it mean the pet loses 1 health every 10 seconds?

**Comment by xXKeyleXx** [comment]
The interval is how often a pet heals itself. If you decrease that value the pet will heal itself more often. A pet will never lose health because of this skill ;)

Heal set: 1 - Interval set: 30   -> Heal: 1 - Interval: 30
Heal inc: 1- Interval dec: 10   -> Heal: 2 - Interval: 20
Heal inc: -1- Interval dec: -10 -> Heal: 1 - Interval: 30

**Comment by tara81** [comment]
interval means how often in seconds?

**Comment by xXKeyleXx** [comment]
yes in seconds

**Comment by tara81** [comment]
Okay I know you don't want to do this.. But please hear me out.

The pets that attack monsters is really cool, but let's face it, most monsters arent much of a challenge anyways.

So, this plugin really shines on servers with custom monsters (epicboss, mythicmobs .. etc)

The problem with custom monsters, is that you just can't have one server with it.  It is way too intensive and requires bungee, multiple servers to help with the load.

Your plugin doesnt support that.  So please, add some bungee database support, somehow.  Else players will have to level their pets on like 4 different servers to do different custom "quest lines"

Much <3 this plugin is truley awesome but does lack this one important feature, especially since it's so well suited for role playing servers with custom monsters.
