### ISSUE TITLE
Spigot 1.8.1 Not work

### ISSUE THREAD

**Issue by Detrais** [xXKeyleXx/MyPet#550]
Why MyPet error on my server, when i command /mypet, its do nothing!

**Comment by zerafox** [comment]
Try updating your MyPet plugin, Build 550 is a much older version of MyPet
and I believe the newer versions of MyPet should still work on a 1.8.1
server.

Do you have any error logs, these are important to know what the errors are
in console.
More information is needed to help you thourghly.
