### ISSUE TITLE
Uskyblock

### ISSUE THREAD

**Issue by brunokcampos** [xXKeyleXx/MyPet#552]
man i need  block mypet my minigame uskyblock, all player coming  pet use /peti  onlyne game.

**Comment by tara81** [comment]
just disable the permission in that world

**Comment by xXKeyleXx** [comment]
Are these mini games held in another world?

**Comment by csorrows** [comment]
uSkyblock has to have it's own world so yes. Also, it is not a minigame, it's a gamemode.

**Comment by xXKeyleXx** [comment]
Then it's easy, just move the world into a different worldgroup and disable the permissions to leash a pet for this world and you are good to go.
