### ISSUE TITLE
The ability to learn skills from items

### ISSUE THREAD

**Issue by MClausz** [xXKeyleXx/MyPet#553]
Here is my little idea and hope you spend your time on it.
Beside training level, pets can also learn skills from owner's item that contain skill's name in the first line lore, by right-clicking on the pet, and the skill can be from any skilltree.

**Comment by tara81** [comment]
I'd rather see bungee support before any new additions

**Comment by xXKeyleXx** [comment]
This is not really possible because the actual skill level is calculated on the fly, based on the XP the pet has. The idea is good but would require a complete rewrite of the skill system.
