### ISSUE TITLE
Remove pet name requirement from release command

### ISSUE THREAD

**Issue by csorrows** [xXKeyleXx/MyPet#554]
Allow pets to be clicked with a configurable item to open skills menu. My server is primarily menu based and the commands just don't fit the feel of the server. Maybe even a main menu on click to do everything that is possible by the commands.

**Comment by xXKeyleXx** [comment]
Do you have any plugin that can bind a command to an item?

**Comment by csorrows** [comment]
I could go that route but commands requiring the pet's name is not possible.

**Comment by xXKeyleXx** [comment]
Only the admin and the release commands need the name and I don't see a reason to make these clickable.

**Comment by csorrows** [comment]
I was under the impression more commands then that required the pet's name. Maybe it was just the video I watched. If you could make the release command clickable, that would make it 100%. thanks for your time.

**Comment by csorrows** [comment]
Thoughts on a release click event. 

On click with <configurable item>
  - First click sends player a message something like "You are about to release this pet, click again within <delay time> to confirm"
 - after a set <delay time>  with no clicks, command is abandoned
 - if a second click happens before <delay time> expires, trigger release routine

**Comment by tara81** [comment]
Bungee support way more important then revising a way to release pets.

**Comment by zerafox** [comment]
https://github.com/xXKeyleXx/MyPet/issues/554#issuecomment-152244914
Please stop pressing the Bungee-Support issue on other tickets.
This pressing on a Harassment Level, please keep comments and replies to the ticket subjects.

**Comment by csorrows** [comment]
@tara81 You care about bungee support, I don't. Please stay off my ticket.

**Comment by zerafox** [comment]
Here's a thought, perhaps variables be added through MyPet, or via other plugins (however this is done to complete compatibility) of %petname%, which can be gathered by checking the player's active (not NPC stored) pet.

**Comment by xXKeyleXx** [comment]
Well the release item will never happen but I could arrange that clickable chat message that will be triggered when the release command is used without a name..

**Comment by zerafox** [comment]
I think that sounds like a great alternative! then the command could be used to tie onto a GUI or Item, and the chat message triggers without the name added into that command.
I think it's a win-win. But that's just me. Even helps out players who forget to add the name into the command too!

**Comment by csorrows** [comment]
Wait so I'm a little confused. Do you mean like fire the command without a name and then click the pet with an item?

**Comment by csorrows** [comment]
Oh, and thanks @xXKeyleXx  for removing the troll.

**Comment by csorrows** [comment]
Thank you =)
