### ISSUE TITLE
/petbeacon null error.

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#556]
Spigot 1.8.8
MyPet: dev build #700
http://pastebin.com/1ivWaVmu

**Comment by tara81** [comment]
Bungee support more important.

**Comment by andris155** [comment]
I don't use Bungee.

**Comment by zerafox** [comment]
https://github.com/xXKeyleXx/MyPet/issues/556#issuecomment-152245003
Please stop pressing the Bungee-Support issue on other tickets.
This pressing on a Harassment Level, please keep comments and replies to the ticket subjects.

**Comment by xXKeyleXx** [comment]
DId this happend more than once? Do you have a plugin that can prevent players from opening an inventory?

**Comment by andris155** [comment]
No write more error. LimitedCreative blocked inventory opening in creative mode.

**Comment by xXKeyleXx** [comment]
Could you please try to open the beacon menu when the creative menu is blocked and see if this error happens again.

**Comment by andris155** [comment]
/petbeacon, and /pbeacon blocked cmds in LimitedCreative.

**Comment by andris155** [comment]
Thanks!
