### ISSUE TITLE
HungerPointsPerFeed: don't work

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#557]
HungerPointsPerFeed: 25
in config.
Rebooted server and tried reloading, still gives the pet the default health per feed of 6 or 7.

**Comment by xXKeyleXx** [comment]
You can make the value as high as you want, the pet will never heal more than 3HP and the hungerpoint cost of it are always healed HP * 2.

**Comment by tara81** [comment]
I'm confused as to why theres a config option then

**Comment by xXKeyleXx** [comment]
There is a Hunger value beside the HP that influences the respawn HP and the beacon range. The higher this value the better. And when it drops to 1 the pet will start to lose health on it's own.
