### ISSUE TITLE
Can't get an EnderDragon pet.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#558]
Hi!
I really want to give my players the ability to have an EnderDragon pet.It does not matter if it's buggy,or it's upside down(for some strange reason i thought it's a thing xd).I just want to know if it's possible,or not.
I will wait patiently for any answers,but please don't make me wait 10 or so months :P.
Sincerly: Kronox12

**Comment by zerafox** [comment]
The EnderDragon has been attempted to be added multiple times before.
The problem with adding the Dragon, is that by default he flies backwards.
And it is very difficult within the code to turn him the right way around
again.

Currently there isn't an EnderDragon pet available within MyPet, but
perhaps somewhere down the road (probably not very soon at all) another
attempt to add him to the Pet Options for tames would be made.
