### ISSUE TITLE
I thought this was implemented but ...

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#559]
I cannot find the command for viewing player's pet's inventories... I checked the command page.

This tool is useful in case a player dupes and hides their duped items in there or "loot steals" from other players after a boss fight ..

**Comment by zerafox** [comment]
/petinventory
        opens the inventory of your MyPet.
        can not be opened when pet is in water/lava
        alias:
            /pi
            /peti

Just include the player/pet-name after the command to specify someone else's pet..

**Comment by tara81** [comment]
oh cool ! Thanks
