### ISSUE TITLE
Help with version!!!

### ISSUE THREAD

**Issue by marciaxe55** [xXKeyleXx/MyPet#562]
Hi!! Congratulation for the plugin... It's perfect! But I don't know how to take a 1.8+ version! I have a server compatible with 1.8.1, 1.8.3, etc., since 1.8.8... But I don't find a mypet version compatible with all of these.... Can you help me?

**Comment by zerafox** [comment]
Check the Dev Builds for a compatible version for 1.8.8. Try the latest available found on jenkins. There is a button for Dev Builds on the plugin page.
