### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by CrazzyNava** [xXKeyleXx/MyPet#564]
Hello, I have the plugin mypet and when a player kill with leash pet type enderman or horse, crashes the game of the user, anyone know how to fix? thanks

**Comment by xXKeyleXx** [comment]
Bukkit/Spigot Build: ?
MyPet Build: ?

**Comment by CrazzyNava** [comment]
MyPet: MyPet-1.2.1-SNAPSHOT-b#647
Spigot: git-Spigot-c3c767f-33d5de3 (MC 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

Thanks! :)

**Comment by xXKeyleXx** [comment]
is it a 1.7.10-1.8 compat build of spigot?

**Comment by CrazzyNava** [comment]
No, this spigot version only supports 1.8 to 1.8.8

**Comment by xXKeyleXx** [comment]
Unfortunately b#646 is too old to say what went wrong :/ The only thing you can try is to test it with the last 1.8 build: http://build.keyle.de/job/MyPet/669/

**Comment by CrazzyNava** [comment]
Thanks you so much!! :)!
