### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#565]
What is it Timer$2?
How to off?
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11165501/98a08e00-8b11-11e5-8387-92d04ceed1f0.PNG)

**Comment by xXKeyleXx** [comment]
I don't know but if I had to guess I would say it's that automatic backup or the autosave and both can be disabled in the config.

**Comment by andris155** [comment]
server java crash = delete mypets.
autobackup run every 48 hours.
AutoSaveTime: 60 (cannot disable)

**Comment by xXKeyleXx** [comment]
just set it to 0 and you are good to go.

**Comment by andris155** [comment]
AutoSaveTime: 0 = no save players pets, and lost server restart?

**Comment by xXKeyleXx** [comment]
no by default all pets will be saved when a player quits, leashes or releases a pet.

**Comment by andris155** [comment]
OnPetRelease, and OnPlayerQuit save disable (tps issues)
https://github.com/xXKeyleXx/MyPet/issues/507

**Comment by xXKeyleXx** [comment]
I made the I/O operations asynchronously, this may help.
