### ISSUE TITLE
Newest Dev builds bug

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#568]
I've just updated the plugin to Dev Build #708 and I found a very big problem with it.
Whenever a player executes the /petb command,it gives back a message,but the mypet does not react to anything at all.
I've executed the /petb aggro/aggressive command,and it gaved back a message saying that my pet is now in Aggressive mode,BUT my pet just sat there doing nothing.
I've summoned a chicken,but he left him alive.Same deal for any hostile mob.

It is very odd,because my friend uses the same version of the plugin (we have the same config for everything),and it worked for him.But not for me tho.

If anyone knows what is the problem,then please let me know.

**Comment by zerafox** [comment]
Server Version?

**Comment by xXKeyleXx** [comment]
Are you in a Towny protected area?

**Comment by andris155** [comment]
Test server paramaters:
Spigot 1.8.8 latest.
Plugins: MyPet build7​08
Not work /petb aggro, and normal mod mob attack.

**Comment by xXKeyleXx** [comment]
please run the "/petadmin ticket" command and upload the ticket.zip somewhere.

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=COl1a-b9O0Q&feature=youtu.be

**Comment by andris155** [comment]
Not fixed latest dev build. :(

**Comment by Kronox12** [comment]
https://www.dropbox.com/s/3izodesys2esb6r/ticket.zip?dl=0

**Comment by xXKeyleXx** [comment]
Please try the latest devbuild

**Comment by Belinda13na** [comment]
Hello our server also has this problem. and it still has it. It also has the problem where you can't tame pets anymore. all permissions added and everything but it still doesnt work.

**Comment by andris155** [comment]
Fixed!
Thanks!

**Comment by xXKeyleXx** [comment]
further discussion -> #576

**Comment by tara81** [comment]
well xxkeylexx my server is huge and uses sql for some plugins lol .
