### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by MatteCarra** [xXKeyleXx/MyPet#569]
I found this on spigot https://hub.spigotmc.org/jira/browse/SPIGOT-1301
This is also happening to me.

Heapdumps: usavsurss.com/heapdump2.7z
usavsurss.com/heapdump.7z

MD_5 reply: I see a poorly written plugin called MyPet, and also the fact that you have over 30,000 entities on your server (7000 chickens (1.3gb), 7000 sheep (1gb), 6000 pigs (900mb), 5000 rabbits (900mb), 4600 cows (600mb), 1500 zombies (1.4gb), 1000 skeletons (500mb)), as well as a bunch of stuff I can't be bothered to add up.
The fact that nearly 7gb of ram is going to just these entities (because you have 10x as many as any normal server!) suggests that your issues are to do with administration and/or plugin choice (mypet) rather than a bug.

**Comment by collller** [comment]
same issue

**Comment by xXKeyleXx** [comment]
NOT the fault of MyPet

**Comment by MatteCarra** [comment]
I like a lot this project. So I want to help you to improve this.
Please don't close this issue.
A part of heapdump:
![cattura](https://cloud.githubusercontent.com/assets/11074527/11374938/e9909228-92d8-11e5-8a68-1f44d8aa13b1.PNG)

**Comment by xXKeyleXx** [comment]
So what do you want to show me with these images?

**Comment by MatteCarra** [comment]
That MyPet is bot the cause of memory leaks, but that you fan improve a bit memory usage.
Nothing more

**Comment by MatteCarra** [comment]
Hi Keyle.
I have to confirm thesis of md_5
MyPet is causing memory leak.
Not with his entity but with metadata.
There are thousands of metadata in the MetadataStore.
Please fix it.
We like a lot this plugin and We ALL appreciate what you are doing :D
Keep doing it!
We will help you!

**Comment by MatteCarra** [comment]
The faulty method is addDamageToEntity in de.Keyle.MyPet.skill.Experience

**Comment by xXKeyleXx** [comment]
Yeah I already thought that... I think it's fixed now

**Comment by MatteCarra** [comment]
Yes I was editing it in that moment to commit it and I have seen WeakHashMap!
I though to be a complete idiot lol.
Ok thanks for the update!
Have a nice day!

**Comment by xXKeyleXx** [comment]
It's way to easy to create such a huge a memory leak like this. Who in the world would thought that you need to detach a MetaDataStore or Weak References if you are using non primitive datatypes like a normal HashMap....

**Comment by MatteCarra** [comment]
Yes.
Can you use only string for this DamageCount?
LivingEntity has a name, right?

**Comment by xXKeyleXx** [comment]
I could use it's unique ID but I think a weak hashmap should be sufficient.

**Comment by MatteCarra** [comment]
Yes, you are right.
String would stay in the hashmap forever
