### ISSUE TITLE
1.8.8

### ISSUE THREAD

**Issue by daiki4304** [xXKeyleXx/MyPet#570]
Are you sure you want to correspond to Mypet At what time 1.8.8?

**Comment by xXKeyleXx** [comment]
I have no clue what you want... but I think it's this:
http://build.keyle.de/job/MyPet/

**Comment by daiki4304** [comment]
Spigot 1.8.8でリードでmobを倒してもペットになりません...
これはSpigot1.8.8に対応していないということですか？
Mypetのversionは#711です

**Comment by xXKeyleXx** [comment]
Sorry but I still have no clue what you want :/ Google Translator isn't very helpful :/

**Comment by zerafox** [comment]
I think they're having trouble taming a pet when killing with a lead, as if
the version was mismatched with their server?
But that is just my best guess.

On Wed, Nov 25, 2015 at 12:01 PM, Sebastian Comans <notifications@github.com

**Comment by tara81** [comment]
Latest build doesnt allow taming of pets.. Just saw this issue sorry for posting it
