### ISSUE TITLE
Can't release pets

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#573]
It says to confirm, click the nametag of your pet.

I do click it and nothing happens.

**Comment by freakyy85** [comment]
same problem. a player clicks the name but nothing happens. me as server owner can do it but they have the permission MyPet.user.command.release. I don't know what to do.

**Comment by xXKeyleXx** [comment]
You clicked on the name that appeared in the chat with the message right?

**Comment by freakyy85** [comment]
The player says yes. I must say for me it works - I can with normal player privileges. And the player is not online right now. but i told him several times to do it by clicking the name in the chat.

**Comment by xXKeyleXx** [comment]
Does the same message appear when they click the name in the chat and if yes please upload a screenshot of their pet's name.

**Comment by tara81** [comment]
I'm sorry it works when I click on the chat, I thought I had to click the name tag above the pet, sorry !

**Comment by freakyy85** [comment]
I dont know, that user told me he got rid of his pet but i dont know how. so i guess its working like it should.
