### ISSUE TITLE
[Spigot 1.7.10] Could not pass event EntityDeathEvent to MyPet v1.2.1

### ISSUE THREAD

**Issue by sanghk** [xXKeyleXx/MyPet#579]
Sometimes the plugin spams these error lines:
Sorry, the cause is unknown:
http://pastebin.com/cWgTxRB9

Server Environment:
　・Java 7u79 x64
　・Spigot 1.7.10 (1649)
　・MyPet 1.2.1 for 1.8.1 Apr 10, 2015

**Comment by xXKeyleXx** [comment]
already fixed bot not for the 1.7.10 version. Sorry

**Comment by sanghk** [comment]
So I must use this : "MyPet 1.2.0 for CB 1.7.9-R0.2" ,mustn't I ?

**Comment by xXKeyleXx** [comment]
It's fixed in build 707 which means it's fixed for 1.8.4+

**Comment by sanghk** [comment]
Which build is suitable for Spigot 1.7.10 ?

**Comment by xXKeyleXx** [comment]
I will answer as soon as my server IP gets unblocked and I can access my server ;)

**Comment by sanghk** [comment]
:)) thanks , I'm waiting

**Comment by xXKeyleXx** [comment]
https://build.keyle.de/job/MyPet/636/

However it will not contain the fix for the problem.

**Comment by sanghk** [comment]
ok, thanks
