### ISSUE TITLE
Mobarena petinventory bug

### ISSUE THREAD

**Issue by ScuroK** [xXKeyleXx/MyPet#581]
If a player dies in mobarena, but the pet survives, it will loose its inventory.

**Comment by xXKeyleXx** [comment]
I need more info about your setup because it works fine for me.

**Comment by ScuroK** [comment]
Did you test it right? 
The player dies in arena while the pet survives= pet-inventory cleared


I testet it on mypet 1.2.2 (devbuild)
mobarena 0.97.1
multiverse-inventories
on spigot 1.8.8

the game was joined from same world like the arena. the pet was allready here when i did /ma join

**Comment by xXKeyleXx** [comment]
put items in pet inventory
/ma join (pet was there)
selected class -> go -> in arena (pet was there)
die
/ma leave
items still there

**Comment by ScuroK** [comment]
i found that "DropWhenOwnerDies" was set to true. I have set it to false now and i will test it again now.

**Comment by xXKeyleXx** [comment]
I think that will fix it

**Comment by ScuroK** [comment]
It fixed it. im sorry i forgot it was on true. No bug!
