### ISSUE TITLE
Database Backend

### ISSUE THREAD

**Issue by xXKeyleXx** [xXKeyleXx/MyPet#582]
Add database backend support to store pets in databases like MySQL or MongoDB.

@Phreag @JugadorON @Darkool The file you can download below is the first step towards database support. It doesn't support db backend yet but I made the changes that are required to support it. It would be nice if you could test the build below because I want to make sure that it works like before and no data is lost or something doesn't work.

~~Edit: this build is for the latest version of Craftbukkit/Spigot !!!
https://dl.dropboxusercontent.com/u/23957620/crap/MyPet-Premium-1.2.3-SNAPSHOT.jar~~

**Comment by Darkool** [comment]
Nice, I Will check as soon is possible, Thanks Keyle ;)

**Comment by tara81** [comment]
Nice xxkeylexx !!!!!!

**Comment by JugadorON** [comment]
Nice!!! I love you!!!

**Comment by Phreag** [comment]
Very nice! i will give it a testing session soon :)

**Comment by JugadorON** [comment]
Can you make this work also for version 1.7.9 craftbukkit please? Thank :)

**Comment by xXKeyleXx** [comment]
Sorry but no, it was a lot of work and I don't want to do it more than once.

**Comment by zerafox** [comment]
There won't be any updates to older versions, it's simply too much work to
do so and if you support updates for one old version.. You get asked to
support several others too.
I hate to say it, but don't expect this update to be added to a 1.7.9
version too.

**Comment by xXKeyleXx** [comment]
Any results yet?

**Comment by Phreag** [comment]
I tested it just a bit for an hour and didnt find any problem.
Is the release form thle link above a big change compared to older builds?
otherwise i can just put it on a world of my server and see if anyone reports a bug.

**Comment by xXKeyleXx** [comment]
Well I made some bigger changes under the hood but it shouldn't change anything for players. It would be very helpful if you put it on your server. Step 2 and 3 are following when I know it's working properly.

**Comment by Phreag** [comment]
Okay. One of my beta testers reported a bug that he lost his pet after relogging.
I did not reproduce this bug but he said he just logged in and out and his pet was gone

**Comment by xXKeyleXx** [comment]
Is there anything in the logs that could be helpful to find the problem?

**Comment by xXKeyleXx** [comment]
Step 2: https://dl.dropboxusercontent.com/u/23957620/crap/MyPet-1.2.3-SNAPSHOT.jar

**Comment by Phreag** [comment]
Yes, it was new, just caught some minutes before

**Comment by xXKeyleXx** [comment]
This version fixes the problems with recently tamed pets and adds new config options to replace the current "PetStorage.OnPlayerQuit", "PetStorage.OnPetLeash" and "PetStorage.OnPetRelease" options.

https://dl.dropboxusercontent.com/u/23957620/crap/MyPet-1.2.3-SNAPSHOT.jar

**Comment by JugadorON** [comment]
This can be used with spigot?

**Comment by xXKeyleXx** [comment]
Sure.

**Comment by Darkool** [comment]
How about the progress to use db, will take a long time?

PS: Thank u so much to make this possible Keyle <3

**Comment by xXKeyleXx** [comment]
The DB part is the smallest piece. But I will not start until I know everything is working to this point ;)

**Comment by xXKeyleXx** [comment]
Soooooooo I got MySQL support up and running ;) The only thing left is a converter...

**Comment by Darkool** [comment]
Ya, I will test it!

**Comment by Phreag** [comment]
Sorry, i will be out over christmas, but i will test it after...

**Comment by xXKeyleXx** [comment]
Here is a MyPet-NPC build that is compatible with the MyPet DB build:
https://build.keyle.de/job/MyPet-NPC/73/

**Comment by Darkool** [comment]
You are on fire Keyle! Merry Christmas!

**Comment by xXKeyleXx** [comment]
Go go go guys, back to work :P

**Comment by Darkool** [comment]
LETS GO! :)

**Comment by JugadorON** [comment]
For all versions minecraft please.

Each person uses a different version "craftbukkit/spigot". Thanks.

**Comment by Darkool** [comment]
It can't be for all versions, only the latest versions get support

**Comment by Phreag** [comment]
I got another question:
by now i am using different pets on different servers. if i will join them togehter i want my players to choose which pet they want to keep. is there any possibility to do this?

Like saying to delete all pets which are not needed and i just import all single my.pet files into mysql?

**Comment by xXKeyleXx** [comment]
About how many pets are we talking? Right now there is no way to merge multiple pet files together. And merging MySQL data is way easier.

**Comment by Phreag** [comment]
i really dont know. the my.pets file is per server about 500kb big.
But: Problem solved, i can just convert each server storage to an own mysql db and then just move singe recordsets.

**Comment by Phreag** [comment]
I have two Questions for this version:
1. How do i migrate a nbt file to mysql?
2. How much will it cost to buy the final version?

**Comment by xXKeyleXx** [comment]
1. set "Repository.Type" to "MySQL" and "Repository.ConvertFrom" to "NBT" and everything from the NBT file will be converted and added to the MySQL Database set under "Repository.MySQL"
2. I think I will set the price arround 4-5€. Would you say that this price is reasonable?

**Comment by tara81** [comment]
Yes reasonable if that is about $5-10 USD :)

**Comment by zerafox** [comment]
That's Euros. And in USD would depend on the conversation rate at the time
from USD to Euro.
In the past few weeks, there has not been a very large difference between
the Dollar and Euro though.

Does this mean you're going to start selling MyPet keyle, or just a MySQL
updated version of it?

**Comment by Phreag** [comment]
@xXKeyleXx this does not work. There is no such option in the config and it even didnt work after adding it.

of course i can do some testing, the new sql version is already running on one of my servers.

**Comment by xXKeyleXx** [comment]
@tara81 1€ = 1,09USD so not that big of a difference ;)

@zerafox No I will not sell MyPet, it's open source and everyone can use it. But the MySQL thing on the other side aims at bigger servers who should have the money anyway.

@Phreag maybe the old version doesn't had it to this point. I think it would be good if you had an account on my Jenkins server so you can download the latest builds straight away. I just need an email address from you.

**Comment by Darkool** [comment]
I will help u  Keyle send me a PM ;)
