### ISSUE TITLE
Interactive Chat Dueling System

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#583]
More advanced player dueling via interactive Chat.

Battle interactive chat and example:

Bob's pet Pikachi challenges your pet.
Do you accept?
[✔] Accept [✖] Decline
Challenge Accepted.
It is Pikachi's Turn. ## Random chance like a coin toss.
Pikachi attacks your pet Slurpy for 4 Damage.
Your pet now has 6 Health.
It is your turn now.
[✔]Attack [❤]Heal [✖] Forfeit #Heal got greyed out due to no heal chance.
Your pet Slurpy attacks Pikachi for 5 Damage.
It is Pikachi's Turn.
Pikachi attacks your pet for 3 Damage.
Your pet now has 3 Health.
It is your turn now.
[✔]Attack [❤]Heal [✖] Forfeit
Your pet Slurpy heals for 4 Health.
Your pet now has 7 Health.
It is Pikachi's Turn.
Pikachi did not attack for 150 seconds and faints. #auto disqualify timer.
Slurpy wins by disqualification!
❤❤❤❤❤ Slurpy is very happy! ❤❤❤❤❤
Slurpy has gained 20 experience!
Slurpy has gained a level!
Slurpy is now level 4.

**Comment by xXKeyleXx** [comment]
Sorry but I don't think that this fits into the plugin.
