### ISSUE TITLE
UTF8 characters

### ISSUE THREAD

**Issue by RoinujNosde** [xXKeyleXx/MyPet#585]
Bukkit/Spigot Build: CraftBukkit version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
MyPet Build: 1.2.1
Problem: Some characters (é,â,ã,...) are replaced by a "?".
![utf8](https://cloud.githubusercontent.com/assets/6441328/11906637/2fa4ac56-a5b5-11e5-98c9-2cad36bb5cec.PNG) ("You don't have a pet")
Language file: [MyPet_pt.zip](https://github.com/xXKeyleXx/MyPet/files/67118/MyPet_pt.zip)

**Comment by xXKeyleXx** [comment]
Thanks ;) the latest build contains the changes

**Comment by RoinujNosde** [comment]
"the latest build" means 1.2.2?

**Comment by xXKeyleXx** [comment]
https://build.keyle.de/job/MyPet/

**Comment by RoinujNosde** [comment]
I see.
All versions from 1.2.2 will only be compatible with Craftbukkit/Spigot 1.8.8?

**Comment by xXKeyleXx** [comment]
Yes, do you need the translations for an earlier version? if that is the case you can create a folder called "locale" inside the MyPet folder and put the improved translation file in there.

**Comment by RoinujNosde** [comment]
I already use this folder.
Only asked because i'm still on 1.8.3.
