### ISSUE TITLE
Phatloots causes pets to drop boss items..

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#586]
Plugin conflict, the phatloots plugin causes my bosses to drop custom loot. However, if the pet name is the same name as the boss, the pet drops loot.

Solution: Make a petname blacklist

**Comment by xXKeyleXx** [comment]
Solution: phatlook should fix that!

**Comment by tara81** [comment]
But that is how phatloots works, how is it to know the difference between a pet and a custom monster ..

**Comment by tara81** [comment]
Thanks, how do you use it in the config?

**Comment by xXKeyleXx** [comment]
it adds 2 example entries by default. Just add the names you want to blacklist to the list. (you can use Regular expressions too)
