### ISSUE TITLE
java.lang.NullPointerException in MyPet 1.2.2

### ISSUE THREAD

**Issue by DardBrinza** [xXKeyleXx/MyPet#593]
Latest spigot 1.8.8
http://pastebin.com/VP1UqmSn

**Comment by xXKeyleXx** [comment]
Is there any other error in the server or MyPet logfiles?

**Comment by DardBrinza** [comment]
In MyPet.log:
http://pastebin.com/P97zF4KH

In server.log only this error and mypet nullpointer:
http://pastebin.com/N57LYbpV

**Comment by xXKeyleXx** [comment]
Did this happened more than once?

**Comment by DardBrinza** [comment]
This rarely happens.

**Comment by xXKeyleXx** [comment]
In theory this error can't happen. When it doesn't affect the server just ignore it. Maybe it's fixed in one of the later builds but I'm not sure ;)

**Comment by DardBrinza** [comment]
Thank you, I will think about switching to dev build :)
