### ISSUE TITLE
Inheritance and permissions

### ISSUE THREAD

**Issue by ExtremoDuro** [xXKeyleXx/MyPet#594]
Two skilltrees, standard skilltree (default) and B,C,D, etc skilltree for each pet type.
Each specific skilltree inherits the abilties from the default one. Do the users need the permission to use the default skilltree? Or if they have the permission for Skilltre B, they have skills from both skilltrees.

Do players need a permission to see their pet xp and level? Some players can see their pet level, while others cant.
Thanks in advance.

**Comment by xXKeyleXx** [comment]
Would you be so kind and execute the "/petadmin ticket" command and upload the ticket.zip from the MyPet folder fo me?

**Comment by zerafox** [comment]
No they will not need the permission to use the Default skill tree if the
trees they can use inherit from it already.
I used a similar system on my server, and you will not need to provide them
with permission (Default) for each pet, if the trees you want players to be
able to use inherit it.

The permissions are only a way to grant players access to click or use the
command option to select the tree as their choice for the Pet's Skilltree.
Which is great, if you don't want players to only use "Default" and want
them to choose a tree that is branched off it's default values instead.

**Comment by ExtremoDuro** [comment]
As an admin, I cannot see pet level or xp.

Url to ticket.zip: http://www.mediafire.com/download/5h1k9xirm7z28d1/ticket.zip
Removed latest.log, as it contains a lot of personal data that should not be public.

If you need any aditional files, I can send you them by email.

Thanks in advance.

**Comment by xXKeyleXx** [comment]
Are you sure you can not see the level of your pet? Is your pet maxlevel?

**Comment by ExtremoDuro** [comment]
Now, I can see the level, but not the xp:

An user pet: https://gyazo.com/5e796f363a86a22ebcc9ba3a1cc18166
My own pet: https://gyazo.com/8556d889a325ca1d44c008d5ca3e5acd
