### ISSUE TITLE
MyPet 1.2.2-b718 File Broken

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#595]
I always get broken files
December - [MyPet] Enabling MyPet v1.2.1
                    [MyPet] 72 pet(s) loaded
After Updating to v1.2.2 to compatible with Minecraft 1.8.8
                      + added a levelcap (config: default is 100)
                      + 1.8.8 support
                      o dropped Java 6 support
                      - fixed a lot of bugs
 Look -->        - fixed a memory leak
Then i Saw this
January - [MyPet] Enabling MyPet v1.2.1
                [MyPet] 0 pet(s) loaded
:disappointed:

**Comment by xXKeyleXx** [comment]
please upload an older My.Pets backup so I can analyze the problem.

**Comment by PinoyLifeCraft** [comment]
What? i will upload my December file?
How to upload?...

**Comment by xXKeyleXx** [comment]
MyPet does backups of your pet database by default. These backups are stored in the backups folder of MyPet. Please select one of theses backups where you think are no pets missind, ZIP the file and upload (drag and drop the file into the textfield where you write your answer) it here.

**Comment by PinoyLifeCraft** [comment]
Sorry for the late response it's because i am so busy to the exam! -.-
but wait here is the file hope to fix it :smiley: 
  ------>
[lastbackup.zip](https://github.com/xXKeyleXx/MyPet/files/87243/lastbackup.zip)

**Comment by xXKeyleXx** [comment]
Well unfortunately it's not the correct file >.< The backup files have this format "YYYY_MM_DD_HH.MM_My.Pets". Please upload the one where you thing all pets are still there (the file size should be larger)

**Comment by PinoyLifeCraft** [comment]
Uhm i'm sorry for that!
Is this the correct file?
  ---> 
[My.zip](https://github.com/xXKeyleXx/MyPet/files/88755/My.zip)

**Comment by xXKeyleXx** [comment]
It's empty so no xD just zip the whole folder xD

**Comment by PinoyLifeCraft** [comment]
Yes its 0 pets loaded again :disappointed: 
[MyPet.zip](https://github.com/xXKeyleXx/MyPet/files/88945/MyPet.zip)

**Comment by xXKeyleXx** [comment]
You disabled the backups... I can't help you...

**Comment by PinoyLifeCraft** [comment]
Wait i enable it now!
Do not abandoned me :cry:

**Comment by zerafox** [comment]
I'm afraid nothing can be done if you don't have working files from before. There is nothing to determine what went wrong.
My suggestion here, is leave the backups enabled and have your players start fresh again with their pets. If it occurs again, create a new ticket and provide a valid backup file then. :\

**Comment by xXKeyleXx** [comment]
As @zerafox said I can't do anything without the data I need to find the problem. And is was your active decision to disable the backups so not really my problem ;)

**Comment by PinoyLifeCraft** [comment]
But i enable the backups now so when i encounter it again i will create a ticket
@zerafox Thanks for your ........
