### ISSUE TITLE
LeashFlag Tamed

### ISSUE THREAD

**Issue by ExtremoDuro** [xXKeyleXx/MyPet#596]
Pets with the leashflag tamed, become a pet when you kill them after being tamed, rather than only taming them.

Example with ocelots: In the config: "LeashFlags: Tamed"

Tamed it, It didnt become a MyPet. I am an operator, and have full permissions. Hit it after being tamed until lowhp and it became a MyPet.

**Comment by xXKeyleXx** [comment]
what does the "/pettype ocelot" command say?

**Comment by ExtremoDuro** [comment]
https://gyazo.com/bd4dd0c3b5012e94b4140a10e7f97434

Updated to last dev version this morning, will post results.

**Comment by ExtremoDuro** [comment]
Still happens.

**Comment by xXKeyleXx** [comment]
Well it works fine for me and others too so it has to be your setup. It would be nice if you could provide more info about your server.

**Comment by ExtremoDuro** [comment]
I agree it is probably something with my config, I created skilltrees, exp.js, etc, so it can be really difficult to reproduce. Will try to reproduce on test server, with different configs, with fresh files, etc.

**Comment by xXKeyleXx** [comment]
anything new?
