### ISSUE TITLE
WorldGuard flag - mobspawning

### ISSUE THREAD

**Issue by RoinujNosde** [xXKeyleXx/MyPet#597]
Bukkit/Spigot Build: CraftBukkit version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
MyPet Build: 1.2.1
WorldGuard: 5.9

I can't tell if it's a bug or not, but pets can spawn in regions with mob-spawning deny.

**Comment by xXKeyleXx** [comment]
No bug.

**Comment by RoinujNosde** [comment]
I see.
Can you make this a feature request? To block pets from spawning inside those regions.

**Comment by xXKeyleXx** [comment]
Why would you want that?

**Comment by RoinujNosde** [comment]
Because i have some regions that are PvP exclusive.
You could make a boolean:
WorldGuard:
  ignoremobspawningflag: false
# Should MyPet ignore WorldGuard mobspawning flag?

**Comment by xXKeyleXx** [comment]
Well they can enter but when PvP is disabled the pet shouldn't be able to attack too.

**Comment by RoinujNosde** [comment]
I know that... I want a region with PvP enabled, but pets are not allowed to enter.
I want a pure and simple PvP, not PvE.

**Comment by RoinujNosde** [comment]
Why declined? :/

**Comment by xXKeyleXx** [comment]
The thing is that player can bypass the spawn protection by spawning them outside of it and then run into it. That doesn't make much sense :/

**Comment by RoinujNosde** [comment]
What if the region is surrounded by walls? :)

**Comment by zerafox** [comment]
WorldGuard already allows you block commands within a region, just block
the call command.

As far as running into the region with a pet, walls work, sure. If you're
teleporting the player into the walled off region, I'm sure you can find a
way to run the dismissal command for the player as their teleported.
Problem solved.

To have MyPet "despawn" the pet on the entry of a region is silly. It can
already stop their summoning. :P

**Comment by RoinujNosde** [comment]
> I'm sure you can find a way to run the dismissal command for the player as their teleported.

I could make the player cross a AncientGates portal that runs /petsa... but it would be better if MyPet respect the mobspawning flag

**Comment by zerafox** [comment]
Players walking into a Region with the mobspawning flag and their pet out
has nothing to do with mobspawning.
Even WorldGuard's Mobspawning flag does not "despawn" mobs, it only
prevents their spawning... So even mobs can walk into those regions.

**Comment by zerafox** [comment]
Not to mention that the game does not treat Pets as mobs anymore, they are
more treated like players.
So if this is a case that players are still able to summon even with that
flag, that's why they are able to.. Because pets aren't "mobs" anymore,
they're more like players.

**Comment by RoinujNosde** [comment]
> Players walking into a Region with the mobspawning flag and their pet out
has nothing to do with mobspawning.
Even WorldGuard's Mobspawning flag does not "despawn" mobs, it only
prevents their spawning... So even mobs can walk into those regions.

There are walls... how the pet will walk into the region?

> Not to mention that the game does not treat Pets as mobs anymore, they are
more treated like players.
So if this is a case that players are still able to summon even with that
flag, that's why they are able to.. Because pets aren't "mobs" anymore,
they're more like players.

I kind realized that...
Why not treat them as mobs?

**Comment by zerafox** [comment]
Because they do not behave as mobs anymore?
And if there are walls, how are the players getting inside? A teleporting
gate anyway, which teleports players, and consequently their pets as well.
Dogs, Ocelots included, not just their MyPets.
Because again, these aren't "Spawning mobs" they're teleporting.

**Comment by RoinujNosde** [comment]
I give up...

**Comment by xXKeyleXx** [comment]
https://laracasts.simplecast.fm/10

**Comment by RoinujNosde** [comment]
As some people say:
> "Não se pode agradar Gregos e Troianos." (You can't please Greeks and Trojans.)

**Comment by CaioWzy** [comment]
I thought MyPet had this feature. Sometimes we want players-only PvP tournament and no pets should be able to teleport to that region. It'd be a pretty useful feature If pets were automatically sent away when a player enters in a blacklisted region.

**Comment by xXKeyleXx** [comment]
Please create a new issue instead of digging up a two year old...

**Comment by RoinujNosde** [comment]
@CaioWzy
Se resolver criar um novo issue, me marque. Gostaria de ver o resultado. :)

**Comment by CaioWzy** [comment]
Oops, I'm sorry.
