### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by JugadorON** [xXKeyleXx/MyPet#598]
1. More types of pets, example: 'Slime Normal', 'Big Slime', 'Magma Cube Normal', 'Wither Skeleton', 'Zombie Villager', 'Dragon', 'Baby pets' ...

2. Mypet NPC -> Add Chest NPC.

3. Add equipment for pets.

4. Fly pets, example: bat, ghast, dragon, ...

5. Add effects pets.

6. Add command to open store Mypet NPC.

7. Compatibility 1.7.9, 1.8.x

**Comment by xXKeyleXx** [comment]
1. everything but the dragon can already be captured as pets
2. ???
3. Zombies, PigZombies and Skeletons can wear armos (cosmetically only)
4. Pet will not really fly because there is no fly AI
5. ???
6. No.
7. Not now.

**Comment by RoinujNosde** [comment]
5. I think he meant particles (like this plugin: https://www.spigotmc.org/resources/supertrails.1879/)

**Comment by JugadorON** [comment]
1. Value dragon in the config please?

2. Mypet NPC

http://dev.bukkit.org/bukkit-plugins/mypet-npc/

http://minecraft-ids.grahamedgecombe.com/

ID 54 -> chest (object) -> I need this as npc.

5. Config effects for pets (particles).

Example:

https://www.youtube.com/watch?v=teKT7JM96cw

**Comment by xXKeyleXx** [comment]
1. Dragons are not possible to get as pets
2. Citizens doesn't support Blocks as NPCs and such specific request aren't worth adding
3. there are already particle effects in MyPet but the particles are for playes that were helpfull for the plugin itself (translators, testers, donators, and premium in the near future)

**Comment by JugadorON** [comment]
Babys pets please? and wither skeleton please? thanks.

**Comment by xXKeyleXx** [comment]
Do your fucking homework. The wiki is there for a reason!

**Comment by JugadorON** [comment]
In the wiki does not put as create 'baby pets'. And wither skeleton.

**Comment by zerafox** [comment]
Yes it does....
Read this page: http://mypet.keyle.de/doku.php?id=en:commands
Find the part about /petadmin create..
There is also this: http://mypet.keyle.de/doku.php?id=en:how_to_get_a_mypet

Have you even tried to tame a Wither Skeleton, or are you just assuming they don't work?
The wiki covers everything you'd ever need to know about MyPet. The information is there, you just have to look for it.

**Comment by JugadorON** [comment]
Not work!

horse baby
donkey
mule
zombie horse
skeleton horse

normal slime
giant slime

normal magmacube
giant magma cube

dragon (echopet plugin dragon? yes! mypet plugin dragon? no!!!)

Not fly!

bat (echopet plugin fly? yes! mypet plugin fly? no!!!)

**Comment by xXKeyleXx** [comment]
1. For gods sake if Echopet is so much better use that fucking plugin.

2. Even if English is not your native language it is not an excuse to write the way you wrote your past messages.

3. "Not work!" -> EVERYTHING you said works fine, you just don't know how and your lack of real questions isn't helping, I even added dragons 30min before you wrote your last message

4. "Not fly!" -> they are not in the ground, they do not touch the ground... I think it's called flying when they do that and who cares?
