### ISSUE TITLE
You Don't have a MyPet

### ISSUE THREAD

**Issue by maginka** [xXKeyleXx/MyPet#601]
MyPet has been running flawlessly for me for a very long time now. I updated Recently however, and now when players log in to the server, get a pet and try /petcall, the pet doesn't exist. You don't have a mypet message is displayed.

I have confirmed this on different accounts, and even as OP, it still happens to me.

The version I am running is the latest 749 build.

I even created a server running with nothing but mypet to see if any incompatibilities, but get the same outcome. 

I have reverted back to version 1.2.2 and all appears to work fine

**Comment by xXKeyleXx** [comment]
I want to release the next version soon and this need to be fixed so could you please run the "/petadmin ticket" command (on any server where it doesn't work) and upload the ticket.zip for me.

**Comment by maginka** [comment]
Here you go, hope this helps.

[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/94782/ticket.zip)
