### ISSUE TITLE
Generate a text dump of a MyPet skilltree.

### ISSUE THREAD

**Issue by triarry** [xXKeyleXx/MyPet#602]
Hey,

Some players on my server want to know what the skilltrees for each MyPet entail. However, we have gotten to the point where we have altered almost every level - it gets hard to keep up! Is there a way you could make it so we can get a plain text dump of skilltrees?

**Comment by xXKeyleXx** [comment]
Well the only way right now is the /petskilltree command

how detailed would you like to get the dump? Just the skills or also the values?

**Comment by triarry** [comment]
I'm not sure what the /petskilltree command is, when I tried to use it, it told me to use it in the console. When I ran it from console, nothing happened. If there was an in-game way of seeing the skilltree (which would be hard for skill trees that are bigger than the length of mc chat history), that would be awesome too. I just think a text dump for forum purposes is the most logical.

Values would be extremely useful, yeah, really just a human readable version of the skilltree in a text format so that it can be posted to forums and such, and people know what goals they need to set in order to unlock different pieces of the skilltree.

**Comment by xXKeyleXx** [comment]
@triarry what format do you think would be the best?

**Comment by triarry** [comment]
For our purposes, either plain text or markdown. Markdown would be sweet as we'll be posting this on a website or a forum. Plain text might make more sense since it would be more versatile.
JSON wouldn't be super useful to the average user - but I could see people doing some neat things with it.

So, plain text or markdown - whichever one you think will hit a larger audience.

**Comment by triarry** [comment]
Didn't see the first part. Text with values, yeah, but it would be sweet (because this is something we physically can't do) if you could show the benefits they get at each level, too. So if they get +5 HP, also  show what their new max HP is, for example.

Basically like:

Level 1:
+1 HP
+1 Damage
Total HP: 11 HP
Total Attack: 1 Damage

Level 2:
+2 HP
+Riding Skill
Total HP: 13 HP
Riding Skill Acquired, you can now mount your pet by right clicking it with a lead.

.... ETC.

So each level would be a summary of changes that affected the pet, but not a complete summary (that could come at the end?)

At max level:
Total HP: 100 HP
Total Melee Damage: 30 Damage
Total Ranged Damage: 15 Damage, uses Arrows as projectile type
Total available beacon effects: 1; Invisibility
Pet has riding skill, you can mount your pet by right clicking it with a lead.

... ETC.

Hope this is a more helpful comment :+1:

**Comment by triarry** [comment]
Was this added?

**Comment by xXKeyleXx** [comment]
Not yet :/ It's not that high on the priority list atm and I haven't had the time to look further into it yet. Sorry.
