### ISSUE TITLE
MyPet 1.2.2-b718 File Broken [Part 2]

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#604]
I still get a broken file

Config:
               Backup:
                         Active: true
                         SaveInterval: 300
                         DateFormat: yyyy_MM_dd_HH.mm
Plugin Version:
               MyPet 1.2.2-b718
Spigot Version:
               Spigot 1.8.8
File:
               --> [MyPet.zip](https://github.com/xXKeyleXx/MyPet/files/95620/MyPet.zip)

**Comment by xXKeyleXx** [comment]
It may be too late but are there any errors in the server logs?

**Comment by PinoyLifeCraft** [comment]
Ok so January 27, 2016    ---> 0 Pets Loaded again
[12:29:50] [Server thread/INFO]: [MyPet] Enabling MyPet v1.2.2
[12:29:51] [Server thread/INFO]: [[0;32;1mM[0;32;22my[0;32;1mP[0;32;22met[m] [0;33;1m0[m pet(s) loaded[m
[12:29:51] [Server thread/INFO]: [[0;32;1mM[0;32;22my[0;32;1mP[0;32;22met[m] version 1.2.2-b718[0;32;1m ENABLED[m
No Error was found :disappointed:

**Comment by xXKeyleXx** [comment]
Well without any error I have no clue what's going wrong on your server and as far as I know you are the only one with this problems :/ Maybe your HDD space is full or the permissions change over time but this are just speculations...

You could try the latest release but I doubt that this will help (but you never know :P )
https://www.spigotmc.org/resources/mypet.12725/

**Comment by PinoyLifeCraft** [comment]
Ok hope that no broken file to encounter :sob:

**Comment by PinoyLifeCraft** [comment]
I think i know what is the problem xXKeyleXx maybe MyPet do not save the pets when the server is close or the computer! :question:

**Comment by xXKeyleXx** [comment]
With the standard configuration you might lose some progress but you will not all the pets, except when you close the server in the moment the plugin saves them. But every plugin would lose them in this case. Just stop the server the way it's supposed (/stop) and everything will be fine.

**Comment by PinoyLifeCraft** [comment]
:angry: it's because of my MAMA or Mother when i pay to long she close all the programs without my permissions or turn of the computer :angry:  hehe i have so many assignment have to do it :disappointed:

**Comment by xXKeyleXx** [comment]
See edit!

**Comment by PinoyLifeCraft** [comment]
:question:  What -> **See edit!** <-

**Comment by xXKeyleXx** [comment]
I might have found the bug. Please try the latest devbuild.

**Comment by PinoyLifeCraft** [comment]
Hehe Give me link i will download it and Test it tomorrow cuz my mom is there have to study!
Fast Give Link! Please !

**Comment by xXKeyleXx** [comment]
https://build.keyle.de/job/MyPet/lastSuccessfulBuild/artifact/target/MyPet-1.2.8-SNAPSHOT.jar

**Comment by PinoyLifeCraft** [comment]
Thanks :smile: Hope not to lose the DATA!
I will Report to you if no Bug to found just give me long day or 1 month to test it pls!

**Comment by PinoyLifeCraft** [comment]
Im using 1.2.6 and how many days now pets is fine! :+1:

**Comment by xXKeyleXx** [comment]
As long as the players leave before the server shuts down everything should be fine in 1.2.6.

**Comment by PinoyLifeCraft** [comment]
OK BTW - i have to sleep BYE :smile:

**Comment by PinoyLifeCraft** [comment]
oh no 7 days ago and there is it again :cry: 0 pets loaded or you don't have mypet !
why other plugin do not loss the save plot or what ever is that! What a sad life :sob:

**Comment by xXKeyleXx** [comment]
Well you said you had backups enabled so it should't be that big of a problem. Could you search the logs (or upload them, all of them) for any error that could explain why it happens.

**Comment by PinoyLifeCraft** [comment]
Mypet logs?
[logs.zip](https://github.com/xXKeyleXx/MyPet/files/125689/logs.zip)

**Comment by xXKeyleXx** [comment]
No the server logs. If you don't want to upload them to the public you can send me the link to admin@keyle.de

**Comment by PinoyLifeCraft** [comment]
No it's ok this is my server logs
[logs.zip](https://github.com/xXKeyleXx/MyPet/files/125777/logs.zip)

**Comment by xXKeyleXx** [comment]
All the logfiles (3) are from Feb 10th so not really the logfiles I hoped for :/ I need the logfiles from the server where your pets are gone missing from the day before it happen until it said 0 pet's loaded

**Comment by PinoyLifeCraft** [comment]
Hehe sorry! every day i delete the logs file but i will not delete it for you :ok:

**Comment by xXKeyleXx** [comment]
Well then let's wait until it happens again xD

**Comment by PinoyLifeCraft** [comment]
Hehe thanks for the time you wait you are not angry in how many days you wait :open_mouth: wow!

**Comment by xXKeyleXx** [comment]
You have the problems, not me :P It's just annoying to know that there is a problem but I don't know where and how to fix it :/

**Comment by PinoyLifeCraft** [comment]
I'm really sorry :disappointed:

**Comment by xXKeyleXx** [comment]
As long as nobody else is complaining it's fine :P

**Comment by PinoyLifeCraft** [comment]
Here are the file Keyle!
  ->  [logs.zip](https://github.com/xXKeyleXx/MyPet/files/129042/logs.zip)

**Comment by xXKeyleXx** [comment]
So it happened again?

**Comment by PinoyLifeCraft** [comment]
Yup! :disappointed_relieved: 
Look in Feb. 13

**Comment by xXKeyleXx** [comment]
Could you upload the MyPet.log too please.

**Comment by PinoyLifeCraft** [comment]
[logs.zip](https://github.com/xXKeyleXx/MyPet/files/129682/logs.zip)

**Comment by xXKeyleXx** [comment]
Isn't there any logfile from the 13th? Because this one is from 2015...

**Comment by PinoyLifeCraft** [comment]
:question:  What do you mean?

**Comment by xXKeyleXx** [comment]
look at the date of the MyPet.log file. It's from december 2015

**Comment by PinoyLifeCraft** [comment]
So what should i do?
Why it's 2015?

**Comment by xXKeyleXx** [comment]
Have you disabled the logger (MyPet.log) in the config?

**Comment by PinoyLifeCraft** [comment]
Check it here!
[config.zip](https://github.com/xXKeyleXx/MyPet/files/131544/config.zip)

**Comment by xXKeyleXx** [comment]
Ok that is not the problem...

Ok I hate to say that but we may have to wait until it happens again.
Use the latest dev build (https://build.keyle.de/job/MyPet/) and delete the MyPet.log file.
If it happens again and there is nothing in any of the logfiles you should consider using another plugin because I can't help you :cry:

**Comment by PinoyLifeCraft** [comment]
Noo!!! I don't want to say Good Bye to this plugin this Pet Plugin is The only best for me :cry:

**Comment by PinoyLifeCraft** [comment]
Ahm when i close the server or turn off the computer.
I don't get the broken file on MyPet
but my computer will auto shutdown i don't know because my brother fix my computer he said that the battery is ???? that's why it will shutdown and i saw this after that's happen 0 pet(S) loaded!

**Comment by xXKeyleXx** [comment]
If your computer is the reason then there is not much I can do to prevent that.

**Comment by PinoyLifeCraft** [comment]
But why my other plugin is fine! then the mypet ?
Like plugin not using .yml - PlotSquared - Furniture Lib - Give Anything Listener (GAL) - Login Security
:cry:  can you make your plugin like that?

**Comment by PinoyLifeCraft** [comment]
I will not stop to Investigate !
As my experiment -> When my computer will turn off automatic now i didn't get any broken file.
In my 2nd experiment -> When the i change my Date and Time i get the broken file.

**Comment by xXKeyleXx** [comment]
Hmm I might be able to fix that problem by writing the new data to a temp file and replace it when writing to the file is done

**Comment by PinoyLifeCraft** [comment]
So do you mean you can fix it?
I hope you'll fix it :smile:

**Comment by xXKeyleXx** [comment]
please try the latest devbuild!

**Comment by xXKeyleXx** [comment]
@PinoyLifeCraft have you already tested it?

**Comment by PinoyLifeCraft** [comment]
Uhm wait i will comment again if i will change my date to 2015 and if it will be fine.
 - i will!!!!

**Comment by PinoyLifeCraft** [comment]
I'm sorry @xXKeyleXx  i get the 0 pet loaded :disappointed:
[MyPet] Enabling MyPet v1.3.2
Level: INFO
[[0;32;22mMyPet[m] [mPvPArena hook activated.[m
[[0;32;22mMyPet[m] [mProtocolLib hook activated.[m
[[0;32;22mMyPet[m] [mCompat mode for v1_8_R3 loaded.[m
[[0;32;22mMyPet[m] [m--- Loading WorldGroups ---------------------------[m
[[0;32;22mMyPet[m] [m   added 'world' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'survivallobby' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'survivalfarm' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'world_the_end' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'world_nether' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'survivalgame' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'survivalplot' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'creative' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'pvplobby' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'pvp' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'pvptdm' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'pvpkit' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'gclobby' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'gcparkour' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'gcskyblock' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'gcskyblock_nether' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'gcskyblockpvp' to 'default'[m
[[0;32;22mMyPet[m] [m   added 'gcspleef' to 'default'[m
[[0;32;22mMyPet[m] [m registered 'default' group[m
[[0;32;22mMyPet[m] [m-------------------------------------------------[m
[[0;32;22mMyPet[m] [mversion 1.3.2-SNAPSHOT-b870[0;32;1m ENABLED[m

**Comment by xXKeyleXx** [comment]
is there a .temp file in the MyPet folder?

**Comment by xXKeyleXx** [comment]
Could you make a step by step guide for me so I can try to reproduce it by myself please

**Comment by PinoyLifeCraft** [comment]
[MyPetlogs.txt](https://github.com/xXKeyleXx/MyPet/files/177006/MyPetlogs.txt)
That is my logs - I didn't find any .temp in MyPet folder even i show hidden files
-----------------------------------------------------------------------------------------------------
Could you make a step by step guide for me so I can try to reproduce it by myself please 
-----------------------------------------------------------------------------------------------------
 - When i open my PC it give me the wrong date and time it's March 22 2015 when i synchronise it i'm using windows 8 it didn't fix i don't know why but i only change it when the PC is starting then Pressing **DEL** and thats it!
-----------------------------------------------------------------------------------------------------
If the date and time is wrong the mypet will be 0 petloaded..

**Comment by xXKeyleXx** [comment]
You should replace the battery on the mainboard ;)

I set my date to 2015 and it still loaded all the pets... Everytime I get more details I have a lesser idea on what might is going on...

**Comment by PinoyLifeCraft** [comment]
Yes i did that!
---------------------------------------
Why in me ? so unfair :cry:

**Comment by PinoyLifeCraft** [comment]
It still happening even i fix my PC

**Comment by PinoyLifeCraft** [comment]
Ok @xXKeyleXx  maybe the only problem is me and not your plugin i close this issue! :fallen_leaf: Bye!
