### ISSUE TITLE
MyPet-NPC Config file issues

### ISSUE THREAD

**Issue by Onoitsu2** [xXKeyleXx/MyPet#606]
Just thought you should know that it is working great in 1.8.8, Spigot. However it is not making the config file that the source looks like it should in the Util folder in Configuration.java and your main MyPetNPCPlugin.java, as shown below the snippet from that.
```java
File configFile = new File(MyPetPlugin.getPlugin().getDataFolder().getPath() + File.separator + "plugins" + File.separator + "NPC" + File.separator + "config.yml");
        configFile.getParentFile().mkdirs();
        Configuration.yamlConfig = new ConfigurationYAML(configFile);"
```

I would have posted in the other Issues section, however it does not have one. Manually creating the folder NPC as the code reflects, and the proposed formatting of it, is unsuccessful also for changing things like Fixed and Factor, so the storage cost is more adjustable.

**Comment by xXKeyleXx** [comment]
Right now the config file is generated under plugins\MyPet\plugins\NPC
Do you think it would be better to generate it in the plugin folder directly?

**Comment by Onoitsu2** [comment]
My apologies, I thought I had to install that just like any other Citizens plugin, and the plugin be in the Citizens/Plugins folder, where it will make the NPC folder. I found it in the MyPets/Plugins/NPC folder as you stated. There was very little information on installing that plugin, and where to place it, so I naturally assumed that it would be like any other Citizens tie-in plugin, mistakenly.
