### ISSUE TITLE
MyPet  Compatibility PaperSpigot Protocol Hack 1.7.10 (1.7.X 1.8.X)

### ISSUE THREAD

**Issue by DMFCraftBR** [xXKeyleXx/MyPet#609]
Hello I Am A Person In The World And I Talk About About 1 Problem And Would Like To Receive 1 Answer Your Casso Possible

The Mypet And not compatible With PaperSpigot 1.7.10 Protocol Hack

There is version Compatible? Runs Mypet Usually the Server

When one player uses more / petcall (/ pc) Of the 1.8 Crash Players

There is version Compatible?

I use Google translator (Am Brazil)

**Comment by MrPowerGamerBR** [comment]
Update to 1.8.8 and use the latest MyPet version.

1.7.10 Protocol Hack is outdated, @xXKeyleXx won't (I think) add support to a older version (heck, even MyPet breaks when a new Minecraft version is released due to internal NMS changes).

**Comment by MrPowerGamerBR** [comment]
Duplicate issue of #473 and #465

> This is a problem with the protocol hack. 1.8 clients need other datatypes for certain fields than 1.7 and the hacky protocol Server thing can't translate them correctly. MyPet is written for either one of the versions and will not work for both (unfortunately).
- @xXKeyleXx

**Comment by xXKeyleXx** [comment]
What @MrPowerGamerBR said is correct. It's either the one or the other but not both.
