### ISSUE TITLE
Permissions (Wolf only pet)

### ISSUE THREAD

**Issue by Pigna** [xXKeyleXx/MyPet#611]
Hey, i want my ranked players to use a pet. But only limited to the Wolf.
I gave them the permission to use it. But they dont seem to be able to. Only limited to OPed players at the moment.
These are the permission i gave them.
*    - MyPet.custom.skilltree
*    - MyPet.custom.skilltree.Combat
*    - MyPet.custom.skilltree.PvP
*    - MyPet.custom.skilltree.Utility
*    - MyPet.user.command.capturehelper
*    - MyPet.user.command.name
*    - MyPet.user.command.name.color
*    - MyPet.user.command.release
*    - MyPet.user.command.respawn
*    - MyPet.user.leash
*    - MyPet.user.leash.Wolf
Am i missing one?
Thanks
-Myron-Pigna

**Comment by xXKeyleXx** [comment]
What permission plugin do you use? And try to remove the MyPet.user.leash permission.

**Comment by Pigna** [comment]
I use groupmanager for the permissions.
Removed MyPet.user.leash and stilll able to kill my wolf without "Mypet taming" him. It was indeed already tamed with a bone.

**Comment by xXKeyleXx** [comment]
Every time someone has problems with permissions they use GroupManager xD

I tested it with the following permissions and it works fine for me:
    - MyPet.custom.skilltree.Combat
    - MyPet.custom.skilltree.PvP
    - MyPet.custom.skilltree.Utility
    - MyPet.user.command.capturehelper
    - MyPet.user.command.name
    - MyPet.user.command.name.color
    - MyPet.user.command.release
    - MyPet.user.command.respawn
    - MyPet.user.leash.Wolf

The only thing was that I had to restart (not reload) the server to make them work.

**Comment by xXKeyleXx** [comment]
Does it work now?

**Comment by Pigna** [comment]
Seems like its my mistake. I made a global group for the mypet permissions. the group did have the permissions but under permissions and not group inheritance. So my bad and not a problem with the plugin.
