### ISSUE TITLE
MyPet v.1.2.4 Chat Spam Not Complete Fix

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#616]
Hello xXKeyleXx it's not done yet! :smile: 
When i use my portal and it's water - Multiverse Portal
It's said - MyPet can not come to you because there is not enough space - IN MULTIPLE :disappointed:
But sometimes no duplicate remind or chat spam
![2016-01-29_09 37 30](https://cloud.githubusercontent.com/assets/13610530/12696031/7ec61b80-c7bb-11e5-9449-0d98a41266eb.png)
![2016-01-29_09 37 45](https://cloud.githubusercontent.com/assets/13610530/12696032/7ec9dc5c-c7bb-11e5-8a4c-5901c1f5574f.png)
![2016-01-29_09 38 58](https://cloud.githubusercontent.com/assets/13610530/12696033/7ed31f88-c7bb-11e5-90bf-7362111a22f7.png)

**Comment by PinoyLifeCraft** [comment]
w0w Quick Response Author [QRA]

**Comment by xXKeyleXx** [comment]
Were both portals in the same world?

**Comment by PinoyLifeCraft** [comment]
First i am in World then go to Game City where the bug was found after that i go to Sky Block and that's it? Sorry for my English :laughing:
