### ISSUE TITLE
The translations don't work

### ISSUE THREAD

**Issue by EverMineServer** [xXKeyleXx/MyPet#617]
I simply put Mypet 1.2.6 - b778 plugin folder without making changes. 
Here things out if I write /pch:
https://gyazo.com/8be0c67ae2ace49e7ba4abb4e2763835

**Comment by xXKeyleXx** [comment]
Have you tried to download it again or restarted the server?
If you open the jar file with any ZIP programm, is there a locales folder in it?

**Comment by EverMineServer** [comment]
I tried before to put Mypet 1.2.6 - b778 in the plugin floder in my server but the translations don't work, then I've created a simple Spigot server 1.8.8 with only Mypet 1.2.6 - b778 and ProtocolLib 3.6.4 but with the same problem. If i open the jar file there is a locale floder with inside all translations.

**Comment by xXKeyleXx** [comment]
Stange... what language do you have selected on your Minecraft **Client**?

**Comment by EverMineServer** [comment]
If I set my client on Italian language i have this problem but I set my client on English language i haven't problem, i think that the solution is create a file called "MyPet_it.properties" in the locale floder. One problem solved. For another probelm I have to create another issues? (Update problem) From 1.2.1 to 1.2.6 in offline mode.

**Comment by EverMineServer** [comment]
Solved :D

**Comment by xXKeyleXx** [comment]
what was the problem?

**Comment by EverMineServer** [comment]
I deleted the Mypet floder and puted in the plugin floder the new version of Mypet, after i edited the new config with my settings and with Bungeecord UUID mode: offline. Finally i restart my server with my old "My.Pets" and now all work perfectly. :)

**Comment by xXKeyleXx** [comment]
hm.. OK then xD
