### ISSUE TITLE
MyPet v.1.2.6 Pet Can come to you even you are flying

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#621]
If your in the land pet will come to you if you do /pc or /petcall - yes that's right :smile: 
![2016-01-31_07 54 13](https://cloud.githubusercontent.com/assets/13610530/12716747/46ffdd64-c93f-11e5-9b39-ea5271e2429d.png)
After doing /pc or /petcall if you fly and do it again [/pc or /petcall] they can come to you DANGER IF HOLE IN THE FLOOR!
![2016-01-31_07 55 39](https://cloud.githubusercontent.com/assets/13610530/12716790/a594021a-c93f-11e5-96dd-d4cbbdf5736c.png)
But if you are in a higher place 15 blocks
![2016-01-31_08 02 50](https://cloud.githubusercontent.com/assets/13610530/12716888/5ed7ab3c-c940-11e5-8f9f-a90afb6110cc.png)

**Comment by xXKeyleXx** [comment]
If you are less than 15 blocks above the ground the plugin will try to find a safe spot to spawn the pet on. When you are near a hole or cliff the pet may fall to death when it moves but this is not the problem of the plugin when owners risks the life of their pet by calling them...
