### ISSUE TITLE
MyPet-Premium

### ISSUE THREAD

**Issue by FynTiKs** [xXKeyleXx/MyPet#624]
Hi can the plugin MyPet-Premium" to add such a function, which was impossible in a creative to give things, and GUI menu to make a translation into Russian language, in advance I will be grateful

**Comment by xXKeyleXx** [comment]
The only thing I understood was that you want something with a Russian translation but I'm not sure if you want to translate it by yourself or something different.

**Comment by FynTiKs** [comment]
Russian translation of the menus of the graphical interface and creative that it was impossible for them to wear or to give them armor

**Comment by FynTiKs** [comment]
Вы понимайте русский?))

**Comment by xXKeyleXx** [comment]
No sorry I don't understand russian :/

Let's do some simple yes/no questions to find out what you want ;)

1. You know about the rusian translation in Mypet (https://github.com/xXKeyleXx/MyPet-Translations/blob/master/MyPet_ru.properties)
2. You want to help me improve this translation
3. You want to say that some translations are missing

4. You want to disable item interactions with MyPets (like equipping them/open inventory)
5. Your players can't equip their pets

**Comment by FynTiKs** [comment]
1) screen http://prntscr.com/9zg0fw no translation into Russian problem =(
2) link to the plugin description I think you will understand what he's doing http://dev.bukkit.org/bukkit-plugins/sharecontrol/
3) Creative - gm 1, do not wear them things or give them their http://prntscr.com/9zg3xh

**Comment by FynTiKs** [comment]
I hope you understand me but overall a good plugin

**Comment by FynTiKs** [comment]
screen - http://prntscr.com/9zg7ht

**Comment by xXKeyleXx** [comment]
Well I expected some simple yes or no but OK :P

1. These are descriptions of the skilltree, you can change them with the [SkilltreeCreator](https://mypet.keyle.de/doku.php?id=en:skilltreecreator)
2. So you want to disable that players add armor to their pets in creative? if yes: 
 - Enable the extended permissions in the config. 
 - Permission:
   - MyPet.user.extended.Equip

**Comment by FynTiKs** [comment]
screen:
http://prntscr.com/9zgytg
http://prntscr.com/9zgzd5

**Comment by xXKeyleXx** [comment]
Have you enabled the extended permissions in the config?

**Comment by FynTiKs** [comment]
Oh )

**Comment by FynTiKs** [comment]
http://prntscr.com/9zh1c6

**Comment by FynTiKs** [comment]
=(

**Comment by xXKeyleXx** [comment]
I your picture the extended permissions are still disabled...

**Comment by FynTiKs** [comment]
vobshem is not working, what  said =(

**Comment by FynTiKs** [comment]
Permissions:
    Enabled: true
    UseExtendedPermissions: true

**Comment by xXKeyleXx** [comment]
Remove the MyPet.user.extended.Equip permission and it will work fine. Permissions are there to allow  things.

**Comment by FynTiKs** [comment]
Oki

**Comment by xXKeyleXx** [comment]
Does it work now?
