### ISSUE TITLE
MyPet Premium /ptrelease lag

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#627]
How to disable petsave petrelease?
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/12858113/5cd3da84-cc4e-11e5-9e28-f5c122abbecf.PNG)

**Comment by xXKeyleXx** [comment]
NBT or MySQL?

**Comment by xXKeyleXx** [comment]
NBT: Repository.NBT.Pet.SaveOnRemove ?
MySQL: Nope

**Comment by andris155** [comment]
I use default storage settings.
  Repository:
    Type: NBT
    ConvertFrom: '-'
    NBT:
      AutoSaveTime: 60
      Pet:
        SaveOnAdd: true
        SaveOnUpdate: true
        SaveOnRemove: true
      Player:
        SaveOnAdd: true
        SaveOnUpdate: true
        SaveOnRemove: true
      Backup:
        Active: true
        SaveInterval: 1440
        DateFormat: yyyy_MM_dd_HH.mm
    MySQL:
      Database: mypet
      Host: localhost
      Password: ''
      User: root
      Port: 3306

**Comment by xXKeyleXx** [comment]
If you really want to reduce timings I would suggest to use MySQL as backend

**Comment by andris155** [comment]
ok. Thanks.
