### ISSUE TITLE
Rabbit food issues.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#628]
Hi!
I have a problem with the Rabbit pettype. In the config file the food for him is Carrot (Id:141) and Rose Red (Id:38). But when I type in the /pettype Rabbit command, it says that for food he needs Air and Rose Red. Also, I am not able to change anything in the pet-config.yml file, because the plugin overwrites it every time I reload/restart the plugin/server. So I am unable to change anything :/ .
I hope it's a bug, and not a "feature", because it's not that great for me :/
![2016-02-06_16 13 09](https://cloud.githubusercontent.com/assets/14863100/12867092/0b339f08-cced-11e5-8be7-a0a09c1ccf52.png)
![kepkivagas](https://cloud.githubusercontent.com/assets/14863100/12867093/10015b2e-cced-11e5-9099-3f3fbf63d523.PNG)

**Comment by xXKeyleXx** [comment]
If you are not using MyPet-Premium please use the latest devbuild: https://build.keyle.de/job/MyPet/
If you use MyPet-Premium you have to wait until I release the next version.

**Comment by Kronox12** [comment]
All right, I will wait then. Thank you for the fast response :D
