### ISSUE TITLE
Users are able to duplicate pets

### ISSUE THREAD

**Issue by PabloMA98** [xXKeyleXx/MyPet#630]
With the command "/pr pay", users can create duplicates of their pets.

![2016-02-08_19 21 12](https://cloud.githubusercontent.com/assets/11474413/12894802/353d1b32-ce99-11e5-9085-38b5af6eb1e5.png)

**Comment by Kronox12** [comment]
Don't try this with the EnderDragon as a pet :x

**Comment by Kronox12** [comment]
The "fake" mypets go away if you unload the chunks, or if you manage to kill it somehow.
