### ISSUE TITLE
EnderDragon problems.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#631]
1.Problem: I cannot see the Ender Dragon in the Skilltree editor, no matter what I do. I made a copy of my existing Wither skilltree, renamed it to enderdragon.st, and it works, but it would be cool to edit it in the editor.
2.Problem: I cannot ride the Ender Dragon. It has the Ride skill, but I cannot find the hitbox, so I cannot ride it.

**Comment by xXKeyleXx** [comment]
To 2.: I need to investigate further why the players can't interact with enderdragons. But as the dragons are not my main priority this may take some time :/

**Comment by Kronox12** [comment]
No problem, it can wait :D
