### ISSUE TITLE
EnderBreath skill

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#632]
When the 1.9 will come out, and the MyPet plugin will be on 1.9, I think it would be cool, if there were a new skill called "EnderBreath" (or something like that) using the new EnderDragon attack.

**Comment by Kronox12** [comment]
Possible date of implementation for it? :D Or this isn't in priority yet?

**Comment by xXKeyleXx** [comment]
I want to rewrite the skill system first and I have another project I need to finish first.

**Comment by Kronox12** [comment]
Understood :)
