### ISSUE TITLE
Again lose all whole db pet....

### ISSUE THREAD

**Issue by xion87** [xXKeyleXx/MyPet#633]
I lost for the 4° times in 3 year my pet database... yeah i am using bungeecord, and 1.8.8...  i think the database is not stable... no errors... i dont have logs enabled for mypet...

**Comment by xXKeyleXx** [comment]
If you want help, create a normal ticket and don't attack me with your passive aggressive behavior.
I don't like it that you have problem too but that is no reason for that!

And next time try to include helpful data:
- MyPet Build: #
- Bukkit/Spigot Build: #
- installed plugin
- ...
