### ISSUE TITLE
Configuration Question - Premium

### ISSUE THREAD

**Issue by adnurmal** [xXKeyleXx/MyPet#635]
I noticed that with a fresh install of the plugin, it generates 2 configuration files:

- config
- pet-config

Do both have to be setup accordingly, as a majority (everything?) in the config, is listed in the pet-config. The only difference I see is the optional pet type and leash flag option

**Comment by xXKeyleXx** [comment]
fixed in 036873c0d2d1d82a2b7bb0c5e0c34cdba33a3abd
I will release a new Premium version in the next few hours.

**Comment by Kronox12** [comment]
Yaaay! :D
