### ISSUE TITLE
Message Error with plugin

### ISSUE THREAD

**Issue by Gabrielanderline** [xXKeyleXx/MyPet#639]
Hi, my name is Gabriel, i'm a pluginner (Not developer),  I installed on my server all 2 versions of the plugin is that the 1.2.8 1.2.9 but there are an error when writing the commands, exactly the response of the message when you type a command, and makes "Message.Command .Help.MoreInfo "and other similar errors. Is a  mistake that you did by mistake or do I go in the config file to set something? Thanks again
P.S: I know mypet from 1.5.2 and never gave these problems! 
(Sorry for my english, i'm italien and i'm learning)

Look to the picture: http://imgur.com/p4nx29G

**Comment by xXKeyleXx** [comment]
It seems that the locale files were not loaded properly. Have you tried to stop and start the server again? Where have you downloaded the file? Do you have your own locale files installed?

**Comment by Gabrielanderline** [comment]
Yes, I have already tried to restart the server, but it doesn't work, I tried to put it alone, even with vault but nothing, I downloaded from the official website:
http://dev.bukkit.org/bukkit-plugins/mypet/files/45-mypet-1-2-9-for-mc-1-8-8/

**Comment by xXKeyleXx** [comment]
Are the locale files included into the jar file? (open/extract MyPet.jar with any ZIP program and look into the locale folder if there are any files in there)

Could you upload the MyPet.log file for me please.

**Comment by Gabrielanderline** [comment]
[MyPet log.txt](https://github.com/xXKeyleXx/MyPet/files/129707/MyPet.log.txt)

Look here

**Comment by Gabrielanderline** [comment]
yes, there are plugin.yml and these folder: "de","images", licences", locale", "META-INF", "skilltrees"

listen, i upload to mediafire my mypet-1.2.9 jar file

**Comment by xXKeyleXx** [comment]
Nah I found the problem. Will upload a fix soon.

**Comment by Gabrielanderline** [comment]
ok, thanks again

**Comment by xXKeyleXx** [comment]
BTW are you interested in translating MyPet to Italian?
