### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Endergirl2900** [xXKeyleXx/MyPet#647]
Hello 

MyPet isnt working on my Spigot 1.8 version. I do get a file named MyPet but the file inside like locale, logs and skills tree are all empty. 

could you help me? 

Greetings Leony

**Comment by xXKeyleXx** [comment]
Which Spigot version is it exactly? Is there anyting in the server log that could explain why this happens?

**Comment by Endergirl2900** [comment]
Hey Keyle

Its a 1.8 version… i seen your version is 1.8.8 :(

Greetings

Leony

**Comment by xXKeyleXx** [comment]
Every MyPet version only works under one Spigot/Bukkit version :/

**Comment by Endergirl2900** [comment]
oh ok… :( but what can i do then???

**Comment by xXKeyleXx** [comment]
Update your server to 1.8.8 or look here for a matching version: http://dev.bukkit.org/bukkit-plugins/mypet/files/
