### ISSUE TITLE
config

### ISSUE THREAD

**Issue by PikachuEXE** [xXKeyleXx/MyPet#648]

**Comment by PikachuEXE** [comment]
crap wrong button D:
Sorry

**Comment by xXKeyleXx** [comment]
@PikachuEXE has stopped working.

**Comment by PikachuEXE** [comment]
lol
Actually there is an issue with ST editor but I workaround it by another editor :P

**Comment by xXKeyleXx** [comment]
Then create a new ticket with your issue.
