### ISSUE TITLE
Pets loose their xp

### ISSUE THREAD

**Issue by ExtremoDuro** [xXKeyleXx/MyPet#652]
Some pets loose their xp, for example from lvl 30 they drop to lvl 1.

They cause of the problem can be the exp.js --> https://github.com/ExtremoDuro/Javascript-levels

I found an error in the logs --> http://pastebin.com/dvdTw2CB

**Comment by xXKeyleXx** [comment]
Line 48:
`return (level - 1)(level - 7);`

you need to put a operator between `(level - 1)` and `(level - 7)`

**Comment by ExtremoDuro** [comment]
That should be a multiplication .... I am so stupid.
Thanks :) On jue., feb. 18, 2016 at 2:40 p. m., Sebastian Comans < notifications@github.com [notifications@github.com] > wrote:
Line 48:
return (level - 1)(level - 7);

you need to put a operator between (level - 1) and (level - 7)

—
Reply to this email directly or view it on GitHub
[https://github.com/xXKeyleXx/MyPet/issues/652#issuecomment-185723370] .[https://github.com/notifications/beacon/AMa2MrMGgQ1oECnjnXjI9myU95YS6Tz8ks5plcEjgaJpZM4HdBUG.gif]

**Comment by xXKeyleXx** [comment]
You're welcome :P
