### ISSUE TITLE
[Feature Request][MyPet-Premium 1.3.0]

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#653]
We have a way to buy pets on our server using a web market. The thing is, if a player has reached his pet limit, and he buys another pet, he cannot switch between the pets. We use the /petadmin create -f PlayerName Pet command, so it doesn!t take in consideration, that the player has already reached his limit.

My question is, could it be possible, that the player can switch between his mypets, even if he already reached his limit?

That way he wouldn't be able to capture more pets with the /pch (because the plugin shouldn't allow him to use that, if he reached his limit), BUT he can buy more pets if he wanted to.

A way to make it possible: The plugin checks the limit. If he reached it, he cannot use the /pch anymore, BUT he would be able to use the /pswitch or /pswitch store commands.

**Comment by Kronox12** [comment]
#646 I've already asked for it, but it seems like it is half done. The plugin checks the limit, and prevents the player from using /pch if he has more pets than his limit (or already reached it), But he still cannot switch between pets if he reached his limit/has more than his limit.

**Comment by xXKeyleXx** [comment]
It was like that before I made the changes of #646... I think I will add a permission that allows players to bypass it when they are over the limit.
