### ISSUE TITLE
[Fixed][Urgent Huge Bug] MyPet-Premium[1.3.1] MyPet Commands 

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#654]
Players are unable to use the mypet commands. Whenever a player types in a command (ex: /peti, /petbeacon, etc.) he gets a message saying that He cannot do that right now. The player has the
- MyPet.user.command.trade.offer
- MyPet.user.command.trade.recieve
- MyPet.user.leash.*
- MyPet.user.command.switch.limit.0
- MyPet.user.command.switch
permissions. And also some extended ones for /petb in different worlds, but I don't have this problem with this one. This is urgent, We cannot go back to a prev. version, because there are other bugs.

**Comment by Kronox12** [comment]
Turns out that the problem was with the extended permissions.

**Comment by xXKeyleXx** [comment]
Please stop adding tags to the title, this is what labels are for. And I rate how urgent the issue is.

**Comment by Kronox12** [comment]
sorry :/

**Comment by xXKeyleXx** [comment]
No problem just wanted you to know ;)
