### ISSUE TITLE
Bug with pets and items

### ISSUE THREAD

**Issue by PabloMA98** [xXKeyleXx/MyPet#655]
1. A player give items to a mob (like armors, head, tools, etc.), I have tested it with a zombie
2. Various players attack the mob with a lead
3. The mob doubles for each player in form of pet
4. Players release their pets and obtain one duplicate of the items

**Comment by xXKeyleXx** [comment]
Do they need to hit the pet at the same time?

**Comment by PabloMA98** [comment]
Yes,

**Comment by xXKeyleXx** [comment]
OK I will look into it

**Comment by xXKeyleXx** [comment]
BTW you can disable it until it's fixed: RetainEquipmentOnTame
