### ISSUE TITLE
Skilltree creator Doesn't work

### ISSUE THREAD

**Issue by bapt59** [xXKeyleXx/MyPet#664]
Hello ! i think you can help me beacause you created the plugin .
So , i downloaded the plugin , but there is no Skilltree/Level creator after downloading it and lauching my server (Exepted a File named "My").
So , please , can you , at least , post a link to download it

**Comment by zerafox** [comment]
You have to launch the .jar file using Java on your personal Computer.
It doesn't install a separate program or anything with the plugin, the
skilltree creator is the plugin.

Right click the mypet.jar and "run with java"

**Comment by bapt59** [comment]
Thx a lot !
