### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by KillerBruno** [xXKeyleXx/MyPet#665]
Hi!! i´m creating a server and the users order me mypet plugin. Can you create 1.7.10 version of MyPet?. I can donate money but you post the version first!

**Comment by zerafox** [comment]
There are already versions of MyPet for 1.7.10 servers.
http://dev.bukkit.org/bukkit-plugins/mypet/files/
Last I checked, the 1.2.0 version worked on 1.7.10 Minecraft.

Updates for old versions, or creations of new versions for older Minecraft
servers won't be done. That takes time away from keeping up with current
Minecraft releases, and once you do it for one old version, you have to do
it for all of them.

Check out that link for a version that will work on your server.

**Comment by xXKeyleXx** [comment]
1.7.10 support for the latest version is coming soon.
