### ISSUE TITLE
BabyPet Request

### ISSUE THREAD

**Issue by gravehq** [xXKeyleXx/MyPet#667]
Hello it woud be soooo awsome if it will possible to have
Baby-Entitys as pets..

- Florian

**Comment by zerafox** [comment]
You can already have baby entities as pets.
Baby forms of all mobs that can be babies, can be tamed as babies. As well
as an admin command to give pets of the form.

**Comment by gravehq** [comment]
Ând how to do this?

**Comment by zerafox** [comment]
Commands: http://mypet.keyle.de/doku.php?id=en:commands#mypet_commands
Taming, just make sure the mob you're taming is a baby... It's that simple..

**Comment by gravehq** [comment]
But we sell the Pets on the Shop with Commandblocks? Is this possible to?

**Comment by zerafox** [comment]
You are running commands, use the command to make it a baby.
See my above comment.

**Comment by gravehq** [comment]
I dont find a command for Baby :(

**Comment by zerafox** [comment]
I provided you with the command section you need to look for.

/petadmin

Read that section carefully, and give it a try in-game to see what available parameters there are for you to use for the various pets...

**Comment by gravehq** [comment]
Ôkay thanks for your Help!
