### ISSUE TITLE
Most mobs die without becoming pets

### ISSUE THREAD

**Issue by FatherWh0** [xXKeyleXx/MyPet#674]
I've just installed MyPet and am testing it out. I am having trouble making a MyPet. I have made a few but 19 out of 20 mobs get punched to death without become a pet. I haven't been able to sort out why I occasionally get a pet but most die of lead punch death.

Using MyPet 1.3.2 snapshot
version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**edit**

After some testing I've been able to narrow down the problem. If 1.3.2 snapshot creates the folder and files mobs usually die without becoming pets. If 1.3.1 creates the files then 1.3.2 works fine.
Also, with some trial-and-error I've determined if 1.3.2 creates the files, then 1.3.1 is launched it works. Also then 1.3.2 works with those files. Apparently 1.3.1 fixes whatever is wrong with this files. I hope this info is useful to the devs.

**Comment by xXKeyleXx** [comment]
Are there any errors in the logs?

**Comment by FatherWh0** [comment]
No. The console is silent about the issue.

**Comment by xXKeyleXx** [comment]
Some of them have different requirements before they get your MyPet. Wolves for example need to be tamed. But this can be changed in the config. Maybe this is your problem.

**Comment by FatherWh0** [comment]
All mobs were failing equally. Reverting back to 1.3.1 fixed the issue. The problem only occurs if the 1.3,2 dev build creates the MyPet folder and files on a fresh install.

**Comment by xXKeyleXx** [comment]
I can't reproduce this behavior. Could you let it generate with 1.3.2 and upload the MyPet folder for me.
And please try the latest dev build.

**Comment by FatherWh0** [comment]
Your most recent dev build fixed the issue. I can no longer reproduce it with the current version.

**Comment by xXKeyleXx** [comment]
Sounds great
