### ISSUE TITLE
ordinary members can not get a pet!

### ISSUE THREAD

**Issue by Zig0to** [xXKeyleXx/MyPet#677]
membros comuns nao conseguem pegar um pet!
eles batem com o lead, mas o mob morre ao inves de ser adestrado.
vou enviar a config.yml

if there is something wrong could pass me the commands already arranged?
only adiministradores the server can pick up pets
ja members can not

thanks in advance

**Comment by xXKeyleXx** [comment]
I would guess it's a permission problem:

https://mypet.keyle.de/doku.php?id=en:permissions

**Comment by Zig0to** [comment]
I would have to write permission to the server adm?
there would release pro personnel?

**Comment by Zig0to** [comment]
/MyPet.user.command.capturehelper

**Comment by xXKeyleXx** [comment]
You said your admins were able to get a pet. What permissions do you grant to your normal users? Do you use a permission plugin at all?

**Comment by Zig0to** [comment]
no, no permission use at all
I play with a group of friends and my server and all released
q pus was home and pets
only that
the homes I could release
however the pets just like I can adm

**Comment by xXKeyleXx** [comment]
Then disable the permissions in the config: `Permissions.Enabled` -> `false`

**Comment by Zig0to** [comment]
relationship with the permission, the only thing q has the codes it is this UseExtendedPermissions: false
You do not have the one you showed
it's the same thing?

**Comment by xXKeyleXx** [comment]
The Permission I mean should be directly above the UseExtendedPermissions one.

**Comment by Zig0to** [comment]
As well ?
in -game chat ?

**Comment by xXKeyleXx** [comment]
???

**Comment by Zig0to** [comment]
like this?

Permissions:
    Permissions.Enabled: false
    Enabled: true
    UseExtendedPermissions: false

**Comment by xXKeyleXx** [comment]
Permissions:
Enabled: false
UseExtendedPermissions: false

**Comment by Zig0to** [comment]
work, our Thanks man, thanks even
sorry to disturb you
I am new at this
Thank you so
hug
