### ISSUE TITLE
Error spam when a player joins with spigot 1.9

### ISSUE THREAD

**Issue by FatherWh0** [xXKeyleXx/MyPet#683]
When a player joins my 1.9 test server the following error occurs:
[19:33:33] [Server thread/ERROR]: [MyPet] Unhandled exception occured in onPacketSending(PacketEvent) for MyPet
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$13.getSpecificValue(BukkitConverters.java:699) ~[ProtocolLib.jar:3.6.5-b222]
Using MyPet 1.3.2 snapshot Build #862.
Spigot 1.9 Build #49

**Comment by xXKeyleXx** [comment]
Yeah I got that too but not all the time. Maybe 2 out of 5 times and a server restart fixed it most of the time. I'm not sure if it's a protocol lib problem or not.

**Comment by FatherWh0** [comment]
The event above was happening on my test server. When I brought my live server up on 1.9 today something different occurred. When I joined the same error spam occurred but the server shut down. I tried repeatedly but with the same results. Unfortunately I had to remove MyPet to bring my server up. Here is the complete error.

http://pastebin.com/W2T3tF5x

I'm really hoping you can help with this. I am hoping to use Mypet Premium to replace the now abandoned Echopets.

**Comment by FatherWh0** [comment]
You were right. ProtocolLib 3.7.0 beta fixed it.
