### ISSUE TITLE
Mypet /pcst /petchooseskilltree

### ISSUE THREAD

**Issue by Killthuzad** [xXKeyleXx/MyPet#684]
Hi I am having issues with /pcst everytime our players or admins try to use this command it says this pet has no skills.

[MyPet.txt](https://github.com/xXKeyleXx/MyPet/files/159638/MyPet.txt)

**Comment by xXKeyleXx** [comment]
What does the "/petskilltree default" prints when you use it from the server console?

**Comment by Killthuzad** [comment]
With further investigation I found when I first installed mypet on my server the skilltree folder was empty so I saw that you can customize the skilltree with the jar file so I created a temporary one called ride for players to use but I really miss the default pet skilltree and I wish I was smart enough to recreate it but I am not I want to buy the premium version of my pet but I am afraid to spend my money if skilltree isn't working that is my dilemma

**Comment by Killthuzad** [comment]
05.03 15:44:04 [Server] INFO [MyPet]    Ride
05.03 15:44:04 [Server] INFO [MyPet] ----- MyPet Skilltrees for: default

is the prints

**Comment by xXKeyleXx** [comment]
Delete the Skilltrees folder and let the plugin recreate the default Skilltrees. No premium required.

**Comment by Killthuzad** [comment]
Wow you are a genius I will support you by getting premium tonight ty so much!!!
