### ISSUE TITLE
Not able to use plugin. Need Help

### ISSUE THREAD

**Issue by cademullen** [xXKeyleXx/MyPet#685]
Im trying to get this plugin working, but I got this error. Need help.

03-05-2016 02:43 [INFO] [MyPet]    A: MyPig{owner=captan100, name=Pig, exp=0.0/7.0, lv=1, status=Despawned, skilltree=-, worldgroup=default, saddle=false, baby=false}
03-05-2016 02:43 [INFO] [MyPet]    I: InactiveMyPet{type=Pig, owner=captan100, name=Pig, exp=0.0, health=20.0, worldgroup=default}
03-05-2016 02:43 [INFO] [MyPet] (L) de.Keyle.MyPet.entity.types.pig.EntityMyPig is no valid MyPet(Entity)!
03-05-2016 02:43 [WARNING] [MyPet] de.Keyle.MyPet.entity.types.pig.EntityMyPig is no valid MyPet(Entity)!
03-05-2016 02:46 [INFO] [MyPet] No Economy plugin found. Economy support not enabled.
03-05-2016 02:47 [INFO] [MyPet] (L) de.Keyle.MyPet.entity.types.pig.EntityMyPig is no valid MyPet(Entity)!
03-05-2016 02:47 [WARNING] [MyPet] de.Keyle.MyPet.entity.types.pig.EntityMyPig is no valid MyPet(Entity)!
03-05-2016 02:47 [INFO] [MyPet] (L) de.Keyle.MyPet.entity.types.pig.EntityMyPig is no valid MyPet(Entity)!
03-05-2016 02:47 [WARNING] [MyPet] de.Keyle.MyPet.entity.types.pig.EntityMyPig is no valid MyPet(Entity)!

Console error.http://pastebin.com/rdcVfFrv

**Comment by xXKeyleXx** [comment]
MyPet version? Server version?

**Comment by cademullen** [comment]
MyPet version 1.2.0. and server version 1.7.10

**Comment by xXKeyleXx** [comment]
This version is more than a year old. I can't support these old versions.  Besides that the latest dev builds support 1.7.10, you should try them out.
