### ISSUE TITLE
Paper problems 1.9

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#688]
I recently updated my server to 1.9. I'm using Paper instead of Spigot. I'm also using Mypet-Premium-1.3.2-BETA5.
The problem is, that the plugin is not responing to the commands typed in by players, or from the console. I don't even get an error message or anything. It's just doesn't care.
I don't know if the plugin supports Paper, but I think it doesn't.
Any ideas?

(Also, in the newest 1.8.8 version of MyPet Premium the /petrespawn auto command did not work for me. If a player typed in the command, and even if it was Enabled, the player still needed to wait till his pet respawns.)

**Comment by xXKeyleXx** [comment]
It should work with paper but I can't do much right now until I'm back home.

**Comment by Kronox12** [comment]
Allright, it can wait :)

**Comment by xXKeyleXx** [comment]
I'm on vocation :P I'm back on the 12th.

**Comment by Phreag** [comment]
I)m also using PaperSpigot, works fine, Paper is not the reason for that.

**Comment by andris155** [comment]
PaperSpigot = 1.8 
Paper = 1.9

**Comment by Phreag** [comment]
Sorry, was not clear about the name change. Using Paper 1.9 currently, works fine ;)

**Comment by Kronox12** [comment]
I think I found the problem.

http://pastebin.com/EQPwzT7U

**Comment by xXKeyleXx** [comment]
It depends on the Skilltree setup so it's a bug.

**Comment by Kronox12** [comment]
I tried to load it with the .json type, even more error appeared in the console.

**Comment by Kronox12** [comment]
Thank you! :D
