### ISSUE TITLE
Unable to increase Pet Level Cap

### ISSUE THREAD

**Issue by PheoZen** [xXKeyleXx/MyPet#690]
The level cap on config is not working.

I try to increase max level in skill tree editors but it struck at 100

I also try to unmark the maximum level, but it still not worked

**Comment by zerafox** [comment]
Please provide the config section for you level-cap.

And if I'm understanding correctly you tried to provide more levels than 100 in skilltrees? Is this correct?

**Comment by PheoZen** [comment]
I mean when I try to set the maximum level on the skill tree.

Then save it, it will automatically set to maximum level at 100.

I need to set the maximum level more than 100

**Comment by xXKeyleXx** [comment]
I think that the max level is a fixed value in the Skilltree creator... I need to fix that...
