### ISSUE TITLE
GrowUpItem

### ISSUE THREAD

**Issue by L0ugs** [xXKeyleXx/MyPet#691]
Hello,  Can you explain what is growup and how it works  
Horse:
      HP: 20.0
      Speed: 0.3
      Food:
      - 353
      - 296
      - 260
      LeashFlags: Tamed
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
      **GrowUpItem: 297**

thx (nice plugin) ! :D

**Comment by zerafox** [comment]
"Grow Up" is when turning a baby pet into the adult version.
If you had tamed a say a baby horse, but decided you don't want it to be a
baby anymore.. You'd use the "Grow Up" item on the pet to make it an Adult
Horse instead.

Although there is no going back to a baby version after you've done this.

**Comment by L0ugs** [comment]
Ok thank you that's what I thought! I just passed because it must sneak and click on the pet! Thank you very much and sorry for my bad english :p

**Comment by zerafox** [comment]
You're very welcome. :)
