### ISSUE TITLE
Pets wont attack

### ISSUE THREAD

**Issue by xkitox** [xXKeyleXx/MyPet#692]
For some reason I cant get my pet to attack the mobs I'm fighting.  Any ideas?

**Comment by zerafox** [comment]
Does the pet have a damage trait?

**Comment by xkitox** [comment]
Im not 100% sure what that means, but if youre asking if it's an aggressive mob, it is.

**Comment by zerafox** [comment]
The skilltree that the pet has, does it have the Damage Trait?
If the pet does not have a damage trait, it will not attack mobs, at all.

Use the command /pinfo
or I think the command /pskill will also tell you what skills the pet has.

**Comment by xkitox** [comment]
Thanks much, I got it :D
