### ISSUE TITLE
Errors for days!  Console spammed with errors on player join and plugin use.

### ISSUE THREAD

**Issue by xkitox** [xXKeyleXx/MyPet#693]
http://pastebin.com/XK9w0B47  
I get tons of errors whenever someone joins or does something related to the plugin.  Is it because I'm using the 1.3.2 SNAPSHOT dev build?  Do I need to have the premium .jar to use it on Spigot 1.9?  Thanks!

**Comment by xkitox** [comment]
I just downloaded the premium version, same issues :(

**Comment by xkitox** [comment]
Just got the premium version, still getting errors =/

**Comment by xXKeyleXx** [comment]
Duplicate to #683
