### ISSUE TITLE
region flag: creative -  item

### ISSUE THREAD

**Issue by ds32** [xXKeyleXx/MyPet#697]
Join in the creative region, 
give pet a weapon\items, 
leave the region, 
/ Petrelease - and get things.

**Comment by xXKeyleXx** [comment]
Where do these regions came from?

**Comment by ds32** [comment]
WorldGuard: /region flag CreativeCity game-mode CREATIVE

**Comment by xXKeyleXx** [comment]
There is a config option for that, please try of that works.
