### ISSUE TITLE
1.9 - Only ops can use pet storage

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#700]
Only OPS can use pet storage

All players have these permissions:

    - mypet.npc.storage.interact
    - mypet.npc.storage.max.5

It says: "You are NOT allowed to use this"

**Comment by xXKeyleXx** [comment]
MyPet NPC dev builds?

**Comment by tara81** [comment]
Build #104 (Mar 4, 2016 2:43:51 PM)

**Comment by xXKeyleXx** [comment]
I changed the permission in the latest dev builds. Try removing the ".interact"

**Comment by tara81** [comment]
Thank u will test =)

On Sat, Mar 12, 2016 at 10:09 AM, Sebastian Comans <notifications@github.com

**Comment by tara81** [comment]
It works :D

**Comment by tara81** [comment]
Btw You should probably document the permission got changed on the mypetnpc page for 1.9+ versions

**Comment by xXKeyleXx** [comment]
yeah when I release it on Spigot I will do that ;)
