### ISSUE TITLE
Pets can push players in 1.9

### ISSUE THREAD

**Issue by triarry** [xXKeyleXx/MyPet#701]
Possibly needs a config toggle or fix, if the event is already made to prevent mob pushing.

**Comment by Phreag** [comment]
Thats not a MyPet-Bug, its a 1.9 Feature. 
In 1.9 Players can push each other ans Mobs can also Push each other and Players.

**Comment by xXKeyleXx** [comment]
I disabled the collisions for the entities but players still get pushed away... maybe the Minecraft client does this too.

**Comment by xXKeyleXx** [comment]
I tried everything I know but I can't fix this problem. It must be a clientside problem.
