### ISSUE TITLE
Since 1.9 ...

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#702]
Using: MyPet-Premium 1.3.2-BETA-5
Pets ranged attacks are not working ;(

Ranged snowball
Ranged witherskull
Ranged Fireball

dont work.

Also zombies spazz out and look like they are on crack and jittery.
Also, sometimes when a players zombie pet dies, they lose their equipped sword , but it duplicates 9 times.

**Comment by tara81** [comment]
Some errors, probably not related to this . Not sure.

http://pastebin.com/mmv3kheC
http://pastebin.com/hXqsXDE6

**Comment by xXKeyleXx** [comment]
all these problems should be fixed. I will upload a new beta version soon
