### ISSUE TITLE
1.9 /pcst menu bug.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#704]
Don't mind the text, it's Hungarian.
![2016-03-14_16 07 34](https://cloud.githubusercontent.com/assets/14863100/13747038/088dda50-e9ff-11e5-8246-7eb629183dbf.png)
![2016-03-14_16 07 36](https://cloud.githubusercontent.com/assets/14863100/13747039/08915950-e9ff-11e5-905a-6a7a16856358.png)
The problem is, that the Wither (Or any custom, mob specific) skilltree is not visible.
I'm using Optifine with the LARGE GUI setting, my monitor is 1920x1080, 21,5".

**Comment by xXKeyleXx** [comment]
There is nothing I can do :/ it's a Minecraft Problem. You can add some more lines instead of one long tho.

**Comment by Kronox12** [comment]
I've got an idea. Thank you! :D
