### ISSUE TITLE
1.9 Wither pet duel problem.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#705]
Wither pets does not seem to duel, even if they have the /petb duel selected for behavior.

**Comment by xXKeyleXx** [comment]
Works fine for me.

**Comment by Kronox12** [comment]
I'll test it again then.

**Comment by zerafox** [comment]
Double check that the Wither has a Damage Trait in their skilltree

**Comment by Kronox12** [comment]
It has. At LvL 4.

**Comment by Kronox12** [comment]
Nvm. It was a tiny problem with /petadmin exp. The command wasn't executed perfectly xd.
