### ISSUE TITLE
/petrespawn auto

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#706]
Doesn't work. It says that the Auto Petrespawn is enabled, but the pet still needs to wait x amount of  time to respawn. The owner has enough money for it.

**Comment by xXKeyleXx** [comment]
It works fine for me. Maybe the minimal respawn time is bigger than the actual respawn time.

**Comment by Kronox12** [comment]
Respawn:
    Time:
      Default:
        Factor: 5
        Fixed: 0
      Player:
        Factor: 5
        Fixed: 0
    EconomyCost:
      Fixed: 0.0
      Factor: 1.0

**Comment by xXKeyleXx** [comment]
if the value is higher than the actual respawn time it will not work

**Comment by Kronox12** [comment]
I'm confused now. On my test server it works perfectly fine, but on the Bungee-Spigot server it doesn't. I use the same config on both servers.
Here is a pic. from my test server:
![2016-03-15_19 03 57](https://cloud.githubusercontent.com/assets/14863100/13786590/0a45fcfa-eae1-11e5-833f-8379f9d81901.png)
1. line: My pet is killed by a Spider.
2. line: He will respawn in 5 seconds.
3. line: The respawn fee has been payed.
4. line: My pet respawned.
This happens when I enable /pr auto (without giving any number after it) on my test server.
But on the main server it only goes to the 2nd line when I use /pr pay.
However, the /pr pay still works. I'm confused :x

**Comment by xXKeyleXx** [comment]
Please do
/petrespawn auto 1

and next time please make the screenshot in english ;)

**Comment by Kronox12** [comment]
![2016-03-15_19 55 41](https://cloud.githubusercontent.com/assets/14863100/13788586/ffa7c00a-eae8-11e5-9323-19f383e3e58c.png)
![2016-03-15_19 55 57](https://cloud.githubusercontent.com/assets/14863100/13788587/fface120-eae8-11e5-8c80-c1d7a9d7ef3c.png)
Test server, using /petrespawn auto 1.

**Comment by Kronox12** [comment]
![2016-03-15_19 58 13](https://cloud.githubusercontent.com/assets/14863100/13789437/a4f933c4-eaec-11e5-8acb-dd621c45a373.png)
(/petrelease auto 1)
![2016-03-15_19 58 28](https://cloud.githubusercontent.com/assets/14863100/13789442/a92c1740-eaec-11e5-81d1-b5a26e8b45ca.png)
(The next picture only showed up,when I used the /pr pay command)
![2016-03-15_19 59 15](https://cloud.githubusercontent.com/assets/14863100/13789444/ac7f2b94-eaec-11e5-8bca-94a972c1aa05.png)
![2016-03-15_19 58 41](https://cloud.githubusercontent.com/assets/14863100/13789448/af9871a0-eaec-11e5-8748-6bcd54bc1c45.png)
This was on the main server.

**Comment by xXKeyleXx** [comment]
Ok I think it's permission problem. The plugin checks the wrong permission.
- MyPet.user.respawn

**Comment by Kronox12** [comment]
I'll test it ASAP.

**Comment by Kronox12** [comment]
It's fixed now :D Thanks! :)
