### ISSUE TITLE
Mypet error in the console.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#709]
![image](https://cloud.githubusercontent.com/assets/14863100/13759922/311b7d76-ea39-11e5-8156-ee87eeb35742.png)

I was just emptying my inventory (I was in creative), so I shift-clicked the X button in the creative menu and This happened. It's only showing in the console, I haven't found any problems with it while I was playing in-game.

**Comment by xXKeyleXx** [comment]
MyPet doesn't even listen to this packet O.o

**Comment by andris155** [comment]
Update Protocollib latest dev.: http://ci.shadowvolt.com/job/ProtocolLib/
