### ISSUE TITLE
 MyPet-Premium 1.3.2-BETA-7 bug (shift)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#710]
https://www.youtube.com/watch?v=gnFpUm6n3jw&feature=youtu.be

**Comment by xXKeyleXx** [comment]
I have no clue what the problem is here

**Comment by andris155** [comment]
old pets bug (?)

**Comment by xXKeyleXx** [comment]
I watched the video but I have no clue what the bug might be...

**Comment by xXKeyleXx** [comment]
It works fine for me.
