### ISSUE TITLE
mypet npc not working

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#717]
cant get mypetnpc Build #107 (Mar 14, 2016 11:55:01 AM)  to work with 
mypet premium 1.3.2-BETA-8 .

**Comment by xXKeyleXx** [comment]
I changed the permission node from `MyPet.npc.storage.interact` to `MyPet.npc.storage`

**Comment by xXKeyleXx** [comment]
In the next release of MyPet I will change most permission nodes.

**Comment by tara81** [comment]
it was actually the release you put out on march 13th for mypet premium. After i put this ticket i tried the march 14th version and mypetnpc worked properly.  Since 1.9 I have to remake my citizen npc to have the traits every time I update mypet now .

**Comment by xXKeyleXx** [comment]
Do they lose the trait? How do you update your plugins?

**Comment by tara81** [comment]
I have no idea if they lose the trait .  I don't know the command to view
npc traits.  But I do have to remake the npc every update since 1.9.  Its
something minor, but I thought I'd let ya know.

On Wed, Mar 16, 2016 at 12:00 PM, Sebastian Comans <notifications@github.com

**Comment by xXKeyleXx** [comment]
Hm that's strange... I update VERY often and it works fine for me :/

**Comment by tara81** [comment]
yeah , perhaps its the citizens version I am on.  I will update u if anotehr citizens versions fixes this :D
