### ISSUE TITLE
MyPet new potion nbts

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#721]
MyPet not support new potion, and potion arrow nbts. (pet inventory)
![12596202_1029644470442425_765296724_n](https://cloud.githubusercontent.com/assets/8324198/13814276/e664887e-eb85-11e5-9c5c-fa5944aeaf7c.jpg)

**Comment by andris155** [comment]
not a bug, this is on old potion from 1.8

**Comment by xXKeyleXx** [comment]
Just tested it :P and yep it works fine.

**Comment by andris155** [comment]
:+1:

**Comment by xXKeyleXx** [comment]
what about #710 ?
