### ISSUE TITLE
Battlearena integration

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#723]
Using mypet premium 

    BattleArena:
      DisablePetsInArena: true

Pets still go into games

I cannot find a permission to negate pets from joining certain worlds (multiworld support) either..

**Comment by xXKeyleXx** [comment]
What version of BattleArena do you use?

There are no permissions. see this article: https://mypet.keyle.de/doku.php?id=en:multiworld

**Comment by tara81** [comment]
R: BattleArena v3.9.10.5 for 1.8

**Comment by xXKeyleXx** [comment]
That's strange, it works fine for me. Pets are removed when a player enters an arena and /pc isn't allowed either.

![2016-03-18_11 34 01](https://cloud.githubusercontent.com/assets/631504/13875323/82737ffe-ecfd-11e5-971f-10882f010ee6.png)

**Comment by xXKeyleXx** [comment]
Is this still a problem?

**Comment by tara81** [comment]
yes it still is a problem on my server.

**Comment by xXKeyleXx** [comment]
Did the multiworld solution work for you?
