### ISSUE TITLE
can't tame pets since premium 2.0.0

### ISSUE THREAD

**Issue by tara81** [xXKeyleXx/MyPet#726]
the MyPet.user.leash.Witch           perms not working ?!

Did you change perms again ?!

**Comment by tara81** [comment]
Players cannot set behaviors no more, cant feed no more ........... what did u do to permissions and extended perms ? I am so confused... WHy u change all this , its a lot of work to readd all these perms and remove the old ones

**Comment by tara81** [comment]
I have special vote boxes that give players perms for certain pets and now i might have to change all these?

**Comment by Phreag** [comment]
The Perms have Changed in 2.0.0
Its now MyPet.leash.witch.

**Comment by xXKeyleXx** [comment]
Read the update notes...
