### ISSUE TITLE
[Question] - How to Separate MyPet

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#728]
@xXKeyleXx is there any way to separate the pets of players like there pet in survival and skyblock
:yum:

**Comment by xXKeyleXx** [comment]
https://mypet.keyle.de/doku.php?id=en:multiworld

**Comment by PinoyLifeCraft** [comment]
Uhm but @xXKeyleXx i'm not using that plugin!
 - it's  Multiverse Core

**Comment by xXKeyleXx** [comment]
"That plugin you are referring to is called MyPet :o I bet you just red the title and not the whole article.

**Comment by PinoyLifeCraft** [comment]
But wait does MyPet support Multiverse Core?
it doesn't work in MV

**Comment by xXKeyleXx** [comment]
Of course does it work. It has nothing to do with MV. What have you tried yet?

**Comment by tara81** [comment]
it appears to work for me.  You need to open the multiworld file in the
mypet folder.

**Comment by PinoyLifeCraft** [comment]
Thanks it works :smiley:
