### ISSUE TITLE
mypet crashes the game

### ISSUE THREAD

**Issue by IceBlade** [xXKeyleXx/MyPet#729]
when we use any command our minecraft crashes than cant login to server?

**Comment by xXKeyleXx** [comment]
Some more info about your setup might help.

**Comment by IceBlade** [comment]
i just downloaded the jar from the link which u gave me and pasted it to plugins folder that is all

**Comment by xXKeyleXx** [comment]
what pet crashed your server?

**Comment by IceBlade** [comment]
Just i wanted to call my sheepthan kabom!

**Comment by xXKeyleXx** [comment]
Sheeps work fine for me. What error does the client show you when Minecraft crashes (please put the error on pastebin)

**Comment by IceBlade** [comment]
[14:26] █YUNUS█play.FastLastMC.com█live:FastLastMc: ---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 19.03.2016 14:23
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 5
 at net.minecraft.tn.b(tn.java)
 at net.minecraft.client.jk.a(jk.java)
 at net.minecraft.x1.a(x1.java)
 at net.minecraft.x1.a(x1.java)
 at net.minecraft.i.b(i.java)
 at net.minecraft.client.uj.e(uj.java)
 at net.minecraft.client.s.A(s.java)
 at net.minecraft.client.s.m(s.java)
 at net.minecraft.client.s.l(s.java)
 at net.minecraft.client.main.Main.main(Main.java)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
 at net.minecraft.tn.b(tn.java)
 at net.minecraft.client.jk.a(jk.java)
 at net.minecraft.x1.a(x1.java)
 at net.minecraft.x1.a(x1.java)
 at net.minecraft.i.b(i.java)
 at net.minecraft.client.uj.e(uj.java)

-- Affected level --
Details:
 Level name: MpServer
 All players: 1 total; [uk['scrafton14'/7474, l='MpServer', x=-654,50, y=-0,01, z=505,50]]
 Chunk stats: MultiplayerChunkCache: 25, 25
 Level seed: 0
 Level generator: ID 01 - flat, ver 0. Features enabled: false
 Level generator options: 
 Level spawn location: World: (-470,4,1211), Chunk: (at 10,0,11 in -30,75; contains blocks -480,0,1200 to -465,255,1215), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
 Level time: 52790579 game time, 142277759 day time
 Level dimension: 0
 Level storage version: 0x00000 - Unknown?
 Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
 Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
 Forced entities: 19 total; [dp['Balçık'/7488, l='MpServer', x=-607,66, y=0,99, z=492,52], dp['Balçık'/7489, l='MpServer', x=-630,59, y=4,00, z=544,00], dp['Balçık'/7490, l='MpServer', x=-624,53, y=4,78, z=544,03], dp['Balçık'/7491, l='MpServer', x=-627,22, y=5,16, z=544,00], dp['Balçık'/7492, l='MpServer', x=-687,53, y=4,47, z=544,06], dp['Balçık'/7493, l='MpServer', x=-681,16, y=4,78, z=544,00], dp['Balçık'/7494, l='MpServer', x=-688,97, y=4,00, z=528,38], dp['Balçık'/7499, l='MpServer', x=-621,97, y=4,00, z=552,84], dp['Balçık'/7500, l='MpServer', x=-616,13, y=4,00, z=544,00], ho['Köylü'/7501, l='MpServer', x=-655,50, y=26,50, z=473,50], ao['At'/7475, l='MpServer', x=-639,91, y=4,00, z=510,63], wo['§bZombie'/7476, l='MpServer', x=-654,50, y=2,00, z=505,50], ao['At'/7477, l='MpServer', x=-677,13, y=-0,01, z=481,78], dp['Balçık'/7478, l='MpServer', x=-670,11, y=1,01, z=468,37], uk['scrafton14'/7474, l='MpServer', x=-654,50, y=-0,01, z=505,50], dp['Balçık'/7479, l='MpServer', x=-669,22, y=21,70, z=475,63], dp['Balçık'/7480, l='MpServer', x=-612,14, y=0,77, z=471,87], dp['Balçık'/7486, l='MpServer', x=-658,93, y=-0,03, z=545,77], co['Koyun'/7487, l='MpServer', x=-699,84, y=-0,01, z=489,75]]
 Retry entities: 0 total; []
 Server brand: Spigot
 Server type: Non-integrated multiplayer server
Stacktrace:
 at net.minecraft.client.it.a(it.java)
 at net.minecraft.client.s.c(s.java)
 at net.minecraft.client.s.l(s.java)
 at net.minecraft.client.main.Main.main(Main.java)

-- System Details --
Details:
 Minecraft Version: 1.7.2
 Operating System: Windows 8.1 (x86) version 6.3
 Java Version: 1.8.0_72, Oracle Corporation
 Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
 Memory: 118379656 bytes (112 MB) / 177250304 bytes (169 MB) up to 523501568 bytes (499 MB)
 JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
 AABB Pool Size: 8636 (483616 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 Launched Version: huzuni-1.7.2
 LWJGL: 2.9.0
 OpenGL: AMD Radeon HD 5450 GL version 4.5.13407 Compatibility Profile Context 15.201.2001.0, ATI Technologies Inc.
 Is Modded: Very likely; Jar signature invalidated
 Type: Client (map_client.txt)
 Resource Packs: []
 Current Language: Türkçe (TR)
 Profiler Position: N/A (disabled)
 Vec3 Pool Size: 129 (7224 bytes; 0 MB) allocated, 14 (784 bytes; 0 MB) used
 Anisotropic Filtering: Off (1) 

here it is

**Comment by xXKeyleXx** [comment]
Endermen are fixed now. I hope there are no more mobs that cause any client crashes...

https://build.keyle.de/job/MyPet/893/artifact/target/MyPet-2.0.3-SNAPSHOT.jar

**Comment by IceBlade** [comment]
trying it

**Comment by IceBlade** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 19.03.2016 16:05
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 5
	at net.minecraft.s2.c(s2.java)
	at net.minecraft.tg.c(tg.java)
	at net.minecraft.client.hn.a(hn.java)
	at net.minecraft.ang.a(ang.java)
	at net.minecraft.ang.a(ang.java)
	at net.minecraft.axd.a(axd.java)
	at net.minecraft.client.ad.h(ad.java)
	at net.minecraft.client.df.s(df.java)
	at net.minecraft.client.df.c(df.java)
	at net.minecraft.client.df.m(df.java)
	at net.minecraft.client.main.Main.main(Main.java)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.s2.c(s2.java)
	at net.minecraft.tg.c(tg.java)
	at net.minecraft.client.hn.a(hn.java)
	at net.minecraft.ang.a(ang.java)
	at net.minecraft.ang.a(ang.java)
	at net.minecraft.axd.a(axd.java)
	at net.minecraft.client.ad.h(ad.java)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [fi['Oxeon'/1194, l='MpServer', x=-799,36, y=29,62, z=462,66]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-532,7,970), Chunk: (at 12,0,10 in -34,60; contains blocks -544,0,960 to -529,255,975), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 52908321 game time, 142731501 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 39 total; [ug['arrow'/4224, l='MpServer', x=-804,72, y=28,03, z=462,72], ug['arrow'/4225, l='MpServer', x=-804,66, y=28,03, z=462,50], ug['arrow'/4226, l='MpServer', x=-804,69, y=28,03, z=462,53], sj['entity.ItemFrame.name'/2054, l='MpServer', x=-784,06, y=29,50, z=465,50], tm['Pig'/2950, l='MpServer', x=-844,81, y=4,00, z=422,31], sj['entity.ItemFrame.name'/2055, l='MpServer', x=-784,06, y=29,50, z=466,50], sy['Chicken'/2951, l='MpServer', x=-838,13, y=4,00, z=431,94], sj['entity.ItemFrame.name'/2056, l='MpServer', x=-784,06, y=30,50, z=467,50], sy['Chicken'/2952, l='MpServer', x=-809,81, y=4,00, z=431,81], sj['entity.ItemFrame.name'/2057, l='MpServer', x=-784,06, y=30,50, z=468,50], tr['Slime'/2953, l='MpServer', x=-760,75, y=4,00, z=432,00], sj['entity.ItemFrame.name'/2058, l='MpServer', x=-784,06, y=30,50, z=469,50], sj['entity.ItemFrame.name'/2059, l='MpServer', x=-784,06, y=29,50, z=470,50], sj['entity.ItemFrame.name'/2060, l='MpServer', x=-784,06, y=29,50, z=471,50], fi['Oxeon'/1194, l='MpServer', x=-799,36, y=29,62, z=462,66], sj['entity.ItemFrame.name'/2061, l='MpServer', x=-804,94, y=29,50, z=471,50], t_['Creeper'/2893, l='MpServer', x=-795,50, y=4,00, z=477,50], tz['Zombie'/3789, l='MpServer', x=-796,17, y=4,00, z=462,76], sj['entity.ItemFrame.name'/2062, l='MpServer', x=-804,94, y=29,50, z=470,50], t_['Creeper'/2894, l='MpServer', x=-801,06, y=4,00, z=476,22], sj['entity.ItemFrame.name'/2063, l='MpServer', x=-804,94, y=30,50, z=469,50], t_['Creeper'/2895, l='MpServer', x=-794,66, y=4,00, z=475,03], sj['entity.ItemFrame.name'/2064, l='MpServer', x=-804,94, y=30,50, z=468,50], tr['Slime'/3216, l='MpServer', x=-847,91, y=4,00, z=509,28], tz['Zombie'/3792, l='MpServer', x=-795,34, y=4,00, z=461,56], sj['entity.ItemFrame.name'/2065, l='MpServer', x=-804,94, y=30,50, z=467,50], sj['entity.ItemFrame.name'/2066, l='MpServer', x=-804,94, y=29,50, z=466,50], sj['entity.ItemFrame.name'/2067, l='MpServer', x=-804,94, y=29,50, z=465,50], t_['Creeper'/2900, l='MpServer', x=-790,50, y=4,00, z=474,50], ts['Spider'/4438, l='MpServer', x=-791,34, y=4,00, z=459,00], tg['§bSkeleton'/4439, l='MpServer', x=-799,38, y=28,00, z=462,66], tg['Skeleton'/3873, l='MpServer', x=-789,44, y=4,00, z=469,16], tg['Skeleton'/3874, l='MpServer', x=-791,97, y=4,00, z=461,25], tg['Skeleton'/3875, l='MpServer', x=-792,78, y=4,00, z=463,13], tr['Slime'/2937, l='MpServer', x=-839,38, y=4,00, z=507,84], tz['Zombie'/4219, l='MpServer', x=-797,50, y=4,00, z=479,00], ug['arrow'/4221, l='MpServer', x=-804,63, y=28,03, z=462,66], ug['arrow'/4222, l='MpServer', x=-804,69, y=28,03, z=462,66], ug['arrow'/4223, l='MpServer', x=-804,63, y=28,03, z=462,47]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.na.a(na.java)
	at net.minecraft.client.df.a(df.java)
	at net.minecraft.client.df.m(df.java)
	at net.minecraft.client.main.Main.main(Main.java)

-- System Details --
Details:
	Minecraft Version: 1.7.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 118570080 bytes (113 MB) / 216227840 bytes (206 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 377 (21112 bytes; 0 MB) allocated, 3 (168 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Apex
	LWJGL: 2.9.0
	OpenGL: GeForce GT 740M/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 138 (7728 bytes; 0 MB) allocated, 26 (1456 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

still giving it with 1.7.2 but runnig perfectly in 1.8.x

**Comment by xXKeyleXx** [comment]
Do you know which pet is causing this?

**Comment by IceBlade** [comment]
i tried with skeleton 1 min ago then crashed

**Comment by xXKeyleXx** [comment]
Thank god we found the problem :wave: I just need to fix it now

**Comment by IceBlade** [comment]
waiting for you :)

**Comment by xXKeyleXx** [comment]
https://build.keyle.de/job/MyPet/895/artifact/target/MyPet-2.0.3-SNAPSHOT.jar

**Comment by IceBlade** [comment]
I didnt saw that oh i am trying in 3 hours im not at home sorry :(

**Comment by IceBlade** [comment]
mm ok i can get a apet with 1.7.x but i cant in 1.8.x

**Comment by IceBlade** [comment]
not crashing when i use my pet on 1.8.x

**Comment by IceBlade** [comment]
than i cant get wolf pet in 1.7

**Comment by IceBlade** [comment]
1.8 can get pets sorry but 1.7x and 1.8.x both of them cant get wolf ocelot spider and blaze while we are attakingwith lead after a 1 min we cant damage them

**Comment by zerafox** [comment]
I thought MyPet didn't support protocol-hacked servers?
