### ISSUE TITLE
Food problems.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#730]
When I type in the /petinfo command, it says that my pet is very hungry (Hunger:1). I want to feed it, but it seems like it does not want to eat, because I'm spamming the correct food on it with right-click, but the Hunger meter is still at 1.

**Comment by xXKeyleXx** [comment]
1.9?

**Comment by Kronox12** [comment]
Yup

**Comment by tara81** [comment]
all permissions were changed ;d

**Comment by Kronox12** [comment]
Right... xd I forgot :'D I will test it again then

**Comment by Kronox12** [comment]
Fixed.
