### ISSUE TITLE
Locale MyPet

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#735]
Hellow @xXKeyleXx /mypetadmin not working and skill for pet locale is wrong!
Sorry for my all English :laughing: 
![a](https://cloud.githubusercontent.com/assets/13610530/13897804/a09925a2-ed51-11e5-97ea-7335a17c5098.png)

**Comment by xXKeyleXx** [comment]
It's /petadmin and I can't do anything against the problem with the chesttitles. Minecraft 1.9 does this :/

**Comment by PinoyLifeCraft** [comment]
But that is 1.8.8
Ok sorry for the /mypetadmin
