### ISSUE TITLE
The maximum level of pet is fixed at 100

### ISSUE THREAD

**Issue by PheoZen** [xXKeyleXx/MyPet#737]
In version 2.0.2, the bug that the maximum level in the skilltree editor is fixed at 100 is already solved. But, the pets in the server could not be more than 100 level.

>>> I tried to set unchecked on the maximum level
>>> I also tried to set the level cap in the config to 10000

But it still not work

**Comment by xXKeyleXx** [comment]
It works fine for me. I set MyPet.Exp.LevelCap to 10000 and the pet hit 1000 without any problems.

**Comment by PheoZen** [comment]
Ok. I will try it again.

I recently switch to the premium version. Do I have to reset my pet data?

**Comment by xXKeyleXx** [comment]
No, you can switch between both and nothing will happen.
