### ISSUE TITLE
/petinfo does not work on other players pets.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#738]
MyPet Premium 2.0.2, Minecraft 1.9.
I have the - MyPet.command.info.other permission, but it doesn't work. It says that I don't have permission to check the other players pets.

**Comment by xXKeyleXx** [comment]
Is this permission problem resolved too like the others?

**Comment by Kronox12** [comment]
This one doesn't :/

**Comment by xXKeyleXx** [comment]
Are you sure you use the correct permission?
- MyPet.command.info.other
It works fine with GM

**Comment by Kronox12** [comment]
Yes, I'm sure. We use PEX tho.

**Comment by xXKeyleXx** [comment]
It has to be something with your permissions. I tried it with PEX and it worked fine too :/

**Comment by Kronox12** [comment]
Theese are the perms. that I use:
    - MyPet.leash.*
    - MyPet.command.info.other
    - MyPet.command.capturehelper
    - MyPet.command.release
    - MyPet.command.name
    - MyPet.command.name.color
    - MyPet.command.respawn
    - MyPet.command.switch
    - MyPet.command.switch.bypass
    - MyPet.command.switch.limit.0
    - MyPet.command.trade.receive
    - MyPet.command.trade.offer
    - MyPet.command.trade.offer.type.*
    - MyPet.command.trade.receive.type.*
    - MyPet.skilltree.*

And also:
    Permissions:
    Enabled: true
    Extended: false
    Legacy: false
    UseExtendedPermissions: false

**Comment by xXKeyleXx** [comment]
Looks fine. What are the commands you try to run?

**Comment by Kronox12** [comment]
For example, "Laci" is a player's name. Then I try to run this command:
/petinfo Laci
But it gives me the "You have no permission to this command" message.

**Comment by xXKeyleXx** [comment]
Could you screenshot the error message for me?

**Comment by Kronox12** [comment]
Well... I don't why, but it's fixed o.O 
Today in the morning it was broken, but now, it works o.O
Maybe it was fixed in the update. I'm currently using MyPet Premium 2.0.3

**Comment by xXKeyleXx** [comment]
:tada:
