### ISSUE TITLE
More spawn reason to deny mypet to gain exp

### ISSUE THREAD

**Issue by FabioZumbi12** [xXKeyleXx/MyPet#739]
Hello Kyle ^^

With your latest version i have done hooked with MyPet for all version ;)

Now i having a issue with a plugin i using on my server. Its the MobStacker. When stack the mobs, this plugin change the spawn reason to CUSTOM when spawn from spawner, then the pets can gain XP with spawners now.

I know is not your fault and is not a bug, but the suggestion is instead to use this:

**Gain:
      MonsterSpawner: false**

You change to we add reasons the pets can gain xp like:

**Gain:
      SPAWNER: false
      CUSTOM: true
      ...and all reasons**

To add to config you can make a loop on spawnReasons and then add the default values.

Or add a simple list:

**Gain:
      Allowed:
      - CUSTOM
     Deny:
     - SPAWNER**

And by default allow all...

If you think this is not necessary, i can fork and make this, and if you like, i can open a Pull.
Thanks ;)

**Comment by xXKeyleXx** [comment]
Of you want you can do it. I don't know when I will have the time for it.

**Comment by xXKeyleXx** [comment]
Oh and I would like the 2nd (list) option :P

**Comment by FabioZumbi12** [comment]
I forked the project but theres a lot of configurations and one project depending of another. I dont have mutch experience with maven projects and configuration, i only run maven to make automatic package of .jar :P

**Comment by xXKeyleXx** [comment]
The only dependencies you have to add to you local repo manually (or change in the POM to use the file directly) are the Spigot and CraftBukkit ones. You can comment out the versions you don't need for testing in the main POM. All the plugins MyPet depends on are in a repo and will be downloaded when needed. 

I hope this helps, if not it's OK too. I will get to this at some point.

**Comment by FabioZumbi12** [comment]
I Cloned the github repo to my workspace, imported pom.xml as maven project but i having this error:

http://prntscr.com/b19p07
http://prntscr.com/b19p9o

Now i have time to make some plugins and revive dead bukkit plugins :)

**Comment by xXKeyleXx** [comment]
1. comment the modules out that you don't need for testing
2. if you have CB and Spigot in your local repo -> good - If not change the dependency to point to a local file.
3.remove the asm-tree folders from your local repo

If you still have problems please tell me.

**Comment by FabioZumbi12** [comment]
Hi,
Now i think is all ok, and i closed the modules i dont want! I looked on codes but i didnt find the configuration classes and main classes...

Heres what i have: http://prntscr.com/b1kdlb

**Comment by xXKeyleXx** [comment]
The config is in the API module and other ones are in the MyPet module. Every other module is for the skills, GUI and the version specific classes.

**Comment by FabioZumbi12** [comment]
Hello,

I found the "FROM_MONSTER_SPAWNER_MOBS" configuration and tryed to find where is used but i didnt find the listener where this is used.

And having this error on try to compile: http://prntscr.com/b1vt1r
Translating: "The command 'git' has nos been recognized as internal or external command..." Why i get this error?

Thanks for help.

**Comment by xXKeyleXx** [comment]
Had some free time to add this too :P

The error you have seems to have its roots in a missing git installation. Do you have Git installed on your machine? You may need to add git to your PATH or say your IDE where your git is installed.

And if you want to add me on skype: keylesc
