### ISSUE TITLE
taming wither boss with a leash

### ISSUE THREAD

**Issue by Khran** [xXKeyleXx/MyPet#740]
hi!

I have set this option on pet-config.yml

-----------------------------------------------
    Wither:
      HP: 20.0
      Speed: 0.3
      Food:
      - 352
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
-----------------------------------------------

But if the player beats the wither with a leash, wither die without becoming his pet.
No error logged on console.

Can you help me ?

thx

**Comment by xXKeyleXx** [comment]
It works fine for me. Are you sure you have the permissions to tame the wither?

**Comment by fatdog66** [comment]
Hi !
I have this perm in my permission file MyPet.leash.wither
