### ISSUE TITLE
Permission problems.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#741]
MyPet - Premium 2.0.2, MC 1.9

Problem: The permission for pettrade isn't working very well. I have every permission that corresponds to the /pettrade command, but it still says that I don't have the permissions for it.

Permissions allowed to the players:

    - MyPet.leash.*
    - MyPet.command.info.other
    - MyPet.command.capturehelper
    - MyPet.command.release
    - MyPet.command.name
    - MyPet.command.name.color
    - MyPet.command.respawn
    - MyPet.command.switch
    - MyPet.command.switch.bypass
    - MyPet.command.switch.limit.0
    - MyPet.command.trade.receive
    - MyPet.command.trade.offer
    - MyPet.command.trade.offer.type.*
    - MyPet.command.trade.receive.type.*
    - MyPet.skilltree.*
    - MyPet.extended.feed
    - MyPet.extended.beacon
    - MyPet.extended.behavior.friendly
    - MyPet.extended.behavior.aggressive
    - MyPet.extended.behavior.farm
    - MyPet.extended.behavior.raid
    - MyPet.extended.behavior.duel
    - MyPet.extended.inventory
    - MyPet.extended.ride
    - MyPet.extended.control
    - MyPet.extended.pickup
    - MyPet.extended.equip

**Comment by Kronox12** [comment]
Also, there are more permissions that doesn't work other than /pettrade.

**Comment by xXKeyleXx** [comment]
What permission plugin do you use? Do they work when you turn the legacy mode on?

**Comment by Kronox12** [comment]
PermissionEX. And somehow, it works now. Magic? xd
