### ISSUE TITLE
Mypet-npc permissions useless? not working

### ISSUE THREAD

**Issue by SxDanking** [xXKeyleXx/MyPet#743]
plugin download line：https://www.spigotmc.org/resources/mypet-npc.15572/

Why I've added this permissions

> - MyPet.npc.storage
> - MyPet.npc.storage.max.9

, the players still can't talk NPC with Mypet-storage?
it will says "You can't use this"

**Comment by xXKeyleXx** [comment]
Does the player had a pet or a pet stored at all? if not you can't do much with the NPC

**Comment by jeannen** [comment]
Same issue for me...

**Comment by xXKeyleXx** [comment]
Does the player had an active pet or a stored pet?

**Comment by zzvenuszz** [comment]
Yes, he had a pet. but plugin answered: you can't use this
