### ISSUE TITLE
PermissionsEX bug

### ISSUE THREAD

**Issue by Killthuzad** [xXKeyleXx/MyPet#745]
capturing pet with lead isn't working with permissions node given and /pcst none of the skilltree is showing up for our players it was working fine before until I updated the spigot jar file

**Comment by xXKeyleXx** [comment]
So you updated Spigot and the plugin stopped working, not the other way around?

**Comment by Killthuzad** [comment]
I do remember updating the plugin but I am not exactly sure when it stop working if it was spigot or the plugin itself

**Comment by Killthuzad** [comment]
I don't know what happened but everything is working now... I didn't even update anything
