### ISSUE TITLE
Zombie Villager

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#746]
If I capture a zombie villager and then release it, it turns into a regular zombie.
MyPet Premium 2.0.2, Minecraft 1.9

**Comment by xXKeyleXx** [comment]
I've tested it and it worked fine for me, do you know which profession the zombie had?

**Comment by Kronox12** [comment]
Sadly, no :/ A player reported it to me, but I don't think that he knew what type of ZombieVillager was.

**Comment by xXKeyleXx** [comment]
OK i tested all of them and every single one was the type I expected so maybe it was before I fixed it in one of the previous versions.
