### ISSUE TITLE
Wolf and Skeleton problems

### ISSUE THREAD

**Issue by Mancio1997** [xXKeyleXx/MyPet#747]
Wolf: when i try to give them some food he crouches on the ground like the vanilla one, making it impossible to feed. (the food set was Rotten Flesh).
Skeleton: when the skeleton start to shoot with arrows, the server shuts down with some errors: http://pastebin.com/x35x6dmm

**Comment by xXKeyleXx** [comment]
First update the plugin then create a ticket.
