### ISSUE TITLE
MyPet Spawner Exp.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#749]
The mypets gain experience from killing mobs spawned by spawners, even tho it is set to 'false' in the config.

  Exp:
    DamageWeightedExperienceDistribution: false
    Passive:
      Always-Grant-Passive-XP: true
      PercentPerMonster: 25
    Loss:
      Percent: 0
      Fixed: 0.0
      Drop: true
    Gain:
      MonsterSpawner: false

MyPet Premium 2.0.3, MC 1.9

**Comment by xXKeyleXx** [comment]
The info that a monster is spawned by a spawner is lost on a server restart/reload, this might be your problem

**Comment by Kronox12** [comment]
We have daily restarts, but this only occured in the latest version of Mypet Premium :/

**Comment by xXKeyleXx** [comment]
I haven't changed anything so it has to work :D (and it did in my tests :P )

**Comment by Kronox12** [comment]
Then I don't know why is this happening :/

**Comment by Kronox12** [comment]
Maybe you are right. It only happened in the morning, so the mobs that spawned before the restart has lost their data about spawners.
