### ISSUE TITLE
Bug riding players

### ISSUE THREAD

**Issue by FlamestoN** [xXKeyleXx/MyPet#750]
Bukkit/Spigot Build: git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
MyPet Build: 903

When chunk load, riding players break.

MyPet.log http://pastebin.com/eG81WkqA
Video: https://www.dropbox.com/s/hx1vpljdjdsjf91/Ashampoo_Snap_2016.03.30_20h29m44s_009_.wmv?dl=0

**Comment by xXKeyleXx** [comment]
Have you tested it with normal horses or pigs?

**Comment by FlamestoN** [comment]
Now, I tested it out.
Normal horses and pigs have it bug. :D

**Comment by xXKeyleXx** [comment]
Not sure what you wanna say :/

**Comment by FlamestoN** [comment]
Sorry for my bad English.
Normal horses and pigs have this bug (broken riding when chunk load).
This Spigot bug

https://www.spigotmc.org/threads/bug-riding-players.135784/

**Comment by xXKeyleXx** [comment]
Ok so it's a MC/Spigot bug and I can't do much ;)

**Comment by xXKeyleXx** [comment]
These forums are not used anymore ;)

**Comment by FlamestoN** [comment]
Why?
Can you give new link?

**Comment by xXKeyleXx** [comment]
look at the big message above the content ;)

**Comment by FlamestoN** [comment]
Thank you! :)
https://hub.spigotmc.org/jira/browse/SPIGOT-2096
