### ISSUE TITLE
Villagers don't have original carrer when they're released

### ISSUE THREAD

**Issue by Citringo** [xXKeyleXx/MyPet#754]
I released my villager which has "Butcher" profession and "Leatherworker" carrer. 

I think if villager-pet is released, he'll still have his profession and carrer. But, he's carrer became "Butcher".

I want villager-pet to inherit his carrer.

**Comment by xXKeyleXx** [comment]
MyPet version?
Spigot version?

**Comment by Citringo** [comment]
Oh, sorry.
MyPet version is 2.0.0
Spigot version is git-Spigot-d20369f-7fc5cd8 (MC-1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by xXKeyleXx** [comment]
Villagers will keep all their villager related data (Riches, Career, CareerLevel, Willing, Inventory, Offers) but will lose some data like the name (e.g. butcher, leather worker, etc.)
