### ISSUE TITLE
2 bugs (translation and drop)

### ISSUE THREAD

**Issue by L0ugs** [xXKeyleXx/MyPet#756]
Hello, I noticed 2 bugs.
First, when you kill the pet does not drop the items he has picked up. I created a new skilltree and I have check the "drop on death".

Second, there are translation problems: http://prntscr.com/aq5hy1

Sorry for my english, i'm french. Thank you

**Comment by xXKeyleXx** [comment]
The drop on death doesn't count for players who have the MyPet.admin permission.

The item names are not translated because the server itself only has the english translation included.
And Behavior should be translated, are you on the latest version?

**Comment by L0ugs** [comment]
Thank you very much. For my translation problem it's just that I had an older version of the plugin. Thank you, good luck (great plugin) :+1:
