### ISSUE TITLE
Spawner Problems

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#758]
In the config file I've set the MonsterSpawner option at the Exp part to false, but somehow the mypets still gain experience when they kill the silverfishes, even tho they are spawned by a spawner.

MyPet Premium 2.0.4, MC 1.9.2

**Comment by xXKeyleXx** [comment]
Do you use any mob altering plugins?

**Comment by Kronox12** [comment]
Nope

**Comment by xXKeyleXx** [comment]
Were the mobs spawned before a server restart?

**Comment by Kronox12** [comment]
Nope

**Comment by xXKeyleXx** [comment]
Is this still a problem in the latest version?
