### ISSUE TITLE
MyPet Crashes my server everytime!

### ISSUE THREAD

**Issue by GuysImTristan** [xXKeyleXx/MyPet#760]
Everytime my friend do /petcall, the server crashes. Here's the error:

`12.04 05:21:49 [Server] ERROR This crash report has been saved to: /./crash-reports/crash-2016-04-12_05.21.49-server.txt 12.04 05:21:49 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:809) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:179) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:77) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:441) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:342) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTrackerEntry.e(EntityTrackerEntry.java:555) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO java.lang.IllegalArgumentException: Don't know how to add class de.Keyle.MyPet.compat.v1_9_R1.skill.skills.ranged.nms.MyPetArrow! 12.04 05:21:49 [Server] ERROR Encountered an unexpected exception 12.04 05:21:49 [Server] INFO ... 24 more 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTracker.addEntity(EntityTracker.java:116) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:441) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:342) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTrackerEntry.e(EntityTrackerEntry.java:555) ~[Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO Caused by: java.lang.IllegalArgumentException: Don't know how to add class de.Keyle.MyPet.compat.v1_9_R1.skill.skills.ranged.nms.MyPetArrow! 12.04 05:21:49 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:629) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1421) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.World.g(World.java:1587) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1612) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.m(EntityMyPet.java:1081) [MyPet-2.0.0.jar:?] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1775) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.n(EntityMyPet.java:916) [MyPet-2.0.0.jar:?] 12.04 05:21:49 [Server] INFO at de.Keyle.MyPet.compat.v1_9_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:969) [MyPet-2.0.0.jar:?] 12.04 05:21:49 [Server] INFO at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) [MyPet-2.0.0.jar:?] 12.04 05:21:49 [Server] INFO at de.Keyle.MyPet.compat.v1_9_R1.entity.ai.attack.RangedAttack.tick(RangedAttack.java:130) [MyPet-2.0.0.jar:?] 12.04 05:21:49 [Server] INFO at de.Keyle.MyPet.compat.v1_9_R1.entity.ai.attack.RangedAttack.shootProjectile(RangedAttack.java:160) [MyPet-2.0.0.jar:?] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.WorldServer.addEntity(WorldServer.java:1074) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.World.addEntity(World.java:936) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.World.addEntity(World.java:1008) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:1121) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.World.b(World.java:1015) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.WorldManager.a(WorldManager.java:18) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTracker.track(EntityTracker.java:45) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTracker.addEntity(EntityTracker.java:142) [Spigot192.jar:git-Spigot-944aa20-8cb1b36] 12.04 05:21:49 [Server] INFO net.minecraft.server.v1_9_R1.ReportedException: Adding entity to track 12.04 05:21:49 [Server] ERROR "Silently" catching entity tracking error.`

**Comment by xXKeyleXx** [comment]
MyPet version?
Spigot version?

**Comment by GuysImTristan** [comment]
Mypet : 2.0.0
Spigot Version : The very latest one that supports 1.9.2.

**Comment by xXKeyleXx** [comment]
Please download the latest version: https://www.spigotmc.org/resources/mypet.12725/history
