### ISSUE TITLE
Can't access to /petswitch store

### ISSUE THREAD

**Issue by Elsopeen** [xXKeyleXx/MyPet#761]
Hello,
I found an issue with your plugin and your permissions : whenever a player types the command /petswitch store, it returns that he doesn't have the permission to. Here is the list of permissions of my players :
    - MyPet.trade.receive.type.*
    - MyPet.trade.receive
    - MyPet.trade.offer.type.*
    - MyPet.trade.offer
    - MyPet.switch
    - MyPet.switch.store
    - MyPet.switch.bypass
    - MyPet.switch.limit.54
    - MyPet.name.color
    - MyPet.command.name
    - MyPet.command.respawn
    - MyPet.command.release
    - MyPet.command.capturehelper
    - MyPet.command.info
    - MyPet.skilltree.*
    - MyPet.leash.*

If there is another permissions that wasn't added on the wiki at today's date, or if it is a bug, I don't know, but I hope you'll be able to fix that, because it's said in the features that we can have severals pets.
Best regards,
Elsopeen

**Comment by xXKeyleXx** [comment]
The trade permissions are not correct.

**Comment by xXKeyleXx** [comment]
- MyPet.command.trade.offer
- MyPet.command.trade.offer.type.<MyPet-Type>
- MyPet.command.trade.receive
- MyPet.command.trade.receive.type.<MyPet-Type>

**Comment by Elsopeen** [comment]
Hello,
I modified the permissions, I'm waiting for a player to test if it's working now.

**Comment by xXKeyleXx** [comment]
Oops I missed the permissions you asked for xD, but the ones I wrote were wrong too anyway :package: 
You can find all the permissions here: https://wiki.mypet-plugin.de/doku.php?id=en:permissions

**Comment by Elsopeen** [comment]
Thanks, it works now,
Good luck for next,
Best regards,
Elsopeen
