### ISSUE TITLE
Pets Vanishing When Selected with Lead.

### ISSUE THREAD

**Issue by elliswin** [xXKeyleXx/MyPet#764]
Hi there I have just installed the premium on our bungeecord/Spiot 1.9 server with My Pet version 2.0.4 and when ever I try to leash a pet I get the message "you've tamed a pet it will be a good my pet! but the pet vanishes and I receive the following error in the control panel:

35:16 [Server] INFO at java.util.regex.Pattern.error(Pattern.java:1955) ~[?:1.8.0_60]
 18.04 14:35:16 [Server] INFO ^
 18.04 14:35:16 [Server] INFO b**ch
 18.04 14:35:16 [Server] INFO Caused by: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 2
 18.04 14:35:16 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
 18.04 14:35:16 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1577) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.EntityPlayer.attack(EntityPlayer.java:1129) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.EntityHuman.attack(EntityHuman.java:999) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:824) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity0(EntityLiving.java:1211) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:602) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:570) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
 18.04 14:35:16 [Server] INFO org.bukkit.event.EventException
 18.04 14:35:16 [Server] ERROR Could not pass event EntityDamageByEntityEvent to MyPet v2.0.4
 18.04 14:35:11 [Server] INFO EllisWin issued server command: /pch

Can you help m getting this up and running plea

**Comment by xXKeyleXx** [comment]
Have you changed the namefilter?
The problem is that the part where it tells me where to look for the problem is missing in your errorlog (why is it bottom to top anyway?)
