### ISSUE TITLE
pets unable to climb blocks

### ISSUE THREAD

**Issue by kamikazifroasty** [xXKeyleXx/MyPet#766]
Hey having an issue with spiders and iron golems not being able to climb up a 1 block high incline. there might be more mobswith this issue but so far that's the only 2 i know of. no errors in console, running off the most recent version of mypet premium , on spigot 1.9.1

**Comment by xXKeyleXx** [comment]
Every type with a width bigger than 1 has this problem....

**Comment by xXKeyleXx** [comment]
https://bugs.mojang.com/browse/MC-98887
https://bugs.mojang.com/browse/MC-97343

**Comment by xXKeyleXx** [comment]
It will be fixed with Minecraft 1.9.3 so until then I will just make them smaller.
