### ISSUE TITLE
players can't capture pets

### ISSUE THREAD

**Issue by jordanwilliams1** [xXKeyleXx/MyPet#769]
Players on my server are unable to capture pets with a lead, It was working fine on 1.8 but since I updated to 1.9 noone can tame pets with a lead :( 

I Can tame pets as OP so? Why can't normal players ;(

**Comment by xXKeyleXx** [comment]
Check if your permissions are correct (I changed them in the past):
https://wiki.mypet-plugin.de/doku.php?id=en:permissions

**Comment by jordanwilliams1** [comment]
ahh, I Though it was a permission error but i couldn't find any perms on your spigot page
