### ISSUE TITLE
Blacklist für Pickup / Blacklist for pickup

### ISSUE THREAD

**Issue by dieloewin** [xXKeyleXx/MyPet#770]
Hallo liebes DEV-Team. 
Ich würde mir eine Einstellungsoption bei dem Skill "Pickup" wünschen, wo man bestimmte Gegenstände von der Aufnahme durch das Pet ausgrenzen kann. Zwei Ideen dazu:
1. config: Gegenstände die niemals aufgenommen werden können. Besonders interessant wenn man zum Beispiel Plkugins wie PickUpMoney nutzt. Das Geld/ die Items, welche droppen, verschwinden sonst einfach.
2. optional, aber hilfreich: Der Spieler selbst, kann bestimmen welche Gegenstände NICHT aufngenommen werden sollen. Optimal wäre das ganze über ein GUI mit Klicken für an/aus.

----
Googletranslator-English: :-)
Dear DEV team .
I would like a setting option in the Skill " Pickup " , where you can exclude certain items from the uptake by the Pet . Two ideas about :
1. config : items that can never be taken . Particularly interesting if one uses , for example as Plugins PickupMoney . The money / the items that drop , disappear otherwise simple.
2. optional but helpful : The player itself can determine which items should not be pickup. The ideal would be all over a GUI with Click to on / off .

**Comment by xXKeyleXx** [comment]
1. Kein Team nur ich :P
2. was stimmt mit dem Feature Request nicht?: #663
