### ISSUE TITLE
Plugin refuses to load newer backups.

### ISSUE THREAD

**Issue by FlyingMuie** [xXKeyleXx/MyPet#771]
Hello,
I've restarted the server today and plugin loaded some older pets (too old, 2-3 weeks old).
I've taken the newest backup file in "backups" folder, renamed it to My.Pets.
Started the server, logged in and backup didn't loaded, I still had the old pet.

**Comment by xXKeyleXx** [comment]
That's not possible. If it is the old pet you
a: didn't overwrote the file
b: didn't stopped the server before replacing the file

**Comment by FlyingMuie** [comment]
a. I did deleted the old My.Pets and renamed the backup to My.Pets
b. I did, I tried using Plugman to unload MyPet and the load it again after I renamed backup.
Plugman didn't worked so I restarted the whole server.

Can the file be corrupted in any way?

**Comment by xXKeyleXx** [comment]
I theory the file can't be corrupted (but you never know). But the case where it loads old pets is simply not possible.
