### ISSUE TITLE
Mypet inventory problem

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#773]
My MyPet is able to pick up items and it has it's own inventory (3 rows).
/pepickup is enabled.
I throw a stack of items at it, it picks up the whole stack and puts it in the inventory. But when I throw single items at it, it picks them up, but the items does not stack in the inventory by default. Instead, they get placed in different slots in the pet's inventory.

MyPet-Premium 2.0.7, MC 1.9.2

**Comment by xXKeyleXx** [comment]
oops wrong ticket
