### ISSUE TITLE
Pets picking up items from Brewery Plugin

### ISSUE THREAD

**Issue by Blackyvk** [xXKeyleXx/MyPet#775]
I'm trying to avoid pets  pkcing up #items from this plugin and the way the plugin avoids players picking up items is like this i think.

`	@EventHandler(ignoreCancelled = true)

	public void onInventoryPickupItem(InventoryPickupItemEvent event){

		if (event.getItem().getPickupDelay() > 1000) {

			event.setCancelled(true);

		}
	}`

any way to do it for my pet ?

**Comment by xXKeyleXx** [comment]
So you have items that have a pickup delay and MyPet doesn't respect the delay?

**Comment by Blackyvk** [comment]
I think (i didnt code that plugin) but thats what i see in the code, players cannot pickup those items when the delay is over 1000 but the pet just take them instantly.

[you can see it here](https://github.com/DieReicheErethons/Brewery/blob/master/src/com/dre/brewery/listeners/InventoryListener.java)

**Comment by xXKeyleXx** [comment]
Ok I made my plugin respect the pickup delay. If you use the non premium version you can download a fixed version here: https://build.keyle.de/job/MyPet/
