### ISSUE TITLE
Taming a pet deletes after relog 

### ISSUE THREAD

**Issue by jordanwilliams1** [xXKeyleXx/MyPet#776]
After taming a pet [any type] upon a relog it has been deleted. This is only happening with 1 player and they have the perms. No other player is getting this?

**Comment by xXKeyleXx** [comment]
What is the name of the player? Cracked server?

**Comment by jordanwilliams1** [comment]
The server is not cracked. I'm using bungee.

Player name: Fatalis_

**Comment by xXKeyleXx** [comment]
And there are no errors in the logs?

**Comment by jordanwilliams1** [comment]
http://hastebin.com/jiwifegipe.avrasm

**Comment by xXKeyleXx** [comment]
Please update the plugin before you open a ticket.

**Comment by jordanwilliams1** [comment]
Okay. Its fixed. The plugin was only outdated by a week :/

**Comment by xXKeyleXx** [comment]
A week is a lot of time :P
