### ISSUE TITLE
Cannot measure distance...

### ISSUE THREAD

**Issue by MClausz** [xXKeyleXx/MyPet#777]
The plugin keep spamming this in the console
http://pastebin.com/mJiDLxuA

**Comment by xXKeyleXx** [comment]
WOW another error that can not happen (in theory). Do you use a modded server?

**Comment by MClausz** [comment]
I'm using Spigot 1.8.8

**Comment by xXKeyleXx** [comment]
Sometimes I don't get it but I should stop asking questions :P will fix it later today.

**Comment by xXKeyleXx** [comment]
If you use the non premium version you can download the fixed version here: https://build.keyle.de/job/MyPet/
