### ISSUE TITLE
Tree creator won't open

### ISSUE THREAD

**Issue by hypernova1912** [xXKeyleXx/MyPet#781]
Whenever my friend clicks or launches the jar in the folder, it gives this error:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Sets
at de.Keyle.MyPet.api.Configuration$LevelSystem$Experience<clinit><Configuration.java:98>
at de.Keyle.MyPet.gui.GuiMain.main,GuiMain.java:66>
Caused by: java.lanf.ClassNotFoundException: com.google.common.collect.Sets
at java.net.URLClassLoader.findClass<Unknown Source>
at java.lang.ClassLoader.loadClass<Unknown Source>
at sun.misc.Launcher$AppClassLoader.loadClass<Unknown Source>
at java.lang.ClassLoader.loadClass<Unknown Source>
... 2 more

Sorry, it's from cmd.exe, so my friend couldn't copy it, meaning the indentation is off. Whenever I launch it, however, it loads fine. He is on a Windows 7 home-built PC, I'm on a MacBook Pro w/ OS X 10.11.4. Using 2.0.0. He's running from the server folder with MC 1.8.8, and I'm using just the naked .jar file. Tried launching from command line. We both have the latest Java. Any ideas?

**Comment by xXKeyleXx** [comment]
You can download a fixed version here: https://build.keyle.de/job/MyPet/
