### ISSUE TITLE
A couple of feature requests.

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#783]
1. Pets would be able to eat from their inventory. I thought about this while I was messing around with the EnderDragon. Hence you can't feed the EnderDragon pets, they starve after a certain amount of time. This addition would fix this issue, at least temporarily. Maybe add a config option to it too.
2. New permission: Change the /pcst more than once. I know you can do it using the option in the config, but there isn't a way to manage it by ranks. I mean, a VIP could change his pet's skills 2 times, but a VIP+(or something bigger) could change it 3 times.
3. Baby EnderDragon pet, because the Baby Wither is cute, but my players want more cuteness xd :,D.

**Comment by xXKeyleXx** [comment]
1. Yes
2. Maybe
3. Not possible

**Comment by tara81** [comment]
The baby wither pet has lots of particles around it and the nametag is really high above it, can this be corrected?

**Comment by xXKeyleXx** [comment]
Nope

**Comment by tara81** [comment]
you can't even remove the particles ? lol.

**Comment by xXKeyleXx** [comment]
Nope

**Comment by tara81** [comment]
oh did you add the particles or is that the default somehow?

**Comment by tara81** [comment]
I am just curious , i've never seen a baby wither til now lol

**Comment by xXKeyleXx** [comment]
No I don't added any particles. You can giant or tiny withers by changing the **Invul** value.

**Comment by tara81** [comment]
Are there any other baby pets that are not normally in the game? like baby skeletons / baby creeper ?

**Comment by xXKeyleXx** [comment]
Nope

**Comment by tara81** [comment]
okay thanks for your information keyle =) Any updates on that feature request for pet sniffing ? :dancer:
