### ISSUE TITLE
Weird "pet wants to come to me" bug

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#787]
If I go into a Region and I'm not a member/owner of that Region and I haven't sent my pet away with the /psa command, it tries to come to me every second, but it only sends me a message that he is respawning ATM. This spams the chat window for the pet's owner. If I type in the /pc commad, it still says that the pet is respawning.

MyPet Premium 2.0.9, MC 1.9.2

**Comment by Kronox12** [comment]
![2016-05-13_23 55 08](https://cloud.githubusercontent.com/assets/14863100/15261646/6f180494-1966-11e6-9240-fd3cc34c68f4.png)
![2016-05-13_23 55 25](https://cloud.githubusercontent.com/assets/14863100/15261647/6f1bef78-1966-11e6-8c33-d7e665460918.png)
![2016-05-13_23 55 29](https://cloud.githubusercontent.com/assets/14863100/15261649/6f20063a-1966-11e6-91a5-38914f930401.png)
![2016-05-13_23 55 32](https://cloud.githubusercontent.com/assets/14863100/15261648/6f20248a-1966-11e6-9294-068ccde65aae.png)

**Comment by Phreag** [comment]
Bug exists also on my server.
Using Paper 1.9.2 and MyPet Premium 2.1.0 #223

**Comment by xXKeyleXx** [comment]
@Phreag could you download the latest devbuild and check if the bug persists.

**Comment by xXKeyleXx** [comment]
Region plugin?

**Comment by Phreag** [comment]
Worldguard 6.1 and Griefprevention 14.5.2
