### ISSUE TITLE
Players can't trade MyPets

### ISSUE THREAD

**Issue by Coolkc456** [xXKeyleXx/MyPet#788]
Players who are not opped cannot establish a trade with other players or accept trades even with permissions. http://pastebin.com/qRzNsv6P

When I attempt to make a trade with other players it says "You do not have access to that command." When I tried accepting a trade from an opped player, it says "You do not have access to accept any offer."

**Comment by Coolkc456** [comment]
Also, I'm using MyPet-Premium 2.0.9

**Comment by xXKeyleXx** [comment]
these permissions are missing:

- MyPet.command.trade.offer.type.<MyPet-Type>
- MyPet.command.trade.receive.type.<MyPet-Type>

https://wiki.mypet-plugin.de/doku.php?id=en:permissions

**Comment by Coolkc456** [comment]
Can you give me an example of what goes in the "<MyPet-Type>"? I want them to be able to trade all types of MyPets but when I do MyPet.command.trade.offer.type.* it still doesn't work. I also tried - MyPet.command.trade.offer.type.horse and - MyPet.command.trade.offer.type.MyPet-horse when attempting to trade horses with another player as a test.

**Comment by xXKeyleXx** [comment]
An `*` for all types should be fine. Do you have these permissions?:

- MyPet.command.trade.offer.type*
- MyPet.command.trade.receive.type.*

**Comment by Coolkc456** [comment]
Yes, here is the updated permissions.yml http://pastebin.com/zCN2Dnq6

**Comment by xXKeyleXx** [comment]
You are missing these permissions:

- MyPet.command.trade.offer
- MyPet.command.trade.receive

Hm... these permissions are pretty useless. I will remove them in the next update.

**Comment by xXKeyleXx** [comment]
- MyPet.command.trade.offer.<MyPet-Type>
- MyPet.command.trade.receive.<MyPet-Type>
