### ISSUE TITLE
Mypet exp

### ISSUE THREAD

**Issue by WindUnwaken** [xXKeyleXx/MyPet#790]
How to get exp for pet without combat skill?

**Comment by xXKeyleXx** [comment]
When the owner kills a mob the pet will gain a percentage (config) of the exp the pet would gain if the pet would have killed it.

**Comment by WindUnwaken** [comment]
` Exp:
    DamageWeightedExperienceDistribution: false
    Passive:
      Always-Grant-Passive-XP: true
      PercentPerMonster: 25
    Loss:
      Percent: 0
      Fixed: 0.0
      Drop: true
    Gain:
      PreventFromSpawnReason:
      - SPAWNER
    LevelCap: 100
    Active:
      CREEPER:
        Min: 5.0
        Max: 5.0
      SKELETON:
        Min: 5.0
        Max: 5.0
      SPIDER:
        Min: 5.0
        Max: 5.0
      GIANT:
        Min: 25.0
        Max: 25.0
      ZOMBIE:
        Min: 5.0
        Max: 5.0
      SLIME:
        Min: 1.0
        Max: 4.0
      GHAST:
        Min: 5.0
        Max: 5.0
      PIG_ZOMBIE:
        Min: 5.0
        Max: 5.0
      ENDERMAN:
        Min: 5.0
        Max: 5.0
      CAVE_SPIDER:
        Min: 5.0
        Max: 5.0
      SILVERFISH:
        Min: 5.0
        Max: 5.0
      BLAZE:
        Min: 10.0
        Max: 10.0
      MAGMA_CUBE:
        Min: 1.0
        Max: 4.0
      ENDER_DRAGON:
        Min: 20000.0
        Max: 20000.0
      WITHER:
        Min: 100.0
        Max: 100.0
      BAT:
        Min: 1.0
        Max: 1.0
      WITCH:
        Min: 10.0
        Max: 10.0
      ENDERMITE:
        Min: 3.0
        Max: 3.0
      GUARDIAN:
        Min: 10.0
        Max: 10.0
      SHULKER:
        Min: 5.0
        Max: 5.0
      PIG:
        Min: 1.0
        Max: 3.0
      SHEEP:
        Min: 1.0
        Max: 3.0
      COW:
        Min: 1.0
        Max: 3.0
      CHICKEN:
        Min: 1.0
        Max: 3.0
      SQUID:
        Min: 1.0
        Max: 3.0
      WOLF:
        Min: 1.0
        Max: 3.0
      MUSHROOM_COW:
        Min: 1.0
        Max: 3.0
      SNOWMAN:
        Min: 0.0
        Max: 0.0
      OCELOT:
        Min: 1.0
        Max: 3.0
      IRON_GOLEM:
        Min: 0.0
        Max: 0.0
      RABBIT:
        Min: 1.0
        Max: 1.0
      VILLAGER:
        Min: 0.0
        Max: 0.0
      ENDER_CRYSTAL:
        Min: 10.0
        Max: 10.0`

This is my config, and when I kill a mob , I type /petinfo still says 0.00/7.00

**Comment by xXKeyleXx** [comment]
Do you have a skilltree selected?

**Comment by WindUnwaken** [comment]
http://i.imgur.com/rm8lee5.png

**Comment by WindUnwaken** [comment]
I use default config and select my custom pickup skill.
I choose skill-tree first and then go to kill a mob.

**Comment by xXKeyleXx** [comment]
MyPet version?

**Comment by WindUnwaken** [comment]
2.1.0

**Comment by xXKeyleXx** [comment]
are the mobs spawned by a monster spawner?

**Comment by WindUnwaken** [comment]
No, they are natural.
But I tried
DamageWeightedExperienceDistribution: false>> true

Spawner, Natural, Egg all of them can get exp.
So, my problem can be fixed.. but I don't really understand what it means 'DamageWeightedExperienceDistribution'

Besides,I don't have others questions, and thanks to help , nice premium plugin.
You can close this issue, and tag Solved.

**Comment by xXKeyleXx** [comment]
I will look further into it.

DamageWeightedExperienceDistribution means the more damage the pet does at an enemy the more XP the pet will get. For example a pet does 50% of the damage to a zombie the pet will get 50% of the XP as he would get when he does 100% of the damage.

Well I don't speak Chinese at all so all translations are community translations. I took some samples but I can't check every translation. If you would be so kind and fix these translations I would be so grateful. You can find them here: https://translation.mypet-plugin.de/translate/zh_tw
