### ISSUE TITLE
Pettrade Suggestion

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#791]
Trading pets for pets, instead of money. Basically, players woukd be able to exchange their pets to another pet without using some sort of payment system.

**Comment by xXKeyleXx** [comment]
You don't need to use any payment system. You can send a pet to any player without him paying for it. But pet for pet is not a bad idea.

**Comment by renzotom** [comment]
Author of TradeMe plugin making support, he say me it.
