### ISSUE TITLE
1.9.2的水桶 服务器上 给了玩家所有的捕捉权限 都只有op才能捕捉宠物 

### ISSUE THREAD

**Issue by huazhizhaozhan** [xXKeyleXx/MyPet#792]
谢谢非常棒棒哒的软件！但是在1.9.2的服务器上就是给了玩家权限，还是不能捕捉宠物，每个版本都有这个毛病，甚至op也捕捉不了了！

**Comment by xXKeyleXx** [comment]
What mob do you wanted to take as a pet? When even OPs can't get one means it's
a. a bug
b. you did something wrong

**Comment by huazhizhaozhan** [comment]
可能有很多腐竹会遇到如此困惑，原因不是插件真实存在bug，而是插件的内置权限与中文官网的WIKI权限不一样，所以造成了困惑。权限在插件的jar包中，请自行查看

**Comment by xXKeyleXx** [comment]
The chinese translation is not up to date so you have to use the english version. I added a notification to the chinese one so others know they should not use it.
