### ISSUE TITLE
Mixed mode server Issue

### ISSUE THREAD

**Issue by Blackyvk** [xXKeyleXx/MyPet#793]
MyPet while using pluings like [FastLogin ](https://github.com/games647/FastLogin/)  fails to give premium players pet, Offline players can get a pet normally. This only happens when online-mode=false  If the server is in online-mode=true both online and offline players get a pet (using autoin) even you get the pet you captured in offlinemode, you just arent able to see you own it until you switch the server to online mode.

The problem is I need the server in offline mode to be able to use fastlogin properly....  is there a way to make MyPet think the server is in online mode when is not ?   

Thanks

**Comment by xXKeyleXx** [comment]
FastLogin -> Yes
AutoIn -> No, but may change with the 4.0 release

**Comment by xXKeyleXx** [comment]
Do you use the Premium version of Mypet?

**Comment by xXKeyleXx** [comment]
should work since 0ac4b768d412a4b58a8f8f4aadfb01a7a6d3ff7a
