### ISSUE TITLE
I can't ride my pet

### ISSUE THREAD

**Issue by WindUnwaken** [xXKeyleXx/MyPet#794]
http://pastebin.com/z5JCJJyy

Spigot 1.9.4  MyPet.2.1.0

I can select three of skills, combat and pickup is fine, but select ride didn't work.

**Comment by xXKeyleXx** [comment]
Problem solved itself? :D

**Comment by WindUnwaken** [comment]
Yep, I mess up my config. :p
But a new question need to ask,
I found skilltree -damage
option add value didn't work.

But, inventory add value is okay?
Could you test it?

**Comment by WindUnwaken** [comment]
I mean I can train my pet to add more slot for backpack
But, I can't make it more stronger to fight.

Quickly fix method is.. I set value for per level  xD

**Comment by xXKeyleXx** [comment]
Please set the value per level, I don't want to put too much time in the old SkilltreeCreator. I'm currently rewriting it. I hope I finish a working version by the end of next week.
