### ISSUE TITLE
Can't fly with pet

### ISSUE THREAD

**Issue by Khran** [xXKeyleXx/MyPet#796]
Hi ! Since the 1.9.4 update, my players and me can't fly whith flying pet skilltree. No change in config or skilltree.

config.yml = http://pastebin.com/ZuYEJ24A
pet-config.yml = http://pastebin.com/ifugNuHL

No error log

MyPetPremium v2.1.0 on spigot 1.9.4

Thx for your help

**Comment by xXKeyleXx** [comment]
This will be fixed in the next version. Thanks for the report.
