### ISSUE TITLE
PSW bug + missing pets + permission bug

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#798]
1. I type in the /psw command, but it says that I don't have permission, but clearly, I do.
![2016-05-25_17 53 50](https://cloud.githubusercontent.com/assets/14863100/15544599/f882791e-22a1-11e6-9f3c-2df233441bf4.png)
Permissions:
    - MyPet.user.command.trade.offer
    - MyPet.user.command.trade.recieve
    - MyPet.user.command.trade.offer.type.*
    - MyPet.user.command.trade.recieve.type.*
    - MyPet.user.leash.*
    - MyPet.user.command.switch.limit.0
    - MyPet.user.command.switch
    - MyPet.user.command.switch.bypass
    - -MyPet.user.extended.Inventory
    - -MyPet.user.extended.Ride
    - -MyPet.user.extended.Control
    - -MyPet.user.extended.Pickup
    - -MyPet.user.extended.Equip
    - -MyPet.user.extended.CanFeed
    - -MyPet.user.extended.Beacon
    - MyPet.custom.skilltree.*

2. When I updated the MyPet version on my test server, all of my pets got lost. (And on my main server, some players told me that they didn't had the permission for the /pettrade command, and they lost their pets when they got the "You have no permission" message. I think it's a bug.)

3. The /pettrade refuses to work on my test server too.
![2016-05-25_18 03 01](https://cloud.githubusercontent.com/assets/14863100/15544924/2a00ba54-22a3-11e6-8a92-4212b519c84e.png)

MyPet - Premium 2.1.1, MC 1.9.4

**Comment by xXKeyleXx** [comment]
Do you have the legacy permissions enabled in the config?

**Comment by Kronox12** [comment]
Main server: Mypet Premium 2.1.0 >>> MyPet Premium 2.1.1
Test server:  Mypet Premium 2.0.8 >>> MyPet Premium 2.1.1

Main server config-Legacy option: false
Test server config-Legacy option: false

**Comment by xXKeyleXx** [comment]
https://wiki.mypet-plugin.de/doku.php?id=en:permissions

**Comment by Kronox12** [comment]
I know where can I find the permissions, and I've wrote down the permissions that I use too. But the problem is still alive.

**Comment by xXKeyleXx** [comment]
Then look at the permissions and then look at your permissions...

**Comment by Kronox12** [comment]
Ooops .-. xd sorry, it's a bit late here and I didn't saw the differences :/ Tomorrow I'll try it when I'll have time. Sorry for my inattention :/

**Comment by Kronox12** [comment]
So I updated my PEX Permissions file: 
    - MyPet.leash.*
    - MyPet.command.info.other
    - MyPet.command.capturehelper
    - MyPet.command.release
    - MyPet.command.name
    - MyPet.command.name.color
    - MyPet.command.respawn
    - MyPet.command.switch
    - MyPet.command.switch.bypass
    - MyPet.command.switch.limit.0
    - MyPet.command.trade.receive
    - MyPet.command.trade.offer
    - MyPet.command.trade.offer.type.*
    - MyPet.command.trade.receive.type.*
    - MyPet.skilltree.*

But the problem is still occuring :/
![2016-05-27_23 46 11](https://cloud.githubusercontent.com/assets/14863100/15620846/7d304ee2-2465-11e6-912f-9e7a1d6bef1d.png)

**Comment by xXKeyleXx** [comment]
Sorry my bad :/ I changed the trade permissions but did not update the wiki...
the new trade permissions are:
- MyPet.command.trade.offer.\<MyPet-Type>
- MyPet.command.trade.receive.\<MyPet-Type>

so in your case you have to remove all trade permissions and add
- MyPet.command.trade.offer.*
- MyPet.command.trade.receive.*

**Comment by Kronox12** [comment]
Allright, thank you :)
