### ISSUE TITLE
about trait incompatibility

### ISSUE THREAD

**Issue by comonier** [xXKeyleXx/MyPet#799]
hello, i have installed. mypet last build (1.8/1.9) MyPet-2.1.1.jar it's working fine on my server - using Spigot 1.8.8 to mc 1.8.8 SnapShot Ap-Version

My problema is about the MyPet-Npc plugin - i already try upload do plugins folder 
both version last builds MyPet-NPC-1.0.5.jar and 
when start the sever, he cant unload, wrong version erro msgs....
can please tell me what is the rigth version to i download ?
on npc when i type: /trait mypet-storage he give-me a error msg. doesnt not exist.
maybe cause he do not load it on server start.

**Comment by xXKeyleXx** [comment]
1.0.5 is not the latest...https://www.spigotmc.org/resources/mypet-npc.15572/

**Comment by comonier** [comment]
about pvp... seted   DisablePetVersusPlayer: true on config
but if i atack some player's he still atacking me like pvp.
cant disable pets damage agains players ?

**Comment by xXKeyleXx** [comment]
Does it work with the latest version of MyPet-NPC?

Please open new tickets when you have additional problems.

I will look into it and fix the problem if necessary.

**Comment by comonier** [comment]
ok ty

**Comment by comonier** [comment]
the plugin was working fine, but i use mlp to reload mypet lose all database, when i get mypet back, all players lose pets... and now npc not work anymore. i can load traits but npc do not work

**Comment by comonier** [comment]
i did a lot of shit, with other plugin used to unload plugins, after that i move old backup of database of saved pets, after that, the npcs of citizens stop to work, after that, i delete, and re-create the npc, he create a new id, so... i just stop the server and start again. its working fine now. xD
