### ISSUE TITLE
npc used to storage pets bugged, players can press shift to steel eggs and green, red wools

### ISSUE THREAD

**Issue by comonier** [xXKeyleXx/MyPet#801]
the players of my server report me a bug on the npc used to storage pets
 if they press shift and click with the right mouse button, on the storaged egg on npc menu, they can take infinites egg-spawn of his pet to inventory, and spawn it on the world, a renamed and unremoved mob .... tis a high and priority problem....  i must to remove the npc, 

 they can use the same method to steel the green and red wool

there is a way to storage pets without this bugged npc ?

**Comment by xXKeyleXx** [comment]
MyPet version? Spigot/Bukkit version? Do you use any inventory changing plugins?

**Comment by Phreag** [comment]
I was not able to reproduce this bug, everything works fine for me:
Paper Build 756
MyPet Premium 2.1.3 Snapshot b246
MyPet-NPC 1.0.7 Snapshot b113

**Comment by comonier** [comment]
were did you get my pet npc 1.0.7? if on bukkit page the last build is 1.0.5 and on spigot page the last build is 1.0.6 ?

**Comment by comonier** [comment]
spigot 1.8.8 citizens 2.0.16 mypet 1.0.6

**Comment by xXKeyleXx** [comment]
https://www.spigotmc.org/resources/mypet-npc.15572/
https://www.spigotmc.org/resources/mypet.12725/

**Comment by comonier** [comment]
that link is from 1.0.6

**Comment by xXKeyleXx** [comment]
1.0.7 is just a dev build with no real changes compared to 1.0.6

**Comment by comonier** [comment]
so what can i do to solve that problem? i am not using any inventory plugin

**Comment by xXKeyleXx** [comment]
What MyPet version are you on?

**Comment by comonier** [comment]
spigot 1.8.8
citizens 2.0.16 
mypet-npc 1.0.6 
mypet 2.1.1

i must to remove the npc, to make player stop to get free egg-spawns

**Comment by comonier** [comment]
letme show my permissions maybe that?

    - citizens.npc.talk
    - MyPet.npc.storage
    - -MyPet.npc.storage.interact
    - -MyPet.npc.storage.bypass
    - MyPet.npc.storage.max.1
    - MyPet.command.release
    - MyPet.command.name
    - MyPet.command.capturehelper
    - MyPet.command.info.other
    - MyPet.command.switch
    - MyPet.command.switch.limit.1
    - MyPet.leash.Zombie
    - MyPet.leash.Skeleton
    - MyPet.skilltree.Combat
    - MyPet.skilltree.Utility
    - -MyPet.skilltree.PvP
    - -MyPet.skilltree.Ride
    - -MyPet.skilltree.Ride.Farm

**Comment by xXKeyleXx** [comment]
It's not a MyPet problem. Which plugins do you have installed?

**Comment by comonier** [comment]
http://prnt.sc/b92z5k

**Comment by comonier** [comment]
can you make a mypet command to help ppl storage the pet..?
cause you already make a command to ppl switch that...
if you do that i will not need mypet-npc or citizens

**Comment by comonier** [comment]
LOOOOL one player already discovery a command /psw store
i dont need the npc anymore ty -- i will ignore this bug without npc.

**Comment by xXKeyleXx** [comment]
I still need to know where this problem came from. Could you ZIP your plugins folder (jars only) and upload it anywhere?

**Comment by comonier** [comment]
no problem
http://www.comonier.net/plugins.zip

**Comment by comonier** [comment]
just tell me if you found the solution ;-P (the plugin who causes the conflit)

**Comment by xXKeyleXx** [comment]
StackableItems is causing it. It just un-cancelles the event that prevents players from taking items out of my menu.

**Comment by xXKeyleXx** [comment]
I think I can fix it from my side.

**Comment by xXKeyleXx** [comment]
Fixed! https://build.keyle.de/job/MyPet/957/

**Comment by comonier** [comment]
i have done the test on my server, its working without bugs now, ty so muth!
