### ISSUE TITLE
Disable Pet fly in specific regions or worlds

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#802]
Could it be possible to add an Option do disable the Pet fly feature in specific worlds or Regions?
Specially i am caring about PvP-Areas. I have Plugins which do not allow Fly and Godmode in a Worldguard-Region where PvP is active. It would be good if MyPet would have such a Worlguard integration or any similar method to specify where flying is not allowed.

**Comment by xXKeyleXx** [comment]
I would love that but WG doesn't support custom flags yet :/

**Comment by xXKeyleXx** [comment]
Added. See Wiki for more info: https://wiki.mypet-plugin.de/doku.php?id=en:configfile

**Comment by zerafox** [comment]
There is a plugin called WorldGuard Custom Flags.
It's an API that allows you to add your own flags and things to World
Guard. I know a couple of plugins use this to apply more flag capabilities
to WG.

**Comment by xXKeyleXx** [comment]
https://www.spigotmc.org/threads/mypet-premium-paid.119508/page-16#post-1620046

**Comment by xXKeyleXx** [comment]
WorldGuard Custom Flags will be added in the next version and will overwrite the flyzones from config when used.
