### ISSUE TITLE
MYPET 1.8

### ISSUE THREAD

**Issue by Endergirl2900** [xXKeyleXx/MyPet#804]
Hey 

We already discussed about this point.. i know. But I payed for a version which says: 

MyPet 2.1.1 (for Minecraft 1.7.10/1.8.X/1.9.X)

so.. what now??? it doesn't work on my server. could you please help me?

Greetings

**Comment by xXKeyleXx** [comment]
If you really want my help you need to give me more info... Logs,errors, info about your setup. So everything I would have expected from you in the first place.

**Comment by xXKeyleXx** [comment]
BTW the moment you bought the plugin you accepted my terms. Plus you had the chance to test it with the free version of MyPet. If it is a bug I will happily fix it, if not it's not my problem.
