### ISSUE TITLE
Player can't Get MyPet why?

### ISSUE THREAD

**Issue by PinoyLifeCraft** [xXKeyleXx/MyPet#806]
Hellow @xXKeyleXx why players in my server reporting to me that they can't get Pets i try it and i can cuz i'm OP can you tell me your suggestion @xXKeyleXx ?

**Comment by xXKeyleXx** [comment]
Then you need to adjust your permissions: https://wiki.mypet-plugin.de/doku.php?id=en:permissions

**Comment by PinoyLifeCraft** [comment]
LOL haven't remember me? I use your Plugin until now even it's always giving me a breaking files :disappointed: And i set that Permission already! Maybe it's GroupManager Problem im using GM for 1.9.4 and i don't think so if it is Verified maybe it's a CopyRight :+1:

**Comment by xXKeyleXx** [comment]
Oh I remember you for sure 😧 😜 When OPs can do what normal players can't do it's always a permission problem. Post your permissions and I will check them for you.

**Comment by PinoyLifeCraft** [comment]
Ok I'll post it all
- > 
[GroupManager.zip](https://github.com/xXKeyleXx/MyPet/files/299343/GroupManager.zip)

**Comment by xXKeyleXx** [comment]
not a single permission is correct... and you wonder why it doesn't work...
