### ISSUE TITLE
Pet max Life and Max Damage

### ISSUE THREAD

**Issue by comonier** [xXKeyleXx/MyPet#807]
All pets starts on level 1 and they can be upgrade to max cap level 100.

Why there is no option to set max Damage / Life for Each Level ?

All pets upgrade life 20 > 22 and stop.
All pets upgrade damage 1 > 6 and stop.

There is any option to modify this values ? On future ?

**Comment by zerafox** [comment]
You can edit everything for pets with the SkillTree editor. Including
Health, Damage, Skills, and when they are obtained.

**Comment by xXKeyleXx** [comment]
As @zerafox said both of these values can be increased by skilltrees (see wiki for more info). Right now you have to increase these value for each level individually. For the time being I would suggest to increase it every 5 to 10 level. But I'm working on a improved version of the skill system that allows to use "level rules". For example: pets gain 1 damage every 5 level.
