### ISSUE TITLE
Item duplication with /peti and /pettrade

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#808]
Player1 offers his pet to Player2.
After pressing the enter button, Player1 types in the /peti command.
When Player2 accepts the trade, Player1 still has acces to the pet's inventory.
Player1 removes everything from his old pet's inventory, because the inventory window was opened when the trade occured.
Player2 types in the /peti command, every single item the pet had is in there. But Player1 has those items too.
This results in the duplication of every item in the pet's inventory

MC 1.9.4, MyPet-Premium 2.1.2-b#245

**Comment by xXKeyleXx** [comment]
Will upload an updated version as soon as the Spigot forums allow me:

https://www.spigotmc.org/threads/the-uploaded-file-is-too-large.153750/

**Comment by Kronox12** [comment]
Thank You :D
