### ISSUE TITLE
Dragon

### ISSUE THREAD

**Issue by Vilican** [xXKeyleXx/MyPet#809]
When I create enderdragon: `/petadmin create -f vilican enderdragon`
It has uncontrollable behavior and it cannot be taken on a lead.
Also, it gets despawned when I fly.

Version: 1.9.4 (Paper 768)
MyPet: 2.1.4

**Comment by xXKeyleXx** [comment]
Enderdragons never really worked as they should. The only problem with them is their sheer size. They are just to big to work with the Minecraft parthfinding. Sure when their vanilla counterparts fly around in the end and it looks nice but they just fly through everything and the rest is just a big open space. I fear they will never be what everyone (including me) wants them to be and I don't have the time and knowledge to fix that :/

**Comment by Vilican** [comment]
Ok, thanks
