### ISSUE TITLE
My Translation doesn't works...

### ISSUE THREAD

**Issue by D3athw0rld** [xXKeyleXx/MyPet#812]
Hi, I created and file MyPet_fr.properties and I have set all of the translation but the plugin is in english... Please help me ! :3 
Sorry for my bad english !

**Comment by xXKeyleXx** [comment]
Is your client in French? 
And there is a French translation included intro mypet.

**Comment by D3athw0rld** [comment]
I understood...
My client is in English (I don't like the french client :3)...
Can I translate in french for users who uses english clients ?
Thanks and sorry for my bad english !

**Comment by xXKeyleXx** [comment]
Rename your french translation to MyPet_en.properties and put it into the locale folder.

If you want you can extract the french translation from the plugin jar (100% translated) and if you don't like a translation you can improve it for everyone ;) https://translation.mypet-plugin.de/translate/fr

**Comment by D3athw0rld** [comment]
That does'nt work...
I'm playing in English (US), it's the good language ?
Thanks !

**Comment by xXKeyleXx** [comment]
It does, I just tried it. Could you upload your translation somewhere (do not just paste it here) so I can test it?

**Comment by D3athw0rld** [comment]
http://pastebin.com/J9Une8zx
Thanks !

**Comment by xXKeyleXx** [comment]
Your file works fine for me. Are you sure you named the file correctly?
![folder](https://cloud.githubusercontent.com/assets/631504/15990117/99ad3806-308a-11e6-91ab-bba1fb241d80.png)

**Comment by D3athw0rld** [comment]
Yep :/
Thanks

**Comment by xXKeyleXx** [comment]
That's strange....
What version of MyPet do you use?

**Comment by D3athw0rld** [comment]
The last... 2.1.3
Thanks

**Comment by xXKeyleXx** [comment]
What happens when you delete the locale folder from the jar (open it with any zipping programm)?

**Comment by D3athw0rld** [comment]
I did it, and I did /petinfo, it said Message.No.HasPet
Thanks

**Comment by xXKeyleXx** [comment]
Ok so the plugin has trouble loading the file. Is there anything that could prevent the plugin to load this file? And again are you 100% sure the file is named correctly and is in the correct folder?

What OS do you use?

**Comment by D3athw0rld** [comment]
I'm using PaperSpigot, maybe that ?
I just verified, and the name is correct... :/
I'm using Windows, because it's my test server
Thanks

**Comment by xXKeyleXx** [comment]
Do you use the normal or the premium version?

**Comment by xXKeyleXx** [comment]
nvm

**Comment by xXKeyleXx** [comment]
I made a version that prints some debug lines to the log.
https://dl.dropboxusercontent.com/u/23957620/crap/MyPet-2.1.4-SNAPSHOT.jar
Please try it with this version and send me the logs.

**Comment by D3athw0rld** [comment]
http://pastebin.com/zBh9TnGm
Thanks.

**Comment by xXKeyleXx** [comment]
The plugin doesn't seem to find the file.
What happens when you enter
C:\Users\coren\Desktop\Serveur Minecraft\plugins\MyPet\locale\MyPet_en.properties
in the adrress bar in your Windows explorer?
