### ISSUE TITLE
MyPet Premium Multi-Server Inventory

### ISSUE THREAD

**Issue by acidbyt3** [xXKeyleXx/MyPet#821]
When using MyPet Premium shared across multiple servers, the pet's inventory is also synchronized, not server-dependent. This can be used to move items between servers, some of which that could be difficult to obtain otherwise. (Eg. Dirt/Diamonds from Survival to Skyblock, OP items to a non-OP server, etc)

Any chance you could add an option to make the inventories server-specific? Either by letting the player choose a prefix for a Pet Inventory table or by having them stored on a local file instead of the database.

As it stands, my only option is to remove the inventory skill from every pet, sadly :/

PS: Great job on the Plugin, everyone absolutely loves it on our server =]

**Comment by xXKeyleXx** [comment]
No, one pet means one inventory. You can block inventories or make them have different pets for different worlds.
