### ISSUE TITLE
Issue with taming an Ender dragon and Premium mypets question.

### ISSUE THREAD

**Issue by Eries** [xXKeyleXx/MyPet#822]
Im trying to tame an Ender Dragon and having a really hard time doing it.

I set the pet-config for the Ender Dragon to
    EnderDragon:
      HP: 200.0
      Speed: 10.0
      Food:
      - 121
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420

I know I have my permissions correct as I have it set to mypet.admin and have had no issue taming any other mob. I also made sure to release any pets I did have prior to trying to tame. 

Any thoughts? If I can get our staff enderdragon pets Im 100% sure they will want me to purchase the premium for the added flight. 
Also can we purchase particle effects for more than 2 players? we currently have 6 admins on our team.

**Comment by xXKeyleXx** [comment]
1. You set the leashflag to low HP that's good
2. You can't fly ender dragons yet
3. well 6 is a lot more than 2 so nope sorry

**Comment by Eries** [comment]
Other than leashflag LowHp is there something else I am supposed to do?
I am still unable to tame ender dragons.

I didnt mean 6 for free. I meant could we purchase 4 more particle effects?
