### ISSUE TITLE
MyPet-NPC wallet

### ISSUE THREAD

**Issue by SgtLegoTown** [xXKeyleXx/MyPet#825]
and use the the pet npc the storage trait work but the wallet isn't. no errors
nothing

i used the command /npc create Cesar --trait mypet-Wallet

**Comment by xXKeyleXx** [comment]
You may need to set it up via commands: https://wiki.mypet-plugin.de/doku.php?id=en:plugins:npc#commands

**Comment by SgtLegoTown** [comment]
i had it working on 1,9, 4 after 1,10 it broke and the premium upgrade ...

**Comment by SgtLegoTown** [comment]
i trues the other command still doens t work i dint iudersatd big fun of your plug in allays worked for me
big fan of this plugin

**Comment by SgtLegoTown** [comment]
i have ever version 1.0,7 the keeper works my-pet-storage -> My-pet Storage

what ever i try my-pet-wallet -> Wallet (Economy) is not working even with the otter commands

**Comment by SgtLegoTown** [comment]
itried evry thing even the dev build no success so far any body any tips ?

**Comment by xXKeyleXx** [comment]
Sorry for the late response. How does your citizens saves.yml look like? Could you upload it to pastebin please.

**Comment by SgtLegoTown** [comment]
i will copy and paste it in a sec but it will help to recompile with the 19 snapshot of citizens i guess and the 1.10.2 release 

http://pastebin.com/VNsA8wrY

**Comment by xXKeyleXx** [comment]
The latest version on Spigot is compiled against the latest MyPet/Bukkit/Citizens versions.
