### ISSUE TITLE
EnderDragon can't be clicked

### ISSUE THREAD

**Issue by ghost** [xXKeyleXx/MyPet#831]
I can't attack,ride and feed EnderDragon.
No matter where I'm from anywhere I can't click on it.
Minecraft version：1.8
spigot version: paperspigot1.8.8

**Comment by Kronox12** [comment]
I think it's a known bug. But I'm not sure.

**Comment by xyblues** [comment]
Minecraft version：1.8
spigot version: paperspigot1.8.8

**Comment by xXKeyleXx** [comment]
I know that this problem exists but I haven't found a way to fix it yet. But it's not super high on my priority list as enderdragons are not usable at all because of their size (besides riding them)
