### ISSUE TITLE
Food item translation bug

### ISSUE THREAD

**Issue by Kronox12** [xXKeyleXx/MyPet#834]
![2016-07-09_14 39 06](https://cloud.githubusercontent.com/assets/14863100/16707781/8a36c964-45e3-11e6-9c1e-449b04c541d7.png)

As you can see, regardless of the client's language (in this case, English UK), the /petinfo doesn't display correctly the name of the food item. I've tried this with Hungarian language too, but it's the same no matter what.

Maybe there is a link between this, and #824 ?

**Comment by xXKeyleXx** [comment]
Well... fuck xD I really thought my solution would be good... It seems that I have to do it the hardcoded way :/ But that has to wait until I have more time ;(

**Comment by Kronox12** [comment]
It seems like that only the fish has this problem (yet :P ) so I don't think that it's necessary to revert the changes.
