### ISSUE TITLE
Problem with beacon effect range 

### ISSUE THREAD

**Issue by Qveshn** [xXKeyleXx/MyPet#838]
In Beacon skill **Buff Range** is always the same. I tried to change it in _skill tree creator_ - all numbers (from 0.00001 to ~1000000 'meter', with 0 beacon just doesn't work) - it still 100 blocks . So all players on spawn takes effects from one of the players pets, which is disturbing.

**Comment by xXKeyleXx** [comment]
It works fine for me (I changed something maybe that fixed it). I will upload a new version now. If the new version doesn't help please upload your config and your skilltree file.

**Comment by Qveshn** [comment]
Thanks! Problem solved! Now it's working normally!
