### ISSUE TITLE
experience and respawn

### ISSUE THREAD

**Issue by cdossow** [xXKeyleXx/MyPet#839]
Greetings, I have 2 problems, no pets gain experience passively, and do not charge money in respawn, I have the Spigot 1.9.4 and mypet 2.1.5, iam using the default config.

Additionally, in my other server also not gain experience by killing mobs, the plugin have some compatibility issue with the mythicmobs plugin?

**Comment by zerafox** [comment]
I don't think mobs gain exp passively by default, so if you're using the
default config they wouldn't.
Also I am not sure that MyPet is mythicmob compatible? IF it is, I'd double
check that config it may be something you have to enable first.

It's ALWAYS a good idea to go through your plugin configs on setup,
especially before creating a ticket. ;P

**Comment by cdossow** [comment]
i checked the config before make this ticket, by default i saw that the pet must gain passive exp, but it's not like that.
```
  Exp:
    DamageWeightedExperienceDistribution: false
    Passive:
      Always-Grant-Passive-XP: true
      PercentPerMonster: 25
```

 i have a local server with few plugins, and other with at least 60 or 70 plugins, in the local server my pet earn exp by killing mobs, but not passively. And in the big server the pets don't earn exp in any form.

in both servers, when the pets revives, the plugin dont charge the fee.

I attached the config file this time, in both server i used Iconomy 7, vault and permissionex for permissions, may be this info help to solve my problem.

sorry for any mistake in traduction, my native language is spanish :)


[config.zip](https://github.com/xXKeyleXx/MyPet/files/370790/config.zip)

**Comment by xXKeyleXx** [comment]
Passive  means that the pet gets XP when the owner kills mobs.
Unless players use the respawn command they will not be charged anything.

**Comment by cdossow** [comment]
my apologies then, I think he had misunderstood, then my only problem remains why pets do not gain experience on my other server, must be a plugin compatibility problem, buy a i have too many to test one by one, dou you have any reference of problematic plugins?

**Comment by xXKeyleXx** [comment]
Maybe you don't have a skilltree selected.

**Comment by cdossow** [comment]
i selected one, and i tried with change it, but dont work

**Comment by cdossow** [comment]
well today the server is restarted, i deleted the old pets and now they can earn exp,sorry for the inconvenience i don't know how could occurred.

thanks for the answers, y love this work, please, support him as much as possible =)
