### ISSUE TITLE
Can a player have more than one pet?

### ISSUE THREAD

**Issue by shellljx** [xXKeyleXx/MyPet#844]

**Comment by tara81** [comment]
yes but you need the mypet-npc and citizens plugins for pet storage i believe. Still only 1 pet active at a time, but extra pets can be stored and retrieved :]

**Comment by shellljx** [comment]
@tara81 but citizens plugin is not work with KCauldron.Unfortunately my server is KCauldron-1.7.10.

**Comment by Phreag** [comment]
You can use the /petswitch command toch change pets.
It ist not possible to have more than one pet at the same time being around you.

**Comment by shellljx** [comment]
@Phreag the /petswitch command need mypet-npc plugin to store pets

**Comment by xXKeyleXx** [comment]
@shellljx NO?!?! The command doesn't need MyPet-NPC at all.
