### ISSUE TITLE
WorldGroups don't work

### ISSUE THREAD

**Issue by PabloMA98** [xXKeyleXx/MyPet#849]
MyPet 2.1.9
Spigot 1.10.2
My config.yml: http://pastebin.com/6nY767YA
My worldgroups.yml: http://pastebin.com/hG1RJ7Hr

I want to allow pets only in "permitidas" worlds, and I have "-MyPet.user.leash.*" set with PermissionsEx in all the "prohibidas" worlds.

**Comment by xXKeyleXx** [comment]
Do they already had them before you disabled leashing in the prohibidas worlds? DO they change the pet when they teleport between a prohibidas and a permitidas world?
