### ISSUE TITLE
Please add option view other players petinventory! /peti <player name>

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#851]

**Comment by xXKeyleXx** [comment]
It's already possible. The only restriction ist that the player has to be online

- /petinventory <playername>

**Comment by andris155** [comment]
Please add custom permission this command!
- MyPet.command.petinventory.others

**Comment by xXKeyleXx** [comment]
It's an admin feature therefore you need the MyPet.admin permission. I might change that in the future but for now it will stay that way.

**Comment by andris155** [comment]
I don't like MyPet.admin permission, because grant all mypet permissions my staffs.

**Comment by xXKeyleXx** [comment]
Yeah I thought that this would be your concern ;) I will split the admin permission in the near future and this will be part of it.

**Comment by xXKeyleXx** [comment]
#852
