### ISSUE TITLE
MyPet Premium 2.2.0 fire arrow kill bug

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#854]
https://www.youtube.com/watch?v=d8Ax-j-Ay_g

**Comment by xXKeyleXx** [comment]
Is it a normal flame bow? I guess it's a WG protected region?

**Comment by andris155** [comment]
flame bow + WG protected region

**Comment by xXKeyleXx** [comment]
But you got the error from the other ticket on server start didn't you?
