### ISSUE TITLE
MyPet v2.2.6 Premium PvPManager 3.6 premium hook not work (?)

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#857]
03.08 12:27:19 [Server] INFO Enabling MyPet v2.2.6
03.08 12:27:19 [Server] INFO MobArena (0.97.1)(com.garbagemule.MobArena.MobArena) hook activated.
03.08 12:27:19 [Server] INFO NoCheatPlus (3.15.0-SNAPSHOT-sMD5NET-b1022) hook activated.
03.08 12:27:19 [Server] INFO ProtocolLib (4.0.2) hook activated.
**03.08 12:27:19 [Server] WARN Please use PvPManager build 113+**
03.08 12:27:19 [Server] INFO SurvivalGames (Beta 1.9.5)(me.maker56.survivalgames.SurvivalGames) hook activated.
03.08 12:27:20 [Server] INFO Vault (1.5.6-b49) hook activated.
03.08 12:27:20 [Server] INFO WorldGuard (6.1.2;e38d98d) hook activated.
03.08 12:27:20 [Server] INFO Compat mode for v1_10_R1 loaded.
03.08 12:27:20 [Server] INFO --- Loading WorldGroups ---------------------------
03.08 12:27:20 [Server] INFO added 'world' to 'default'
03.08 12:27:20 [Server] INFO added 'world_nether' to 'default'
03.08 12:27:20 [Server] INFO added 'world_the_end' to 'default'
03.08 12:27:20 [Server] INFO added 'plotworld' to 'default'
03.08 12:27:20 [Server] INFO added 'Spawn' to 'default'
03.08 12:27:20 [Server] INFO added 'event' to 'default'
03.08 12:27:20 [Server] INFO added 'SurvivalGames' to 'default'
03.08 12:27:20 [Server] INFO -------------------------------------------------
03.08 12:27:20 [Server] INFO Thank you for buying MyPet-Premium!
03.08 12:27:20 [Server] INFO version 2.2.6-b326P ENABLED
03.08 12:27:20 [Server] INFO mypet has been loaded and enabled.
03.08 12:27:20 [Server] INFO Added hook: MyPet [1.0].

**Comment by xXKeyleXx** [comment]
PvPManager Premium is obfuscated so it's very unlikely that it will work. Unless the dev will provide any kind of API I will not try to make it compatible again.
