### ISSUE TITLE
MyPET compatibility with GriefPreventionPlus

### ISSUE THREAD

**Issue by CaioWzy** [xXKeyleXx/MyPet#860]
Hi, there's a nice fork of GriefPrevention called [GriefPreventionPlus](https://github.com/KaiKikuchi/GriefPreventionPlus) that is not recognized by MyPet, could you make it work with GriefPreventionPlus also?

Thanks!

**Comment by xXKeyleXx** [comment]
Where can I get the jar of this plugin? or do I have to compile it myself?

**Comment by xXKeyleXx** [comment]
Please check it out and tell me if it works: https://build.keyle.de/job/MyPet/1043/
