### ISSUE TITLE
More WorldGuard Flags

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#863]
By now you only have the mypet-damage flag in worldguard.
Could it be possible to add one or both from the following:

**mypet-disable**: Disables Pets completely in a specific area, they will despawn if the owner enters the flag and cannot be called when within the flag.

**mypet-fly**: the feature is already there but needs to be configured in the config. managing via flag would be more comfortable

**Comment by xXKeyleXx** [comment]
1. Will add that flag 
2. mypet-fly was the first flag I added ;) so it's already in there.

**Comment by ScuroK** [comment]
and there is the super awesome myped-deny flag aswell. but yeah flags are a nice thing ti have :)
