### ISSUE TITLE
Bug: Pets attack players in a PVE world with PVP disabled

### ISSUE THREAD

**Issue by Nachodiazv** [xXKeyleXx/MyPet#864]
Hi, can you add a world list in where the DisablePetVersusPlayer can be true or false in specific worlds?
For example, I have a Survival world and a PvP world. I want to enable player vs pet only in the PvP world.

Thanks .

**Comment by zerafox** [comment]
Pets can only attack other players when the players could do so too.
If you have a PvE world where PvP is disabled, the pets shouldn't be able
to attack players either.

**Comment by Nachodiazv** [comment]
Well then if Im posting this, its because the new version of MyPet premium has this bug. When players put pb in aggresive, pets are able to atrack player in my Pve world with PVP disabled

**Comment by xXKeyleXx** [comment]
Which plugin disables the PvP in this world?

**Comment by Nachodiazv** [comment]
Multiverse Core

**Comment by Nachodiazv** [comment]
Hi, I discovered something strange. Apparently the plugin inverted de game rules. In my PvP world pets don't attack players... And in my no PvP world pets attack players. 

I don't understand whay this is happening. Im usind your plugin seens an long time and in 1.8 every thing was perfect so if I upgraded to 1.9 premium and Im using the same config this might be somthing with the plug.

**Comment by Nachodiazv** [comment]
Hi! I'm using spigot version 1.9.4, Multiverse version 2.5
I upgraded to the last build you uploaded and this bug continues.

When you hit a pet that is in normal or agressive, pet can hit you even if you are in a world with PvP disabled

**Comment by xXKeyleXx** [comment]
A fixed version will be uploaded tomorrow.
