### ISSUE TITLE
Load button für Skillcreator

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#865]
Could u add a way to import/load own mypetskilltree? At the moment I can only save and will be very happy when I can load my skilltrees to rework.

**Comment by zerafox** [comment]
The editor reloads your skilltrees from the folder located in the same
location as the editor. If you're saving your skilltrees in a different
location than the default, you'll need to move them to the default location
the skilltree editor tries to save them in, so it can reload them the next
time you open the editor.

**Comment by xXKeyleXx** [comment]
When you start the SkilltreeCreator it expects the same folder structure as it would be in the plugins folder of your server. So download the MyPet folder from your server and put it in the same folder like the jar.

**Comment by Sprungente** [comment]
ahh it's works thanks
