### ISSUE TITLE
Maven cannot find parent

### ISSUE THREAD

**Issue by games647** [xXKeyleXx/MyPet#867]
I'm trying to use this project as a dependency, but it fails, because it cannot find the mypet-parent. My issue seems to be similar to #830 and I tried to @Rocologo project pom, but it stills fails for me. 

Tried with

```xml
        <!--MyPet-->
        <repository>
            <id>mypet-repo</id>
            <url>https://nexus.keyle.de/content/groups/public/</url>
        </repository>

        <dependency>
            <groupId>de.keyle</groupId>
            <artifactId>mypet</artifactId>
            <version>2.2.4</version>
        </dependency>
```

**Comment by Rocologo** [comment]
<repository>
			<id>mypet-repo1</id>
			<url>http://repo.keyle.de/</url>
		</repository>

**Comment by xXKeyleXx** [comment]
I have this problem with MyPet-NPC too :/

I have 2 options here but I don't know which way I should go:

1. switch to Gradle
2. fix project structure

**Comment by xXKeyleXx** [comment]
It will work with the latest build (2.2.5-SNAPSHOT) again.

**Comment by games647** [comment]
It still doesn't work for me. Same repository link, but the different version as you told us.

```xml
            <dependency>
                <groupId>de.keyle</groupId>
                <artifactId>mypet</artifactId>
                <version>2.2.5-SNAPSHOT</version>
            </dependency>
```

I even tried it from a different maven local repository. I think it's because only the MyPet module is hosted on the maven repo not the parent pom and so doesn't even know about the change from the last commit e46f4c96c5892275d365df890fcd9cfb3d7c3217

**Comment by xXKeyleXx** [comment]
Please use http://repo.keyle.de/ as the repo URL. I know they are the same but I prefer others to use this URL.

Have you tried to delete MyPet from your local repo?

I really need to switch to a better project structure or gradle....

**Comment by games647** [comment]
I will be redirected to the other repo url anyway, but I give it a try.

>Have you tried to delete MyPet from your local repo?

Yes deleted all everything. So even it's not cached (although -U refetches the stuff too). 

No it doesn't work neither.

**Comment by xXKeyleXx** [comment]
Please try it again.

**Comment by games647** [comment]
Yes it works now.
