### ISSUE TITLE
Support for Residence - flags

### ISSUE THREAD

**Issue by renzotom** [xXKeyleXx/MyPet#868]
Hello, you adding flags to WorldGuard plugin, but you can also add flags to Residence plugin. Here is API for own flags in Residence plugin - https://github.com/bekvon/Residence/wiki/API. My question is, can you add flags from WorldGuard to Residence plugin?

**Comment by renzotom** [comment]
Why it is  Closed?

**Comment by xXKeyleXx** [comment]
I implemented it, got no feedback = I guessed everything works fine = close

**Comment by renzotom** [comment]
And when it will be released?

**Comment by xXKeyleXx** [comment]
In the next update. The free version has dev builds where you can try it.
