### ISSUE TITLE
Petranklist

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#869]
Today I've edited some skilltree's with Mypet-**Premium** i had a good idea.

Could you add a petranklist maybe with /pettop to display the pets with Petownername Petname exp and level? I think it's a good idea to bind users.

**Comment by xXKeyleXx** [comment]
I'm not sure what you mean. Erklär mal auf deutsch was du meinst. Vllt. versteh ich dich dann ;)

**Comment by Sprungente** [comment]
Ahh Deutsch, kommt mir als Schweizer entgegen
also....
Als ich heute Skillbäume mit Mypet-Premium gemacht habe ist mir ein Wunsch aufgekommen.

Könntest du (evtl als Premiumfeature) einen neuen Befehl einführen, der eine Rangliste mit Pet's anzeigt.
Dort könnte angezeigt werden:
Rang Petname Petinhaber XP und Level 

Diese Rangliste kann man in der Config einstellen, wie viele Plätze angezeigt werden. (Default schlage ich 10 vor)

BSP:
1. Schwein Spieler1 6/7 lvl1 
2. Huhn Spieler2 5.8/7 lvl1
usw. bis rang 10. Am ende der Rangliste steht die Rangposition des aktuellen Pets, sofern man nicht unter den top 10 (in unserem Beispiel) ist.
BSP:
9. Schwein Spieler1 1/7 lvl1 
10. Huhn Spieler2 0.8/7 lvl1
17. Spinne Dein Pet 0.1/1 Lvl1

Damit könntest du
- Die Premiumversion attraktiver machen

Für Spieler würde es den Anreiz geben, das stärkste und höchste Pet zu haben.

Hoffe dir gefällt meine Idee/Wunsch

**Comment by xXKeyleXx** [comment]
Chat oder Scoreboard?

An sich ist die Idee nicht schlecht aber die Auswertung könnte kompliziert werden. Ich muss mal schauen ob ich das ohne weiteres hin bekomme. Möglich ist es auf jeden Fall nur der Aufwand können ein Problem werden.

**Comment by Sprungente** [comment]
Chat

**Comment by xXKeyleXx** [comment]
Naja eig wäre beides sinnvoll xD Ich schau mal.
