### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#870]
Language file / Text:

- [x] ''Max level for this skilltree reached!'' string can't be translated.
- [x] Max level for this skilltree reached message shoots on lvl 10, while the max level is 15.
- [x] The stomp upgrade message placeholder is broken: http://imgur.com/Uq8nnUz
- [x] A , misses between Aggresive and Duel: http://imgur.com/Uq8nnUz
- [X] When your pet dies because of a Cave Spider, it shows name.cavespider
- [X] Another issue with name.SmallFireball: http://imgur.com/LU3KdVj
- [X] Stomp upgrade message shoots twice instead of once.

Pathfinder:

- [x] Pets push you off blocks due to the 1.10 collisions.
- [x] You can't push pets away when they are in front of you when building.

**Comment by xXKeyleXx** [comment]
Language file / Text:
- #829 This text is part of the skilltree and can be changed there
- Have you changed the max level in the config and on the skilltree?
- The image is not correct but I guess the broken placeholder was in the first upgrade message

Pathfinder:
- I'm on that
- send them away when you want to build

**Comment by Sikatsu** [comment]
- You mean can't be changed yet, but planned?
- Yes I did, and you can actually just lvl to 15, tho it says the level cap is 10. (It was before, just not anymore)
- Right, well it shows {2} in the stomp upgrade message, the second placeholder I believe.

Thanks

**Comment by Sikatsu** [comment]
Dutch translation file: https://www.dropbox.com/s/a5fbkdusgydhpxr/MyPet_nl.properties?dl=0

**Comment by xXKeyleXx** [comment]
- You can change it with the SkilltreeCreator. It's the level up message of level 10.
- If you set a max level in the skilltree it will use this level. otherwise the max level from the config will be used

- I disabled collisions for 1.9+ pets. Only downside is you can't push your pets around anymore.

**Comment by Sikatsu** [comment]
- Ahhh now I see what you mean, thanks!

- I believe you couldn't push away the pets anyway as I mentioned before ^^ Thanks!

**Comment by Sikatsu** [comment]
@xXKeyleXx Not sure if this is intended or if it's a bug, but I just updated to the latest devbuild and now my pet has the green particle which I believe is from the Premium version of MyPet.

Thanks for the help and quick fixes! Finally found a good pet plugin replacement,

If I find more bugs or feature requests I'll inform you. If the plugin is popular for my players I'll buy the premium version.

**Comment by xXKeyleXx** [comment]
The particles are only for you because you are a translator ;)

**Comment by Sikatsu** [comment]
Ohh really, much appreciated! Btw, my pet didn't have collisions, I right clicked on the pet once and now it seems to have collisions again :P

**Comment by Sikatsu** [comment]
Collisions seem to be gone again after a server reload, interesting

**Comment by xXKeyleXx** [comment]
That doesn't happen to me. If it happens again please tell me what type the pet is.

**Comment by Sikatsu** [comment]
Cave spider > Combat skilltree. You can come and see on my test server eventually.

At first, the collisions were gone, now it's back but I can push away the pet now.

**Comment by xXKeyleXx** [comment]
Is the pet yours? Are there any errors in the logs?

**Comment by Sikatsu** [comment]
I'm with a friend on my test server, his pet doesn't have collisions, mine does. Then randomly his pet has collisions, and mine doesn't lol. There are no errors.

I also noticed a placeholder bug I believe? http://imgur.com/vzWEUW3

**Comment by xXKeyleXx** [comment]
https://translation.mypet-plugin.de/translate/nl/Name$SmallFireball

Give me your server address please so I can check it out.

**Comment by Sikatsu** [comment]
Will translate that soon today, first making the plugin ready to be on my official server.

Test server: 185.133.72.30:25576
