### ISSUE TITLE
Show level instead of XP in switch menus

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#871]
- It will be nice if instead of EXP, the level of the pet shows within the NPC.
- Show the pet level within the name ''Winstin [Level 10]'' (config option)

Question, how well does it work with AAC? (Instead of NCP)

**Comment by Sikatsu** [comment]
-  Ah I see, because within /pinfo it shows the level, I thought it might've been possible to show the level within the NPC and /petswitch command. Thanks for the answer :)

- Whoops, missed that, thanks for pointing it out.

Will test it with AAC, thanks for your response!

**Comment by xXKeyleXx** [comment]
- The level is calculated when the pet gets activated. But they don't get activated in the switch menus. I will change that in the future but this might take some time to rewrite every part of the skill system.

**Comment by Sikatsu** [comment]
Understood, thanks!
