### ISSUE TITLE
Some bugs and a feature request

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#875]
Bugs:

- [x] The colorcode shows up when buying a pet:  http://imgur.com/a/vTrTS
       Happens when you add a colorcode in the name thru the pets-shop.yml file.

- [x] Money placeholder not working, same image as above.

- [x] ''{petname} is hungry. You need to feed Winston now!'' As you see, placeholder is broken in this string.

- [x] Small issue within the shop confirm message: http://imgur.com/a/SX0n9

- [x] The regrow wool feature for the sheep doesn't seem to work. Tested with the default item aswell for item ID 2.

- [x] Shearing the sheep doesn't seem to work correctly, even while it gave 2 random wools.

Question:

- [x] I made a new dutch translation suggestion, please merge it (not sure if you receive a message)
      Message.Command.Trade.Owner.Offer.Price

Feature request:

- [x] When you want to buy a pet, it says ''You already have a MyPet''. Could you add an option so that the pet you buy automatically goes to the NPC storage somehow? Maybe with some permission.

**Comment by xXKeyleXx** [comment]
Please don't translate the messages when you find problems with the translations.

Is it like {petname} in the chat or how does it look like?

Do you think it would be a good idea to merge all storage permissions together?

**Comment by Sikatsu** [comment]
Alright, thought it might be easier for you to find out the correct message.

It i deed shows {petname} in blue in the chat. Forgot to screenshot it yesterday.

How do you mean merge exactly?

**Comment by xXKeyleXx** [comment]
Not really :P

Do you have a translation file in your locale folder? Because there is not a single line in any of the translations with {petname}.

One permission to handle the storage for: NPC, switch command & shop

**Comment by Sikatsu** [comment]
A very old one, but since the new translations show up in-game I thought that file doesn't matter. It's one of the hungry messages.

Hmm, well, my players do not have the permission for the switch command, as I prefer them to use the NPC then switching with a command. However, it would be nice if somehow when you buy a pet it automatically goes to the NPC storage. 

"Your new MyPet can be collected by an NPC/Pet Master"
"You can't buy this MyPet because the max storage has been reached"

**Comment by xXKeyleXx** [comment]
Your own translation files will overwrite the latest translations so that is the case for your {petname}problem ;)

All the systems (NPC, switch & shop) use the same storage anyway and one permission could bypass another one. So merging them together might make it more simple to set it up. I asked to merge them because I would need to add a 3rd permission for the same storage...

**Comment by Sikatsu** [comment]
Ah, will remove that file then.

I know, but i'm planning to make the switch command for certain higher ranks, so they should not be able to use /petswitch, but just the NPC's within the spawn. :/

**Comment by xXKeyleXx** [comment]
Using the command is not what I talk about. I talk about the amounts of pets a player can store with any of the methods.

**Comment by Sikatsu** [comment]
Ooh, merging these would be good yes.
