### ISSUE TITLE
Permission is useless

### ISSUE THREAD

**Issue by zzvenuszz** [xXKeyleXx/MyPet#876]
I added fllowing permission to players group:
- MyPet.npc.storage

But players still cant use mypet NPC.

**Comment by Sprungente** [comment]
Which version to use:
Spigot
Citizens
Mypet-NPC
Mypet

Does your Permissionsystem inherit previous groups? When yes, then could it something wrong. 


A similar problem I had recently. Maybe I can help you,

**Comment by xXKeyleXx** [comment]
MyPet.npc.storage only allows to interact with the NPC at all. You need to set the amount a player can store before they can use it.

- MyPet.npc.storage.max.<amount>
