### ISSUE TITLE
Erfolge und Statistiken

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#879]
Wie wäre es, dass man Erfolge (auch benutzerdefinierte) Erfolge und Statistiken bekommen kann. Die Erfolge könnten auch ein GUI bekommen, bei dem auf einem Item den Erfolgname (Beispiel Duelikat)  und was dafür erforderlich **war** (Beispiel Gewinne ein Duell gegen ein anderes Haustier). **war** weil ich es als gute Idee fände, dass man als Spieler die noch nicht erhaltenen Erfolg noch nicht ansehen sollte. Dies sollte zum Wohle der Mehrheit in der Config änderbar sein. Vorgeschlagener Befehl /petachievements abgekürzt /peta

Bei den Petstatistiken habe ich die Idee, dass man mit /petstats statistiken einsehen kann. Beispiel Wie viel es gestorben ist, gefüttert wurde, wann es eingefangen wurde, wie viele Petduelle es gewonnen/verloren hat etc.  

Das ganze noch in einer Checkliste verpackt
- [ ] Peterfolge
- [ ] Petstatistik

**Comment by xXKeyleXx** [comment]
Irgendwann werd ich sowas vielleicht hinzufügen, aber im Moment sind andere Sachen wichtiger.
