### ISSUE TITLE
/petshop Permissionsfehler

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#880]
Ich hab heute für meinen Server die neue Version runtergezogen, /petshop funktioniert mit allen Permissions und Op-Rechte nicht. Meldung: Du darfst das nicht benutzen.

Wenn ich einen NPC mit dem trait mypet-shop rechtsklicke, kommt die Meldung (glaub ich) auf norwegisch statt auf Deutsch.

**Comment by Sprungente** [comment]
Der Permissionsfehler ist behoben worden, doch ich kann nicht den NPC Shop benutzen.

Meldung: Thar iz no shop wif dis naym (Obwohl die Sprache auf deutsch gestellt ist)

Ich hab den trait mypet-shop auf den NPC gemacht und danach /mypetnpcconfig shop default eingegeben. Die Meldung ist immer noch dieselbe.

**Comment by xXKeyleXx** [comment]
Ups xD hab die deutsche mit der lolcat Übersetzung vertauscht...  zum glück kommt die Meldung in der Regel nicht so oft :D

**Comment by xXKeyleXx** [comment]
also die default shops heißen all und babies, du musst also folgende Befehle benutzen:

/mypetnpcconfig shop all
oder
/mypetnpcconfig shop babies

**Comment by Sprungente** [comment]
xD kann mal passieren und der Shop funktioniert auch.
