### ISSUE TITLE
[BUG] Petshop Slime/Magma Cube

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#881]
When buying a slime within the adult shop, it will give a baby slime instead of a big/medium slime.

Same goes for the Magma Cube.

**Comment by xXKeyleXx** [comment]
That's not a bug as slimes can not be baby. The default size is 1. Just add size:2 to the options for slimes and magmacubes.

I will change it in the default shop file.

**Comment by Sikatsu** [comment]
Thanks.

**Comment by Sikatsu** [comment]
@xXKeyleXx This doesn't seem to work tho

**Comment by Sikatsu** [comment]
@xXKeyleXx 

Closed, but still not working? Even if I add the size, it stays tiny? :o

**Comment by xXKeyleXx** [comment]
The reload doesn't work so it has nothing to do with the size.

**Comment by Sikatsu** [comment]
Aha, it worked before tho?
