### ISSUE TITLE
Can't regrow sheep wool

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#882]
I can't seem to give the sheep wool anymore after shaving him.

**Comment by xXKeyleXx** [comment]
It takes a looooong time to regrow (~10x the normal rate).

**Comment by Sikatsu** [comment]
What? How many times do I need to click to let him grow wool? I told you yesterday it didn't work and tested again today, but still my sheep has no wool o.O

**Comment by xXKeyleXx** [comment]
You can't force grow the wool. You have to wait (on grass blocks) for it to regrow like for normal sheeps

**Comment by Sikatsu** [comment]
Where are these for then? Pets don't eat grass, or atleast the animation is gone. Weird

     CanRegrowWool: true
      GrowUpItem: 2

**Comment by xXKeyleXx** [comment]
CanRegrowWool -> can regrow wool
GrowUpItem -> baby to adult

**Comment by Sikatsu** [comment]
Oh, right. I thought those were linked to eachother.
