### ISSUE TITLE
Pets seem to have collisions again

### ISSUE THREAD

**Issue by Sikatsu** [xXKeyleXx/MyPet#883]
Pets seem to have collisions again..

**Comment by Sikatsu** [comment]
Can be tested on my server. (Not the test server)

**Comment by xXKeyleXx** [comment]
All pets or just some types?

**Comment by Sikatsu** [comment]
It seems all pets.

**Comment by Sikatsu** [comment]
May be closed.

In it's current state it seems the pets won't push you away. And when the pets are in the way, you can push them away.

In case I get complains from players, which I think I won't, i'll reopen it. Tho I think we are fine :)
