### ISSUE TITLE
error in the command /petcall

### ISSUE THREAD

**Issue by esleeser** [xXKeyleXx/MyPet#888]
09-02-2016 12:12 [INFO] [MyPet] Compat mode for v1_7_R4 loaded.
09-02-2016 12:12 [INFO] [MyPet] Default skilltree file created (default.st).
09-02-2016 12:12 [INFO] [MyPet] No groups found. Everything will be in 'default' group.
09-02-2016 12:12 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
09-02-2016 12:12 [INFO] [MyPet] added spawn to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] added spawn_nether to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] added spawn_the_end to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] added arena to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] added world_nether to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] added Comz to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] added quake to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] added word to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] added world_the_end to 'default' group.
09-02-2016 12:12 [INFO] [MyPet] -------------------------------------------------
09-02-2016 12:12 [INFO] [MyPet] version 2.0.0-b873 ENABLED
09-02-2016 12:14 [INFO] [MyPet] Disabling MyPet v2.0.0
09-02-2016 12:14 [INFO] [MyPet] Compat mode for v1_7_R4 loaded.
09-02-2016 12:14 [INFO] [MyPet] [NBT] 0 PetPlayer(s) loaded
09-02-2016 12:14 [INFO] [MyPet] [NBT] 0 pet(s) loaded
09-02-2016 12:14 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
09-02-2016 12:14 [INFO] [MyPet]    added 'spawn' to 'default'
09-02-2016 12:14 [INFO] [MyPet]    added 'spawn_nether' to 'default'
09-02-2016 12:14 [INFO] [MyPet]    added 'spawn_the_end' to 'default'
09-02-2016 12:14 [INFO] [MyPet]    added 'arena' to 'default'
09-02-2016 12:14 [INFO] [MyPet]    added 'world_nether' to 'default'
09-02-2016 12:14 [INFO] [MyPet]    added 'Comz' to 'default'
09-02-2016 12:14 [INFO] [MyPet]    added 'quake' to 'default'
09-02-2016 12:14 [INFO] [MyPet]    added 'word' to 'default'
09-02-2016 12:14 [INFO] [MyPet]    added 'world_the_end' to 'default'
09-02-2016 12:14 [INFO] [MyPet]  registered 'default' group
09-02-2016 12:14 [INFO] [MyPet] -------------------------------------------------
09-02-2016 12:14 [INFO] [MyPet] version 2.0.0-b873 ENABLED
09-02-2016 12:14 [INFO] [MyPet] Disabling MyPet v2.0.0
09-02-2016 12:16 [INFO] [MyPet] Compat mode for v1_7_R4 loaded.
09-02-2016 12:16 [INFO] [MyPet] [NBT] 0 PetPlayer(s) loaded
09-02-2016 12:16 [INFO] [MyPet] [NBT] 0 pet(s) loaded
09-02-2016 12:16 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
09-02-2016 12:16 [INFO] [MyPet]    added 'spawn' to 'default'
09-02-2016 12:16 [INFO] [MyPet]    added 'spawn_nether' to 'default'
09-02-2016 12:16 [INFO] [MyPet]    added 'spawn_the_end' to 'default'
09-02-2016 12:16 [INFO] [MyPet]    added 'arena' to 'default'
09-02-2016 12:16 [INFO] [MyPet]    added 'world_nether' to 'default'
09-02-2016 12:16 [INFO] [MyPet]    added 'Comz' to 'default'
09-02-2016 12:16 [INFO] [MyPet]    added 'quake' to 'default'
09-02-2016 12:16 [INFO] [MyPet]    added 'word' to 'default'
09-02-2016 12:16 [INFO] [MyPet]    added 'world_the_end' to 'default'
09-02-2016 12:16 [INFO] [MyPet]  registered 'default' group
09-02-2016 12:16 [INFO] [MyPet] -------------------------------------------------
09-02-2016 12:16 [INFO] [MyPet] version 2.0.0-b873 ENABLED

**Comment by xXKeyleXx** [comment]
I don't see any errors there.

**Comment by xXKeyleXx** [comment]
And the version of MyPet you are using is older than the dinosaurs...
