### ISSUE TITLE
Armor stand pets

### ISSUE THREAD

**Issue by renzotom** [xXKeyleXx/MyPet#892]
Hello, can you add sometimes armor stand pets (pets from armor stand with hand, items, equipments, animations....)? Later. If yes, add it to feature list please :D .

**Comment by Sikatsu** [comment]
Like a MiniMe, not that I'm a developer but I guess it wouldn't be to hard :P

**Comment by renzotom** [comment]
Yes, but with function of  every pet, so you can ride, fly, level up...
