### ISSUE TITLE
Custom pets (like custom furniture)

### ISSUE THREAD

**Issue by renzotom** [xXKeyleXx/MyPet#895]
Hello, can you add sometimes  custom pets (like is furniture via command blocks or without them, like plugin Vehicles, maybe also way to create own custom pets)? Later. If yes, add it to feature list please :D .

**Comment by renzotom** [comment]
Why is Custom Pets idea  declined? It can be great feature later.
Ex. in Vehicles plugin you can also ride, fly, all blocks move.... so I think, it can be

**Comment by xXKeyleXx** [comment]
MyPet is not that kind of plugin.

**Comment by renzotom** [comment]
But it will be pets, only custom :D .
