### ISSUE TITLE
language Dutch

### ISSUE THREAD

**Issue by TurcQuase** [xXKeyleXx/MyPet#896]
Hi, I was trying to download the languages on your wiki. 
but i can't and i don't know if i can or its bugged.
I can write my own but you have a loooottttt of translations in there..
Can you please help me?

Greetings, Noah

**Comment by xXKeyleXx** [comment]
Is there something wrong with the current one?

**Comment by TurcQuase** [comment]
Oh i have never seen that one before, couldn't find it at all. Now i can use it! Thanks Keyle :)

**Comment by xXKeyleXx** [comment]
The version you can download there is included into the plugin so you don't need it if you don't want to modify it.
