### ISSUE TITLE
Random skilltree assignment weighting

### ISSUE THREAD

**Issue by xXKeyleXx** [xXKeyleXx/MyPet#898]
Add a way to weight the rolls so that you can a have common/uncommon/rare tree setup and make it 70/20/10% chance of getting them when a pet is captured.

**Comment by zerafox** [comment]
I am eagerly awaiting this update for MyPet 3.0 myself.
Sadly with my current skill tree system I cannot update to 3.0 with another unique system in place.

My Skilltrees are just too advanced for the non-inheritance of 3.0 at this time.
With a system like this I can create something else unique for our pets instead.
Or the possibilities of a combination of the two! Oh, I'm getting excited just thinking about it. :)
