### ISSUE TITLE
MySQL port problem

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#900]
Hallo, könnte mir jemand kurz helfen?

Ich wollte auf MYSQL wechseln, habe mir diese Seite zur Hilfe genommen. https://wiki.mypet-plugin.de/doku.php?id=en:how_to_upgrade_from_file_to_mysql
Nun habe ich das Problem: Seit dem 4.9 sind die Pets in einer pets.db gespeichert.
Mypet möchte nach Umstellung in der Config nichts in der MySQL-Datenbank erstellen. Eine meldung in den Logs ist nicht vorhanden.
Was habe ich falsch gemacht?

**Comment by xXKeyleXx** [comment]
Du musst eigentlich nur anstelle von **NBT**, **SQLite** eintragen. Ich werde den Wiki Eintrag später aktualisieren.

**Comment by Sprungente** [comment]
Habe ich gemacht. Hab aber immernoch das gleiche Problem. Mypet möchte nichts mit der MYSQL-Datenbank anfangen, möchte nicht einmal auf die MQSql wechseln :(

**Comment by xXKeyleXx** [comment]
wrote sieht der storage Anschnitt deiner config den aus?

**Comment by Sprungente** [comment]
https://gist.github.com/Sprungente/e6649d74680ea4374d90a763a18edb7b

Ist eine Kopie meiner config.yml

**Comment by xXKeyleXx** [comment]
Hm... die Config sieht gut aus. Aber du hast die Premium version drauf oder?

**Comment by Sprungente** [comment]
ja hab ich

**Comment by xXKeyleXx** [comment]
Haste es mittlerweile hinbekommen?

**Comment by Sprungente** [comment]
ne hat noch nicht geklappt

**Comment by xXKeyleXx** [comment]
könntest du mir deinen MyPet Ordner ZIPen und mal hochladen?

**Comment by Sprungente** [comment]
http://www.filedropper.com/mypet

**Comment by xXKeyleXx** [comment]
Also bei mir hats einwandfrei geklappt. Und laut den logs zufolge hat es bei dir auch schon (mehrfach) geklappt. Woran merkst du denn das es nicht geklappt hat?

**Comment by Sprungente** [comment]
Wenn ich in die MySQL rein schaue, zeigt es mir nichts an, keine einzige Tabelle, leer mit 0b

**Comment by Sprungente** [comment]
Gibts mittlerweile eine Lösung ?

Damit du es auch bildlich siehst, dass in der MySQl nichts ist: https://picload.org/view/rddgwppd/neuebitmap.png.html

**Comment by xXKeyleXx** [comment]
da du leider der einzige bist und ich keine Ahnung habe warum der bei dir nicht will kann ich dir nur anbieten das bei mir zu konvertieren und dir als SQL Datei zu schicken

**Comment by xXKeyleXx** [comment]
steht im Lot von deinem SQL Server eig irgendwas diesbezüglich?

**Comment by Sprungente** [comment]
Hab die SQl im Petordner testweise gelöscht, somit war das plugin gezwungen eine neue Datenbank zu erstellen. Hat vielleicht diese Warnung was damit zu tun?
27.09 00:15:40 [Server] WARN RepositoryInitException{exception=de.Keyle.MyPet.util.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization: HikariPool-0 - Connection is not available, request timed out after 30000ms.}
27.09 00:15:40 [Server] WARN at de.Keyle.MyPet.repository.types.MySqlRepository.init(MySqlRepository.java:92)
27.09 00:15:40 [Server] WARN at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:267)
27.09 00:15:40 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
27.09 00:15:40 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
27.09 00:15:40 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
27.09 00:15:40 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
27.09 00:15:40 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
27.09 00:15:40 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
27.09 00:15:40 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
27.09 00:15:40 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
27.09 00:15:40 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
27.09 00:15:40 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
27.09 00:15:40 [Server] WARN at java.lang.Thread.run(Unknown Source)

**Comment by Sprungente** [comment]
Die Datenbank wurde aber trotz allem wieder im Mypetordner erstellt

**Comment by xXKeyleXx** [comment]
Ja wenn MySQL nicht klappt fällt der auf SQLite zurück.

Ok das Problem liegt echt beim Plugin... Für den Port wird auch der Datenbankname verwendet :no_good: 
Manchmal frage ich mich echt was die anderen mit dem Plugin machen dass das Monatelang nicht auffällt...

**Comment by xXKeyleXx** [comment]
It should be fixed in the latest dev build
