### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Rocologo** [xXKeyleXx/MyPet#904]
I get this error it looks like MyPet still works, but you must have some kind of error in your SQL statements.

> [08:37:56] [Craft Scheduler Thread - 73/WARN]: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (column name is not unique)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at org.sqlite.DB.newSQLException(DB.java:383)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at org.sqlite.DB.newSQLException(DB.java:387)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at org.sqlite.DB.execute(DB.java:342)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at org.sqlite.DB.executeUpdate(DB.java:363)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at de.Keyle.MyPet.repository.types.SqLiteRepository$14.run(SqLiteRepository.java:956)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [08:37:56] [Craft Scheduler Thread - 73/WARN]:    at java.lang.Thread.run(Thread.java:745)
> [08:37:56] [Server thread/INFO]: Command executed successfully!
> [08:38:09] [Server thread/INFO]: Rocologo lost connection: Disconnected
> [08:38:09] [Server thread/WARN]: [[0;32;22mMyPet[m] [m==========================================[m
> [08:38:09] [Server thread/WARN]: [[0;32;22mMyPet[m] [mPlease report this to the MyPet developer![m
> [08:38:09] [Server thread/WARN]: [[0;32;22mMyPet[m] [mMyPet: MyWolf{owner=Rocologo, name=Wolf, exp=0.0/7.0, lv=1, status=Here, skilltree=-, worldgroup=survival, collarcolor=RED, baby=false}[m
> [08:38:09] [Server thread/WARN]: [[0;32;22mMyPet[m] [mMyPetOwner: MyPetPlayer{name=Rocologo, internal-uuid=a28d1a0d-a039-40c0-a1f1-d62c3d0af3e7, mojang-uuid=3c9a8292-0fa7-4e7c-8413-2bcb15968204, name=Rocologo}[m
> [08:38:09] [Server thread/WARN]: [[0;32;22mMyPet[m] [mOwner online: false[m
> [08:38:09] [Server thread/WARN]: [[0;32;22mMyPet[m] [m==========================================[m

**Comment by xXKeyleXx** [comment]
Was this error the result of a command? If so please show me like 10 lines that got printed above this error.

Do you run a non-premium server?

**Comment by Rocologo** [comment]
Unfortunately I deleted the log file :-( but it is not first time I see this error, so I will grab some more next time I see the error :-| I will get back.

And its not a premium server.
