### ISSUE TITLE
Nether portals duplicating pets

### ISSUE THREAD

**Issue by Nachodiazv** [xXKeyleXx/MyPet#906]
Hi, I don't know if someone posted this, but... When a player cross a Nether portal with a pet, that pet gets duplicated.. For example.. If you cross with your horse pet through the nether portal... The result is another horse... So at the end you have your pet and an duplicated horse (Not Pet). 

Players take advantage of this by crossing mobs and getting babys..

**Comment by xXKeyleXx** [comment]
I need more info about your server setup like plugins, spigot version, mypet build, etc.
