### ISSUE TITLE
Cannot store more than 0 MyPets

### ISSUE THREAD

**Issue by Latamier** [xXKeyleXx/MyPet#907]
A player of mine is getting this when he wants to get another pet. 

Cannot Store more than 0 MyPets
![cannotstoremorethan0pets](https://cloud.githubusercontent.com/assets/20458757/19335826/54035f60-90d4-11e6-8147-712905de16ea.jpeg)

I also have noticed that the command / pet store isn't working and is not even listed in commands any more. 

He has the permission to store pets too. 
I am using the latest update on spigot and running 1.10

Thank you for any help you can give in this matter...

**Comment by IceCraftNation** [comment]
I'm getting the exact same error message with my plugin lately as well

**Comment by xXKeyleXx** [comment]
New permission: MyPet.petstorage.limit.\<X>
