### ISSUE TITLE
Pet Inventory and Monster Kill

### ISSUE THREAD

**Issue by zenandreas** [xXKeyleXx/MyPet#908]
Hello,

Apparently pet inventories aren't stored and synced between servers, not sure if intended or a bug.

Also, mobs are not attacking pets, also not sure if a bug.

**Comment by xXKeyleXx** [comment]
But the pets are synced?

Don't they attacks pets at all (even of the pet attacks first)?

**Comment by zenandreas** [comment]
Yes the pets are synced everything works but the inventory doesn't work on all servers.

Yes they are basicly ignored by the mobs.
