### ISSUE TITLE
Player losing their pet.

### ISSUE THREAD

**Issue by HunkyHenry** [xXKeyleXx/MyPet#910]
Had reports from players on my server that their mypet was gone when they came back onto the server. Somehow their pet was not saved? Is there a way to bring back their pet and how can i prevent this from happening again in the future?

**Comment by xXKeyleXx** [comment]
1. Do you use MyPet-Premium? If so what is the storage method you use?
2. Do pets of all types get lost or just certain types?
3. What was the method they got their pets? (trading, catching, admin command, etc)

**Comment by HunkyHenry** [comment]
We are not using premium. The type of mob was a cow, not sure if this is a type sensitive issue since right now i have only allowed players to use a few types and this has only happening with a cow so far. The method they got their pet was by catching it. Only been using the plugin of a couple of days now. Thanks for this great mod players seem to love so far, just want to figure out how i can prevent their future heartbreak at losing their pets.

**Comment by xXKeyleXx** [comment]
Could you send me the logs from the days it happened please.

**Comment by HunkyHenry** [comment]
Was mostly hoping it was a simple thing, like a config option i fucked up or something, if it happens again i will make sure to send the logs.

**Comment by xXKeyleXx** [comment]
No, this should happen under no circumstance and the logs may be the only way to find this problem :(
