### ISSUE TITLE
Pet invincible when player is invincible

### ISSUE THREAD

**Issue by HunkyHenry** [xXKeyleXx/MyPet#911]
Pet invincible when player is invincible. So pets can't be harmed in areas like spawn and in towns with pvp off.

**Comment by xXKeyleXx** [comment]
That is intended. As long as the player can't be harmed, the pet can't be either.

**Comment by HunkyHenry** [comment]
no i meant that pets were taking damage, when their player was invincible.

**Comment by xXKeyleXx** [comment]
What plugin prevents the damage for players?

**Comment by HunkyHenry** [comment]
world guard

**Comment by xXKeyleXx** [comment]
Are there any errors in the logs? What are the flags of these regions? Who is the owner of the region. Does the owner matter?

**Comment by xXKeyleXx** [comment]
?

**Comment by HunkyHenry** [comment]
Sorry. I haven't had a problem with this again. Only problem we are having at all with the mypets plugin now is that sometimes players pets will not be saved when they quit and when they come back on it will load a previous version of the pet at a lower level or a different pet altogether if they had recently changed pets.

**Comment by xXKeyleXx** [comment]
Do you have a bungeecord network?

**Comment by HunkyHenry** [comment]
no we do not.

**Comment by HunkyHenry** [comment]
Here is our last two logs. I know for a fact that a players pet did reset to their old pet within these logs. The players pet reset just now when i restarted the server. I watched console load didn't see anything weird.

[net2ftp-1479443504.zip](https://github.com/xXKeyleXx/MyPet/files/599062/net2ftp-1479443504.zip)
