### ISSUE TITLE
/psw store not working

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#912]
When i do /psw store it shows me the choice of my pets instead of storing it.
Permissions are set correctly, i can store the pet using the npc trait.

Mypet Premium 2.3.2 Snapshot Build 408.
Latest Paperspigot.

**Comment by xXKeyleXx** [comment]
if I remember correctly I replaced it with a /petstore command.

**Comment by Phreag** [comment]
ah, then the wiki needs to be updated ;)
