### ISSUE TITLE
Pet not auto loading on server switch

### ISSUE THREAD

**Issue by Phreag** [xXKeyleXx/MyPet#913]
When i use any Command which switches me to a different server on Bungeecord, the pet is not loaded and teleported to my location. But it can be just called with /pc.

Mypet Premium 2.3.2 Snapshot Build 408.
Latest Paperspigot.

**Comment by xXKeyleXx** [comment]
The delay when a player joins might not be high enough. I will add a config option to make the delay adjustable.

**Comment by Phreag** [comment]
Tested it again:
Have Pet with me on server 1, then warping to server 2, pet ist not there but can be called.
But when i warp to server 2, disconnect and reconnect again the pet is still not there (but can be called)

**Comment by Phreag** [comment]
Issue is not fixed in Build 411. Sorry :P
