### ISSUE TITLE
pcst Fehler 

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#914]
Fehlermeldung tritt aktuell bei Zombies bei mir auf:
26.10 15:19:50 [Server] ERROR null
26.10 15:19:50 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'pcst' in plugin MyPet v2.3.2
26.10 15:19:50 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
26.10 15:19:50 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
26.10 15:19:50 [Server] INFO Caused by: java.lang.NullPointerException
26.10 15:19:50 [Server] INFO at de.Keyle.MyPet.compat.v1_8_R3.util.iconmenu.IconMenuInventory.createItemStack(IconMenuInventory.java:132) ~[?:?]
26.10 15:19:50 [Server] INFO at de.Keyle.MyPet.compat.v1_8_R3.util.iconmenu.IconMenuInventory.open(IconMenuInventory.java:78) ~[?:?]
26.10 15:19:50 [Server] INFO at de.Keyle.MyPet.api.util.inventory.IconMenu.open(IconMenu.java:92) ~[?:?]
26.10 15:19:50 [Server] INFO at de.Keyle.MyPet.commands.CommandChooseSkilltree.onCommand(CommandChooseSkilltree.java:187) ~[?:?]
26.10 15:19:50 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot187.jar:git-Spigot-21fe707-e1ebe52]
26.10 15:19:50 [Server] INFO ... 15 more

Kann es daran liegen, dass bei den Skillbäumen das Icon 51 (brennendes Feuer) nicht nutzbar ist?

**Comment by xXKeyleXx** [comment]
Jo das Feuer ist Schuld, nur keine Ahnung wiso. Ich fixe es sobald ich dazu komme.
