### ISSUE TITLE
PREMIUM: skilltree entfernen von offline-spielern

### ISSUE THREAD

**Issue by ScuroK** [xXKeyleXx/MyPet#917]
Hey
Ich habe eine Frage. Es gibt ja die Mögllichkeit Skilltrees mit permissions zu setzen. Manche unserer Spieler bekommen 1 Jahr Zugriff auf einen "Premium Skilltree". Jetzt habe ich folgendes Problem: Wenn der Rang nach einem Jahr abgelaufen ist, verliert der Spieler den Premium-Skilltree nicht. Das wäre ansich ok, jedoch kann ich ihn nur entfernen, wenn der Spieler online ist.Ich habe Mypet Premium und will manchen Spielern gerne die Pet-Fly Option geben.
Wäre es möglich dass ich den Skilltree eines Offline-Spielers ändern könnte?
eigentlich würde folgendes reichen: ein cmd der das pet eines bestimmten spielers löscht
also /petadmin remove SPIELER. Wenn der Spieler mehrere Pets hat, einfach alle.
ODER: Permission für den skill immer prüfen, wenn das pet gerufen wird. falls spieler die permission nicht mehr hat, automatisch zu einem "default skilltree" wechseln
was meinst du? 
die 2. variante wäream besten
wir geben einem Spieler 1 Jahr lang einen Permission-Rang auf dem server.
inhaber dieses ranges können einen "premium skilltree" nutzen und so in der farmwelt mit pet fliegen usw.
nach 1 jahr verliert der spieler diesen rang wieder.
wenn das pet diesen skill aber behält, kann das Pet des Spielers weiterhin rumfliegen etc .

**Comment by zerafox** [comment]
Isn't selling things like "fly" against the EULA of Mojang?
Selling anything to donators that gives an advantage is against the EULA. :\

**Comment by ScuroK** [comment]
@zerafox 
1. I dont "sell" anything in general. There are plenty of player which belong to the same permission group as some of our donators do.
2. Players can also get fly permissions on our server without donating any money.

3. What they DO get for money are certain pets which can fly. Its about cosmetic and not about "fly" itself. 

This is not just legal but even suggested by mojang:
"You are allowed to sell in-game items so long as they don’t affect gameplay
We don’t mind you selling items in game, but they must be purely cosmetic. **Pets**, hats, and particle effects are OK, but swords, invincibility potions, and man-eating pigs are not. We want all players to be presented with the same gameplay features, whether they decide to pay or not.

There is one exception to this rule - capes! We have a lot of fun making cool capes for extra-special members of our community and Minecon attendees. We’d like to keep them as exclusive as possible. So, yeah, no capes please, even if you’re giving them away for free."
source: https://mojang.com/2014/06/lets-talk-server-monetisation/

We dont talk about flying permissions. we only talk about pets flying with you ;)

**Comment by ScuroK** [comment]
And last but not least, right now we are just planning to add this feature. Nothing will be implemented before checking the eula.

My request remains the same.

**Comment by zerafox** [comment]
But if the Pets can fly if you donate, but you can't get flying pets
without donating.. That's still selling an advantage there.
Yes the EULA says Pets are OK, but I'm certain the Pets the EULA mentions
are purely cosmetic pets that just follow players and not something like
MyPet. :P

If what you're talking about is something like "Players can get flying cows
ingame, but have to donate for flying pigs" that's a purely cosmetic
approach to it. Since you can still obtain a flying pet without donating.

**Comment by zerafox** [comment]
Besides, pets don't "fly with you". You fly while riding the pet, so it's
another form of flying for the player.
Sadly they don't "Follow while flying", it's a form of riding.

**Comment by ScuroK** [comment]
no you arr wrong sir. Flying normally or while sitting on a pet is a cosmetic difference.Every player on our server has access to mypets without donating. Those pet features which can be considered competative are open to all.

We are lucky to have a law expert in case of eula conflicts. I do t worry at all.

We are not a buisness and the donations ar not even enough to cover all our server costs. and we talk about a 42 slot server. What i provide is non profit since 4 years and will remain like this. I pay the most to give all our players a fun time. including mypet premium which i bought! I am a customer here. If i need eula advice i wo t come to the mypet github.

So please dont blame me here or come with old eula discussions.  Thats not the right place and i am not the right guy! -.-

**Comment by ScuroK** [comment]
U make me angry. U dont know any details about our server and our non profit service we provide since years! Just mind your own buisness before telling me i do illegal actions. And if u truely care dont do it on a issue page of a customer who PAYED for this plugin. -.-

**Comment by ScuroK** [comment]
So yes: flying pets and shall be accessable without donating to. Thats it.

Most eula discussions on the web are way to philosophical. Anyway. I do like the eula since it stopps the huge money servers from destroying the game. But its purpose is not to destroy little community projects.
