### ISSUE TITLE
petrelease not work

### ISSUE THREAD

**Issue by linbo10** [xXKeyleXx/MyPet#922]
I used latest version,but petrelease command can not use.

**Comment by xXKeyleXx** [comment]
I need more info like: MyPet version, spigot version, released pet, errors from the logs, etc

**Comment by SioWolf** [comment]
I'm also running the latest version and /petrelease is working perfectly for me.

**Comment by Sprungente** [comment]
I think i have the same problem ^^

**Comment by Sprungente** [comment]
@SioWolf it's works on the most mobtypes. Other typed for example Horses or
llama the command will not work correctly. The pet will not be released but it's spawn a new Entity.
