### ISSUE TITLE
Crash Cilent bug

### ISSUE THREAD

**Issue by WindUnwaken** [xXKeyleXx/MyPet#923]
When players type
/petoptions resource-pack

Bungeecord will said 
The server you were previously on went down, you have been connected to fallback server.

Transfer player to fallback server, or can't log in and freeze his cilent.

In cofig.yml, I don't change anything
Activate-Resourcepack-By-Default: false

Player without any permission can type 
/petoptions resource-pack
and cause this problem

**Comment by xXKeyleXx** [comment]
Are there any errors in the server (not bungee) logs?

**Comment by WindUnwaken** [comment]
No any errors.
But I delete the db, can let players login again

**Comment by WindUnwaken** [comment]
Maybe spigot problem, I've heard some plugins which require resource-pack,(Some minigames, worldresourcepack_downloader )
and didn't set download link correctly will cause this issue,too.

My opinion is "petoptions" as standalone permission

**Comment by xXKeyleXx** [comment]
I think it's a bungee problem because it works fine without it.

 I will add a permission for it.

**Comment by xXKeyleXx** [comment]
The permission will be: MyPet.command.options.resourcepack
