### ISSUE TITLE
List of 1.11 Issues

### ISSUE THREAD

**Issue by SioWolf** [xXKeyleXx/MyPet#926]
Following is a list of issues we are currently having running 1.11 on my server:

- [x] Skeleton horses are not working, likely because they now have their own ID.
- [ ] Villagers, vindicators, and other humanoid entities are showing "Impossible, LowHP" with /pettype after attempting to make them impossible in the pet-config. Oddly, other mobs such as the enderdragon are showing the correct flag
- [x] Mobs still have their old IDs in the config file, and the plugin does not recognize the new IDs.

**Comment by xXKeyleXx** [comment]
The problem with the leashflag doesn't happen to me. Are you sure you remove LowHP from the config for these types?

**Comment by SioWolf** [comment]
Fairly certain. Here is my config: http://pastebin.com/CPhUq02w
