### ISSUE TITLE
shulker

### ISSUE THREAD

**Issue by Sprungente** [xXKeyleXx/MyPet#928]
Hey, jemand von meinem Server hat mich gefragt warum man keine shulker zähmen kann. Ich wollte die aktivieren, doch da ist mir aufgefallen, dass die gar nicht in der Pet-Config drinne sind. Kann das sein, dass die untergegangen sind?

**Comment by xXKeyleXx** [comment]
Nein sind sie nicht. Problem ist das sie nur durch Pistons bewegt werden können und somit schlechte Pets abgeben wenn sie nur dumm in der Gegen rumstehen.
