### ISSUE TITLE
view update bug

### ISSUE THREAD

**Issue by FlamestoN** [xXKeyleXx/MyPet#929]
I'm use last spigot build.
I'm use last dev build MyPet.

When a player join to the server, he can't see MyPet entities.
http://snap.ashampoo.com/Pr5oUJGg

**Comment by zerafox** [comment]
"Last" and "Latest" are like curse words in tickets.
Please post the actual version numbers of the builds you're using.

**Comment by FlamestoN** [comment]
b1107
git-Spigot-f950f8e-1d54397
