### ISSUE TITLE
My pet experience level

### ISSUE THREAD

**Issue by Moorlock152** [xXKeyleXx/MyPet#931]
Hi,
I am trying to create a skilltree for pets but I can't seem to be able to get the pet level to go higher than 100. No matter how much exp I set the message comes back that the pets exp is set to 17647.0 and level is 100.
Could you please explain to me how to allow a pet to gain exp and go higher than level 100 please.

Spigot version 1.8.8
My Pet version 2.2.7

I used to have pets able to go over level 100 and any help would be appreciated.
Many thanks.

**Comment by xXKeyleXx** [comment]
There are multiple ways to limit the level the pets (config/skilltree/XP script). Maybe one of them is blocking them to level beyong the lvl 100 mark.
