### ISSUE TITLE
Vex pet shift bug

### ISSUE THREAD

**Issue by andris155** [xXKeyleXx/MyPet#937]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
This server is running Paper version git-Paper-962 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

**MyPet Build/Version:**
MyPet-Premium 2.3.2

**Do you use the premium version? (this wont change anything for you)**
yes

**Error:**
![2016-12-19_17 05 34](https://cloud.githubusercontent.com/assets/8324198/21319415/80f55eec-c60d-11e6-989c-612843e629e0.png)

**Comment by xXKeyleXx** [comment]
There is not much I can do here. It's a Minecraft visual bug.
