### ISSUE TITLE
Disappearance mob after domestication

### ISSUE THREAD

**Issue by nikitik7** [xXKeyleXx/MyPet#939]
**Bukkit/Spigot/Bungee Build/Version:** Thermos 1614.58

**MyPet Build/Version:** 2.2.8

**Do you use the premium version? (this wont change anything for you)** No

**What is the expected result?** I get Pet.

**What happens instead of that?** Disappearance mob, but i can listen here sounds.

**Full log:** [MyPet.txt](https://github.com/xXKeyleXx/MyPet/files/671226/MyPet.txt)

**Error:** 
Error occured while creating the de.Keyle.MyPet.api.util.service.types.EntityConverterService service.
[/]: java.lang.InstantiationException
[/]: 	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source)
[/]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[/]: 	at java.lang.Class.newInstance(Unknown Source)
[/]: 	at de.Keyle.MyPet.api.util.service.ServiceManager.registerService(ServiceManager.java:59)
[/]: 	at de.Keyle.MyPet.compat.v1_7_R4.CompatManager.init(CompatManager.java:12)
[/]: 	at de.Keyle.MyPet.MyPetPlugin.onLoad(MyPetPlugin.java:125)
[/]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:348)
[/]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
[/]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138)
[/]: 	at net.minecraft.world.World.<init>(World.java:374)
[/]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162)
[/]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375)
[/]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[/]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[/]: 	at java.lang.Thread.run(Unknown Source)

**Comment by xXKeyleXx** [comment]
Forge based servers are not officially supported so I'm sorry that it doesn't work but I will not fix it for now.
