### ISSUE TITLE
pet wont get stats

### ISSUE THREAD

**Issue by Andriolf** [xXKeyleXx/MyPet#940]
**Bukkit/Spigot/Bungee Build/Version:** 1.11

**MyPet Build/Version:** Newest

**Do you use the premium version? (this wont change anything for you)** no

**What is the expected result?** x

**What happens instead of that?** x

Pets stats stop increasing past lv.10. Any way to fix it?

**Comment by xXKeyleXx** [comment]
The skilltrees shipped with MyPet only upgrade stats until level 10. I can't balance them for every server and this is where you have to work :P You can open the editor by double clicking the plugin JAR file.
