### ISSUE TITLE
Plugin not working.

### ISSUE THREAD

**Issue by WhispTheFox** [xXKeyleXx/MyPet#941]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.11.2
**MyPet Build/Version:**
2.3.3 premium and 2.3.4 premium beta
**Do you use the premium version? (this wont change anything for you)**
yes
**What is the expected result?**
That the plugin works.
**What happens instead of that?**
When I click on a tamed animal with the lead nothing happens. Also, most of the commands aren't working. This was also a problem when I tried with 1.11.0. 
**Error:**
The error only printed when I clicked on the pet and it printed in console and I couldn't copy it.

**Comment by xXKeyleXx** [comment]
Well without the error message I can't do anything.

BTW: **_That the plugin works._** is not very helpful either

**Comment by WhispTheFox** [comment]
Sorry, it was 2am and I was tired. I'll see if I can get the error copied. And as for what I'm expecting to happen, I'm expecting the lead to actually claim the pets and the commands to successfully run.

On Dec 24, 2016 4:38 AM, Sebastian Comans <notifications@github.com> wrote:

Well without the error message I can't do anything.

BTW: That the plugin works. is not very helpful either
