### ISSUE TITLE
Crash with Spigot 1.11.2 and MyPet 2.2.8

### ISSUE THREAD

**Issue by PabloMA98** [xXKeyleXx/MyPet#943]
Server log: http://pastebin.com/3CA04pGp
Crash report: [crash-2016-12-25_21.54.49-server.txt](https://github.com/xXKeyleXx/MyPet/files/672350/crash-2016-12-25_21.54.49-server.txt)

**Comment by xXKeyleXx** [comment]
Already fixed. Try the latest dev build.
