### ISSUE TITLE
Duplication Error

### ISSUE THREAD

**Issue by Brabant1973** [xXKeyleXx/MyPet#945]
Info:
Spigot version 1.11
MyPet Build/Version:2.3.4
Do you use the premium version? yes as 'Brabant'
What is the expected result?
/petrelease should remove the skeleton pet from the owner (only seems to be skeleton and Zombie types not other pets)
What happens instead of that?**
skeleton pet is duplicated  (only skeleton and zombie type pet is duplicated)

**Error:**
pet duplication 

mypet.log (most recent portion)
12-27-2016 16:55 [INFO] [MyPet] Thank you for buying MyPet-Premium!
12-27-2016 16:55 [INFO] [MyPet] version 2.3.2-SNAPSHOT-b422P ENABLED
12-27-2016 16:55 [INFO] [MyPet] ShopService service activated.
12-27-2016 16:55 [INFO] [MyPet-NPC] version 1.1.0-b133 ENABLED
12-27-2016 17:09 [INFO] [MyPet-NPC] Disabling MyPet-NPC v1.1.0
12-27-2016 17:09 [INFO] [MyPet] Enabling MyPet v2.3.2
12-27-2016 17:09 [INFO] [MyPet] Citizens (2.0.21-SNAPSHOT (build 1463)) hook activated.
12-27-2016 17:09 [INFO] [MyPet] GriefPrevention (15.3) hook activated.
12-27-2016 17:09 [INFO] [MyPet] Vault (1.5.6-b49) hook activated.
12-27-2016 17:09 [INFO] [MyPet] WorldGuard (6.1.2;e38d98d) hook activated.
12-27-2016 17:09 [INFO] [MyPet] Compat mode for v1_11_R1 loaded.
12-27-2016 17:09 [INFO] [MyPet] --- Loading WorldGroups ---------------------------
12-27-2016 17:09 [INFO] [MyPet]    added 'world' to 'default'
12-27-2016 17:09 [INFO] [MyPet]    added 'world_nether' to 'default'
12-27-2016 17:09 [INFO] [MyPet]    added 'world_the_end' to 'default'
12-27-2016 17:09 [INFO] [MyPet]    added 'Herobrine' to 'default'
12-27-2016 17:09 [INFO] [MyPet]    added 'Emerald_Adventure' to 'default'
12-27-2016 17:09 [INFO] [MyPet]    added 'xmasbuildcomp' to 'default'
12-27-2016 17:09 [INFO] [MyPet] -------------------------------------------------
12-27-2016 17:09 [INFO] [MyPet] Thank you for buying MyPet-Premium!
12-27-2016 17:09 [INFO] [MyPet] version 2.3.2-SNAPSHOT-b422P ENABLED
12-27-2016 17:09 [INFO] [MyPet] ShopService service activated.
12-27-2016 17:09 [INFO] [MyPet-NPC] version 1.1.0-b133 ENABLED

If you need more information pls let me know, this is the first time i have had to do one of these :P

12 17:50:17 [ Server ] [ Information ] Admins: Brabant
27.12 17:50:17 [ Server ] [ Information ] Players: Leopard Blossom.
27.12 17:50:44 [ Server ] WARN Task # 2 for Mythic Drops v3.1.0-SNAPSHOT-b0-DEFAULT generated an exception
27.12 17:50:44 [ Server ] [ Information ] java.lang.NullPointerException
27.12 17:50:44 [ Server ] [ Information ] The Xmas build comp is now over, 1st prize to kittysmc, joint 2nd to several at entries (all soooo good!)
27.12 17:50:49 [ Server ] [ Information ] CONSOLE issued server command: / list
27.12 17:50:49 [ Server ] [ Information ] Admins: Brabant
27.12 17:50:49 [ Server ] [ Information ] Players: Leopard Blossom
27.12 17:50:54 [ Server ] [ Information ] java.lang.NullPointerException
27.12 17:50:58 [ Server ] [ Information ] Leopard Blossom issued server command: / spawn

27.12 17:51:53 [ Server ] [ Information ] CONSOLE issued server command: / list
27.12 17:51:53 [ Server ] [ Information ] Admins: Brabant
27.12 17:51:53 [ Server ] [ Information ] Players: Leopard Blossom

27.12 17:52:48 [ Server ] [ Information ] Brabant issued server command: / Petr lease
27.12 17:52:50 [ Server ] [ Information ] Brabant issued server command: / Petr lease Zombie
27.12 17:52:50 [ Server ] ERROR null
27.12 17:52:50 [ Server ] [ Information ] org.bukkit.command.CommandException: An unhandled exception executing command 'Petr leasing' in MyPet Plugin v2.3.2
27.12 17:52:50 [ Server ] [ Information ] at org.bukkit.command.PluginCommand.execute (PluginCommand.java:46) ~ [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at org.bukkit.command.SimpleCommandMap.dispatch (SimpleCommandMap.java:141) ~ [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand (CraftServer.java:649) ~ [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand (PlayerConnection.java:1335) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.PlayerConnection.a (PlayerConnection.java:1170) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.PacketPlayInChat.a (PacketPlayInChat.java:45) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.PacketPlayInChat.a (PacketPlayInChat.java:1) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at $ net.minecraft.server.v1_11_R1.PlayerConnectionUtils 1.run (Source File: 13) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at $ java.util.concurrent.Executors RunnableAdapter.call (Executors.java:511) [: 1.8.0_91]
27.12 17:52:50 [ Server ] [ Information ] at java.util.concurrent.FutureTask.run (FutureTask.java:266) [: 1.8.0_91]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.SystemUtils.a (Source File: 46) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.MinecraftServer.D (MinecraftServer.java:739) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.DedicatedServer.D (DedicatedServer.java:399) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.MinecraftServer.C (MinecraftServer.java:675) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at net.minecraft.server.v1_11_R1.MinecraftServer.run (MinecraftServer.java:574) [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at java.lang.Thread.run (Thread.java:745) [: 1.8.0_91]
27.12 17:52:50 [ Server ] [ Information ] Caused by: java.lang.UnsupportedOperationException: Not supported.
27.12 17:52:50 [ Server ] [ Information ] at org.bukkit.craftbukkit.v1_11_R1.entity.CraftZombie.setVillagerProfession (CraftZombie.java:50) ~ [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] at de.Keyle.MyPet.commands.CommandRelease.onCommand (CommandRelease.java:184) ~ [:?]
27.12 17:52:50 [ Server ] [ Information ] at org.bukkit.command.PluginCommand.execute (PluginCommand.java:44) ~ [spigot-1.11.jar: git-Spigot-f950f8e-0fa1ad2]
27.12 17:52:50 [ Server ] [ Information ] ... 15 more
27.12 17:52:52 [ Server ] WARN Task # 2 for Mythic Drops v3.1.0-SNAPSHOT-b0-DEFAULT generated an exception

**Comment by xXKeyleXx** [comment]
You posted an error from 2.3.2 but said you use 2.3.4. So this error was fixed long ago.
