### ISSUE TITLE
Crash seconds after connecting to server

### ISSUE THREAD

**Issue by rustyshakelford2** [xXKeyleXx/MyPet#949]
Spigot 1.11.2, Bungee 1217

MyPet Build 2.3.3 Premium

**Error:**
When I join the server I am kicked after about 3 seconds. This error appears in bungee console. No errors in spigot console. Others are on the server without issue. Removing MyPet stops the error. 
http://pastebin.com/JpQhwuAv

**Comment by rustyshakelford2** [comment]
All i've done as far as mypet goes is install it and configure the sql database. I had no issues for hours and then that started happening. We do have a server resource pack.

**Comment by NOBUTSS** [comment]
Same problem as I met
