### ISSUE TITLE
Beacon Skill

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#952]
So for as long as I have used MyPet, I have never once used the Beacon skill.
I've double, even triple checked the Wiki but can't find any solid information on what the Skill does exactly, or more so how to set it up.

I see all Beacon options on screen, and a check box to "Change Values".. But I am not sure how to specify which options **are** or **are not** available via the Pet's beacon. I suppose I could play around with it, but to be honest I am lazy and I for-see that taking a while to figure out what option does what exactly. Haha

I understand "Range" and "Duration" those are easy, but "Select-able Buffs"? Is that how many buffs may be enabled at a time?

**Comment by xXKeyleXx** [comment]
Sorry for the late response. Did you read the wiki page already?
https://wiki.mypet-plugin.de/skills/beacon

**Comment by zerafox** [comment]
Yeah that displays the available options and how it looks from a player perspective but it doesn't explain what the options are in the skilltree editor.
Such as "enable" box, and then sometimes there's another checkbox depending on which one there, etc;

**Comment by zerafox** [comment]
So then technically by default, all buffs are disabled when you add the
Skill to a tree.
Since nothing is checked inside the BeaconSkill at all?

**Comment by xXKeyleXx** [comment]
Yup.

**Comment by zerafox** [comment]
That makes sense. I thought that was the case, but I wasn't entirely sure. Since it appears some of the other skills in the editor are by default ON I thought this might've been the case here.
Does having a buff on the 1st(Left) or 2nd(Right) set of buffs have any effect on anything as well?
