### ISSUE TITLE
Moving between World-Groups without Storing Pet.

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#953]
So here's a question I feel I should know..

I have 2 world groups, and they happen to share a few worlds together.
Now, if I go from say "Hub" to "PvE" which are in the same world group, but I originally came from "PvP" which shares with "Hub" but not "PvE".. What happens if I tame a pet in PvE without storing my pet?

Essentially, if I go from 1 world to another, that doesn't share pets and tame a new pet. Then go to a mutual shared world without storing either Pet in-between. What happens to a pet?

Does one of my pets go into a storage system?
If I have MyPet-NPC can the Pet be found there, or will I have to use a /petswitch command?

**Comment by zerafox** [comment]
So it's impossible to have a World that belongs to BOTH groups? Because
that's where my concern was..

**Comment by xXKeyleXx** [comment]
There is no way this could happen. a world can only belong to one group and ever pet belongs to one world group. no transfer possible (unless you modify the database)

**Comment by zerafox** [comment]
:P Well that's good news too!
Thank you. <3
