### ISSUE TITLE
MyPet-Shop NPC

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#954]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** 1.11.2

**MyPet Build/Version:** 2.3.4

**Do you use the premium version? (this wont change anything for you)** yes

**What is the expected result?** I expect to be able to open the designated shop given to my NPC

**What happens instead of that?** Literally nothing. :'( 

**Error:**
I don't even get an error in console. :'(

**Notes**
I've created an NPC using Citizens, I have given it the "mypet-shop" trait and then followed up with **/mypetnpcconfig shop all**. Sadly right nor left clicking the NPC opens anything, and I am OP as well as having given the permission nodes to players for the shop as well.
I have another NPC in the same area/map and they share a region together from World Guard, but I am able to access the other NPC just fine. (This NPC is not a MyPet NPC) Other NPCs (that are mypet npcs) are working just fine as well.

**Comment by Sprungente** [comment]
Save as mine #962 .
