### ISSUE TITLE
Crash with Squid into water?

### ISSUE THREAD

**Issue by freakyy85** [xXKeyleXx/MyPet#958]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
latest
**MyPet Build/Version:**
MyPet version 2.2.8
**Do you use the premium version? (this wont change anything for you)**
no
**What is the expected result?**
no crash
**What happens instead of that?**
crash with crashreport at pastebin
**Error:**
http://paste.ubuntu.com/23782739/

**Comment by zerafox** [comment]
So what exactly were you trying to do?

Also "latest" is awful.. Don't say latest..
It's like an awful disease.

Did the squid follow you into water? Did you ride the squid into water? Did
you tame the squid while it was in the water?

"no crash" for expected results is awful.
:\ Might as well have just deleted the pre-layout and pasted the error to
the ticket with this information.
Can you give us more to go on?

Also, why aren't you using "latest" Mypet for "latest" Spigot/Bukkit/Bungee?

**Comment by freakyy85** [comment]
a player was riding the squid while going into water. the crash occured 2 times in a row. i didnt update mypet yet. sorry.
