### ISSUE TITLE
No access to shop

### ISSUE THREAD

**Issue by bloomyflower** [xXKeyleXx/MyPet#959]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** 1.11.2

**MyPet Build/Version:** 2.3.4

**Do you use the premium version? (this wont change anything for you)** Yes

**What is the expected result?** I wish to be able to open the shop, and give the command to my players.

**What happens instead of that?** Even I as an opped player get a message saying "You do not have access to that"

**Error:** Cant use commands.

**Comment by xXKeyleXx** [comment]
What was the command you tried to use (full command please)?

**Comment by bloomyflower** [comment]
Just /petshop
