### ISSUE TITLE
Ender dragon as pet

### ISSUE THREAD

**Issue by Jbiere** [xXKeyleXx/MyPet#963]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.11.2

**MyPet Build/Version:**
2.2.9

**Do you use the premium version? (this wont change anything for you)**
No.

**What is the expected result?**
get EnderDragon as pet.

**What happens instead of that?**
I run my own server and I have always wanted to have the EnderDragon as a pet, but when I hit it with a lead it just dies and doesn't become my pet.

**Error:**
EnderDragon not being my pet.

**Comment by zerafox** [comment]
Did you enable the capture of the enderdragon in the config file?

**Comment by Jbiere** [comment]
Yes, I changed "impossible" to "LowHp" but it didn't work. Is there something else I need to do?

**Comment by zerafox** [comment]
Did you give the permission node to catch it?

**Comment by Jbiere** [comment]
I have every permission and am OP.
Here is my Config.yml http://pastebin.com/M6yZfJb2

Here is my Pet-Config.yml http://pastebin.com/fWHK2m8K

**Comment by zerafox** [comment]
Any errors that appear in the console at all when you try?

**Comment by Jbiere** [comment]
Nope... no errors appear.

**Comment by xXKeyleXx** [comment]
Do you have ProtocolLib installed on your server?
