### ISSUE TITLE
Pets appears in blocked worlds / Pet inventory duplicating items

### ISSUE THREAD

**Issue by Jozznak** [xXKeyleXx/MyPet#967]
**Bukkit/Spigot/Bungee Build/Version:** 
- 1.10.2

**MyPet Build/Version:** 
- 2.3.4

**Do you use the premium version? (this won't change anything for you)** 
- Yes I do.

**Bug explanation:**
So this is a very easy to do bug and I hope you find a solution because players can duplicate items as they wish. 

The problem on solving this bug is that it requires other plugins such as CombatTagPlus and a plugin that can teleport players.. in this case AreaShop (/as tp command)

So, many of us has pets blocked in some of our server worlds. But players found a way to bring their pets in worlds that are blocked.

**Steps to reproduce the bug**

1. Open the Pet inventory in any allowed world and put on it the items you want to duplicate.
2. Go to a blocked world that has pvp true. You will notice that the pets are clearly blocked in that world. Because you can't bring it with /pc or any other command and all pet commands are not available. This is just to clarify that everything is well configured in my server.
3. Combat tag with a friend.
4. Here is the important thing. Just in the moment you get combattagged, run a teleport command that teleports you instantly, such as /as teleport X. Areashop will teleport you BUT combattag has teleports blocked during combat, so automatically you will be teleported back. If you did everything well, you will see that your pet will appear and all pet commands will now be available, including pet inventory.
5. Open the pet inventory in the blocked world and take all the items from it.
6. Go to an allowed world and open the pet inventory again. You will see that all the items you taked in the blocked world still there in the pet inventory, so you can take them again and make this process the times you want to duplicate items.

So to solve this bug I can simply block the as teleport command. But, I found very interesting how this glitch makes pets appear in blocked worlds(I can't explain why this happens...) and really makes this bug possible. Hope you can do something, if not.. At least you know that there is a way to bug out the blocked worlds and duplicate items with the inventories.

**Error:**
No crash reports.

Have a great day. 
Sorry for my english, im from Chile, hope you understand everything.

**Comment by xXKeyleXx** [comment]
How did you block the worlds?

**Comment by Jozznak** [comment]
Created 2 worlds in groupworlds.yml 

Deafult
Nopet

Then remove the leash permision in no pet worlds.

**Comment by xXKeyleXx** [comment]
Ok thanks for clarifying that for me. I will test that tomorrow.

**Comment by xXKeyleXx** [comment]
Please try the latest dev build: https://mypet-plugin.de/download

**Comment by Jozznak** [comment]
Hi, 
We tested with Premium 2.3.5 SNAPSHOT and the same happens. Bug still possible. Users discovered something else. If for some reason the bug doesn't work, you can change the petname in the blocked world and it will work.

**Comment by xXKeyleXx** [comment]
Please try it again. If it's still possible I need to dig deeper to find the real problem...
https://mypet-plugin.de/download

**Comment by Jozznak** [comment]
Hey! Good news! You solved the main problem, pets don't come when trying the bug. The only strange thing is that it doesn't say that player has no pets... in fact.. it says that he has a pet but he can't use the commands. So, as is not very important because pets don't come, it's your decision to look at that, but the bug is officially solved.

Awesome work! Thanx for the support!

**Comment by xXKeyleXx** [comment]
The thing is that the moment they teleport, the pet can spawn and the message appears but the pet spawns with a delay. I could display both messages if that is desired by you.
