### ISSUE TITLE
Beacon GUI not opening for players

### ISSUE THREAD

**Issue by MapleMoosey** [xXKeyleXx/MyPet#974]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** 1.11.2

**MyPet Build/Version:** 2.2.9

**Do you use the premium version? (this wont change anything for you)** Yes

**What is the expected result?** Beacons are suppose to open a gui menu for players

**What happens instead of that?**
It allows them to select the beacon role for their pet but it doesn't open up the gui menu for them to select anything from the beacon role

**Error:**

**Comment by xXKeyleXx** [comment]
Are there any errors in the logs and do you get any message when you use the command?

**Comment by MapleMoosey** [comment]
Heya, I just tested it with my pet and there are no errors in the console for this action and no GUI menu opens up 
https://gyazo.com/402aefc5ea99c00166c4fa59206fd722
this also shows that I have selected the support skill tree
