### ISSUE TITLE
Mythic Mob Support

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#976]
Now I know folks have opened Tickets pertaining to Mythic Mobs in the past, but this request is a tad different.

I've noticed that if Mythic Mobs are created using Entities that can be tamed, for example a Zombie, and are disguised at something else, say a Bat. The player can still tame the Zombie/Bat mob and keep it as a Pet.. As a Zombie.
Ideally it'd be nice if Mythic Mobs couldn't be tamed by MyPet in this manner at all. It definitely ruins the illusion for one, and can make certain mobs easier to tame too. :( If players figured out they could do this, it could ruin certain setups.

The only thing I could imagine working to resolve this, would be to check for certain values in nameplates or something? I honestly have no idea. :'( One way to get around the "Disguise" bit was to avoid allowing taming anything in Disguise via LibDisguises, since that is what MM uses to disguise it's mobs. But that doesn't resolve taming something like a "Skeleton King" boss. (Which doesn't matter TOO much, since the pet takes it's own properties, but still.)

**Comment by xXKeyleXx** [comment]
I added a MythicMobs hook that disables leashing mobs of this plugin. Please try the latest dev build and tell me if it works.
