### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by Freakert** [xXKeyleXx/MyPet#979]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
1.11.2
**MyPet Build/Version:**
Latest build
**Do you use the premium version? (this wont change anything for you)**
no
**What is the expected result?**
information about customisable skilltrees
**What happens instead of that?**
hopefully i get information 
**Error:**
I am searching for a way to edit/customize the skilltrees. Is this possible with the free version?
If yes, what do i need/where can i find some info about it?

Kind regards

King_Freakert

**Comment by zerafox** [comment]
Open the Plugin jar with Java on your Computer.
The Skilltree editor will open.
