### ISSUE TITLE
/petcall node

### ISSUE THREAD

**Issue by ElementalRealm** [xXKeyleXx/MyPet#981]
I want to make forbiden /petcall command in 2 worlds. But there is no node to do that with permissions. How can I disable MyPet on certain worlds. I use Multiverse.

**Comment by xXKeyleXx** [comment]
https://wiki.mypet-plugin.de/multiworld ?

**Comment by ElementalRealm** [comment]
I use PermissionEx too not essentials perms

**Comment by xXKeyleXx** [comment]
What are you talking about? This has nothing to do with your choice of the permission plugin O.o

**Comment by ElementalRealm** [comment]
I didn't get how can I do it then. Can you explain me like I am really dumb? MyPet is the only plugin that I use that I don't understand much of its config
