### ISSUE TITLE
MyPet.log

### ISSUE THREAD

**Issue by Rocsapocsa** [xXKeyleXx/MyPet#982]
Please provide the following info.
I believe I did something wrong, and maybe missunderstood the wiki permission page.
**Bukkit/Spigot/Bungee Build/Version:**
Spigot
**MyPet Build/Version:**
2.2.9
**Do you use the premium version? (this wont change anything for you)**
No
**What is the expected result?**
Disable the ride skilltree with MyPet.extended.ride. 
**What happens instead of that?**
Don't block it
**Error:**

**Comment by xXKeyleXx** [comment]
do you want to disable the skill or the skilltree?

**Comment by Rocsapocsa** [comment]
Yes, i do

**Comment by xXKeyleXx** [comment]
you can't answer an 'or' question with yes.

**Comment by Rocsapocsa** [comment]
ah sorry, im really tired, I want to take away the permission from a group to use that skilltree.

**Comment by Rocsapocsa** [comment]
so i want to remove the skilltree from the /pcst command or just block it.

**Comment by xXKeyleXx** [comment]
the permission node should be MyPet.skilltree.ride

**Comment by Rocsapocsa** [comment]
Thank you!
