### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by corwinbass** [xXKeyleXx/MyPet#983]
Hello, 
i would like to ask if it would be possible (for my plugin) to catch some events from MyPet, like getting event when player catches or releases pet, including entity data of the pet(original mob)?
i would like my plugin to log time and location when player catches(or releases) new pet and log entity data from catched animal/mob.

**Comment by xXKeyleXx** [comment]
there is a package called API that contains all the available events. you can find it in this repo under modules/API

**Comment by xXKeyleXx** [comment]
of you need more info you have to wait until I come home from my vocation

**Comment by corwinbass** [comment]
thank you. i should have checked this repo before asking.
