### ISSUE TITLE
Custom Pets Suggestion

### ISSUE THREAD

**Issue by Prowco** [xXKeyleXx/MyPet#985]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.11.2

**MyPet Build/Version:**
Lastest

**Do you use the premium version? (this wont change anything for you)**
Not for now

**What is the expected result?**
Yes

Sugestion:
One question its possible add custom pets?, For example
i want make 3 bats with diferent skills each one:
- name          ///          type         ///       skill
-Ice Bat           ///          bat        ///      ranged snowball
-Fire Bat             ///       bat       ///       ranged fireball     
-Electric Bat          ///    bat    ///            lightning

And the way for give custom pets can be something like:
/petadmin create player bat custom Ice Bat
Or maybe just: /petadmin create player bat Ice Bat
So the permission for /petname is disable for the player so they cant change the pet to other changing the name.

Can you please add this is for my mmorpg server :3 sorry for my bad english i am spanish.

**Comment by zerafox** [comment]
You can create skill trees to simulate this already.
Set 3 different skilltrees with "snowball ranged" for bat, "fireball
ranged" and "Lightning".
Then you can assign these skilltrees to a player's Pet Bat with an admin
command.

It would look something like this:

/petadmin create <player> bat
/petadmin skilltree <player> <name of skilltree for ice bat>

Though to automate you'd need to use a plugin that can run commands to run
these when trigger appropriately depending on your chosen command running
plugin.

**Comment by Prowco** [comment]
**You can create skill trees to simulate this already.
Set 3 different skilltrees with "snowball ranged" for bat, "fireball
ranged" and "Lightning".
Then you can assign these skilltrees to a player's Pet Bat with an admin
command.**

And where i can save the skills? bc if i save the skills in default all the pets have the skills if i put the skills in the bat, the bat have the 3 skills so where i can save the skills for stay hide? and just can give the skill with the admin cmd /petadmin skilltree <player> <name of skilltree for ice bat>

**Comment by zerafox** [comment]
You create them for the bat, and set them to have a permission node. Then just don't give that permission node to your players.
If players don't have the permission for the skilltree, it won't show up when they do /pcst command
