### ISSUE TITLE
Custom Pet Specific Skill Trees Not Working

### ISSUE THREAD

**Issue by doitliketyler** [xXKeyleXx/MyPet#987]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Paper Spigot 1.11.2

**MyPet Build/Version:**
2.3.4

**Do you use the premium version? (this wont change anything for you)**
Yes

**What is the expected result?**
For a skill tree that only has the Ride skill tree to work for all 4/8 legged creatures and a default skill tree that only has Combat, PVP, Utility and Farm skill trees.

**What happens instead of that?**
They don't work when using the Skill tree editor. For example, I created one for the Wolf that has the Combat, PVP, Utility and Farm skill trees and then I created one for the Horse that only has the Ride skill tree. When activating either a wolf or horse pet none of the skill trees show up when using /pcst. Now if I customize the default skill tree and just remove Ride that it that works for all pets just fine.

**Error:**
There are no errors its just not work :(

Thoughts?

**Comment by zerafox** [comment]
Did you make sure to give permissions for your newly created skilltrees?

**Comment by zerafox** [comment]
Also make sure your skill trees aren't sharing the same names as the
default trees too, this could be the problem you're experiencing if you're
trying to use the same names of existing trees located in the Default Root
Skilltrees

**Comment by doitliketyler** [comment]
Yes I did give the appropriate permissions. Also, the skill trees for all pets can have the same name just as long as they are not in the same file. Either way I did try changing the name from Ride to Mount just to test it and it unfortunately did not work.

**Comment by zerafox** [comment]
If you've given the proper permission nodes to your players/users for your
new trees, but the skilltrees still arent' appearing in /pcst I'm at a loss
for what to tell you.
My guess is there is something somewhere that you've missed, as I've got
several skilltrees for each and every Pet available and they're all working
just fine.

Can you give these skilltrees to pets using the petadmin command?

**Comment by doitliketyler** [comment]
Well thats hard to believe because I literally took the default.sd and renamed it to Horse.sd then opened it in the editor and removed all the skill trees except Ride and saved it.

**Comment by zerafox** [comment]
Why would you do it that way?
That right there might be why you're not working properly.

Did you try making trees with the editor, WITHOUT copying a file and
changing the name over?
Try it for something you haven't touched yet.. Like a Squid or something.
Just make a fresh, dummy, skilltree.. Without copying default.sd and
renaming it.

**Comment by doitliketyler** [comment]
I did it that way because I only wanted the Ride skill tree with its default set of levels and skills. It doesn't save the pet type inside the actual file so why would I spend time rebuilding it to be exactly the same when I can simply adjust the default.sd? I went ahead and tried what you told me to do and its still no working.

I would also like to point out that I did exactly this same scenario when I first got the plugin last year and it worked fine. I just moved onto working on other items and am just now getting back to it and it no longer works. Whats sucks more is that I kept updating it without actually using the plugin yet so I don't even know what version it stopped working at.

**Comment by zerafox** [comment]
Lots of changes can be made over different versions, especially considering
the differences between Spigot and Bukkit coding.

Also you can "copy" trees now and paste them in to other pets.
Which is a lot easier still than copy+paste a file, change it's name and
then remove the unwanted trees.

I'm afraid without more information other than you're sure you gave the
right nodes, there isn't much more anyone can do for you.
If there are no errors, nothing in the mypet.log or otherwise.. The only
other thing I could suggest would be to start completely fresh, create a
brand new skill tree (or even copy a tree over from default and remove it
from default for this test) and see if that changes anything.

**Comment by doitliketyler** [comment]
So I tried the copy and paste and that did the trick I didn't even know I was able to do that. Thank you so much!

**Comment by zerafox** [comment]
Glad you got it working. :)
Based on that, I'm going to have to assume somewhere something went funny with the copy/renaming of files or something of the sort.
This copy+paste should make things heap easier though, I know it did for me!

**Comment by doitliketyler** [comment]
Definitely. Again...thank you so much. I really appreciate you taking the time to help me through the issue.
