### ISSUE TITLE
Material cannot be null ranged Skeleton from scratch

### ISSUE THREAD

**Issue by bentinata** [xXKeyleXx/MyPet#991]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
11.2

**MyPet Build/Version:**
2.2.8-b#1121

**Do you use the premium version? (this wont change anything for you)**
No.

**What is the expected result?**
Custom skilltree with only ranged skill Skeleton shoot.

**What happens instead of that?**
IllegalArgumentException: Material cannot be null

**Comment by xXKeyleXx** [comment]
Please provide the full error.

**Comment by bentinata** [comment]
I can't reproduce the error, sorry.
Already fixing it by rebuilding the skilltree.
