### ISSUE TITLE
Mypet Plugin: Glitching through walls

### ISSUE THREAD

**Issue by LethalHost** [xXKeyleXx/MyPet#995]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:** Latest Version

**MyPet Build/Version:** latest version

**Do you use the premium version? (this wont change anything for you)** no

**What is the expected result?** Patch fix

**What happens instead of that?**

**Error:** Glitching through walls when you jump off your mypet while riding very bad for base protection

**Comment by zerafox** [comment]
"Latest Version" is very bad practice, and can actually be harmful to your ticket report.
Please include the version numbers so we can properly assist you.
