### ISSUE TITLE
Transferring data

### ISSUE THREAD

**Issue by leuransw** [xXKeyleXx/MyPet#996]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.11.2

**MyPet Build/Version:**
Latest (downloaded yesterday)
**Do you use the premium version? (this wont change anything for you)**
YES
**What is the expected result?**
Be able to transfer my player data to a new server and connect that data to mySQL

**What happens instead of that?**
All data was reset

**Error:**
I am trying to transfer all mypet data to my new server where I connected to mySQL. I have copied the whole plugin folder to my new server but when I connected to the database everything seemed to be reset. Is there a way to fix this.

**Comment by zerafox** [comment]
Unless you transfer the MySQL database information from one mySQL to the next, there is no information to carry over.
Transferring plugin folders only transfers configuration files. If you're using the same database for both servers, make sure the information for the MySQL is correct if it's not connecting properly after transferring.

**Comment by leuransw** [comment]
How about if my old server does not use SQL.

**Comment by zerafox** [comment]
Did you set the ConvertFrom: option in your configuration file to switch to
MySQL from your original save format?
If you've told the plugin to save to MySQL but you didn't "Convertfrom"
there is nothing to convert over to your MySQL database in the first place,
which is why you'd be experiencing a reset of your pets.

**Comment by zerafox** [comment]
Double check this page on the wiki if you're unsure how to approach this
sort of conversion from your old file save format to your new MySQL
database.
https://wiki.mypet-plugin.de/configfile

**Comment by leuransw** [comment]
Alright my bad, I have now transferred all data.
