### ISSUE TITLE
Some bugs about MyPet

### ISSUE THREAD

**Issue by Soldier233** [xXKeyleXx/MyPet#999]
Hello there
I am running the latest MyPet plugin on Spigot 1.8.8
But there may be some bugs with other plugins.
If a player catches a silverfish as his pet, the pet will break stone bricks that are under protection of Residence without permissions.
If a player rides a pet,and use the item Hook(I am not sure wether the item in Slimefun English Edition is called Hook, because I am a Chinese, but it means Hook in English) in Slimefun,and it will spawn a new entity which is the same type of its pet.
I hope the problems can be solved soon
Or you can tell you the cause of the problems so that I can fix it by myself
Thanks a lot

**Comment by xXKeyleXx** [comment]
Pet's (beside sheeps) don't break any blocks. I don't unterstand your 2nd problem.

**Comment by Soldier233** [comment]
The 2nd problem also has some another causes
If a player leads his pet to someone's resdience which refuses others to move,the pet will be copied.and the copies of the animals can't be killed

**Comment by xXKeyleXx** [comment]
Could you make a video of that?

**Comment by Soldier233** [comment]
Yes
I will make it when I am free.
But how can I send it to you？

**Comment by xXKeyleXx** [comment]
Upload it as an unlisted video on Youtube and post it here :P

**Comment by Soldier233** [comment]
https://youtu.be/oDvQmPHx388

I described it in English
(I am poor in English, If you don't understand, I can explain it for you)

**Comment by Soldier233** [comment]
And I found that it can be copied not only by riding it, but also make it into the residence

**Comment by xXKeyleXx** [comment]
What flags do you have on the residence?

**Comment by Soldier233** [comment]
move false

**Comment by xXKeyleXx** [comment]
I tried to move into a residence while riding a pet and I can't reproduce the problem. I simply unmount and my pet don't gets duplicated. Do you use any other plugin that might be able to cause this problem?

**Comment by Soldier233** [comment]
Some users of your plugin have talked me about the bug I recorded.
They all have the same problem.

**Comment by Soldier233** [comment]
http://i1.piimg.com/569794/0e2a2e3d0d3abdc5.png
Here is my plugin list

**Comment by xXKeyleXx** [comment]
The problem is that I can not fix it when I'm not able to reproduce it :/ Could you upload your plugins folder and send me the link in a private message on spigot?

**Comment by Soldier233** [comment]
Do you use skype or some other communication software?

**Comment by xXKeyleXx** [comment]
keylesc on Skype

**Comment by Soldier233** [comment]
Or you can use QQ
I remembered that you asked for a Chinese user that has a QQ account

**Comment by xXKeyleXx** [comment]
I only have TGP and I have no clue what to do in it as I don't speak chinese xD

**Comment by Soldier233** [comment]
It has international edition

**Comment by Sprungente** [comment]
I had for a long time (2 months) a player with 2 pet on his side. The first one it's possible to kill the second is immun from attacks. i can't reproduce this bug. 
Maybe my comment is useless but i think it's nice to know.
